(*
 $Id$
 ISO TC184/SC4/WG12 N - ISO/WD 10303-1444 Project management work structure connector - EXPRESS MIM
*)
(* UNDER DEVELOPMENT *)
SCHEMA Project_management_work_structure_connector_mim;
  USE FROM Work_structure_mim;
  USE FROM Management_resource_information_mim;
  USE FROM Project_management_resource_information_mim;
  USE FROM Organization_structure_mim;
  USE FROM Project_breakdown_mim;
  USE FROM Schedule_mim;
END_SCHEMA;
