(*
   $Id$
   ISO TC184/SC4/WG3 N1990 - ISO/TS 10303-1612 AP210 device functional and physical characterization - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1635
*)

SCHEMA Ap210_device_functional_and_physical_characterization_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Chemical_substance_arm;	-- ISO/TS 10303-1655
	USE FROM Packaged_part_black_box_model_arm;	-- ISO/TS 10303-1710
	USE FROM Part_feature_grouping_arm;	-- ISO/TS 10303-1713
END_SCHEMA;

