(*
   $Id$
   ISO TC184/SC4/WG12 N3981 - ISO/TS 10303-1678 Functional decomposition with nodal representation to packaged mapping - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3429
*)

SCHEMA Functional_decomposition_with_nodal_representation_to_packaged_mapping_arm;

	USE FROM Functional_decomposition_to_design_arm; -- ISO/TS 10303-1676
	USE FROM Physical_connectivity_definition_arm;	-- ISO/TS 10303-1755

  ENTITY Aggregate_connectivity_requirement;
      connectivity_requirement : SET [1:?] OF Functional_unit_network_node_definition;
  END_ENTITY;

  ENTITY Connectivity_allocation;
      implementation           : Physical_connectivity_definition;
      connectivity_requirement : Aggregate_connectivity_requirement;
    UNIQUE
      UR1 : implementation;
  END_ENTITY;

END_SCHEMA;


