(*
   $Id$
   N - ISO/CD-TS - 10303- product_and_manufacturing_information_with_nominal_3d_models - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Product_and_manufacturing_information_with_nominal_3d_models_mim;

USE FROM Product_and_manufacturing_information_view_context_mim;
USE FROM Shape_property_assignment_mim; -- ISO/TS 10303-1032
USE FROM Advanced_boundary_representation_mim; -- ISO/TS 10303-1514
USE FROM Manifold_surface_mim; -- ISO/TS 10303-1509
USE FROM Manifold_subsurface_mim; -- ISO/TS 10303-1702
USE FROM Construction_geometry_mim; -- ISO/TS 10303-1131

END_SCHEMA;
