(*
   $Id$
   ISO TC184/SC4/WG12 N6625 - ISO/TS - 10303-1404 geometric_model_2d_3d_relationship - EXPRESS ARM
*)

SCHEMA Geometric_model_2d_3d_relationship_arm;

USE FROM Contextual_shape_positioning_arm;          -- ISO/TS 10303-1027
USE FROM Geometric_model_relationship_arm;          -- ISO/TS 10303-1403

  ENTITY Axis_placement_2d_3d_mapping;
      transform_item_1 : Axis_placement_2d;
      transform_item_2 : Axis_placement_3d;
  END_ENTITY;
 
  ENTITY Coordinated_geometric_relationship_with_2d_3d_placement_transformation
    SUBTYPE OF (Geometric_model_relationship_with_transformation);
      transformation: Axis_placement_2d_3d_mapping;
    WHERE
     WR1 : NOT('GEOMETRIC_MODEL_RELATIONSHIP_ARM.DEFINITIONAL_REPRESENTATION_RELATIONSHIP' IN TYPEOF(SELF));
  END_ENTITY;

END_SCHEMA;
