--==============================================
-- Associative_draughting_elements for
--  aic_associative_draughting_elements; --  ISO 10303-520

SCHEMA Associative_draughting_elements_mim;

USE FROM Appearance_assignment_mim;

USE FROM aic_associative_draughting_elements; --  ISO 10303-520
(*
ENTITY draughting_model
  SUBTYPE OF (styled_model);
UNIQUE
  UR1:  SELF\representation.name;
END_ENTITY;
*)
END_SCHEMA;  
