(* Genenerated from: ../../irs/wg12n550.exp *)

SCHEMA fea_scalar_vector_tensor_schema;

  REFERENCE FROM measure_schema 
      (context_dependent_measure);

  REFERENCE FROM representation_schema
      (representation_item);

TYPE angular_value = 
     context_dependent_measure;
END_TYPE;

TYPE scalar = 
     context_dependent_measure;
END_TYPE;

TYPE tensor1 = SELECT
  (tensor1_2d,
   tensor1_3d);
END_TYPE;

TYPE tensor1_2d = 
     ARRAY [1:2] OF context_dependent_measure;
END_TYPE;

TYPE tensor1_3d = 
  ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor2_2d = SELECT
  (anisotropic_symmetric_tensor2_2d);
END_TYPE;

TYPE anisotropic_symmetric_tensor2_2d = 
  ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor2_3d = SELECT
  (isotropic_symmetric_tensor2_3d,
   orthotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor2_3d);
END_TYPE;

TYPE isotropic_symmetric_tensor2_3d = 
     context_dependent_measure;
END_TYPE;

TYPE orthotropic_symmetric_tensor2_3d = 
     ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE anisotropic_symmetric_tensor2_3d = 
     ARRAY [1:6] OF context_dependent_measure;
END_TYPE;

TYPE symmetric_tensor4_2d = SELECT
  (anisotropic_symmetric_tensor4_2d);
END_TYPE;

TYPE anisotropic_symmetric_tensor4_2d = 
     ARRAY [1:6] OF context_dependent_measure;
END_TYPE;

TYPE tensor_type = SELECT 
  (scalar,
   angular_value,
   tensor1_2d,
   tensor1_3d,
   anisotropic_symmetric_tensor2_2d,
   isotropic_symmetric_tensor2_3d,
   orthotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor2_3d,
   anisotropic_symmetric_tensor4_2d,
   anisotropic_symmetric_tensor4_3d,
   fea_isotropic_symmetric_tensor4_3d,
   fea_iso_orthotropic_symmetric_tensor4_3d,
   fea_transverse_isotropic_symmetric_tensor4_3d,
   fea_column_normalised_orthotropic_symmetric_tensor4_3d,
   fea_column_normalised_monoclinic_symmetric_tensor4_3d);
END_TYPE;

TYPE symmetric_tensor4_3d = SELECT
 (anisotropic_symmetric_tensor4_3d,
  fea_isotropic_symmetric_tensor4_3d,
  fea_iso_orthotropic_symmetric_tensor4_3d,
  fea_transverse_isotropic_symmetric_tensor4_3d,
  fea_column_normalised_orthotropic_symmetric_tensor4_3d,
  fea_column_normalised_monoclinic_symmetric_tensor4_3d);
END_TYPE;

TYPE anisotropic_symmetric_tensor4_3d = 
     ARRAY [1:21] OF context_dependent_measure;
END_TYPE;

TYPE fea_isotropic_symmetric_tensor4_3d = 
     ARRAY [1:2] OF context_dependent_measure;
END_TYPE;

TYPE fea_iso_orthotropic_symmetric_tensor4_3d = 
     ARRAY [1:3] OF context_dependent_measure;
END_TYPE;

TYPE fea_transverse_isotropic_symmetric_tensor4_3d = 
     ARRAY [1:5] OF context_dependent_measure;
END_TYPE;

TYPE fea_column_normalised_orthotropic_symmetric_tensor4_3d = 
     ARRAY [1:9] OF context_dependent_measure;
END_TYPE;

TYPE fea_column_normalised_monoclinic_symmetric_tensor4_3d = 
     ARRAY [1:13] OF context_dependent_measure;
END_TYPE;

ENTITY tensor_representation_item
  SUBTYPE OF (representation_item);
  tensor_value              : tensor_type;
END_ENTITY;

END_SCHEMA; -- fea_scalar_vector_tensor_schema
