(*
   $Id$
   N - ISO/CD-TS - 10303- geometric_model_relationship - EXPRESS MIM*)
(* UNDER DEVELOPMENT *)
SCHEMA Geometric_model_relationship_mim;

USE FROM Elemental_geometric_shape_mim;    -- ISO/TS 10303-1004

USE FROM representation_schema(
  definitional_representation_relationship
);

USE FROM product_property_representation_schema -- ISO 10303-41
  (shape_representation_relationship);


END_SCHEMA;
