/* Generated by JSDAI Express Compiler, version 3.5, build 225, 2003-04-23 */

// Java class implementing aggregate of  second_entity of level 1

package jsdai.SExample_2;
import jsdai.lang.*;


public class ASecond_entity extends AEntity {
	public ESecond_entity getByIndex(int index) throws SdaiException {
		return (ESecond_entity)getByIndexObject(index);
	}
	public ESecond_entity getCurrentMember(SdaiIterator iter) throws SdaiException {
		return (ESecond_entity)getCurrentMemberObject(iter);
	}
}
