(*
   $Id$
   ISO TC184/SC4/WG3 N2040 - ISO/TS 10303-1622 AP210 interconnect technology constraints - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1665
*)

SCHEMA Ap210_interconnect_technology_constraints_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Fabrication_technology_arm;	-- ISO/TS 10303-1670


TYPE aitc_ee_product_definition_with_annotation_elements = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ee_product_definition_with_annotation_elements WITH 
   	(Part_usage_view);
END_TYPE; 
END_SCHEMA;

