(*
   $Id$
   N - ISO/CD-TS - 10303- ap242_managed_model_based_3d_engineering - EXPRESS MIM*)

SCHEMA Ap242_managed_model_based_3d_engineering_mim;

USE FROM Mating_structure_mim;
USE FROM Shape_data_quality_inspection_result_mim; -- ISO/TS 10303-1524
USE FROM Geometric_constraints_mim; -- ISO/TS 10303-1789
USE FROM Machining_features_mim;
USE FROM Form_feature_in_panel_mim;
USE FROM Assembly_constraints_mim;
USE FROM Kinematic_analysis_control_and_result_mim;
USE FROM Process_plan_mim;
-- geometry model for point clouds
USE FROM Constructive_solid_geometry_2d_mim; -- ISO/TS 10303-1731
USE FROM Product_as_individual_assembly_and_test_mim;

USE FROM Characterized_representation_mim;
USE FROM Chemical_substance_mim; -- ISO/TS 10303-1655 
USE FROM Composite_material_aspects_mim; -- ISO/TS 10303-1768
USE FROM Compound_shape_representation_mim; -- ISO/TS 10303-1327
USE FROM Constructive_solid_geometry_3d_mim; -- ISO/TS 10303-1068
USE FROM Curve_swept_solid_mim; -- ISO/TS 10303-1659
USE FROM Default_tolerance_mim; -- ISO/TS 10303-1052
USE FROM Design_product_data_management_mim; -- ISO/TS 10303-1628
USE FROM Dimension_and_tolerance_callouts_mim; -- ISO/TS 10303-1362
USE FROM Dimension_tolerance_mim; -- ISO/TS 10303-1050
USE FROM Drawing_definition_mim;  -- ISO/TS 10303-1309
USE FROM Elementary_boundary_representation_mim; -- ISO/TS 10303-1329
USE FROM External_currency_mim; -- ISO/TS 10303-1777
USE FROM External_representation_item_mim; -- ISO/TS 10303-1779
USE FROM Geometric_tolerance_mim; -- ISO/TS 10303-1051
USE FROM Geometric_validation_property_representation_mim; -- ISO/TS 10303-1039
USE FROM Inertia_characteristics_mim; -- ISO/TS 10303-1350
USE FROM Manifold_subsurface_mim; -- ISO/TS 10303-1702
USE FROM Mechanical_design_presentation_representation_with_draughting_mim; -- ISO/TS 10303-1315
USE FROM Modified_swept_solid_mim; -- ISO/TS 10303-1322
USE FROM Numerical_interface_mim;
USE FROM Part_and_zone_laminate_tables_mim;  -- ISO/TS 10303-1770
USE FROM Picture_representation_mim;  -- ISO/TS 10303-1308
USE FROM Planned_characteristic_mim; -- ISO/TS 10303-1733
USE FROM Ply_orientation_specification_mim;  -- ISO/TS 10303-1772
USE FROM Representation_with_uncertainty_mim; -- ISO/TS 10303-1228
USE FROM Shape_feature_mim;    -- ISO/TS 10303-1764
USE FROM Solid_with_local_modification_mim; -- ISO/TS 10303-1319
USE FROM Surface_conditions_mim; -- ISO/TS 10303-1110 
USE FROM Text_representation_mim;	-- ISO/TS 10303-1750
USE FROM Thickened_face_solid_mim; -- ISO/TS 10303-1320
USE FROM Wireframe_2d_mim; -- ISO/TS 10303-1347
USE FROM Model_based_3d_geometrical_dimensioning_and_tolerancing_representation_mim;
USE FROM Product_and_manufacturing_annotation_presentation_mim;
USE FROM Change_management_mim; -- ISO/TS 10303-1661
USE FROM Sketch_mim; -- ISO/TS 10303-1792


USE FROM application_context_schema   -- ISO 10303-41
  (application_context,
   application_protocol_definition,
   product_context,
   product_definition_context); 
USE FROM product_concept_schema(product_concept_relationship); 
USE FROM product_definition_schema(  -- ISO 10303-41
  product_definition_context_role, 
  product_category_relationship); 
REFERENCE FROM support_resource_schema   -- ISO 10303-41
  (bag_to_set,
   type_check_function); 

USE FROM product_property_representation_schema
  (item_identified_representation_usage_definition);   


  CONSTANT
    deprecated_interfaced_data_types : SET OF STRING := 
      ['document_with_class',
       'ordinal_date', 
       'product_definition_formation_with_specified_source', 
       'week_of_year_and_day_date']; 
    deprecated_constructed_data_types : SET OF STRING := 
      ['approved_item',
       'certified_item', 
       'change_request_item', 
       'contracted_item', 
       'cc_classified_item', 
       'date_time_item', 
       'cc_person_organization_item', 
       'cc_specified_item', 
       'start_request_item', 
       'work_item']; 
    deprecated_entity_data_types : SET OF STRING := 
      ['cc_design_approval',
       'cc_design_certification', 
       'cc_design_contract', 
       'cc_design_date_and_time_assignment', 
       'cc_design_person_and_organization_assignment', 
       'cc_design_security_classification', 
       'cc_design_specification_reference', 
       'change', 
       'change_request', 
       'design_context', 
       'design_make_from_relationship', 
       'mechanical_context', 
       'start_request', 
       'start_work', 
       'supplied_part_relationship']; 
  END_CONSTANT; 
  
  TYPE item_identified_representation_usage_definition_242 = SELECT BASED_ON item_identified_representation_usage_definition WITH
   (applied_action_assignment,
    applied_action_method_assignment, 
    applied_action_request_assignment, 
    applied_approval_assignment,
    applied_certification_assignment, 
    applied_classification_assignment, 
    applied_contract_assignment, 
    applied_date_and_time_assignment, 
    applied_date_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment, 
    applied_external_identification_assignment,
    applied_group_assignment,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_name_assignment,
    applied_organization_assignment, 
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    product_definition_relationship,
    property_definition);
  END_TYPE;
  
  TYPE draughting_model_item_definition_242 = SELECT BASED_ON draughting_model_item_definition WITH
   (applied_action_assignment,
    applied_action_method_assignment, 
    applied_action_request_assignment, 
    applied_approval_assignment,
    applied_certification_assignment, 
    applied_classification_assignment, 
    applied_contract_assignment, 
    applied_date_and_time_assignment, 
    applied_date_assignment,
    applied_document_reference,
    applied_document_usage_constraint_assignment,
    applied_effectivity_assignment,
    applied_event_occurrence_assignment, 
    applied_external_identification_assignment,
    applied_group_assignment,
    applied_identification_assignment,
    applied_ineffectivity_assignment,
    applied_name_assignment,
    applied_organization_assignment, 
    applied_organizational_project_assignment,
    applied_person_and_organization_assignment,
    applied_security_classification_assignment,
    applied_time_interval_assignment,
    applied_usage_right,
    product_definition_relationship,
    property_definition);
  END_TYPE;
  
  TYPE ap242_change_management_object = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON change_management_object WITH 
    (action_items,
     action,
     action_relationship,
     project_item,
     class,
     event_occurrence);
  END_TYPE;

  TYPE ap242_change_relationship_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON change_relationship_select WITH 
    (product_definition_relationship,
     action_relationship,
     shape_aspect_relationship);
  END_TYPE;

  TYPE action_request_item_242 = SELECT BASED_ON action_request_item WITH 
    (product_definition_formation_relationship,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	resource_property);
  END_TYPE; 

  TYPE aliasable_item_242 = SELECT BASED_ON aliasable_item WITH 
    (approval_status, 
    general_property, 
    organization, 
    product, 
    product_definition, 
    product_definition_formation, 
    security_classification,
    shape_representation);
  END_TYPE; 

  TYPE approval_item_242 = SELECT BASED_ON approval_item WITH 
    (alternate_product_relationship, 
    assembly_component_usage_substitute, 
    certification, 
    contract, 
    document_file, 
    executed_action, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_definition_relationship,
     draughting_model,
     drawing_revision,
     mechanical_design_geometric_presentation_representation,
	 presentation_area,
	 resource_property);
  END_TYPE; 

  TYPE approved_item = SELECT
    (certification, 
    change, 
    change_request, 
    configuration_effectivity, 
    configuration_item, 
    contract, 
    product, 
    security_classification, 
    start_request, 
    start_work);
  END_TYPE; 

  TYPE attribute_language_item_242 = SELECT BASED_ON attribute_language_item WITH 
    (alternate_product_relationship, 
    application_context, 
    applied_certification_assignment, 
    applied_identification_assignment, 
    applied_security_classification_assignment, 
    assembly_component_usage_substitute, 
    attribute_value_assignment, 
    configuration_design, 
    configuration_item, 
    descriptive_representation_item, 
    effectivity, 
    effectivity_relationship, 
    event_occurrence, 
    external_source, 
    general_property, 
    general_property_relationship, 
    geometric_representation_item, 
    geometric_tolerance, 
    make_from_usage_option, 
    mapped_item, 
    organization_role, 
    person_and_organization_role, 
    product_concept, 
    product_concept_relationship, 
    product_definition_context, 
    product_definition_formation, 
    product_definition_formation_relationship, 
    product_definition_shape, 
    product_related_product_category, 
    property_definition, 
    representation, 
    security_classification, 
    security_classification_assignment, 
    shape_aspect, 
    shape_aspect_relationship, 
    shape_representation, 
    time_interval_role, 
    topological_representation_item, 
    uncertainty_measure_with_unit, 
    uncertainty_qualifier,
	draughting_title,
	kinematic_pair,
	actuated_kinematic_pair,
	presentation_layer_assignment,
	process_product_association,
	requirement_for_action_resource,
	resource_property,
	resource_requirement_type,
	styled_item,
	versioned_action_request_relationship);
  END_TYPE; 

  TYPE certification_item_242 = SELECT BASED_ON certification_item;
  END_TYPE; 

  TYPE certified_item = SELECT
    (supplied_part_relationship);
  END_TYPE; 

  TYPE change_request_item = SELECT
    (product_definition_formation);
  END_TYPE; 

  TYPE cc_classified_item = SELECT 
    (assembly_component_usage, 
    product_definition_formation);
  END_TYPE; 

  TYPE contract_item_242 = SELECT BASED_ON contract_item WITH 
    (drawing_revision,
    executed_action, 
    product_definition_formation);
  END_TYPE; 

  TYPE contracted_item = SELECT
    (product_definition_formation);
  END_TYPE; 

  TYPE date_and_time_item_242 = SELECT BASED_ON date_and_time_item WITH 
    (applied_organization_assignment, 
    applied_person_and_organization_assignment, 
    approval_person_organization, 
    certification, 
    contract, 
    organizational_project, 
    product_definition, 
    product_definition_formation, 
    security_classification,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

  TYPE date_item_242 = SELECT BASED_ON date_item WITH 
    (applied_organization_assignment, 
    applied_person_and_organization_assignment, 
    approval_person_organization, 
    certification, 
    contract, 
    organizational_project, 
    product_definition, 
    product_definition_formation, 
    security_classification,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

  TYPE date_time_item = SELECT
    (approval_person_organization, 
    certification, 
    change, 
    change_request, 
    contract, 
    product_definition, 
    security_classification, 
    start_request, 
    start_work);
  END_TYPE; 

  TYPE document_reference_item_242 = SELECT BASED_ON document_reference_item WITH 
    (product, 
    product_definition, 
    product_definition_formation, 
    product_definition_relationship,
	feature_definition,
	presentation_area,
	process_plan,
	resource_requirement_type,
	retention,
	product_definition_process);
  END_TYPE; 

  TYPE effectivity_item_242 = SELECT BASED_ON effectivity_item WITH 
    (assembly_component_usage_substitute, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_definition_relationship,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

  TYPE event_occurrence_item_242 = SELECT BASED_ON event_occurrence_item WITH (
    organizational_project,
	requirement_for_action_resource,
	resource_property,
	presentation_area,
	mechanical_design_geometric_presentation_representation,
	draughting_model,
	drawing_revision);
  END_TYPE; 

  TYPE external_identification_item_242 = SELECT BASED_ON external_identification_item WITH 
    (document_file, 
    product_definition);
  END_TYPE; 

  TYPE groupable_item_242 = SELECT BASED_ON groupable_item WITH 
    (geometric_representation_item,
     shape_representation_relationship, 
     representation_relationship_with_transformation, 
     mapped_item,
     shape_aspect, 
     styled_item, 
     topological_representation_item);
  END_TYPE; 

  TYPE identification_item_242 = SELECT BASED_ON identification_item WITH 
    (approval_status, 
    document_file, 
    general_property, 
    organization, 
    product, 
    product_definition, 
    product_definition_formation, 
    security_classification, 
    security_classification_level, 
    shape_representation,
	draughting_model,
	mechanical_design_geometric_presentation_representation,
	presentation_area);
  END_TYPE; 

  TYPE multi_language_attribute_item_242 = SELECT BASED_ON multi_language_attribute_item WITH 
    (alternate_product_relationship, 
    application_context, 
    applied_certification_assignment, 
    applied_identification_assignment, 
    assembly_component_usage_substitute, 
    attribute_value_assignment, 
    colour, 
    configuration_design, 
    configuration_item, 
    descriptive_representation_item, 
    effectivity, 
    effectivity_relationship, 
    event_occurrence, 
    external_source, 
    general_property, 
    general_property_relationship, 
    geometric_representation_item, 
    geometric_tolerance, 
    make_from_usage_option, 
    mapped_item, 
    organization_role, 
    person_and_organization_role, 
    product_concept, 
    product_concept_relationship, 
    product_definition_context, 
    product_definition_formation, 
    product_definition_formation_relationship, 
    product_definition_shape, 
    product_related_product_category, 
    property_definition, 
    representation, 
    representation_relationship, 
    security_classification, 
    security_classification_assignment, 
    shape_aspect, 
    shape_aspect_relationship, 
    shape_representation, 
    time_interval_role, 
    topological_representation_item, 
    uncertainty_measure_with_unit,
	draughting_title,
	kinematic_pair,
	actuated_kinematic_pair,
	presentation_layer_assignment,
	process_product_association,
	requirement_for_action_resource,
	resource_property,
	resource_requirement_type,
	styled_item,
	versioned_action_request_relationship);
  END_TYPE; 

  TYPE organization_item_242 = SELECT BASED_ON organization_item WITH 
    (alternate_product_relationship, 
    applied_action_assignment, 
    applied_identification_assignment, 
    applied_security_classification_assignment, 
    assembly_component_usage_substitute, 
    certification, 
    document_file, 
    general_property, 
    organizational_project, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_definition_formation_relationship, 
    property_definition, 
    shape_representation,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

  TYPE organizational_project_item_242 = SELECT BASED_ON project_item WITH 
    (executed_action, 
    product_concept);
  END_TYPE; 

  TYPE person_and_organization_item_242 = SELECT BASED_ON person_and_organization_item WITH 
    (alternate_product_relationship, 
    applied_action_assignment, 
    applied_security_classification_assignment, 
    assembly_component_usage_substitute, 
    certification, 
    document_file, 
    general_property, 
    organizational_project, 
    product, 
    product_definition, 
    product_definition_formation, 
    product_definition_formation_relationship, 
    property_definition, 
    shape_representation,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

  TYPE property_variable_rep_select_242 = SELECT BASED_ON property_variable_rep_select WITH (
     dimensional_size,
     dimensional_location,
     representation);
  END_TYPE; 
  
  TYPE cc_person_organization_item = SELECT
    (change, 
    change_request, 
    configuration_item, 
    contract, 
    product, 
    product_definition, 
    product_definition_formation, 
    security_classification, 
    start_request, 
    start_work);
  END_TYPE; 

  TYPE presented_item_select_242 = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON presented_item_select WITH 
    (action,
    action_method,
    action_relationship,
    product_concept,
    product_concept_feature,
    product_concept_feature_category,
    product_definition,
    product_definition_formation,
    product_definition_relationship);
  END_TYPE;

  TYPE security_classification_item_242 = SELECT BASED_ON security_classification_item WITH 
    (document_file, 
    product_definition, 
    product_definition_formation, 
    product_definition_usage,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	resource_property);
  END_TYPE; 

  TYPE cc_specified_item = SELECT
    (product_definition, 
    shape_aspect);
  END_TYPE; 

  TYPE start_request_item = SELECT
    (product_definition_formation);
  END_TYPE; 

  TYPE time_interval_item_242 = SELECT BASED_ON time_interval_item WITH 
    (time_interval_based_effectivity,
	draughting_model,
	drawing_revision,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property);
  END_TYPE; 

TYPE action_items_242 = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH ( 
	executed_action,
	mechanical_design_geometric_presentation_representation,
	presentation_area,
	requirement_for_action_resource,
	resource_property,
	draughting_model,
	drawing_revision);
END_TYPE; 

TYPE classification_item_242 = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH ( 
	feature_definition,
	general_feature,
	plus_minus_tolerance,
	process_operation,
	resource_property);
END_TYPE; 

TYPE configured_effectivity_item_242 = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON configured_effectivity_item WITH ( 
	process_plan,
	product_process_plan);
END_TYPE; 

  TYPE work_item = SELECT
    (product_definition_formation);
  END_TYPE; 

  ENTITY cc_design_approval
    SUBTYPE OF (approval_assignment);
      items : SET[1:?] OF approved_item;
  END_ENTITY;

  ENTITY cc_design_certification
    SUBTYPE OF (certification_assignment);
      items : SET[1:?] OF certified_item;
  END_ENTITY;

  ENTITY cc_design_contract
    SUBTYPE OF (contract_assignment);
      items : SET[1:?] OF contracted_item;
  END_ENTITY;

  ENTITY cc_design_date_and_time_assignment
    SUBTYPE OF (date_and_time_assignment);
      items : SET[1:?] OF date_time_item;
  END_ENTITY;

  ENTITY cc_design_person_and_organization_assignment
    SUBTYPE OF (person_and_organization_assignment);
      items : SET[1:?] OF cc_person_organization_item;
    WHERE
      WR1: cc_design_person_and_organization_correlation(SELF);
  END_ENTITY;

  ENTITY cc_design_security_classification
    SUBTYPE OF (security_classification_assignment);
      items : SET[1:?] OF cc_classified_item; 
  END_ENTITY;

  ENTITY cc_design_specification_reference
    SUBTYPE OF (document_reference);
      items : SET[1:?] OF cc_specified_item; 
  END_ENTITY;

  ENTITY change
    SUBTYPE OF (action_assignment);
      items : SET[1:?] OF work_item;
  END_ENTITY;

  ENTITY change_request
    SUBTYPE OF (action_request_assignment);
      items : SET[1:?] OF change_request_item;
  END_ENTITY;

  ENTITY design_context
    SUBTYPE OF (product_definition_context);
    WHERE
      WR1: SELF.life_cycle_stage = 'design';
  END_ENTITY;

  ENTITY design_make_from_relationship
    SUBTYPE OF (product_definition_relationship);
  END_ENTITY;

  ENTITY mechanical_context
    SUBTYPE OF (product_context);
    WHERE
      WR1: SELF.discipline_type = 'mechanical';
  END_ENTITY;

  ENTITY start_request
    SUBTYPE OF (action_request_assignment);
      items : SET[1:?] OF start_request_item;
  END_ENTITY;

  ENTITY start_work
    SUBTYPE OF (action_assignment);
      items : SET[1:?] OF work_item;
  END_ENTITY;

  ENTITY supplied_part_relationship
    SUBTYPE OF (product_definition_relationship);
  END_ENTITY;

  RULE dimensioning_data_requires_document FOR (applied_document_reference, product_definition_context_association, role_association);
    LOCAL
      adr : SET OF applied_document_reference := (QUERY(adr <* applied_document_reference |
                         (adr\document_reference.assigned_document\document.kind\document_type.product_data_type = 'Standards Document') AND
                         ((adr\document_reference.assigned_document\document.id = 'ASME Y14.41-2003') OR 
                         (adr\document_reference.assigned_document\document.id = 'ASME Y14.5M-1994') OR 
                         (adr\document_reference.assigned_document\document.id = 'ISO 1101: 2004'))));
      pdca : SET OF product_definition_context_association := (QUERY(pdca <* product_definition_context_association |
                         (pdca\product_definition_context_association.role\product_definition_context_role.name = 'additional context') AND
                         (pdca\product_definition_context_association.frame_of_reference\application_context_element.name = 'Geometric Dimensioning and Tolerancing Product Specification')));
      ra : SET OF role_association := (QUERY(ra <* role_association |
                         ra\role_association.role\object_role.name = 'dimensioning standard'));
      ra1 : SET OF role_association := [];
      pdpdca : SET OF product_definition := [];
      pdadr : SET OF product_definition := [];
      pass : BOOLEAN := TRUE;
    END_LOCAL;

    REPEAT i := 1 TO HIINDEX(pdca);
       pdpdca := pdpdca + pdca[i]\product_definition_context_association.definition;
    END_REPEAT;
    REPEAT i := 1 TO HIINDEX(adr);
       ra1 := bag_to_set(USEDIN(adr[i],'BASIC_ATTRIBUTE_SCHEMA.ROLE_ASSOCIATION.ITEM_WITH_ROLE'));
       IF (ra1 * ra) <> ra1 THEN 
        pass := FALSE;
       END_IF;
      REPEAT j := 1 to HIINDEX(adr[i]\applied_document_reference.items);
       IF 'PRODUCT_DEFINITION_SCHEMA.PRODUCT_DEFINITION' IN TYPEOF(adr[i]\applied_document_reference.items[j]) THEN
        pdadr := pdadr + adr[i]\applied_document_reference.items[j];
       END_IF;
      END_REPEAT;
    END_REPEAT;

    WHERE
     WR1 : pass; 
     WR2 : pdpdca = pdadr;
 
END_RULE;




  RULE application_protocol_definition_required FOR 
      (application_context); 
    WHERE 
      WR1:  SIZEOF( QUERY( ac <* application_context | 
              (SIZEOF (QUERY (apd <* USEDIN(ac,'APPLICATION_CONTEXT_SCHEMA.APPLICATION_PROTOCOL_DEFINITION.APPLICATION') | 
                apd.application_interpreted_model_schema_name = 'ap242_managed_model_based_3d_engineering' 
                )) > 0) 
              )) > 0;    
 
  END_RULE; 

  FUNCTION cc_design_person_and_organization_correlation
   (e : cc_design_person_and_organization_assignment) : BOOLEAN; 
    LOCAL
      po_role : STRING;
    END_LOCAL;
      po_role := e\person_and_organization_assignment.role.name;
    CASE po_role OF
      'request_recipient'      : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF(['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_REQUEST'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN(FALSE);
                               END_IF;
      'initiator'              : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF(['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_REQUEST',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'START_WORK',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CHANGE'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN(FALSE);
                               END_IF;
      'creator'                : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 SIZEOF (['AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION',
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION'] *
                                 TYPEOF (x)) = 1))
                                 THEN RETURN (FALSE);
                               END_IF;
      'part_supplier'          : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'design_supplier'        : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'PRODUCT_DEFINITION_FORMATION'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'design_owner'           : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.PRODUCT'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'configuration_manager'  : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'CONFIGURATION_ITEM'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'contractor'             : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.CONTRACT'
                                 IN TYPEOF (x)))
                                 THEN RETURN(FALSE);
                               END_IF;
      'classification_officer' : IF SIZEOF (e.items) <>
                                 SIZEOF (QUERY (x <* e.items |
                                 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM.' +
                                 'SECURITY_CLASSIFICATION'
                                 IN TYPEOF (x))) THEN
                                 RETURN(FALSE);
                               END_IF;
    OTHERWISE : RETURN(TRUE);
  END_CASE;
  RETURN (TRUE);
  END_FUNCTION; 

END_SCHEMA;
