(*
   $Id$
   ISO TC184/SC4/WG12 N4587 - ISO/CD-TS 10303-1492 Function based behaviour representation - EXPRESS MIM
*)

SCHEMA Function_based_behaviour_representation_mim;

USE FROM Extended_task_element_mim;

USE FROM Foundation_representation_mim;

USE FROM systems_engineering_representation_schema
  (functional_model,
   functional_representation_context,
   functional_representation_item);

END_SCHEMA;

