(*
   $Id$
   ISO TC184/SC4/WG12 N6894 - ISO/TS 10303-1309 Drawing definition - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N5363
*)

SCHEMA Drawing_definition_mim;

USE FROM Draughting_annotation_mim;
USE FROM Presentation_hierarchy_mim;

USE FROM drawing_definition_schema;

USE FROM presentation_organization_schema
  (camera_image_2d_with_scale);
  
ENTITY drawing_sheet_layout
  SUBTYPE OF (draughting_symbol_representation);
END_ENTITY;

END_SCHEMA;
