(*
   $Id$
   ISO TC184/SC4/WG12 N4012 - ISO/TS 10303-1688 Interconnect non planar shape - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3454
*)


SCHEMA Interconnect_non_planar_shape_mim;
    USE FROM Physical_unit_3d_shape_mim;	-- ISO/TS 10303-1727	
	USE FROM Physical_unit_non_planar_design_view_mim;	-- ISO/TS 10303-1613
	USE FROM Part_template_2d_shape_mim;	-- ISO/TS 10303-1716

ENTITY manifold_constraining_context_dependent_shape_representation
  SUBTYPE OF (context_dependent_shape_representation, representation_relationship);
END_ENTITY; 

ENTITY component_part_2d_non_planar_geometric_representation_relationship
  SUBTYPE OF (shape_representation_relationship, representation_relationship_with_transformation);
END_ENTITY; 
	
END_SCHEMA;

