(*
   $Id$
   ISO TC184/SC4/WG12 N4234 - ISO/TS 10303-1763 Integral shield - EXPRESS MIM
*)

SCHEMA Integral_shield_mim;

USE FROM Layered_interconnect_module_with_printed_component_design_mim;	-- ISO/TS 10303-1700
USE FROM Requirement_assignment_mim;

ENTITY integral_shield
  SUBTYPE OF (laminate_component);
END_ENTITY;

ENTITY routed_shield 
    SUBTYPE OF (integral_shield);
END_ENTITY;

END_SCHEMA;
