(*
   $Id$
   ISO TC184/SC4/WG12 N5915 - ISO/TS 10303-1471 State based behaviour representation - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4617
*) 

SCHEMA State_based_behaviour_representation_mim;

USE FROM Foundation_representation_mim;    -- ISO/TS 10303-1006

USE FROM Foundation_state_definition_mim;    -- ISO/TS 10303-1469

USE FROM systems_engineering_representation_schema   -- ISO 10303-61
  (se_representation_proxy_select,
   state_based_behaviour_model,
   state_based_behaviour_representation_context,
   state_based_behaviour_representation_item); 


END_SCHEMA;  -- State_based_behaviour_representation_mim


