(*
 $Id$
 ISO TC184/SC4/WG12 N4371 - ISO/TS 10303-1038 Independent property representation - EXPRESS ARM
 Supersedes ISO TC184/SC4/WG12 N2966
*) 


SCHEMA Independent_property_representation_arm; 

USE FROM Property_assignment_arm;    -- ISO/TS 10303-1030 

ENTITY Independent_property_representation
  SUBTYPE OF (Property_definition_representation);
    SELF\Property_definition_representation.definition RENAMED property : Independent_property;
END_ENTITY;

END_SCHEMA;  -- Independent_property_representation_arm
