(*
 $Id$
 ISO TC184/SC4/WG3 N2165 - ISO/TS 10303-1352 Catalog data information and shape representation - EXPRESS ARM
*)

SCHEMA Catalog_data_information_and_shape_representation_arm;

USE FROM Advanced_boundary_representation_arm;

USE FROM Constructive_solid_geometry_3d_arm;

USE FROM Edge_based_wireframe_arm;

USE FROM Faceted_boundary_representation_arm;

USE FROM Geometric_tolerance_arm;

USE FROM Geometric_validation_property_representation_arm;

USE FROM Geometrically_bounded_surface_arm;

USE FROM Geometrically_bounded_wireframe_arm;

USE FROM Manifold_surface_arm;

USE FROM Shell_based_wireframe_arm;

USE FROM Surface_conditions_arm;

USE FROM Wireframe_2d_arm;

USE FROM Catalog_data_information_arm;


TYPE furniture_properties_select_ap236cc2 = EXTENSIBLE SELECT BASED_ON furniture_properties_select_ap236cc1 WITH
	(Geometric_tolerance);
END_TYPE;

SUBTYPE_CONSTRAINT subtype_exclusiveness_geometric_model FOR Geometric_model;
ONEOF (
	Advanced_brep_shape_representation ,
	Edge_based_wireframe_shape_representation ,
	Faceted_brep_shape_representation ,
	Geometrically_bounded_2d_wireframe_shape_representation ,
	Geometrically_bounded_surface_shape_representation ,
	Geometrically_bounded_wireframe_shape_representation ,
	Manifold_surface_shape_representation ,
	Shell_based_wireframe_shape_representation);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
