(*
   $Id$
   ISO TC184/SC4/WG3 N2271 - ISO/CD-TS 10303-433 Ap233 system engineering and design - EXPRESS MIM
*)

SCHEMA Ap233_system_engineering_and_design_mim;
  USE FROM Program_management_mim;
  USE FROM System_modelling_mim;
  USE FROM product_property_definition_schema   -- ISO 10303-41
  (characterized_object); 
  USE FROM state_type_schema;
	
--  push up comes from the Program_management_mim; branch

TYPE upfrompm_pmri_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(product_definition,
	descriptive_representation_item,
	measure_representation_item);
END_TYPE;

TYPE upfrompm_pmri_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(property_definition);
END_TYPE;

TYPE upfrompm_pmri_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(group,
	group_relationship,
	product_definition_formation_relationship);
END_TYPE;

TYPE upfrompm_pmri_name_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON name_item WITH
	(group,
	group_relationship);
END_TYPE;

TYPE upfrompm_pmri_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(characterized_object,
	configuration_effectivity);
END_TYPE;

TYPE upfrompm_pmri_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(descriptive_representation_item,
	representation,
	group,
	group_relationship,
	property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(group,
	group_relationship,
	property_definition_representation);
END_TYPE;


TYPE upfrompm_pmri_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH
	(group_relationship);
END_TYPE;


TYPE upfrompm_pmri_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(group,
	group_relationship,
	measure_representation_item);
END_TYPE;


TYPE upfrompm_pmri_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(descriptive_representation_item,
	measure_representation_item);
END_TYPE;


TYPE upfrompm_pmri_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(descriptive_representation_item,
	measure_representation_item);
END_TYPE;


TYPE upfrompm_pmri_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(property_definition_representation);
END_TYPE;

TYPE upfrompm_pmri_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(property_definition_representation);
END_TYPE;


TYPE upfrompm_pmri_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(product_definition_relationship);
END_TYPE;


TYPE upfrompm_pmri_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(characterized_object,
	product_definition_relationship);
END_TYPE;


TYPE upfrompm_pb_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	product,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfrompm_pb_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_aliasable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON aliasable_item WITH
	(interface_connection,
	product,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product_definition_shape,
	product_definition_formation,
	product_definition,
	shape_aspect_relationship);
END_TYPE;

TYPE upfrompm_pb_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	in_zone,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	product,
	interface_specification_definition,
	interface_specification_version,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfrompm_pb_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(alternate_product_relationship,
	interface_connection,
	interface_connector_version,
	interface_definition_connection,
	interface_specification_version,
	product,
	product_definition_formation);
END_TYPE;

TYPE upfrompm_pb_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(alternate_product_relationship,
	in_zone,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product_definition_shape,
	product,
	product_definition_formation);
END_TYPE;


TYPE upfrompm_pb_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(alternate_product_relationship,
	interface_connection,
	interface_connector_definition,
	interface_definition_connection,
	interface_specification_definition,
	product_definition);
END_TYPE;

TYPE upfrompm_pb2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_definition_connection);
END_TYPE;


TYPE upfrompm_pb3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_definition_connection);
END_TYPE;


TYPE upfrompm_pb3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(interface_connector_version,
	interface_specification_version,
	product,
	product_definition_formation);
END_TYPE;


TYPE upfrompm_pb_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfrompm_pb_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_for,
	product,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(interface_connection,
	product,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_specification_definition,
	interface_specification_version,
	product_definition_shape);
END_TYPE;


TYPE upfrompm_pb_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;


TYPE upfrompm_pb_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,	
	interface_connection,
	product,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;

TYPE upfrompm_pb_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;


TYPE upfrompm_pb_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	product,
	interface_specification_definition,
	interface_specification_version);
END_TYPE;

TYPE upfrompm_pb_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_definition_for,
	product,
	interface_specification_definition,
	interface_specification_version);
END_TYPE;


TYPE upfrompm_pb_product_definition_or_product_definition_relationship = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON product_definition_or_product_definition_relationship WITH
	(interface_connector_occurrence);
END_TYPE;


(*TYPE upfrompm_pb_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;*)

ENTITY upfrompm_pb_characterizable_hierarchical_interface_connection
  SUBTYPE OF (hierarchical_interface_connection, characterized_object);
END_ENTITY;


ENTITY upfrompm_pb_characterizable_interface_connection
  SUBTYPE OF (interface_connection, characterized_object);
END_ENTITY;


ENTITY upfrompm_pb_characterizable_interface_connector_occurrence
  SUBTYPE OF (interface_connector_occurrence, characterized_object);
END_ENTITY;


ENTITY upfrompm_pb_characterizable_interface_definition_connection
  SUBTYPE OF (interface_definition_connection, characterized_object);
END_ENTITY;


TYPE upfrompm_pb_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connector_occurrence,
	product,
	product_definition_formation);
END_TYPE;


TYPE upfrompm_pb_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(interface_connector_occurrence,
	product_definition_formation,
	shape_aspect);
END_TYPE;

TYPE upfrompm_pb_2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connection,
	product,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	interface_specification_definition,
	interface_specification_version,
	product_definition_formation,
	product_definition,
	promissory_usage_occurrence);
END_TYPE;


TYPE upfrompm_pb_selected_item_context_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_context_items WITH
	(product,
	product_definition_formation);
END_TYPE;


TYPE upfrompm_pb_selected_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_select WITH
	(interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;


TYPE upfrompm_pb_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	product,
	interface_specification_definition,
	interface_specification_version,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	product,
	interface_specification_definition,
	interface_specification_version,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_pb_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connection,
	product,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for);
END_TYPE;

TYPE upfrompm_pb_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connection,
	product,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for);
END_TYPE;


TYPE upfrompm_pb5_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;


TYPE upfrompm_ss_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(applied_action_method_assignment,
	action_method_assignment_relationship
	);
END_TYPE;

TYPE upfrompm_ss_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(applied_action_method_assignment,
	state_observed_assignment,
	state_type_assignment,
	state_observed,
	state_type);
END_TYPE;


TYPE upfrompm_ss_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(applied_action_method_assignment,
	state_observed_assignment,
	state_type_assignment,
	state_observed,
	state_type);
END_TYPE;


TYPE upfrompm_ap233_3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(group,
	requirement_source,
	applied_action_method_assignment,
	action_method_assignment_relationship,
	verification);
END_TYPE;


TYPE upfrompm_ap233_7_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	group,
	in_zone,
	requirement_assignment,
	applied_action_method_assignment,
	action_method_assignment_relationship,
	verification);
END_TYPE;


TYPE upfrompm_ap233_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(analysis_assignment,
	group,
	verification);
END_TYPE;


TYPE upfrompm_ap233_analysed_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON analysed_item WITH
	(executed_action,
	action_method,
	group,
	action_method_relationship,
	action_property,
	action_relationship,
	alternate_product_relationship,
	assembly_component_usage_substitute,
	property_definition,
	groupable_item,
	condition,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	--lessons_learned,
	action_resource_relationship,
	observation,
	observation_consequence,
	representation,
	observation_relationship,
	organization,
	organization_relationship,
	product,
	product_concept,
	product_design_to_individual,
	product_design_version_to_individual,
	product_group_relationship,
	product_planned_to_realized,
	product_relationship,
	product_definition_formation_relationship,
	product_definition,
	organizational_project_relationship,
	requirement_assignment,
	resource_property,
	--risk_analysis,
	--risk_assessment,
	--risk_consequence,
	--risk_control,
	--risk_criteria,
	--risk_estimation,
	--risk_evaluation,
	--risk_perception_relationship,
	--risk_reduction,
	--risk_relationship,
	--risk_treatment,
	state_observed,
	ascribable_state,
	state_type,
	state_observed_role,
	applied_action_method_assignment,
	task_method,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_context,
	product_definition_relationship,
	action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(verification,
	verification_evidence,
	verification_relationship);
END_TYPE;

TYPE upfrompm_ap233_name_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON name_item WITH
	(product);
END_TYPE;


TYPE upfrompm_ap233_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(assembly_component_usage_substitute,
	groupable_item,
	applied_action_method_assignment,
	verification_evidence);
END_TYPE;


(*TYPE upfrompm_ap233_characterized_activity_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_activity_definition WITH
	(analysis,
	applied_action_method_assignment
	verification,);
END_TYPE;*)


TYPE upfrompm_ap233_4_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(analysis_assignment,
	group,
	applied_action_method_assignment,
	verification);
END_TYPE;

TYPE upfrompm_ap233_2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(requirement_source,
	applied_action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(analysis_assignment,
	requirement_assignment,
	verification_evidence);
END_TYPE;

TYPE upfrompm_ap233_2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product);
END_TYPE;

TYPE upfrompm_ap233_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(applied_action_method_assignment,
	verification);
END_TYPE;


TYPE upfrompm_ap233_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	applied_action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	applied_action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_experience_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_item WITH
	(group);
END_TYPE;


TYPE upfrompm_ap233_experience_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_type_item WITH
	(analysis_assignment,
	groupable_item);
END_TYPE;


(*TYPE upfrompm_ap233_description_attribute_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON description_attribute_select WITH
	(analysed_item,
	analysis,
	groupable_item,
	event_occurrence,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	action_resource,
	observation,
	--risk_analysis,
	--risk_treatment,
	applied_action_method_assignment);
END_TYPE;*)


TYPE upfrompm_ap233_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(alternate_product_relationship,
	product,
	applied_action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	constrained_general_parameter_relationship);
END_TYPE;

TYPE upfrompm_ap233_event_occurrence_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON event_occurrence_item WITH
	(verification);
END_TYPE;


TYPE upfrompm_ap233_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH
	(executed_action,
	action_method,
	approval,
	breakdown_of,
	certification,
	condition,
	contract,
	effectivity,
	event_occurrence,
	experience_type,
	document_file,
	interface_connection,
	interface_definition_for,
	product,
	location,
	action_resource,
	observation,
	organizational_project,
	action_resource_requirement,
	--risk,
	applied_action_method_assignment,
	verification,
	versioned_action_request);
END_TYPE;


TYPE upfrompm_ap233_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(assembly_component_usage_substitute,
	applied_action_method_assignment);
END_TYPE;


TYPE upfrompm_ap233_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(alternate_product_relationship,
	in_zone,
	applied_action_method_assignment,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_issue_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON issue_reference_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	assembly_component_usage_substitute,
	group,
	characterized_object,
	action_method,
	description_attribute,
	expression_assignment,
	generic_expression,
	group_relationship,
	in_zone,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	product_definition_shape,
	configuration_effectivity,
	requirement_assignment,
	requirement_source,
	shape_aspect_relationship,
	action_method_assignment_relationship,
	verification,
	verification_evidence,
	verification_relationship);
END_TYPE;


TYPE upfrompm_ap233_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(analysis_assignment,
	assembly_component_usage_substitute,
	group,
	description_attribute,
	requirement_assignment);
END_TYPE;


TYPE upfrompm_ap233_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(analysis_assignment);
END_TYPE;


TYPE upfrompm_ap233_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(analysis_assignment);
END_TYPE;

TYPE upfrompm_ap233_observed_context_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON observed_context_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	assembly_component_usage_substitute,
	group,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	requirement_assignment,
	verification,
	verification_evidence);
END_TYPE;



TYPE upfrompm_ap233_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(alternate_product_relationship,
	applied_action_method_assignment);
END_TYPE;

TYPE upfrompm_ap233_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(alternate_product_relationship,
	applied_action_method_assignment);
END_TYPE;


TYPE upfrompm_ap233_parameter_value_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON parameter_value_select WITH
	(representation,
	representation_item,
	--risk_analysis,
	state_type,
	state_observed_relationship);
END_TYPE;


TYPE upfrompm_ap233_position_in_organization_group_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_group_item WITH
	(interface_definition_connection,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_position_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_item WITH
	(interface_definition_connection,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_position_in_organization_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_type_item WITH
	(interface_definition_connection,
	verification,
	verification_evidence);
END_TYPE;


(*TYPE upfrompm_ap233_probable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON probable_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_relationship);
END_TYPE;*)


TYPE upfrompm_ap233_location_representation_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_representation_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	constrained_general_parameter_relationship,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	applied_action_method_assignment,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connection,
	interface_definition_connection,
	applied_action_method_assignment);
END_TYPE;


(*TYPE upfrompm_ap233_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(alternate_product_relationship,
	--Analysis_assignment,
	generic_expression,
	in_zone,
	requirement_source,
	--Task_io_hierarchy,
	--Verification,
	--Verification_evidence,
	--Verification_relationship);
END_TYPE;*)

ENTITY upfrompm_ap233_characterizable_alternate_product_relationship
  SUBTYPE OF (alternate_product_relationship, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_generic_expression
  SUBTYPE OF (generic_expression, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_in_zone
  SUBTYPE OF (in_zone, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_requirement_source
  SUBTYPE OF (requirement_source, characterized_object);
END_ENTITY;

ENTITY upfrompm_ap233_characterizable_analysis_assignment
  SUBTYPE OF (analysis_assignment, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_action_method_assignment_relationship
  SUBTYPE OF (action_method_assignment_relationship, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_verification
  SUBTYPE OF (verification, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_verification_evidence
  SUBTYPE OF (verification_evidence, characterized_object);
END_ENTITY;


ENTITY upfrompm_ap233_characterizable_verification_relationship
  SUBTYPE OF (verification_relationship, characterized_object);
END_ENTITY;

TYPE upfrompm_ap233_3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	verification);
END_TYPE;


TYPE upfrompm_ap233_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(action_property,
	alternate_product_relationship,
	in_zone,
	interface_definition_for,
	action_method);
END_TYPE;


TYPE upfrompm_ap233_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(alternate_product_relationship,
	applied_approval_assignment,
	approval_person_organization,
	applied_certification_assignment,
	applied_contract_assignment,
	directed_action,
	in_zone,
	interface_definition_for,
	observation,
	applied_organization_assignment, applied_person_and_organization_assignment,
	product_concept,
	applied_organizational_project_assignment,
	action
	--risk_analysis,
	--risk_stakeholder,
	--risk_treatment
	);
END_TYPE;


TYPE upfrompm_ap233_4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	group,
	interface_connection,
	interface_definition_connection,
	interface_definition_for,
	requirement_assignment,
	action_method_assignment_relationship,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	interface_connector_occurrence,
	verification_evidence);
END_TYPE;


(*TYPE upfrompm_ap233_risk_impact_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON risk_impact_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	requirement_assignment,
	requirement_source,
	verification,
	verification_evidence,
	verification_relationship);
END_TYPE;*)


(*TYPE upfrompm_ap233_risk_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON risk_source_item WITH
	(alternate_product_relationship,
	assembly_component_usage_substitute,
	expression_assignment,
	generic_expression,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	requirement_assignment,
	requirement_source,
	verification,
	verification_evidence,
	verification_relationship);
END_TYPE;*)


TYPE upfrompm_ap233_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(in_zone);
END_TYPE;



TYPE upfrompm_ap233_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	group,
	action_method_assignment_relationship,
	verification);
END_TYPE;


TYPE upfrompm_ap233_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	group,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_person_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_type_item WITH
	(analysis_assignment,
	group,
	groupable_item,
	interface_definition_connection,
	interface_definition_for,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfrompm_ap233_verification_evidence_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON verification_evidence_item WITH
	(action_actual,
	action_request_solution,
	action_method_relationship,
	action_relationship,
	action_status,
	applied_action_request_assignment,
	alternate_product_relationship,
	analysis_assignment,
	applied_action_method_assignment,
	applied_usage_right,
	state_observed_assignment,
	applied_approval_assignment,
	assembly_component_usage_substitute,
	property_definition,
	group,
	groupable_item,
	breakdown_of,
	applied_action_assignment,
	applied_contract_assignment,
	date_assignment, date_and_time_assignment,
	ascribable_state_relationship,
	description_attribute,
	directed_action,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	expression_assignment,
	interface_connector_definition,
	interface_definition_connection,
	interface_definition_for,
	justification_group_assignment,  justification_assignment,
	product_relationship,
	justification_support_assignment,
	applied_location_assignment,
	observation,
	observation_consequence,
	observation_relationship,
	applied_organization_assignment, applied_person_and_organization_assignment,
	person,
	person_and_organization,
	applied_position_in_organization_assignment,
	product,
	product_design_to_individual,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	applied_organizational_project_assignment,
	representation,
	representation_context,
	representation_item,
	action_method,
	action_resource_relationship,
	action_property,
	--risk_analysis,
	--risk_communication,
	--risk_consequence,
	--risk_criteria,
	--risk_estimation,
	--risk_evaluation,
	--risk_treatment,
	state_observed,
	ascribable_state,
	state_observed_relationship,
	action_method_assignment_relationship,
	applied_time_interval_assignment,
	applied_person_type_assignment,
	product_definition_context,
	product_definition_relationship,
	action_method_assignment,
	versioned_action_request);
END_TYPE;


TYPE upfrompm_ap233_5_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	verification);
END_TYPE;


TYPE upfrompm_ap233_6_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	group,
	applied_action_method_assignment,
	verification_evidence);
END_TYPE;

-- start upfromsm_ from System_modelling;

TYPE upfromsm_pmri3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(location,
	representation, applied_location_representation_assignment, address);
END_TYPE;

TYPE upfromsm_os_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(position_in_organization,
	group);
END_TYPE;

TYPE upfromsm_pb3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(group);
END_TYPE;

TYPE upfromsm_ss3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(state_observed_assignment,
	action_resource,
	action,
	action_method,
	applied_action_method_assignment,
	state_observed,
	state_observed_relationship,
	task_method);
END_TYPE;

TYPE upfromsm_ap233_3_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(--risk,
	action_method);
END_TYPE;


TYPE upfromsm_pmri2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(location,
	applied_location_representation_assignment);
END_TYPE;

TYPE upfromsm_os3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(organization_type,
	position_in_organization,
	group,
	position_in_organization_type,
	person_type,
	person_type_definition);
END_TYPE;

TYPE upfromsm_pb4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product_group);
END_TYPE;

TYPE upfromsm_ss3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_resource,
	action,
	action_method,
	state_observed_relationship,
	task_method);
END_TYPE;

TYPE upfromsm_ap233_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(--applied_risk_impact_assignment,
	--Observation,
	--risk,
	task_objective);
END_TYPE;

-- activity_realization_select Doesn't appear in mim.exp.  Appears only in the mapping table, see 1307

(*TYPE upfromsm_ss_activity_realization_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON activity_realization_select WITH
	(action_method,
	action_method,
	task_method,
	task_method);
END_TYPE;*)

(*TYPE upfromsm_ap233_activity_realization_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON activity_realization_select WITH
	(executed_action,
	action_method,
	product,
	product_definition_formation,
	product_definition,
	task_element);
END_TYPE;*)


TYPE upfromsm_pb_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(product_group);
END_TYPE;


(*TYPE upfromsm_ap233_action_request_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_request_item WITH
	(risk);
END_TYPE;*)


TYPE upfromsm_pmri_aliasable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON aliasable_item WITH
	(product_relationship);
END_TYPE;


TYPE upfromsm_ap233_analysed_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON analysed_item WITH
	(group,
	--lessons_learned,
	action_resource_relationship,
	observation,
	observation_consequence,
	representation,
	observation_relationship,
	product_group_relationship,
	product_relationship,
	action_relationship,
	--risk_analysis,
	--risk_assessment,
	--risk_consequence,
	--risk_control,
	--risk_criteria,
	--risk_estimation,
	--risk_evaluation,
	--risk_perception_relationship,
	--risk_reduction,
	--risk_relationship,
	--risk_treatment,
	state_observed,
	ascribable_state,
	state_type,
	state_observed_role,
	task_method,
	action_method_assignment,
	action_method_relationship);
END_TYPE;


TYPE upfromsm_os_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(applied_experience_assignment,
	experience_type,
	applied_organization_type_assignment,
	applied_position_in_organization_assignment,
	group,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	position_in_organization_type,
	applied_qualification_type_assignment,
	qualification_type,
	person_type,
	applied_person_type_assignment);
END_TYPE;

TYPE upfromsm_pb_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(action_method_relationship,
	group,
	state_observed_assignment,
	action,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action_method,
	applied_action_method_assignment,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_approval_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON approval_item WITH
	(ascribable_state,
	state_observed_relationship,
	action_method_assignment);
END_TYPE;


TYPE upfromsm_ap233_name_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON name_item WITH
	(observation
	--risk
	);
END_TYPE;


TYPE upfromsm_pb_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(product_group,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(task_method,
	task_objective);
END_TYPE;

(*TYPE upfromsm_ap233_certification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON certification_item WITH
	(lessons_learned);
END_TYPE;*)


(*TYPE upfromsm_ss_characterized_activity_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_activity_definition WITH
	(action,
	action_method,
	task_objective);
END_TYPE;*)

(*TYPE upfromsm_ap233_characterized_activity_definition = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_activity_definition WITH
	(risk);
END_TYPE;*)



(*TYPE upfromsm_ss_characterized_resource_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON characterized_resource_select WITH
	(action_resource);
END_TYPE;*)


TYPE upfromsm_pmri_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(applied_location_assignment,
	representation, 
	address,
	applied_location_representation_assignment,
	product_relationship,
	measure_representation_item,
	selected_item,
	selected_item_assignment);
END_TYPE;

TYPE upfromsm_os_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(applied_experience_assignment,
	experience,
	organization_type,
	applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	applied_qualification_type_assignment,
	qualification_type_relationship);
END_TYPE;


TYPE upfromsm_ss_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
	(ascribable_state_relationship,
	ascribable_state);
END_TYPE;


TYPE upfromsm_pmri_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(approval,
	applied_approval_assignment,
	approval_relationship,
	approval_status,
	approval_person_organization,
	certification,
	applied_certification_assignment,
	condition,
	applied_action_method_assignment,
	action_method_relationship,
	context_dependent_unit,
	contract,
	date_assignment, date_and_time_assignment,
	descriptive_representation_item,
	document_file,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	product_definition_relationship,
	applied_external_identification_assignment,
	representation,
	effectivity,
	applied_effectivity_assignment,
	document_relationship,
	group,
	group_relationship,
	applied_identification_assignment,
	general_property,
	general_property_relationship,
	property_definition_representation,
	product,
	justification_group_assignment,  justification_assignment,
	justification_support_assignment,
	language,
	location,
	location_relationship,
	product_concept_context,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_location_representation_assignment,
	product_category,
	product_concept,
	product_relationship,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	applied_organizational_project_assignment,
	organizational_project_relationship,
	measure_representation_item,
	representation_context,
	representation_item,
	security_classification,
	time_interval_relationship,
	uncertainty_measure_with_unit,
	named_unit, derived_unit,
	measure_with_unit,
	product_definition_context);
END_TYPE;

TYPE upfromsm_os_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(person_and_organization_address,  organizational_address,
	organization_relationship,
	person_and_organization);
END_TYPE;

TYPE upfromsm_pb_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(alternate_product_relationship,
	breakdown_context,
	product_definition_group_assignment, breakdown_element_group_assignment,
	breakdown_element_usage,
	interface_connection,
	interface_connector_definition,
	interface_definition_connection,
	interface_specification_definition,
	product_definition);
END_TYPE;

TYPE upfromsm_ss_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(executed_action,
	action_method,
	action_property,
	action_property_representation,
	action_relationship,
	applied_action_assignment,
	property_definition,
	action,
	applied_event_occurrence_assignment,
	event_occurrence_relationship,
	action_resource,
	action_resource_relationship,
	property_definition_representation,
	group,
	action_resource_requirement,
	action_resource_requirement_relationship,
	resource_property,
	resource_property_representation);
END_TYPE;

TYPE upfromsm_ap233_attribute_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_classification_item WITH
	(description_attribute);
END_TYPE;


TYPE upfromsm_pmri4_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(approval,
	applied_approval_assignment,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	product_definition_relationship);
END_TYPE;

TYPE upfromsm_pb4_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(hierarchical_interface_connection,
	interface_connection,
	interface_definition_connection,
	product_definition_group_assignment, breakdown_element_group_assignment);
END_TYPE;

TYPE upfromsm_ss4_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(property_definition);
END_TYPE;

TYPE upfromsm_ap233_4_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(action_method,
	action_property,
	analysis_assignment,
	--applied_risk_impact_assignment,
	group,
	product,
	action_resource_requirement,
	action,
	--risk_analysis,
	state_type,
	applied_action_method_assignment,
	verification);
END_TYPE;



TYPE upfromsm_pmri2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(approval,
	applied_approval_assignment,
	calendar_date,
	applied_certification_assignment,
	applied_classification_assignment,
	applied_contract_assignment,
	date_assignment, date_and_time_assignment,
	date_and_time,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	applied_identification_assignment,
	property_definition_representation,
	applied_organization_assignment, applied_person_and_organization_assignment,
	product,
	product_related_product_category,
	product_concept,
	product_definition_formation,
	product_definition,
	representation,
	product_definition_relationship);
END_TYPE;

TYPE upfromsm_pb2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	product_as_individual,
	product_definition_group_assignment, breakdown_element_group_assignment);
END_TYPE;

TYPE upfromsm_ss2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(property_definition,
	property_definition_representation,
	state_observed,
	state_type);
END_TYPE;

TYPE upfromsm_ap233_2_action_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_items WITH
	(executed_action,
	action_property,
	requirement_source,
	applied_action_method_assignment,
	action_method);
END_TYPE;


TYPE upfromsm_pb_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(action_method_relationship,
	group,
	action_resource,
	action_resource_relationship,
	action,
	action_relationship,
	applied_action_method_assignment,
	task_method_relationship,
	task_method_version_relationship);
END_TYPE;

TYPE upfromsm_ap233_condition_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON condition_action_method_items WITH
	(applied_location_assignment,
	applied_qualification_type_assignment
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_ss2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_resource,
	action_resource_relationship,
	action,
	state_observed,
	ascribable_state);
END_TYPE;

(*TYPE upfromsm_ap233_3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(risk_analysis);
END_TYPE;*)


TYPE upfromsm_pb_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(product_group,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(action_method_relationship,
	group,
	action_resource,
	action,
	task_method,
	applied_action_method_assignment,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_contract_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON contract_item WITH
	(issue
	--risk_analysis,
	--risk_control,
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_pmri_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(applied_location_assignment,
	representation, applied_location_representation_assignment, address,
	product_relationship,
	selected_item);
END_TYPE;

TYPE upfromsm_pmri_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(applied_location_assignment,
	representation, applied_location_representation_assignment, address,
	product_relationship,
	selected_item);
END_TYPE;

TYPE upfromsm_os_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(applied_organization_type_assignment,
	applied_position_in_organization_assignment,
	group,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	applied_person_type_assignment);
END_TYPE;

TYPE upfromsm_os_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(applied_organization_type_assignment,
	applied_position_in_organization_assignment,
	group,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	applied_person_type_assignment);
END_TYPE;

TYPE upfromsm_pb_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_pb_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_date_and_time_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_and_time_item WITH
	(action_method_relationship,
	group,
	action,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action_method,
	applied_action_method_assignment,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ss_date_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON date_item WITH
	(action_method_relationship,
	group,
	action,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action_method,
	applied_action_method_assignment,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;


TYPE upfromsm_ap233_experience_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_item WITH
	(group,
	applied_event_occurrence_assignment,
	--lessons_learned,
	observation_consequence,
	product,
	organizational_project,
	--risk_analysis,
	action_method);
END_TYPE;


TYPE upfromsm_ap233_person_definition_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_definition_item WITH
	(group,
	applied_position_in_organization_group_assignment,
	position_in_organization_assignment,
	position_in_organization_type_assignment,
	--risk_stakeholder,
	applied_person_type_assignment,
	action_method_assignment);
END_TYPE;


TYPE upfromsm_ap233_experience_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_type_item WITH
	(analysis_assignment,
	groupable_item,
	event_occurrence,
	issue,
	--lessons_learned,
	observation_consequence,
	product,
	product_group,
	--risk_analysis,
	--risk_assessment,
	action_method_assignment);
END_TYPE;


(*TYPE upfromsm_ap233_description_attribute_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON description_attribute_select WITH
	(action_resource,
	observation,
	risk_analysis,
	risk_treatment);
END_TYPE;*)


TYPE upfromsm_pmri_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(location,
	applied_location_assignment,
	location_relationship,
	applied_location_representation_assignment,
	product_relationship,
	representation,
	selected_item);
END_TYPE;

TYPE upfromsm_os_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(experience,
	experience_type,
	organization_type,
	applied_position_in_organization_assignment,
	group,
	position_in_organization,
	position_in_organization_type,
	applied_position_in_organization_type_assignment,
	position_in_organization_type_assignment,
	qualification_type,
	person_type,
	person_type_definition);
END_TYPE;

TYPE upfromsm_pb_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(action_method_relationship,
	group,
	action,
	action_resource,
	state_observed,
	ascribable_state,
	task_method,
	applied_action_method_assignment,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

(*TYPE upfromsm_ap233_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH
	(risk_analysis,
	risk_treatment);
END_TYPE;*)


TYPE upfromsm_pmri_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(applied_location_assignment,
	product_relationship,
	selected_item_assignment);
END_TYPE;

TYPE upfromsm_os_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(group,
	applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	applied_person_type_assignment);
END_TYPE;


TYPE upfromsm_ss_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(action_resource_relationship);
END_TYPE;

TYPE upfromsm_ap233_effectivity_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON effectivity_item WITH
	(state_observed_assignment,
	issue_consequence
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_ap233_event_occurrence_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON event_occurrence_item WITH
	(observation
	--risk
	);
END_TYPE;


TYPE upfromsm_ap233_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH
	(--risk_stakeholder,
	action_method);
END_TYPE;


TYPE upfromsm_ap233_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH
	(experience_type,
	location,
	action_resource,
	observation,
	--risk,
	action_method);
END_TYPE;


TYPE upfromsm_pmri_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(location,
	representation, 
	 address,
	applied_location_representation_assignment,
	product_relationship);
END_TYPE;

TYPE upfromsm_os_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(experience_type,
	organization_type,
	applied_position_in_organization_assignment,
	group,
	position_in_organization_assignment,
	applied_qualification_type_assignment,
	qualification_type,
	person_type);
END_TYPE;

TYPE upfromsm_pb_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(action_method_relationship,
	group,
	action,
	action_resource,
	task_method_relationship,
	applied_action_method_assignment,
	task_method,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
	(--applied_risk_probability_assignment,
	--applied_risk_impact_assignment,
	--applied_risk_source_assignment,
	--risk,
	--risk_analysis,
	--risk_identification,
	--risk_consequence,
	--risk_stakeholder,
	--risk_treatment,
	applied_action_method_assignment);
END_TYPE;


TYPE upfromsm_ss_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(task_method,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_ir_usage_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON ir_usage_item WITH
	(action_resource,
	--risk_treatment,
	action_method);
END_TYPE;


TYPE upfromsm_ap233_issue_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON issue_reference_item WITH
	(executed_action,
	action_method,
	action_request_solution,
	action_relationship,
	group,
	action_method_relationship,
	action_property,
	action_property_representation,
	action_status,
	address,
	person_and_organization_address,  organizational_address,
	applied_action_request_assignment,
	alternate_product_relationship,
	analysis_assignment,
	applied_action_assignment,
	applied_action_method_assignment,
	applied_usage_right,
	--applied_risk_probability_assignment,
	--applied_risk_impact_assignment,
	--applied_risk_source_assignment,
	--risk_status_assignment,
	state_observed_assignment,
	state_type_assignment,
	approval,
	applied_approval_assignment,
	approval_relationship,
	approval_status,
	approval_person_organization,
	assembly_component_usage_substitute,
	property_definition,
	applied_attribute_classification_assignment,
	multi_language_attribute_assignment,
	breakdown_context,
	breakdown_of,
	calendar_date,
	certification,
	applied_certification_assignment,
	characterized_object,
	class,
	applied_classification_assignment,
	condition,
	action,
	contract,
	applied_contract_assignment,
	date_assignment, date_and_time_assignment,
	date_and_time,
	ascribable_state_relationship,
	description_attribute,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	product_definition_relationship,
	effectivity,
	applied_effectivity_assignment,
	effectivity_relationship,
	event_occurrence,
	applied_event_occurrence_assignment,
	event_occurrence_relationship,
	applied_experience_assignment,
	experience,
	experience_type,
	experience_type_relationship,
	expression_assignment,
	external_class_library,
	applied_external_identification_assignment,
	document_file,
	document_relationship,
	generic_expression,
	group_relationship,
	applied_identification_assignment,
	in_zone,
	general_property,
	general_property_relationship,
	information_right,
	information_usage_right,
	usage_association,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	configuration_design,
	product_definition_shape,
	configuration_effectivity,
	product,
	justification_group_assignment,  justification_assignment,
	product_relationship,
	justification_support_assignment,
	language,
	attribute_language_assignment,
	local_time,
	location,
	applied_location_assignment,
	location_relationship,
	representation, applied_location_representation_assignment, 
	action_resource,
	action_resource_relationship,
	product_concept_context,
	applied_name_assignment,
	observation,
	observation_consequence,
	observation_relationship,
	organization,
	applied_organization_assignment, applied_person_and_organization_assignment,
	applied_organization_type_assignment,
	organization_relationship,
	organization_type,
	person,
	person_and_organization,
	position_in_organization,
	applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	position_in_organization_relationship,
	position_in_organization_assignment,
	position_in_organization_type,
	position_in_organization_type_assignment,
	product_category,
	product_related_product_category,
	product_category_relationship,
	product_concept,
	configuration_item,
	product_definition_group_assignment, breakdown_element_group_assignment,
	product_design_to_individual,
	product_design_version_to_individual,
	product_group,
	product_group_membership,
	product_group_relationship,
	product_planned_to_realized,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	organizational_project_relationship,
	property_definition_representation,
	applied_qualification_type_assignment,
	qualification_type,
	qualification_type_relationship,
	measure_representation_item,
	representation_context,
	representation_item,
	action_resource_requirement,
	action_resource_requirement_relationship,
	requirement_assignment,
	requirement_source,
	resource_property,
	resource_property_representation,
	--risk,
	--risk_analysis,
	--risk_assessment,
	--risk_attitude,
	--risk_communication,
	--risk_consequence,
	--risk_context,
	--risk_control,
	--risk_estimation,
	--risk_evaluation,
	--risk_identification,
	--risk_owner_person_assignment, --risk_owner_person_and_organization_assignment, --risk_owner_organization_assignment,
	--risk_perception,
	--risk_perception_formation,
	--risk_perception_relationship,
	--risk_reduction,
	--risk_relationship,
	--risk_stakeholder,
	--risk_status,
	--risk_treatment,
	security_classification,
	applied_security_classification_assignment,
	selected_item_assignment,
	shape_aspect_relationship,
	state_observed,
	ascribable_state,
	state_type,
	state_type_relationship,
	state_type_role,
	state_observed_relationship,
	state_observed_role,
	action_method_assignment_relationship,
	task_objective,
	time_interval,
	applied_time_interval_assignment,
	time_interval_relationship,
	time_interval_role,
	coordinated_universal_time_offset,
	person_type,
	applied_person_type_assignment,
	person_type_definition,
	person_type_definition_relationship,
	applied_person_type_definition_assignment,
	named_unit, derived_unit,
	measure_with_unit,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_context,
	action_method_assignment,
	versioned_action_request,
	action_request_status);
END_TYPE;


TYPE upfromsm_pmri_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(applied_location_assignment);
END_TYPE;


TYPE upfromsm_ss_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(action_method_relationship,
	group,
	action_resource_relationship,
	action_resource,
	action,
	ascribable_state,
	applied_action_method_assignment,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_justification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_item WITH
	(issue,
	qualification_type
	--risk
	);
END_TYPE;


TYPE upfromsm_pmri_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(location,
	applied_location_assignment);
END_TYPE;


TYPE upfromsm_ss_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(state_observed_assignment,
	state_observed,
	state_observed_relationship);
END_TYPE;

(*TYPE upfromsm_ap233_justification_support_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON justification_support_item WITH
	(risk_analysis,
	risk_consequence,
	risk_stakeholder);
END_TYPE;*)


TYPE upfromsm_pmri_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(product,
	product_definition,
	product_definition_formation,
	document_file,
	organizational_project);
END_TYPE;

TYPE upfromsm_os_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(organization,
	organization_type,
	person,
	person_and_organization,
	position_in_organization,
	position_in_organization_type,
	person_type);
END_TYPE;

TYPE upfromsm_pb_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	product_group);
END_TYPE;

TYPE upfromsm_ss_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(executed_action,
	applied_action_assignment,
	applied_action_method_assignment,
	action_resource_requirement,
	action_method,
	action_resource,
	task_element,
	task_method,
	task_method_version_relationship);
END_TYPE;

TYPE upfromsm_ap233_location_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_item WITH
	(analysis_assignment,
	event_occurrence
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_ap233_observation_recorder_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON observation_recorder_item WITH
	(person,
	person_and_organization,
	applied_person_type_assignment);
END_TYPE;


TYPE upfromsm_ap233_observed_context_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON observed_context_item WITH
	(executed_action,
	action_method,
	action_property,
	alternate_product_relationship,
	analysis_assignment,
	applied_action_assignment,
	applied_action_method_assignment,
	--applied_risk_impact_assignment,
	--applied_risk_source_assignment,
	state_observed_assignment,
	state_type_assignment,
	applied_approval_assignment,
	assembly_component_usage_substitute,
	property_definition,
	group,
	applied_certification_assignment,
	applied_contract_assignment,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	applied_event_occurrence_assignment,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	issue,
	justification_group_assignment,  justification_assignment,
	action_resource,
	observation_consequence,
	product,
	product_concept,
	configuration_item,
	product_design_to_individual,
	product_group,
	product_planned_to_realized,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	property_definition_representation,
	representation,
	representation_item,
	action_resource_requirement,
	requirement_assignment,
	action,
	resource_property,
	--risk,
	--risk_analysis,
	--risk_assessment,
	--risk_attitude,
	--risk_consequence,
	--risk_control,
	--risk_estimation,
	--risk_evaluation,
	--risk_context,
	--risk_perception,
	--risk_reduction,
	--risk_status,
	--risk_treatment,
	applied_security_classification_assignment,
	state_observed,
	ascribable_state,
	state_type,
	state_type_relationship,
	state_observed_relationship,
	state_observed_role,
	task_method,
	task_objective,
	verification,
	verification_evidence,
	product_definition_relationship);
END_TYPE;


TYPE upfromsm_pmri_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(applied_location_assignment,
	product_relationship,
	selected_item,
	selected_item_assignment);
END_TYPE;

TYPE upfromsm_pmri_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(applied_location_assignment,
	product_relationship,
	selected_item,
	selected_item_assignment);
END_TYPE;

TYPE upfromsm_os_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	position_in_organization_type,
	applied_person_type_assignment);
END_TYPE;

TYPE upfromsm_os_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(applied_position_in_organization_assignment,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_type_assignment,
	position_in_organization_type,
	applied_person_type_assignment);
END_TYPE;

TYPE upfromsm_pb_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_pb_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(action_method_relationship,
	group,
	action,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action_method,
	task_method_relationship,
	applied_action_method_assignment,
	task_method,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ss_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(action_method_relationship,
	group,
	action,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action_method,
	task_method_relationship,
	applied_action_method_assignment,
	task_method,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_person_and_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_and_organization_item WITH
	(issue_consequence,
	--risk_analysis,
	--risk_assessment,
	--risk_communication,
	--risk_control,
	--risk_estimation,
	--risk_identification,
	--risk_owner_person_assignment, --risk_owner_person_and_organization_assignment, --risk_owner_organization_assignment,
	applied_action_method_assignment,
	task_method);
END_TYPE;


TYPE upfromsm_ap233_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON organization_item WITH
	(issue_consequence,
	--risk_analysis,
	--risk_assessment,
	--risk_communication,
	--risk_control,
	--risk_estimation,
	--risk_identification,
	--risk_owner_person_assignment, --risk_owner_person_and_organization_assignment, --risk_owner_organization_assignment,
	applied_action_method_assignment,
	task_method);
END_TYPE;


TYPE upfromsm_ap233_parameter_value_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON parameter_value_select WITH
	(--risk_analysis,
	state_observed_relationship);
END_TYPE;


TYPE upfromsm_ap233_2_experience_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON experience_type_item WITH
	(applied_organization_assignment, applied_person_and_organization_assignment,
	applied_position_in_organization_assignment,
	group,
	--risk_stakeholder,
	person_type,
	person_type_definition_relationship);
END_TYPE;


TYPE upfromsm_pmri_position_in_organization_group_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_group_item WITH
	(approval_person_organization,
	product_definition,
	applied_organization_assignment, applied_person_and_organization_assignment);
END_TYPE;

TYPE upfromsm_pb_position_in_organization_group_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_group_item WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfromsm_ap233_position_in_organization_group_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_group_item WITH
	(executed_action,
	action_method,
	event_occurrence,
	interface_definition_connection,
	location,
	product_category,
	product_concept,
	configuration_item,
	product_group,
	organizational_project,
	action_resource_requirement,
	action,
	state_observed,
	verification,
	verification_evidence,
	action_method_assignment,
	versioned_action_request);
END_TYPE;


TYPE upfromsm_pmri_position_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_item WITH
	(approval_person_organization,
	product_definition,
	applied_organization_assignment, applied_person_and_organization_assignment);
END_TYPE;

TYPE upfromsm_pb_position_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_item WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfromsm_ap233_position_in_organization_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_item WITH
	(executed_action,
	action_method,
	event_occurrence,
	interface_definition_connection,
	location,
	product_category,
	product_concept,
	configuration_item,
	product_group,
	organizational_project,
	action_resource_requirement,
	action,
	state_observed,
	verification,
	verification_evidence,
	action_method_assignment,
	versioned_action_request);
END_TYPE;


TYPE upfromsm_pmri_position_in_organization_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_type_item WITH
	(approval_person_organization,
	product_definition,
	applied_organization_assignment, applied_person_and_organization_assignment);
END_TYPE;

TYPE upfromsm_pb_position_in_organization_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_type_item WITH
	(product,
	product_definition_formation,
	product_definition);
END_TYPE;

TYPE upfromsm_ap233_position_in_organization_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON position_in_organization_type_item WITH
	(executed_action,
	action_method,
	event_occurrence,
	interface_definition_connection,
	location,
	product_category,
	product_concept,
	configuration_item,
	product_group,
	organizational_project,
	action_resource_requirement,
	action,
	state_observed,
	verification,
	verification_evidence,
	action_method_assignment,
	versioned_action_request);
END_TYPE;


(*TYPE upfromsm_ap233_probable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON probable_item WITH
	(executed_action,
	action_method,
	action_method_relationship,
	action_property,
	action_relationship,
	alternate_product_relationship,
	applied_action_method_assignment,
	state_observed_assignment,
	assembly_component_usage_substitute,
	condition,
	applied_action_assignment,
	contract,
	applied_contract_assignment,
	general_property,
	general_property_relationship,
	action_resource,
	product_concept_context,
	product,
	product_definition_formation,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	representation,
	representation_item,
	action_resource_requirement,
	action_method,
	action,
	resource_property,
	state_observed,
	state_type,
	state_type_relationship,
	state_observed_relationship,
	applied_action_method_assignment,
	task_objective,
	applied_action_method_assignment,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_relationship);
END_TYPE;*)


TYPE upfromsm_ap233_location_representation_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON location_representation_item WITH
	(executed_action,
	action_method,
	alternate_product_relationship,
	assembly_component_usage_substitute,
	breakdown_of,
	applied_action_assignment,
	constrained_general_parameter_relationship,
	event_occurrence,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	product,
	attribute_language_assignment,
	--lessons_learned,
	action_resource,
	product_concept_context,
	--Observation,
	--risk_organization_stakeholder,
	organization_type,
	product_concept,
	organizational_project,
	representation,
	action_resource_requirement,
	action,
	resource_property,
	--risk,
	--risk_assessment,
	--risk_attitude,
	--risk_consequence,
	--risk_estimation,
	--risk_reduction,
	--risk_stakeholder,
	--risk_treatment,
	state_observed,
	state_type,
	state_observed_relationship,
	applied_action_method_assignment,
	verification,
	verification_evidence,
	product_definition_relationship,
	versioned_action_request);
END_TYPE;



TYPE upfromsm_pb_product_definition_or_product_definition_relationship = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON product_definition_or_product_definition_relationship WITH
	(product_group);
END_TYPE;


TYPE upfromsm_pb_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(action_method_relationship,
	group,
	task_method,
	applied_action_method_assignment,
	task_objective);
END_TYPE;

(*TYPE upfromsm_ap233_project_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON project_item WITH
	(applied_risk_impact_assignment,
	applied_risk_source_assignment,
	lessons_learned,
	risk_person_stakeholder,
	risk_analysis,
	risk_communication,
	risk_control,
	risk_evaluation,
	risk_identification,
	risk_context,
	risk_reduction,
	risk_relationship,
	risk_stakeholder);
END_TYPE;*)


(*TYPE upfromsm_pmri_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(applied_location_assignment);
END_TYPE;*)

ENTITY upfromsm_pmri_characterizable_applied_location_assignment
  SUBTYPE OF (applied_location_assignment, characterized_object);
END_ENTITY;


(*TYPE upfromsm_ss_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(applied_action_method_assignment,
	applied_action_method_assignment);
END_TYPE;*)

ENTITY upfromsm_ss_characterizable_applied_action_method_assignment
  SUBTYPE OF (applied_action_method_assignment, characterized_object);
END_ENTITY;


(*TYPE upfromsm_ap233_property_assignment_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON property_assignment_select WITH
	(applied_risk_probability_assignment,
	applied_risk_impact_assignment,
	applied_risk_source_assignment,
	action,
	applied_action_assignment,
	--Observation,
	--Observation_consequence,
	product_group,
	group,
	action_resource,
	action,
	risk_analysis,
	risk_assessment,
	risk_consequence,
	risk_control,
	risk_estimation,
	risk_evaluation,
	risk_context,
	risk_perception,
	risk_reduction,
	risk_treatment,
	ascribable_state,
	ascribable_state,
	task_objective);
END_TYPE;*)

ENTITY upfromsm_ap233_characterizable_action
  SUBTYPE OF (action, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_applied_action_assignment
  SUBTYPE OF (applied_action_assignment, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_action_resource
  SUBTYPE OF (action_resource, characterized_object);
END_ENTITY;


(*ENTITY upfromsm_ap233_characterizable_applied_risk_impact_assignment
  SUBTYPE OF (applied_risk_impact_assignment, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_applied_risk_probability_assignment
  SUBTYPE OF (applied_risk_probability_assignment, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_applied_risk_source_assignment
  SUBTYPE OF (risk_source_assignment, characterized_object);
END_ENTITY;*)


ENTITY upfromsm_ap233_characterizable_ascribable_state
  SUBTYPE OF (ascribable_state, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_group
  SUBTYPE OF (group, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_product_group
  SUBTYPE OF (product_group, characterized_object);
END_ENTITY;


(*ENTITY upfromsm_ap233_characterizable_risk_analysis
  SUBTYPE OF (risk_analysis, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_assessment
  SUBTYPE OF (risk_assessment, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_consequence
  SUBTYPE OF (risk_consequence, characterized_object);
END_ENTITY;


ENTITY vcharacterizable_risk_context
  SUBTYPE OF (risk_context, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_control
  SUBTYPE OF (risk_control, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_estimation
  SUBTYPE OF (risk_estimation, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_evaluation
  SUBTYPE OF (risk_evaluation, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_perception
  SUBTYPE OF (risk_perception, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_reduction
  SUBTYPE OF (risk_reduction, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_risk_treatment
  SUBTYPE OF (risk_treatment, characterized_object);
END_ENTITY;
*)

ENTITY upfromsm_ap233_characterizable_task_objective
  SUBTYPE OF (task_objective, characterized_object);
END_ENTITY;

ENTITY upfromsm_ap233_characterizable_observation
  SUBTYPE OF (observation, characterized_object);
END_ENTITY;


ENTITY upfromsm_ap233_characterizable_observation_consequence
  SUBTYPE OF (observation_consequence, characterized_object);
END_ENTITY;
  
TYPE upfromsm_os4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(position_in_organization,
	position_in_organization_type,
	person_type);
END_TYPE;

TYPE upfromsm_ss6_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_method,
	task_method,
	applied_action_method_assignment,
	task_method_version_relationship);
END_TYPE;

TYPE upfromsm_ap233_4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(applied_action_assignment,
	action_resource
	--risk_analysis,
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_ss_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(state_observed_assignment,
	state_observed);
END_TYPE;

TYPE upfromsm_ap233_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH
	(action_method);
END_TYPE;


TYPE upfromsm_ss_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(state_observed_assignment,
	state_observed);
END_TYPE;

TYPE upfromsm_ap233_requirement_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_source_item WITH
	(observation,
	action
	--risk_analysis,
	--risk_stakeholder,
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_ap233_5_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_actual,
	action_method,
	action_request_solution,
	action_method_relationship,
	applied_action_request_assignment,
	analysis_assignment,
	applied_action_assignment,
	applied_action_method_assignment,
	--applied_risk_impact_assignment,
	group,
	certification,
	applied_certification_assignment,
	state_type_assignment,
	contract,
	applied_contract_assignment,
	directed_action,
	event_occurrence,
	applied_event_occurrence_assignment,
	interface_connection,
	interface_definition_connection,
	interface_definition_for,
	--lessons_learned,
	observation,
	observation_consequence,
	representation,
	product,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	representation_item,
	requirement_assignment,
	action,
	action_property,
	action_relationship,
	--risk,
	--risk_analysis,
	--risk_assessment,
	--risk_communication,
	--risk_control,
	--risk_estimation,
	--risk_evaluation,
	--risk_consequence,
	--risk_context,
	--risk_perception,
	--risk_reduction,
	--risk_treatment,
	applied_security_classification_assignment,
	state_observed,
	ascribable_state,
	state_type,
	state_type_relationship,
	state_observed_relationship,
	state_observed_role,
	action_method_assignment_relationship,
	task_objective,
	verification,
	verification_evidence,
	action_method_assignment);
END_TYPE;


TYPE upfromsm_pmri_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(location);
END_TYPE;

TYPE upfromsm_pb_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product_group);
END_TYPE;

TYPE upfromsm_ap233_2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_resource,
	applied_position_in_organization_group_assignment);
END_TYPE;


TYPE upfromsm_pmri3_action_method_items= EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(location);
END_TYPE;

TYPE upfromsm_os5_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(organization_type,
	position_in_organization,
	position_in_organization_type,
	person_type);
END_TYPE;

TYPE upfromsm_pb2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product_group);
END_TYPE;


(*TYPE upfromsm_ap233_risk_impact_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON risk_impact_item WITH
	(executed_action,
	action_method,
	group,
	action_property,
	action_relationship,
	alternate_product_relationship,
	applied_action_assignment,
	state_observed_assignment,
	approval,
	assembly_component_usage_substitute,
	breakdown_context,
	breakdown_of,
	condition,
	ascribable_state_relationship,
	event_occurrence,
	event_occurrence_relationship,
	general_property,
	general_property_relationship,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	issue,
	issue_consequence,
	action_resource,
	action_resource_relationship,
	product_concept_context,
	organization,
	applied_organization_assignment, applied_person_and_organization_assignment,
	person,
	person_and_organization,
	product,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	representation,
	representation_item,
	action_resource_requirement,
	action_method,
	requirement_assignment,
	requirement_source,
	action,
	action_resource,
	action_method,
	action_resource_relationship,
	resource_property,
	state_observed,
	ascribable_state,
	ascribable_state,
	state_type_relationship,
	state_observed_relationship,
	applied_action_method_assignment,
	task_objective,
	applied_action_method_assignment,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_relationship);
END_TYPE;*)


(*TYPE upfromsm_ap233_risk_source_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON risk_source_item WITH
	(action_property,
	action_relationship,
	alternate_product_relationship,
	state_observed_assignment,
	approval,
	approval_person_organization,
	assembly_component_usage_substitute,
	property_definition,
	breakdown_context,
	breakdown_of,
	applied_certification_assignment,
	condition,
	applied_action_assignment,
	contract,
	applied_contract_assignment,
	ascribable_state_relationship,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	applied_effectivity_assignment,
	event_occurrence,
	applied_event_occurrence_assignment,
	event_occurrence_relationship,
	applied_experience_assignment,
	experience,
	expression_assignment,
	document_file,
	generic_expression,
	general_property,
	general_property_relationship,
	information_right,
	information_usage_right,
	interface_connection,
	interface_connector_occurrence,
	interface_definition_connection,
	interface_definition_for,
	product,
	justification_group_assignment,  justification_assignment,
	product_relationship,
	justification_group_assignment, justification_support_assignment,
	action_resource,
	action_resource_relationship,
	product_concept_context,
	observation,
	observation_consequence,
	observation_relationship,
	organization,
	applied_organization_assignment, applied_person_and_organization_assignment,
	person,
	person_and_organization,
	applied_position_in_organization_assignment,
	group,
	position_in_organization,
	applied_position_in_organization_assignment,
	group,
	applied_position_in_organization_group_assignment,
	applied_position_in_organization_assignment,
	applied_position_in_organization_type_assignment,
	position_in_organization_relationship,
	position_in_organization_assignment,
	position_in_organization_type,
	applied_position_in_organization_type_assignment,
	position_in_organization_type_assignment,
	product_concept,
	product_design_to_individual,
	product_design_version_to_individual,
	product_group,
	product_group_relationship,
	product_planned_to_realized,
	product_definition_formation,
	product_definition_formation_relationship,
	product_definition,
	organizational_project,
	applied_organizational_project_assignment,
	organizational_project_relationship,
	applied_qualification_type_assignment,
	qualification_type,
	representation,
	representation_item,
	action_resource_requirement,
	action_method,
	requirement_assignment,
	requirement_source,
	action_resource,
	action,
	action_resource,
	action_method,
	action_resource_relationship,
	resource_property,
	selected_item,
	selected_item_assignment,
	state_observed,
	ascribable_state,
	ascribable_state,
	state_type,
	state_type_relationship,
	state_observed_relationship,
	applied_action_method_assignment,
	task_objective,
	applied_action_method_assignment,
	person_type,
	applied_person_type_assignment,
	person_type_definition,
	person_type_definition_relationship,
	applied_person_type_definition_assignment,
	verification,
	verification_evidence,
	verification_relationship,
	product_definition_relationship,
	action_method,
	action_method,
	action_method_assignment);
END_TYPE;*)


TYPE upfromsm_pmri_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(product_relationship);
END_TYPE;

TYPE upfromsm_pb_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(product_group,
	product_group_membership,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(action_method_relationship,
	group,
	applied_action_method_assignment,
	task_method,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_security_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON security_classification_item WITH
	(action_resource
	--risk_communication,
	--risk_consequence,
	--risk_treatment
	);
END_TYPE;


TYPE upfromsm_pmri_selected_item_context_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_context_items WITH
	(contract,
	product_concept,
	configuration_item,
	organizational_project);
END_TYPE;

TYPE upfromsm_pb_selected_item_context_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_context_items WITH
	(product,
	product_definition_formation,
	product_as_individual,
	Product_as_individual_version);
END_TYPE;


TYPE upfromsm_pmri_selected_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_select WITH
	(product,
	product_definition_formation);
END_TYPE;

TYPE upfromsm_pb_selected_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON selected_item_select WITH
	(interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_definition_connection);
END_TYPE;


TYPE upfromsm_pmri_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(location);
END_TYPE;


TYPE upfromsm_pb_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(product_group);
END_TYPE;

TYPE upfromsm_ss_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(action_resource,
	action_method,
	action_resource_relationship,
	action,
	action_property,
	action_relationship);
END_TYPE;

TYPE upfromsm_ap233_state_type_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_type_of_item WITH
	(--applied_risk_impact_assignment,
	--lessons_learned,
	observation_consequence,
	--risk,
	--risk_attitude,
	--risk_control,
	--risk_consequence,
	--risk_context,
	--risk_treatment,
	state_observed);
END_TYPE;


TYPE upfromsm_pmri_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(certification,
	contract,
	document_file,
	location,
	product_concept,
	configuration_item,
	security_classification,
	product_definition_relationship);
END_TYPE;

TYPE upfromsm_os_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(organization,
	person_and_organization);
END_TYPE;

TYPE upfromsm_pb_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(alternate_product_relationship,
	assembly_component_usage,
	assembly_component_usage_substitute,
	product,
	product_definition,
	product_definition_group_assignment, breakdown_element_group_assignment,
	breakdown_element_usage,
	product_definition_formation,
	interface_connection,
	interface_connector_definition,
	interface_connector_occurrence,
	interface_connector_version,
	interface_definition_connection,
	interface_specification_definition,
	interface_specification_version,
	product_as_individual,
	product_as_individual_view,
	product_as_planned,
	product_as_realized,
	product_group);
END_TYPE;

TYPE upfromsm_ss_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(executed_action,
	action_method,
	applied_action_assignment,
	action_resource,
	action_resource_relationship,
	action,
	action_property,
	action_relationship,
	task_method,
	task_objective);
END_TYPE;

TYPE upfromsm_ap233_state_observed_of_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON state_observed_of_item WITH
	(alternate_product_relationship,
	analysis_assignment,
	--applied_risk_impact_assignment,
	state_type_assignment,
	group,
	product_definition,
	product,
	product_definition_formation,
	event_occurrence,
	document_file,
	applied_external_identification_assignment,
	observation,
	observation_consequence,
	--risk_analysis,
	--risk_attitude,
	--risk_communication,
	--risk_control,
	--risk_evaluation,
	--risk_consequence,
	--risk_perception,
	--risk_treatment,
	state_observed,
	ascribable_state,
	state_type,
	state_type_relationship,
	state_observed_relationship,
	state_observed_role,
	person_type,
	verification,
	verification_evidence);
END_TYPE;


TYPE upfromsm_pmri_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(representation,
	location,
	applied_location_assignment,
	location_relationship,
	applied_location_representation_assignment,
	product_relationship,
	measure_representation_item);
END_TYPE;

TYPE upfromsm_pmri_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(representation,
	location,
	applied_location_assignment,
	location_relationship,
	applied_location_representation_assignment,
	product_relationship,
	measure_representation_item);
END_TYPE;

TYPE upfromsm_os_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(applied_experience_assignment,
	experience_type,
	organization_type,
	position_in_organization,
	group,
	position_in_organization_relationship,
	position_in_organization_assignment,
	position_in_organization_type,
	qualification_type,
	person_type,
	applied_person_type_assignment,
	person_type_definition,
	person_type_definition_relationship);
END_TYPE;

TYPE upfromsm_os_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(applied_experience_assignment,
	experience_type,
	organization_type,
	position_in_organization,
	group,
	position_in_organization_relationship,
	position_in_organization_assignment,
	position_in_organization_type,
	qualification_type,
	person_type,
	applied_person_type_assignment,
	person_type_definition,
	person_type_definition_relationship);
END_TYPE;

TYPE upfromsm_pb_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(product_group,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_pb_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(product_group,
	product_group_relationship);
END_TYPE;

TYPE upfromsm_ss_multi_language_attribute_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON multi_language_attribute_item WITH
	(action_method_relationship,
	group,
	action,
	action_resource,
	action_resource_relationship,
	action_property,
	action_relationship,
	task_method_relationship,
	task_method,
	applied_action_method_assignment,
	task_method_version_relationship,
	task_objective);
END_TYPE;

TYPE upfromsm_ss_attribute_language_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON attribute_language_item WITH
	(action_method_relationship,
	group,
	action,
	action_resource,
	action_resource_relationship,
	action_property,
	action_relationship,
	task_method,
	applied_action_method_assignment,
	task_method_relationship,
	task_method_version_relationship,
	task_objective);
END_TYPE;


TYPE upfromsm_os_person_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_type_item WITH
	(person_and_organization,
	position_in_organization,
	group,
	position_in_organization_type);
END_TYPE;

TYPE upfromsm_ap233_person_type_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON person_type_item WITH
	(executed_action,
	action_method,
	action_request_solution,
	analysis_assignment,
	--applied_risk_impact_assignment,
	group,
	groupable_item,
	applied_document_reference,  applied_document_usage_constraint_assignment,
	applied_experience_assignment,
	experience,
	experience_type,
	interface_definition_connection,
	interface_definition_for,
	observation_consequence,
	product,
	product_definition_formation,
	organizational_project,
	applied_organizational_project_assignment,
	--risk_analysis,
	--risk_treatment,
	verification,
	verification_evidence,
	product_definition_relationship,
	action_method_assignment,
	versioned_action_request);
END_TYPE;



TYPE upfromsm_ap233_verification_evidence_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON verification_evidence_item WITH
	(state_observed_assignment,
	applied_action_assignment,
	ascribable_state_relationship,
	applied_location_assignment,
	observation,
	observation_consequence,
	observation_relationship,
	applied_position_in_organization_assignment,
	action_method,
	action_resource_relationship,
	action_property,
	action_relationship,
	--risk_analysis,
	--risk_communication,
	--risk_consequence,
	--risk_criteria,
	--risk_estimation,
	--risk_evaluation,
	--risk_treatment,
	state_observed,
	ascribable_state,
	state_observed_relationship,
	applied_action_method_assignment,
	applied_person_type_assignment,
	action_method_assignment);
END_TYPE;



TYPE upfromsm_ss4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(executed_action,
	action_method,
	applied_action_assignment,
	applied_action_method_assignment,
	event_occurrence,
	task_element,
	task_method);
END_TYPE;

TYPE upfromsm_ap233_6_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(analysis_assignment,
	organizational_project,
	verification);
END_TYPE;


TYPE upfromsm_pmri4_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(contract,
	product,
	product_definition,
	product_definition_formation,
	document_file,
	location,
	applied_organizational_project_assignment);
END_TYPE;

TYPE upfromsm_os2_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(organization,
	organization_type,
	person,
	person_and_organization,
	position_in_organization,
	position_in_organization_type,
	person_type);
END_TYPE;

TYPE upfromsm_pb3_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(product,
	product_definition_formation,
	product_definition,
	product_as_individual,
	product_as_individual_version,
	product_as_individual_view,
	product_group);
END_TYPE;

TYPE upfromsm_ss5_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_resource,
	action_resource_requirement,
	state_type);
END_TYPE;

TYPE upfromsm_ap233_7_action_method_items = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON action_method_items WITH
	(action_method,
	analysis_assignment,
	group,
	--risk_analysis,
	--risk_assessment,
	--risk_evaluation,
	--risk_reduction,
	--risk_treatment,
	applied_action_method_assignment,
	verification_evidence);
END_TYPE;

-- end upfromsm_

END_SCHEMA;
