(*
   $Id$
   ISO TC184/SC4/WG3 N1965 - ISO/TS 10303-1608 AP210 assembly physical requirements - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1623
*)

SCHEMA Ap210_assembly_physical_requirements_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Assembly_module_usage_view_arm;	-- ISO/TS 10303-1642
	USE FROM Test_requirement_allocation_arm;	-- ISO/TS 10303-1751
END_SCHEMA;

