(*
   $Id$
   ISO TC184/SC4/WG12 N3972 - ISO/TS 10303-1675 Functional decomposition to assembly design - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3417
*)

SCHEMA Functional_decomposition_to_assembly_design_arm;

	USE FROM Assembly_technology_arm;	-- ISO/TS 10303-1649
	USE FROM Functional_decomposition_to_design_arm; -- ISO/TS 10303-1676

  ENTITY Design_functional_unit_allocation_to_assembly_joint;
      functional_design_definition_path : Design_composition_path;
      implementation                    : Assembly_joint;
    UNIQUE
      UR1 : functional_design_definition_path;
  END_ENTITY;

END_SCHEMA;
