(*
 * $Id$
 *
 * JSDAI(TM), a way to implement STEP, ISO 10303
 * Copyright (C) 1997-2008, LKSoftWare GmbH, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License
 * version 3 as published by the Free Software Foundation (AGPL v3).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * JSDAI is a registered trademark of LKSoftWare GmbH, Germany
 * This software is also available under commercial licenses.
 * See also http://www.jsdai.net/
 *)

(*
   Derived from ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Ap210 interconnect design - EXPRESS ARM
   by LKSoftWare GmbH for implementation purpose within IDA-STEP(TM)
*)

SCHEMA Ap210_interconnect_design_xim;

	USE FROM Ap210_interconnect_design_for_microwave_xim;	-- ISO/TS 10303-1618

RULE non_conductive_cross_section_template_population_constraint FOR
    (Template_definition);
WHERE
  WR1:  SIZEOF( QUERY( td <* Template_definition |
('PRINTED_PHYSICAL_LAYOUT_TEMPLATE_XIM.NON_CONDUCTIVE_CROSS_SECTION_TEMPLATE_ARMX' IN TYPEOF(td))
              )) = 0;
END_RULE;

RULE printed_part_cross_section_template_population_constraint FOR
    (Template_definition);
WHERE
  WR1:  SIZEOF( QUERY( td <* Template_definition |
('PRINTED_PHYSICAL_LAYOUT_TEMPLATE_XIM.PRINTED_PART_CROSS_SECTION_TEMPLATE_ARMX' IN TYPEOF(td))
              )) = 0;
END_RULE;

RULE printed_part_cross_section_template_terminal_population_constraint FOR
    (Printed_part_template_terminal_armx);
WHERE
  WR1:  SIZEOF( QUERY( pptt <* Printed_part_template_terminal_armx |
('PRINTED_PHYSICAL_LAYOUT_TEMPLATE_XIM.PRINTED_PART_CROSS_SECTION_TEMPLATE_TERMINAL_ARMX' IN TYPEOF(pptt))
              )) = 0;
END_RULE;

RULE printed_part_template_material_population_constraint FOR
    (Printed_part_template_material_armx);
WHERE
  WR1:  SIZEOF(Printed_part_template_material_armx) = 0;
END_RULE;

RULE printed_part_template_material_link_population_constraint FOR
    (Printed_part_template_material_link_armx);
WHERE
  WR1:  SIZEOF(Printed_part_template_material_link_armx) = 0;
END_RULE;

RULE template_material_cross_section_boundary_population_constraint FOR
    (Template_material_cross_section_boundary_armx);
WHERE
  WR1:  SIZEOF(Template_material_cross_section_boundary_armx) = 0;
END_RULE;

RULE printed_part_template_terminal_class_population_constraint FOR
    (Printed_part_template_terminal_armx);
WHERE
  WR1:  SIZEOF( QUERY( pptt <* Printed_part_template_terminal_armx |
NOT(pptt.connection_zone_category = printed_part_template_terminal_class.surface_point)
              )) = 0;
END_RULE;
   
END_SCHEMA;

