(*
 * $Id$
 *
 * JSDAI(TM), a way to implement STEP, ISO 10303
 * Copyright (C) 1997-2008, LKSoftWare GmbH, Germany
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License
 * version 3 as published by the Free Software Foundation (AGPL v3).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * JSDAI is a registered trademark of LKSoftWare GmbH, Germany
 * This software is also available under commercial licenses.
 * See also http://www.jsdai.net/
 *)

(*
   Derived from ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Design specific assignment to interconnect usage view - EXPRESS ARM
   by LKSoftWare GmbH for implementation purpose within IDA-STEP(TM)
*)

SCHEMA Design_specific_assignment_to_interconnect_usage_view_xim;

USE FROM Fabrication_joint_xim;

	SUBTYPE_CONSTRAINT dsatiuv_component_feature_to_physical_usage_view_assignment_subtypes FOR Component_feature_to_physical_usage_view_assignment;     
		ONEOF (Component_terminal_to_interconnect_module_macro_terminal_assignment,
		 Component_terminal_to_interconnect_module_interface_terminal_assignment);
	END_SUBTYPE_CONSTRAINT;

 	TYPE interconnect_or_assembly_module_select = SELECT
 		(Component_termination_passage_interface_terminal,
     	Printed_connector_component_interface_terminal,
     	Land_interface_terminal);
	END_TYPE;


  ENTITY Component_terminal_to_interconnect_module_interface_terminal_assignment
    (* CONNOTATIONAL *) SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
      SELF\Component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal	: Interconnect_module_interface_terminal_armx;
      SELF\Component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal	: interconnect_or_assembly_module_select;
    DERIVE
      SELF\shape_aspect_relationship.description : text := ?;
  END_ENTITY;

  ENTITY Component_terminal_to_interconnect_module_macro_terminal_assignment
    (* CONNOTATIONAL *) SUBTYPE OF (Component_feature_to_physical_usage_view_assignment);
      SELF\Component_feature_to_physical_usage_view_assignment.defined_part_feature RENAMED usage_view_terminal : Interconnect_module_macro_terminal_armx;
      SELF\Component_feature_to_physical_usage_view_assignment.assigned_design_object RENAMED assigned_terminal	: fabricated_feature_select;
    DERIVE
      SELF\shape_aspect_relationship.description : text := ?;
  END_ENTITY;

  ENTITY Stratum_concept_to_physical_usage_view_assignment
  	(* CONNOTATIONAL *) SUBTYPE OF (shape_aspect_relationship);
      assigned_design_object 																												: stratum_concept;
      SELF\shape_aspect_relationship.relating_shape_aspect RENAMED defined_part_feature	: Part_feature;
      SELF\shape_aspect_relationship.description RENAMED purpose                		: OPTIONAL text;
    DERIVE
      SELF\shape_aspect_relationship.related_shape_aspect : shape_aspect := ?;
      SELF\shape_aspect_relationship.name : label := ?;
    UNIQUE
    	UR1 : defined_part_feature;
    WHERE
      WR1 : NOT ('DESIGN_SPECIFIC_ASSIGNMENT_TO_INTERCONNECT_USAGE_VIEW_xim.INTERCONNECT_MODULE_TERMINAL_ARMX' IN TYPEOF(defined_part_feature));
  END_ENTITY;

END_SCHEMA;




