(*
   $Id$
   ISO TC184/SC4/WG12 N5726 - ISO/TS 10303-1708 Packaged connector model - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4072
*)


SCHEMA Packaged_connector_model_mim;
	USE FROM Packaged_part_black_box_model_mim;	-- ISO/TS 10303-1710

ENTITY packaged_connector
  SUBTYPE OF (packaged_part);
END_ENTITY;

ENTITY packaged_connector_terminal_relationship
 SUBTYPE OF (shape_aspect, shape_aspect_relationship);
END_ENTITY;
	
END_SCHEMA;


