(*
   $Id$
   ISO TC184/SC4/WG12 N3921 - ISO/TS 10303-1658 Connectivity allocation to physical network - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3375
*)

SCHEMA Connectivity_allocation_to_physical_network_arm;

	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_arm;	-- ISO/TS 10303-1678
	USE FROM Layered_interconnect_module_design_arm;	-- ISO/TS 10303-1698

  ENTITY Connectivity_allocation_to_physical_network;
      implementation           : Generic_physical_network;
      connectivity_requirement : Aggregate_connectivity_requirement;
    UNIQUE
      UR1 : implementation;
  END_ENTITY;

END_SCHEMA;  
