(*
   $Id$
   ISO TC184/SC4/WG12 N3922 - ISO/TS 10303-1658 Connectivity allocation to physical network - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3376
*)


SCHEMA Connectivity_allocation_to_physical_network_mim;
	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_mim;	-- ISO/TS 10303-1678
	USE FROM Layered_interconnect_module_design_mim;	-- ISO/TS 10303-1698
END_SCHEMA;

