(*
 $Id$
 ISO TC184/SC4/WG12 N5291 - ISO/TS 10303-1311 Associative draughting elements - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N4658
*)

SCHEMA Associative_draughting_elements_mim;

USE FROM Shape_property_assignment_mim; -- ISO/CD-TS 10303-1032

USE FROM Draughting_element_mim; -- ISO/CD-TS 10303-1310

USE FROM aic_associative_draughting_elements; --  ISO 10303-520

USE FROM draughting_dimension_schema(dimension_callout); --  ISO 10303-101

USE FROM product_property_definition_schema(shape_definition);

  TYPE draughting_model_item_association_select = SELECT
    (annotation_occurrence,
     draughting_callout);
  END_TYPE;

  TYPE draughting_model_item_definition = EXTENSIBLE GENERIC_ENTITY SELECT (
 	product_definition_shape,
 	shape_aspect,
 	shape_aspect_relationship);
  END_TYPE; 

	ENTITY draughting_model_item_association
 		SUBTYPE OF(item_identified_representation_usage);
 			SELF\item_identified_representation_usage.definition : draughting_model_item_definition;
 			SELF\item_identified_representation_usage.used_representation : annotation_representation_select;
 			SELF\item_identified_representation_usage.identified_item : draughting_model_item_association_select;
 	END_ENTITY;
END_SCHEMA;  
