(*
   $Id$
   ISO TC184/SC4/WG3 N2057 - ISO/TS 10303-1625 AP210 packaged part white box model - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG3 N1675
*)


SCHEMA Ap210_packaged_part_white_box_model_mim;
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Packaged_part_white_box_model_mim;	-- ISO/TS 10303-1709
	USE FROM Part_feature_grouping_mim;	-- ISO/TS 10303-1713
END_SCHEMA;

