(*
 $Id$
 ISO TC184/SC4/WG12 N6850 - ISO/TS 10303-1488 Verification and validation - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N6602
*) 


SCHEMA Verification_and_validation_mim;

USE FROM Group_mim;    -- ISO/TS 10303-1113

USE FROM Requirement_assignment_mim;    -- ISO/TS 10303-1233

USE FROM State_observed_mim;    -- ISO/TS 10303-1256


TYPE evidence_item = EXTENSIBLE GENERIC_ENTITY SELECT
   (validation, 
    verification);
END_TYPE; 

TYPE v_and_v_state_observed = SELECT BASED_ON state_observed_of_item WITH 
   (group);
END_TYPE; 

TYPE validation_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH 
   (product_definition_formation);
END_TYPE; 

ENTITY evidence
  SUBTYPE OF (group_assignment);
  items : SET[1:?] OF evidence_item;
END_ENTITY;

ENTITY validation
  SUBTYPE OF (group);
END_ENTITY;

ENTITY verification
  SUBTYPE OF (group);
END_ENTITY;

ENTITY verification_relationship
  SUBTYPE OF (group_relationship);
  SELF\group_relationship.relating_group : verification;
  SELF\group_relationship.related_group : verification;
END_ENTITY;

END_SCHEMA;  -- Verification_and_validation_mim
