(*
   $Id$
   ISO TC184/SC4/WG12 N5795 - ISO/TS 10303-1734 Pre defined datum symbol - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4150
*)


SCHEMA Pre_defined_datum_symbol_mim;
	USE FROM Layered_3d_shape_mim;	-- ISO/TS 10303-1694
	USE FROM Pre_defined_datum_2d_symbol_mim;	-- ISO/TS 10303-1735
	USE FROM Pre_defined_datum_3d_symbol_mim;	-- ISO/TS 10303-1736

SUBTYPE_CONSTRAINT pdds_shape_definition_3d_intersection_subtypes FOR shape_definition_3d_intersection;         
  (ONEOF (pre_defined_parallel_datum_axis_symbol_3d_2d_relationship,
          pre_defined_perpendicular_datum_axis_symbol_3d_2d_relationship,
          pre_defined_perpendicular_datum_plane_symbol_3d_2d_relationship));
END_SUBTYPE_CONSTRAINT;        
	
ENTITY pre_defined_parallel_datum_axis_symbol_3d_2d_relationship
  SUBTYPE OF (shape_definition_3d_intersection);
END_ENTITY; 

ENTITY pre_defined_perpendicular_datum_axis_symbol_3d_2d_relationship
  SUBTYPE OF (shape_definition_3d_intersection);
END_ENTITY; 

ENTITY pre_defined_perpendicular_datum_plane_symbol_3d_2d_relationship
  SUBTYPE OF (shape_definition_3d_intersection);
END_ENTITY; 
	
END_SCHEMA;

