(*
   $Id$
   ISO TC184/SC4/WG12 N6373 - ISO/TS 10303-1670 Fabrication technology - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N5648
*)


SCHEMA Fabrication_technology_mim;
    USE FROM Constructive_solid_geometry_2d_mim; 	-- ISO/TS 10303-1731
	USE FROM Extended_geometric_tolerance_mim;	-- ISO/TS 10303-1666
	USE FROM Part_template_mim; -- ISO/TS 10303-1722

TYPE ft_classification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH (
	stratum_technology_occurrence_relationship);
END_TYPE;

TYPE ft_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH 
   (stratum_technology);
END_TYPE; 
	
TYPE ft_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
   (passage_technology,
    stratum_technology);
END_TYPE; 

TYPE ft_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH 
     (passage_technology,
     stratum_technology,
     stratum_technology_occurrence,
     stratum_technology_occurrence_relationship);
END_TYPE; 

SUBTYPE_CONSTRAINT ft_property_definition_subtypes FOR property_definition; 
    (ONEOF (stratum_technology_occurrence_relationship,
	 stratum_technology_occurrence));
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT ft_property_definition_relationship_subtypes FOR property_definition_relationship; 
    (ONEOF (stratum_technology_occurrence_relationship,
	 stratum_technology_swap_relationship));
END_SUBTYPE_CONSTRAINT;

ENTITY allocated_passage_minimum_annular_ring
  SUBTYPE OF (characterized_object);
END_ENTITY;    

ENTITY copy_stratum_technology_occurrence_relationship
  SUBTYPE OF (derived_stratum_technology_occurrence_relationship);
END_ENTITY;
  
ENTITY derived_stratum_technology_occurrence_relationship
  ABSTRACT SUPERTYPE OF (ONEOF (
    copy_stratum_technology_occurrence_relationship,
    inverse_copy_stratum_technology_occurrence_relationship))
  SUBTYPE OF (stratum_technology_occurrence_relationship);
END_ENTITY;

ENTITY design_stack_model
  SUBTYPE OF(stratum_stack_model);
END_ENTITY;

ENTITY equivalent_stackup_model_definition
  SUBTYPE OF (product_definition, product_definition_relationship);
    SELF\product_definition_relationship.relating_product_definition RENAMED primary_stackup_model   : stratum_stack_model;
    SELF\product_definition_relationship.related_product_definition RENAMED equivalent_stackup_model : stratum_stack_model;
  WHERE
    WR1 : primary_stackup_model :<>: equivalent_stackup_model;
END_ENTITY;
 
ENTITY equivalent_sub_stack_definition
  SUBTYPE OF (product_definition);
END_ENTITY;

ENTITY footprint_library_stratum_technology
  SUBTYPE OF (stratum_technology);
END_ENTITY;

ENTITY impedance_measurement_setup_requirement
  SUBTYPE OF (predefined_requirement_view_definition);
END_ENTITY;

ENTITY impedance_requirement
  SUBTYPE OF (predefined_requirement_view_definition);
END_ENTITY;
  
ENTITY inverse_copy_stratum_technology_occurrence_relationship
  SUBTYPE OF (derived_stratum_technology_occurrence_relationship);
END_ENTITY;

ENTITY local_linear_stack
  SUBTYPE OF (stratum_sub_stack);
END_ENTITY;

ENTITY passage_deposition_material_identification
  SUBTYPE OF (material_designation);
    SELF\material_designation.definitions : SET [1:?] OF passage_technology;
END_ENTITY;

ENTITY passage_filling_material_identification
  SUBTYPE OF (material_designation);
    SELF\material_designation.definitions : SET [1:?] OF passage_technology;
END_ENTITY;

ENTITY passage_technology
  SUBTYPE OF (characterized_object, product_definition_shape);
  DERIVE
    SELF\property_definition.definition : characterized_definition := SELF;
UNIQUE
  UR1: SELF\characterized_object.name;
END_ENTITY;

ENTITY passage_technology_allocation_to_stack_model
  SUBTYPE OF (stratum_sub_stack);
END_ENTITY;

ENTITY stratum_sub_stack 
  ABSTRACT SUPERTYPE OF (ONEOF(local_linear_stack, 
    passage_technology_allocation_to_stack_model))
  SUBTYPE OF (part_template_definition);
END_ENTITY;      

ENTITY stratum_stack_model
  ABSTRACT SUPERTYPE
  SUBTYPE OF(part_template_definition);
END_ENTITY;

ENTITY stratum_surface_technology
  SUBTYPE OF (shape_aspect);
    SELF\shape_aspect.of_shape RENAMED associated_technology : stratum_technology;
END_ENTITY;
  
ENTITY stratum_technology
  SUBTYPE OF (characterized_object, product_definition_shape);
  DERIVE
    SELF\property_definition.definition : characterized_definition := SELF;
UNIQUE
  UR1: SELF\characterized_object.name;
END_ENTITY;

ENTITY stratum_technology_occurrence
  SUBTYPE OF(property_definition);
END_ENTITY;

ENTITY stratum_technology_occurrence_link
  SUBTYPE OF(stratum_technology_occurrence_relationship);
END_ENTITY;

ENTITY stratum_technology_occurrence_relationship
  ABSTRACT SUPERTYPE OF (ONEOF
    (derived_stratum_technology_occurrence_relationship,
     stratum_technology_occurrence_link,
     stratum_technology_occurrence_feature_constraint,
     stratum_technology_occurrence_swap_relationship))
  SUBTYPE OF(property_definition, property_definition_relationship);         
END_ENTITY;

ENTITY stratum_technology_occurrence_feature_constraint
  SUBTYPE OF (stratum_technology_occurrence_relationship);
END_ENTITY;

ENTITY stratum_technology_occurrence_swap_relationship
  SUBTYPE OF (stratum_technology_occurrence_relationship);
END_ENTITY;

ENTITY stratum_technology_swap_relationship
  SUBTYPE OF(property_definition_relationship);
END_ENTITY;

ENTITY stratum_technology_mapping_relationship
  SUBTYPE OF(property_definition_relationship);
END_ENTITY;

END_SCHEMA;
