(*
   $Id$
   ISO TC184/SC4/WG12 N5672 - ISO/TS 10303-1687 Interconnect module with macros - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4009
*)


SCHEMA Interconnect_module_with_macros_mim;
USE FROM Layered_interconnect_module_design_mim;	-- ISO/TS 10303-1698

  ENTITY interconnect_module_macro_component
    SUBTYPE OF (physical_component);
  END_ENTITY;
	
  ENTITY interconnect_module_macro_component_join_terminal
    SUBTYPE OF (physical_component_terminal);
  END_ENTITY;
	
END_SCHEMA;

