(*
   $Id$
   ISO TC184/SC4/WG12 N4709 - ISO/CD-TS 10303-1310 Draughting element - EXPRESS MIM
*)

SCHEMA Draughting_element_mim;

USE FROM Associative_text_mim; -- ISO/CD-TS 10303-1132

USE FROM Curve_appearance_mim; -- ISO/CD-TS 10303-1003

USE FROM draughting_element_schema    --  ISO 10303-101
  (annotation_plane,
  leader_curve,
  draughting_callout,
  dimension_curve,
  projection_curve);

USE FROM presentation_definition_schema(  
  annotation_fill_area_occurrence);

END_SCHEMA;
