(*
   $Id$
   ISO TC184/SC4/WG12 N4201 - ISO/TS 10303-1751 Test requirement allocation - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3625
*)


SCHEMA Test_requirement_allocation_mim;
	USE FROM Functional_assignment_to_part_mim;	-- ISO/TS 10303-1674
	USE FROM Requirement_decomposition_mim;	-- ISO/TS 10303-1740
	USE FROM Functional_usage_view_mim;	-- ISO/TS 10303-1705

TYPE tra_groupable_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON groupable_item WITH 
     (property_definition_representation,
     shape_aspect_relationship);
END_TYPE;

TYPE tra_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH 
   (product_definition_formation);
END_TYPE; 

	
END_SCHEMA;

