(*
   $Id$
   ISO TC184/SC4/WG12 N4690 - ISO/CD-TS 10303-1775 Currency - EXPRESS ARM
*)

SCHEMA Currency_arm;

USE FROM Value_with_unit_arm; -- ISO/TS 10303-1054

  ENTITY Currency
    ABSTRACT SUPERTYPE
    SUBTYPE OF (Unit);
  END_ENTITY;

  ENTITY Currency_value 
    SUBTYPE OF (Value_with_unit); 
      SELF\Value_with_unit.unit : Currency;
  END_ENTITY; 

  ENTITY Iso4217_currency 
    SUBTYPE OF (Currency);
  END_ENTITY; 

END_SCHEMA;
