(*
 $Id$
 ISO TC184/SC4/WG12 N4989 - ISO/CD-TS 10303-1027 Contextual shape positioning - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N4252
*)
SCHEMA Contextual_shape_positioning_mim;

USE FROM Extended_basic_geometry_mim; -- ISO/TS 10303-1667
USE FROM Shape_property_assignment_mim; --  ISO/TS 10303-1032

USE FROM product_property_representation_schema -- ISO 10303-41
  (context_dependent_shape_representation);

USE FROM representation_schema 	-- ISO 10303-43
      (functionally_defined_transformation,
      representation_relationship_with_transformation,
      mapped_item);

END_SCHEMA;




