(*
 $Id$
 ISO TC184/SC4/WG12 N6029 - ISO/TS 10303-1397 Conditional effectivity - EXPRESS MIM
*) 


SCHEMA Conditional_effectivity_mim;

USE FROM Condition_mim;    -- ISO/TS 10303-1253

USE FROM Effectivity_mim;    -- ISO/TS 10303-1057

USE FROM effectivity_schema   -- ISO 10303-41
  (effectivity); 


ENTITY conditional_effectivity
  SUBTYPE OF (condition, effectivity);
END_ENTITY;

END_SCHEMA;  -- Conditional_effectivity_mim
