(*
 $Id$
 ISO TC184/SC4/WG12 N - ISO/WD 10303-1452 Requirement categorization - EXPRESS MIM
*)
(* UNDER DEVELOPMENT *)
SCHEMA Requirement_categorization_mim;
  USE FROM Requirement_assignment_mim;    -- ISO/TS 10303-1233
  USE FROM Requirement_model_assignment_mim;    -- ISO/TS 10303-1233
  USE FROM Requirement_view_definition_mim;    -- ISO/TS 10303-1141
  USE FROM Document_assignment_mim;
  USE FROM Position_in_organization_mim;
  USE FROM Person_organization_mim;
END_SCHEMA;
