(*
 $Id$
 ISO TC184/SC4/WG12 N5450 - ISO/TS 10303-1215 Physical breakdown - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N4947
*) 

SCHEMA Physical_breakdown_mim;

USE FROM Product_breakdown_mim;    -- ISO/TS 10303-1248


  ENTITY physical_breakdown_context
    SUBTYPE OF (breakdown_context);
  END_ENTITY;

  ENTITY physical_element_usage
    SUBTYPE OF (breakdown_element_usage);
  END_ENTITY;

END_SCHEMA;  