SCHEMA Requirement_view_definition_relationship_arm;

USE FROM Product_view_definition_relationship_arm;

USE FROM Requirement_view_definition_arm;

ENTITY Requirement_collection_relationship
SUBTYPE OF (Requirement_view_definition_relationship);
  SELF\Requirement_view_definition_relationship.primary RENAMED collection : Requirement_view_definition;
  SELF\Requirement_view_definition_relationship.secondary RENAMED member : Requirement_view_definition;
END_ENTITY;

ENTITY Requirement_view_definition_relationship
SUPERTYPE OF (ONEOF(Requirement_collection_relationship, Tracing_relationship))
SUBTYPE OF (View_definition_relationship);
  SELF\View_definition_relationship.relating_view RENAMED primary : Requirement_view_definition;
  SELF\View_definition_relationship.related_view RENAMED secondary : Requirement_view_definition;
WHERE
    WR1: primary :<>: secondary;
END_ENTITY;

ENTITY Tracing_relationship
SUBTYPE OF (Requirement_view_definition_relationship);
  SELF\Requirement_view_definition_relationship.primary RENAMED traces_from : Requirement_view_definition;
  SELF\Requirement_view_definition_relationship.secondary RENAMED traces_to : Requirement_view_definition;
END_ENTITY;

END_SCHEMA;

