/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lksoft_ia_CommonAppdata */

#ifndef _Included_com_lksoft_ia_CommonAppdata
#define _Included_com_lksoft_ia_CommonAppdata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lksoft_ia_CommonAppdata
 * Method:    getCommonAppdataDir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lksoft_ia_CommonAppdata_getCommonAppdataDir
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
