(*
 $Id$
 ISO TC184/SC4/WG12 N - ISO/WD 10303-1440 Project management project management resource information connector - EXPRESS MIM
*)
(* UNDER DEVELOPMENT *)
SCHEMA Project_management_project_management_resource_information_connector_mim;
  USE FROM Management_resource_information_mim;
  USE FROM Organization_structure_mim;
  USE FROM Project_breakdown_mim;
  USE FROM Project_management_resource_information_mim;
  USE FROM Schedule_mim;
  USE FROM Work_structure_mim;
END_SCHEMA;
