(*
   $Id$
   ISO TC184/SC4/WG12 N4557 - ISO/CD-TS 10303-1482 Behaviour identification and version - EXPRESS MIM
*) 

SCHEMA Behaviour_identification_and_version_mim;

USE FROM Identification_assignment_mim;

USE FROM Product_version_relationship_mim;

TYPE behaviour_and_version_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON identification_item WITH
  (product,
   product_definition_formation);
END_TYPE;

END_SCHEMA;

