(*
   $Id$
   ISO TC184/SC4/WG12 N5867 - ISO/TS 10303-1468 External state based behaviour model - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4581
*) 

SCHEMA External_state_based_behaviour_model_mim;

USE FROM Document_assignment_mim;    -- ISO/TS 10303-1122

USE FROM File_identification_mim;    -- ISO/TS 10303-1127

USE FROM State_based_behaviour_representation_mim;    -- ISO/WD 10303-1471


TYPE external_sbb_model_document_reference_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON document_reference_item WITH 
   (external_state_based_behaviour_model);
END_TYPE; 

ENTITY external_state_based_behaviour_model
  SUBTYPE OF (state_based_behaviour_model);
END_ENTITY;

END_SCHEMA;  -- External_state_based_behaviour_model_mim
