(*
   $Id$
   ISO TC184/SC4/WG12 N3841 - ISO/TS 10303-1631 Area 2d - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3637
*)

SCHEMA Area_2d_mim;
	USE FROM Extended_basic_geometry_mim;	-- ISO/TS 10303-1667
	USE FROM Value_with_unit_extension_mim;	-- ISO/TS 10303-1753
	USE FROM geometric_model_schema
		(circular_area,
		elliptic_area,
		polygonal_area,
		primitive_2d,
		rectangular_area);
END_SCHEMA;
