(*
   $Id$
   ISO TC184/SC4/WG12 N4595 - ISO/CD-TS 10303-1487 Measure of effectiveness - EXPRESS ARM
*) 

SCHEMA Measure_of_effectiveness_arm;

USE FROM Requirement_view_definition_arm;

TYPE maximize_or_minimize = ENUMERATION OF 
  (maximize,
   minimize);
END_TYPE;

ENTITY Measure_of_effectiveness
SUBTYPE OF (Requirement_view_definition);
  optimization_direction : maximize_or_minimize;
END_ENTITY;

END_SCHEMA;

