(*
	$Id$
	ISO TC184/SC4/WG12 N6243 - ISO/TS 10303-1509 Manifold surface - EXPRESS ARM
	Supersedes ISO TC184/SC4/WG12 N5419
*)


SCHEMA Manifold_surface_arm;

USE FROM Topologically_bounded_surface_arm; --ISO/TS 10303-1511:2004

  ENTITY Manifold_surface_shape_representation
    SUBTYPE OF (Geometric_model);
  END_ENTITY;

  ENTITY Shell_based_surface_model
    SUBTYPE OF (Detailed_geometric_model_element);
  END_ENTITY;


END_SCHEMA;
