(*
 $Id$
 ISO TC184/SC4/WG12 N - ISO/WD 10303-1447 System requirements connector - EXPRESS MIM
*)
(* UNDER DEVELOPMENT *)
SCHEMA System_requirements_connector_mim;
  USE FROM Management_resource_information_mim;
  USE FROM Project_management_resource_information_mim;
  USE FROM Organization_structure_mim;
  USE FROM Project_breakdown_mim;
  USE FROM Schedule_mim;
  USE FROM Work_structure_mim;
  USE FROM System_requirements_mim;
END_SCHEMA;
