(*
   $Id$
   ISO TC184/SC4/WG12 N4669 - ISO/CD-TS 10303-1369 Binary representation - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3709
*) 


SCHEMA Binary_representation_arm; 

USE FROM Foundation_representation_arm;    -- ISO/TS 10303-1006


  ENTITY Binary_representation_item 
    SUBTYPE OF (Representation_item); 
  END_ENTITY; 

  ENTITY Bytes_representation_item 
    SUBTYPE OF (Binary_representation_item); 
  END_ENTITY; 

END_SCHEMA; 

