(*
   $Id$
   ISO TC184/SC4/WG3 N1982 - ISO/TS 10303-1611 AP210 connection zone based model extraction - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG3 N1633
*)


SCHEMA Ap210_connection_zone_based_model_extraction_mim;
	USE FROM Analytical_model_mim;	-- ISO/TS 10303-1603
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
    USE FROM Feature_and_connection_zone_mim; -- ISO/TS 10303-1671	
END_SCHEMA;

