(*
   $Id$
   ISO TC184/SC4/WG12 N4218 - ISO/TS 10303-1757 Test select product - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3679
*)
SCHEMA Test_select_product_arm;

	USE FROM Product_replacement_arm;	-- ISO/TS 10303-1046

  ENTITY Test_select_product
    SUBTYPE OF (Alternate_product_relationship);
  WHERE
    WR1: NOT EXISTS (SELF\Alternate_product_relationship.criteria);
  END_ENTITY;

END_SCHEMA;
