(*
   $Id$
   ISO TC184/SC4/WG12 N4191 - ISO/TS 10303-1748 Stratum non planar shape - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N3615
*)

SCHEMA Stratum_non_planar_shape_arm;

	USE FROM Layered_interconnect_module_design_arm;	-- ISO/TS 10303-1698
	USE FROM Manifold_surface_arm;	-- ISO/TS 10303-1509

  TYPE stratum_surface_shape_model_select = SELECT
    (Stratum_surface_shape_model,
     Stratum_average_surface_shape_model);
  END_TYPE;

  ENTITY Stratum_average_surface_shape_model
    SUBTYPE OF (Manifold_surface_shape_representation);
      of_surface : Stratum_average_surface;
    UNIQUE
    	UR1 : of_surface;  
    WHERE
      WR1 : NOT EXISTS(SELF\Representation.name);
      WR2 : NOT EXISTS(SELF\Representation.description);
  END_ENTITY;

  ENTITY Stratum_feature_non_planar_2d_shape_model
    SUBTYPE OF (Manifold_surface_shape_representation);
      shape_characterized_component : Stratum_feature;
    WHERE
      WR1 : NOT EXISTS(SELF\Representation.name);
      WR2 : NOT EXISTS(SELF\Representation.description);
  END_ENTITY;

  ENTITY Stratum_feature_shape_stratum_average_surface_shape_relationship;
      of_stratum_feature_shape         : Stratum_feature_non_planar_2d_shape_model;
      of_stratum_average_surface_shape : Stratum_average_surface_shape_model;
  END_ENTITY;

  ENTITY Stratum_feature_shape_stratum_surface_shape_relationship;
      of_stratum_feature_shape : Stratum_feature_non_planar_2d_shape_model;
      of_stratum_surface_shape : Stratum_surface_shape_model;
  END_ENTITY;
 
   ENTITY Stratum_surface_shape_model
    SUBTYPE OF (Manifold_surface_shape_representation);
      of_surface : Stratum_surface;
    UNIQUE
    	UR1 : of_surface;  
    WHERE
      WR1 : NOT EXISTS(SELF\Representation.name);
      WR2 : NOT EXISTS(SELF\Representation.description);
  END_ENTITY;

END_SCHEMA;
