(*
   $Id$
   ISO TC184/SC4/WG3 N2030 - ISO/TS 10303-1620 AP210 interconnect physical requirements - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1659
*)

SCHEMA Ap210_interconnect_physical_requirements_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Fabrication_requirement_arm;	-- ISO/TS 10303-1669
	USE FROM Interconnect_placement_requirements_arm;	-- ISO/TS 10303-1690
	USE FROM Interconnect_module_to_assembly_module_relationship_arm;	-- ISO/TS 10303-1685
	USE FROM Test_requirement_allocation_arm;	-- ISO/TS 10303-1751
END_SCHEMA;

