(*
   $Id$
   ISO TC184/SC4/WG3 N2022 - ISO/TS 10303-1618 AP210 interconnect design for microwave - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG3 N1654
*)


SCHEMA Ap210_interconnect_design_for_microwave_mim;
	USE FROM Design_product_data_management_mim;	-- ISO/TS 10303-1628
	USE FROM Chemical_substance_mim;	-- ISO/TS 10303-1655
	USE FROM Connectivity_allocation_to_physical_network_mim;	-- ISO/TS 10303-1658
	USE FROM Design_specific_assignment_to_interconnect_usage_view_mim;	-- ISO/TS 10303-1663
	USE FROM Device_marking_mim;	-- ISO/TS 10303-1664
	USE FROM Interconnect_2d_shape_mim;	-- ISO/TS 10303-1682
	USE FROM Interconnect_non_planar_shape_mim;	-- ISO/TS 10303-1688	
	USE FROM Interconnect_module_to_assembly_module_relationship_mim;	-- ISO/TS 10303-1685
	USE FROM Layered_interconnect_module_2d_design_mim;	-- ISO/TS 10303-1695
	USE FROM Layered_interconnect_module_3d_design_mim;	-- ISO/TS 10303-1696
	USE FROM Layout_macro_definition_mim;	-- ISO/TS 10303-1701
	USE FROM Pre_defined_datum_symbol_mim;	-- ISO/TS 10303-1734
	USE FROM Via_component_mim;	-- ISO/TS 10303-1754

 SUBTYPE_CONSTRAINT aidfm_shape_definition_3d_intersection_subtypes FOR shape_definition_3d_intersection;  
	 (ONEOF (edge_segment_cross_section,
	 pre_defined_perpendicular_datum_plane_symbol_3d_2d_relationship,
	 pre_defined_perpendicular_datum_axis_symbol_3d_2d_relationship,
	 pre_defined_parallel_datum_axis_symbol_3d_2d_relationship));
 END_SUBTYPE_CONSTRAINT;  
	
	
END_SCHEMA;

