--=======================================  
-- Mechanical_design_geometric_presentation for
--  aic_mechanical_design_geometric_presentation; --  ISO 10303-517
-- Light_sources has to go into the Mechanical_design_geometric_presentation


SCHEMA Mechanical_design_geometric_presentation_arm;

USE FROM Camera_view_arm;

USE FROM Appearance_assignment_arm;

USE FROM Colour_arm;

ENTITY Mechanical_design_view_area   -- AIM is mechanical_design_geometric_presentation_area
  SUBTYPE OF (View_area);
END_ENTITY;

ENTITY  Mechanical_representation_styled_model  -- AIM is mechanical_design_geometric_presentation_representation
  SUBTYPE OF (Styled_model);
END_ENTITY;

ENTITY Light_source;
  light_type : STRING;
  colour : OPTIONAL Colour;
  is_defined_for : SET[1:?] OF Model_image;
END_ENTITY;

END_SCHEMA;  
