(*
   $Id$
   ISO TC184/SC4/WG12 N3988 - ISO/TS 10303-1680 Functional unit requirement allocation - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3433
*)


SCHEMA Functional_unit_requirement_allocation_mim;
	USE FROM Network_functional_design_view_mim;	-- ISO/TS 10303-1704
	
TYPE fura_requirement_assigned_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON requirement_assigned_item WITH 
     (component_functional_unit);
END_TYPE; 
	
END_SCHEMA;

