(*
   $Id$
   ISO TC184/SC4/WG3 N2045 - ISO/TS 10303-1623 AP210 laminate assembly design - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1668
*)

SCHEMA Ap210_laminate_assembly_design_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Interconnect_module_to_assembly_module_relationship_arm;	-- ISO/TS 10303-1685
	USE FROM Sequential_laminate_assembly_design_arm;	-- ISO/TS 10303-1741
   --- look IS
END_SCHEMA;

