(*
   $Id$
   ISO TC184/SC4/WG12 N4090 - ISO/TS 10303-1714 Part feature location - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N3517
*)


SCHEMA Part_feature_location_mim;
	USE FROM Shape_feature_mim;	-- ISO/TS 10303-xxxx
	USE FROM product_property_representation_schema(item_identified_representation_usage);

  ENTITY usage_concept_usage_relationship
    SUBTYPE OF (mapped_item, item_identified_representation_usage);
      SELF\item_identified_representation_usage.used_representation : shape_representation;
      SELF\item_identified_representation_usage.definition          : shape_aspect;
    DERIVE
      SELF\item_identified_representation_usage.identified_item : usage_concept_usage_relationship := SELF;
    WHERE
      WR1: SELF IN SELF\item_identified_representation_usage.used_representation.items;
  END_ENTITY;
	
END_SCHEMA;

