SCHEMA Property_as_definition_arm;

USE FROM Property_assignment_arm;

TYPE representation_proxy_select = EXTENSIBLE GENERIC_ENTITY SELECT ;
END_TYPE;

ENTITY Property_as_definition
SUBTYPE OF (Assigned_property);
DERIVE
  SELF\Assigned_property.name : STRING := 'THIS';
UNIQUE
  UR1: SELF\Assigned_property.described_element;
END_ENTITY;

ENTITY Representation_proxy_item
SUBTYPE OF (Representation_item);
  item : representation_proxy_select;
END_ENTITY;

END_SCHEMA;

