(*
   $Id$
   ISO TC184/SC4/WG12 N5854 - ISO/TS 10303-1491 Expression assignment - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4568
*)   

SCHEMA Expression_assignment_arm;

USE FROM Expression_arm;

TYPE expression_assignment_item = EXTENSIBLE GENERIC_ENTITY SELECT ;
END_TYPE;

ENTITY Expression_assignment;
  expression : Expression;
  items : SET [1 : ?] OF expression_assignment_item;
END_ENTITY;

END_SCHEMA;