(*
   $Id$
   ISO TC184/SC4/WG12 N - ISO/CD-TS 10303-xxxx Same as external item - EXPRESS ARM
*)


SCHEMA Same_as_external_item_arm;

USE FROM External_source_arm;    -- ISO/TS 10303-1331


TYPE same_as_item = EXTENSIBLE GENERIC_ENTITY SELECT;
END_TYPE; 

ENTITY Same_as_external_item;
  external_item_id : STRING;
  description : OPTIONAL STRING;
  role : STRING;
  external_source : External_source;
  items : SET[0:?] OF same_as_item;
END_ENTITY;

END_SCHEMA;  -- Same_as_external_item_arm

