(*
   $Id$
   ISO TC184/SC4/WG12 N4998 - ISO/CD-TS 10303-1762 Generic product occurrence - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N4231
*)

SCHEMA Generic_product_occurrence_mim;

USE FROM Assembly_structure_mim;	-- ISO/TS 10303-1026
USE FROM Product_view_definition_relationship_mim;	-- ISO/TS 10303-1041
USE FROM Extended_measure_representation_mim;	-- ISO/TS 10303-1106	
USE FROM Specified_product_mim;	-- ISO/TS 10303-1104	

END_SCHEMA;
