(*
   $Id$
   ISO TC184/SC4/WG12 N4739 - ISO/CD-TS 10303-1778 External library - EXPRESS MIM
*)
SCHEMA External_library_mim;

USE FROM External_properties_mim; -- ISO/CD-TS 10303-1129

USE FROM External_source_mim;  -- ISO/CD-TS 10303-1331

USE FROM Plib_class_reference_mim; -- ISO/CD-TS 10303-1291

  TYPE el_external_identification_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON external_identification_item WITH  
    (external_source);
  END_TYPE;

END_SCHEMA;
