(*  
   $Id$
   ISO TC184/SC4/WG12 N4941 - ISO/CD-TS 10303-1349 Incomplete data reference mechanism - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N2635
*)
SCHEMA Incomplete_data_reference_mechanism_mim;

USE FROM Classification_assignment_mim;

USE FROM Document_definition_mim;

USE FROM Part_view_definition_mim;

  TYPE idrm_marked_item = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON classification_item WITH
    (document_file,
     product_definition);
  END_TYPE;

END_SCHEMA;

