
(*
 $Id$
 ISO TC184/SC4/WG12 N3799 - ISO/CD-TS 10303-1232 Design material aspects - EXPRESS ARM
*)

SCHEMA Design_material_aspects_arm;

USE FROM Generic_material_aspects_arm;

USE FROM Product_view_definition_arm;

USE FROM Shape_property_assignment_arm;

TYPE dma_material_item_select = EXTENSIBLE GENERIC_ENTITY SELECT BASED_ON material_item_select WITH
  (Item_shape,
   Product_view_definition,
   Shape_element);
END_TYPE;

END_SCHEMA;

