(*
   $Id$
   ISO TC184/SC4/WG12 N5365 - ISO/TS 10303-1667 Extended basic geometry - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG12 N4726
*)

SCHEMA Extended_basic_geometry_arm;

USE FROM Basic_geometry_arm;	-- ISO/TS 10303-1652
USE FROM Geometric_model_relationship_arm;

  SUBTYPE_CONSTRAINT alternate_extended_geometry_items FOR
    Detailed_geometric_model_element;
    ONEOF (Cartesian_point,
           Direction,
           Axis_placement,
           Cartesian_transformation_2d,
           Cartesian_transformation_3d,
           Curve,
           Geometric_model_element_relationship,
           Point_on_curve,
           Point_on_surface,
           Surface,
           Vector);
  END_SUBTYPE_CONSTRAINT;

  ENTITY Detailed_geometric_model_element_relationship;
    item_1: Detailed_geometric_model_element;
    item_2: Detailed_geometric_model_element;
   WHERE 
    WR1: item_1 <> item_2;
  END_ENTITY;

  ENTITY Geometric_model_element_relationship
    SUBTYPE OF (Detailed_geometric_model_element_relationship, Detailed_geometric_model_element);
  END_ENTITY;

  ENTITY Vector
    SUBTYPE OF (Detailed_geometric_model_element);
      orientation: Direction;
      magnitude: length_measure;
    WHERE
      WR1 : magnitude >= 0.0 ;
  END_ENTITY;

END_SCHEMA;
