(*
   $Id$
   ISO TC184/SC4/WG3 N1950 - ISO/TS 10303-1605 AP210 assembly functional requirements - EXPRESS ARM
   Supersedes ISO TC184/SC4/WG3 N1614
*)

SCHEMA Ap210_assembly_functional_requirements_arm;
	USE FROM Design_product_data_management_arm;	-- ISO/TS 10303-1628
	USE FROM Functional_decomposition_to_assembly_design_arm;	-- ISO/TS 10303-1675
	USE FROM Functional_decomposition_with_nodal_representation_to_packaged_mapping_arm;	-- ISO/TS 10303-1678
	USE FROM Physical_node_requirement_to_implementing_component_allocation_arm;	-- ISO/TS 10303-1723
	USE FROM Planned_characteristic_arm;	-- ISO/TS 10303-1733
	USE FROM Test_requirement_allocation_arm;	-- ISO/TS 10303-1751
END_SCHEMA;

