(*
  $Id$
  ISO TC184/SC4/WG12 N5468 - ISO/TS 10303-1318 Procedural solid model - EXPRESS MIM
  Supersedes ISO TC184/SC4/WG12 N4790
*)

SCHEMA Procedural_solid_model_mim;

USE FROM Procedural_shape_model_mim;  -- ISO/CD-TS 10303-1317

USE FROM geometric_model_schema  -- ISO 10303-42 
      (solid_model,
      csg_primitive,
      boolean_result);

USE FROM solid_shape_element_schema  -- ISO 10303-111 
    (modified_solid,
     base_solid_select);
            
END_SCHEMA;

