-- ap212 arm, 2000-09-08

--SCHEMA ap212_application_reference_model;
SCHEMA ap212_arm;

  TYPE ac_dc = ENUMERATION OF
    (dc,
     ac_single_phase,
     ac_3_phases,
     ac_5_phases,
     others);
  END_TYPE; -- ac_dc

  TYPE activity_element_select = SELECT
    (cable_pull_information,
     configuration_information_select,
     connectivity_item_select,
     design_item_select,
     documentation_element_select,
     relation1_select,
     specification_information_select,
     configuration,
     function_version,
     item_version,
     data_element,
     product_identification,
     classification_system,
     item,
     data_element_association,
     activity_method,
     manufacturing_configuration,
     data_element_definition,
     alternate_item_relationship,
     class_structure_relationship);
  END_TYPE; -- activity_element_select

  TYPE activity_element_type = SELECT
    (type_of_activity_element,
     name);
  END_TYPE; -- activity_element_type

  TYPE activity_kind = SELECT
    (name,
     type_of_activity);
  END_TYPE; -- activity_kind

  TYPE activity_method_assignment_type = SELECT
    (name,
     type_of_activity_method_assignment);
  END_TYPE; -- activity_method_assignment_type

  TYPE activity_relationship_type = SELECT
    (name,
     type_of_activity_relationship);
  END_TYPE; -- activity_relationship_type

  TYPE alias_designation_select = SELECT
    (port,
     terminal,
     device,
     document_representation,
     drawing,
     drawing_sheet,
     function_unit,
     location,
     product_component,
     signal,
     technical_system);
  END_TYPE; -- alias_designation_select

  TYPE alias_name_select = SELECT
    (path_node,
     node,
     approval_status,
     classification_system,
     design_discipline_item_definition,
     organization,
     data_element_definition,
     document,
     item,
     notification,
     connectivity_definition,
     path,
     interface_terminal,
     interface_port,
     component_colour,
     classification_attribute,
     document_representation,
     document_type_property,
     document_version,
     device,
     function_definition,
     functional_connectivity_definition,
     functionality,
     general_classification,
     item_version,
     section_interface,
     process_variable,
     product_class,
     product_identification,
     requirement,
     route,
     section,
     specification_category,
     security_level,
     specification,
     function_unit,
     drawing,
     drawing_sheet,
     location,
     port,
     terminal,
     technical_system,
     signal,
     complex_product,
     physical_instance);
  END_TYPE; -- alias_name_select

  TYPE allocation_select = SELECT
    (connectivity_allocation,
     functional_unit_allocation,
     port_allocation,
     preferred_item_allocation,
     preferred_item_terminal_allocation,
     activity_method_assignment,
     offered_function_allocation);
  END_TYPE; -- allocation_select

  TYPE annotated_item_select = SELECT
    (connectivity_item_select,
     design_item_select,
     cable_pull_information,
     data_element_definition,
     activity,
     work_order,
     data_element,
     classification_attribute,
     relation2_select,
     requirement,
     routed_segment,
     connectivity_allocation,
     preferred_item_terminal_allocation,
     product_class,
     product_specification,
     specification_expression,
     configuration,
     contract,
     classification_system,
     class_specification_association,
     class_inclusion_association,
     class_condition_association,
     class_category_association,
     data_element_association,
     data_element_specification,
     document,
     document_file,
     document_version,
     drawing_sheet,
     drawing_view,
     free_segment,
     function_version,
     functional_unit_allocation,
     functionality,
     item,
     item_version,
     material,
     marking,
     offered_function_allocation,
     port_allocation,
     preferred_item_allocation,
     specification_inclusion,
     complex_product,
     activity_method,
     activity_relationship,
     alternate_item_relationship,
     application_context,
     approval_relationship,
     assembly_substitute_relationship,
     certification,
     class_structure_relationship,
     product_identification,
     document_file_relationship,
     effectivity,
     effectivity_relationship,
     event_reference,
     external_library_reference,
     data_element_definition_relationship,
     specification_category,
     classification_system,
     general_classification,
     alias_identification,
     organization_relationship,
     project,
     project_relationship,
     specification,
     specification_expression,
     product_class_relationship,
     specific_item_classification,
     work_request);
  END_TYPE; -- annotated_item_select

  TYPE approval_item_select = SELECT
    (configuration,
     data_element_definition,
     contract,
     cable_pull_information,
     activity_element,
     work_item_select,
     specification_information_select,
     relation1_select,
     function_version,
     documentation_element_select,
     design_item_select,
     allocation_select,
     connectivity_item_select,
     data_element,
     item_version,
     security_classification,
     product_identification,
     manufacturing_configuration,
     class_category_association,
     class_condition_association,
     class_inclusion_association,
     class_specification_association,
     classification_system,
     material,
     specification_expression,
     specification_inclusion,
     data_element_association,
     alternate_item_relationship,
     classification_association,
     certification,
     class_structure_relationship,
     general_classification);
  END_TYPE; -- approval_item_select

  TYPE approval_level = SELECT
    (name,
     level_of_approval);
  END_TYPE; -- approval_level

  TYPE approval_relationship_type = SELECT
    (name,
     type_of_approval_relationship);
  END_TYPE; -- approval_relationship_type

  TYPE arrangement_select = SELECT
    (free_segment,
     routed_segment);
  END_TYPE; -- arrangement_select

  TYPE assigned_alias_identification = SELECT
    (alias_designation,
     alias_identification);
  END_TYPE; -- assigned_alias_identification

  TYPE assigned_document_select = SELECT
    (document,
     document_version,
     document_representation,
     document_file);
  END_TYPE; -- assigned_document_select

  TYPE associated_system_select = SELECT
    (functional_connectivity_definition,
     connectivity_definition,
     device,
     design_discipline_item_definition,
     function_definition,
     function_unit,
     port,
     physical_instance,
     technical_system,
     terminal);
  END_TYPE; -- associated_system_select

  TYPE callout_component_select = SELECT
    (annotation_curve,
     annotation_symbol,
     text);
  END_TYPE; -- callout_component_select

  TYPE certified_element_select = SELECT
    (supplier_solution,
     device,
     item_version,
     item_version_relationship);
  END_TYPE; -- certified_element_select

  TYPE character_type = SELECT
    (type_of_code,
     name);
  END_TYPE; -- character_type

  TYPE characteristic_of_signal_value = ENUMERATION OF
    (linear);
  END_TYPE; -- characteristic_of_signal_value

  TYPE class_condition_type = SELECT
    (name,
     type_of_condition);
  END_TYPE; -- class_condition_type

  TYPE class_source_select = SELECT
    (external_library_reference,
     class_reference);
  END_TYPE; -- class_source_select

  TYPE class_specification_type = SELECT
    (name,
     type_of_association);
  END_TYPE; -- class_specification_type

  TYPE class_structure_relationship_type = SELECT
    (type_of_class_structure_relationship,
     name);
  END_TYPE; -- class_structure_relationship_type

  TYPE classification_association_type = SELECT
    (name,
     type_of_classification_association);
  END_TYPE; -- classification_association_type

  TYPE classification_element_select = SELECT
    (general_classification,
     security_classification,
     security_level,
     classification_attribute,
     classification_system,
     classification_association);
  END_TYPE; -- classification_element_select

  TYPE classified_item_select = SELECT
    (design_discipline_item_definition,
     approval,
     connectivity_definition,
     contract,
     data_element_definition,
     item,
     item_version,
     location,
     path,
     function_version,
     device,
     function_definition,
     functional_connectivity_definition,
     functionality,
     terminal,
     interface_port,
     interface_terminal,
     port,
     function_unit,
     user_defined_symbol_definition,
     drawing,
     drawing_sheet,
     document,
     document_version,
     requirement,
     route,
     section,
     section_interface,
     signal,
     typical_schematic_node,
     data_element,
     approval_status,
     specification_category,
     security_level,
     activity_method,
     annotation_subfigure_definition,
     path_node,
     product_class,
     project,
     complex_product,
     product_identification,
     document_file,
     work_order,
     activity,
     data_element_association,
     work_request);
  END_TYPE; -- classified_item_select

  TYPE colour_type = ENUMERATION OF
    (black,
     blue,
     cyan,
     green,
     magenta,
     red,
     white,
     yellow);
  END_TYPE; -- colour_type

  TYPE complex_product_relationship_type = SELECT
    (type_of_complex_product_relationship,
     name);
  END_TYPE; -- complex_product_relationship_type

  TYPE configuration_information_select = SELECT
    (class_category_association,
     class_condition_association,
     class_inclusion_association,
     class_specification_association,
     specification_expression,
     specification_inclusion);
  END_TYPE; -- configuration_information_select

  TYPE configuration_select = SELECT
    (connectivity_definition,
     functional_connectivity_definition,
     device,
     function_unit,
     location,
     signal,
     complex_product);
  END_TYPE; -- configuration_select

  TYPE configured_specification_select = SELECT
    (class_condition_association,
     class_specification_association);
  END_TYPE; -- configured_specification_select

  TYPE connectivity_allocation_select = SELECT
    (connectivity_definition,
     device,
     function_unit,
     physical_instance);
  END_TYPE; -- connectivity_allocation_select

  TYPE connectivity_definition_relationship_type = SELECT
    (name,
     type_of_connectivity_definition_relationship);
  END_TYPE; -- connectivity_definition_relationship_type

  TYPE connectivity_item_select = SELECT
    (connectivity_definition,
     function_interface,
     functional_connectivity_definition,
     interface,
     interface_port,
     interface_terminal,
     port,
     terminal);
  END_TYPE; -- connectivity_item_select

  TYPE connectivity_presentation_select = SELECT
    (functional_connectivity_definition,
     connectivity_definition);
  END_TYPE; -- connectivity_presentation_select

  TYPE constrained_design_element_select = SELECT
    (functionality,
     function_version,
     drawing_view,
     design_item_select,
     connectivity_item_select,
     product_class,
     item_version,
     item,
     data_element,
     product_specification,
     relation2_select,
     document,
     document_version,
     drawing_sheet,
     generic_note,
     marking,
     complex_product);
  END_TYPE; -- constrained_design_element_select

  TYPE context_select = SELECT
    (product_class,
     organization);
  END_TYPE; -- context_select

  TYPE contracted_element_select = SELECT
    (item_version,
     function_version,
     work_item_select,
     design_item_select,
     data_element);
  END_TYPE; -- contracted_element_select

  TYPE data_element_context_select = SELECT
    (technical_system,
     organization,
     product_class);
  END_TYPE; -- data_element_context_select

  TYPE data_element_definition_relationship_type = SELECT
    (name,
     type_of_data_element_definition_relationship);
  END_TYPE; -- data_element_definition_relationship_type

  TYPE data_element_relationship_type = SELECT
    (name,
     type_of_data_element_relationship);
  END_TYPE; -- data_element_relationship_type

  TYPE data_element_select = SELECT
    (cable_pull_information,
     connectivity_item_select,
     design_item_select,
     functionality,
     item,
     item_version,
     function_version,
     free_segment,
     port_association,
     activity,
     relation2_select,
     document_version,
     connectivity_allocation,
     document,
     marking,
     offered_function_allocation,
     port_allocation,
     generic_note,
     work_order,
     preferred_item_terminal_allocation,
     requirement,
     routed_segment,
     functional_unit_allocation,
     drawing_sheet,
     document_file,
     product_class,
     preferred_item_allocation,
     product_identification,
     complex_product,
     document_representation);
  END_TYPE; -- data_element_select

  TYPE data_element_source_select = SELECT
    (external_library_reference,
     property_reference);
  END_TYPE; -- data_element_source_select

  TYPE date_and_person_assignment_type = SELECT
    (name,
     type_of_date_and_person_assignment);
  END_TYPE; -- date_and_person_assignment_type

  TYPE date_time_assignment_type = SELECT
    (name,
     type_of_date_time_assignment);
  END_TYPE; -- date_time_assignment_type

  TYPE described_object_select = SELECT
    (classification_element_select,
     organizational_item_select,
     configuration_information_select,
     connectivity_item_select,
     design_item_select,
     item,
     data_element_specification,
     functionality,
     function_version,
     drawing_view,
     drawing_sheet,
     drawing,
     data_element_definition,
     cable_pull_information,
     object_designation,
     item_identification,
     item_version,
     marking,
     work_item_select,
     data_element,
     generic_note,
     specification,
     specification_category,
     activity_method,
     assembly_component_relationship,
     physical_assembly_relationship,
     product_class,
     product_identification,
     product_structure_relationship,
     general_classification,
     item_definition_relationship,
     complex_product,
     activity_element,
     certification);
  END_TYPE; -- described_object_select

  TYPE design_item_select = SELECT
    (device,
     technical_system,
     function_unit,
     node,
     notification,
     path,
     path_node,
     physical_instance,
     section_end,
     route,
     section,
     section_interface,
     signal,
     design_discipline_item_definition,
     function_definition,
     location,
     signal_value,
     process_variable);
  END_TYPE; -- design_item_select

  TYPE device_relationship_type = SELECT
    (name,
     type_of_device_relationship);
  END_TYPE; -- device_relationship_type

  TYPE dimension_symbol_type = ENUMERATION OF
    (arc_length,
     conical_taper,
     counterbore,
     countersink,
     depth,
     diameter,
     radius,
     slope,
     spherical_diameter,
     spherical_radius,
     square);
  END_TYPE; -- dimension_symbol_type

  TYPE document_assignment_type = SELECT
    (name,
     type_of_document_assignment);
  END_TYPE; -- document_assignment_type

  TYPE document_file_relationship_type = SELECT
    (name,
     type_of_document_file_relationship);
  END_TYPE; -- document_file_relationship_type

  TYPE document_select = SELECT
    (drawing,
     document_version,
     document_representation,
     document_file,
     document);
  END_TYPE; -- document_select

  TYPE document_structure_type = SELECT
    (name,
     type_of_document_structure);
  END_TYPE; -- document_structure_type

  TYPE document_version_relationship_type = SELECT
    (name,
     type_of_document_version_relationship);
  END_TYPE; -- document_version_relationship_type

  TYPE documentation_element_select = SELECT
    (drawing,
     drawing_sheet,
     generic_note,
     marking,
     document,
     document_version,
     document_file,
     document_representation);
  END_TYPE; -- documentation_element_select

  TYPE drawing_assignment_select = SELECT
    (organizational_item_select,
     configuration_information_select,
     connectivity_item_select,
     design_item_select,
     item,
     data_element_specification,
     functionality,
     function_version,
     data_element_definition,
     cable_pull_information,
     product_class,
     object_designation,
     item_identification,
     item_version,
     marking,
     work_item_select,
     physical_assembly_relationship,
     data_element,
     security_level,
     security_classification,
     specification,
     specification_category,
     classification_attribute,
     general_classification,
     classification_system,
     generic_note,
     product_identification,
     complex_product);
  END_TYPE; -- drawing_assignment_select

  TYPE drawing_sheet_relationship_type = SELECT
    (type_of_drawing_sheet_relationship,
     name);
  END_TYPE; -- drawing_sheet_relationship_type

  TYPE effective_element_select = SELECT
    (classification_system,
     configuration_information_select,
     connectivity_item_select,
     design_item_select,
     documentation_element_select,
     relation1_select,
     specification_information_select,
     cable_pull_information,
     data_element_association,
     data_element,
     configuration,
     function_version,
     item,
     item_version,
     product_identification,
     security_classification,
     assembly_substitute_relationship,
     class_structure_relationship,
     data_element_definition);
  END_TYPE; -- effective_element_select

  TYPE effectivity_assignment_type = SELECT
    (name,
     type_of_effectivity_assignment);
  END_TYPE; -- effectivity_assignment_type

  TYPE effectivity_relationship_type = SELECT
    (name,
     type_of_effectivity_relationship);
  END_TYPE; -- effectivity_relationship_type

  TYPE encountered_object_select = SELECT
    (location,
     product_component,
     function_unit,
     functional_connectivity_definition,
     signal,
     device,
     connectivity_definition,
     physical_instance);
  END_TYPE; -- encountered_object_select

  TYPE event_or_date_select = SELECT
    (event_reference,
     date_time);
  END_TYPE; -- event_or_date_select

  TYPE final_specification_select = SELECT
    (descriptive_specification,
     design_discipline_item_definition,
     function_definition,
     physical_instance);
  END_TYPE; -- final_specification_select

  TYPE function_definition_relationship_type = SELECT
    (name,
     type_of_function_definition_relationship);
  END_TYPE; -- function_definition_relationship_type

  TYPE function_unit_definition_select = SELECT
    (function_definition,
     product_identification);
  END_TYPE; -- function_unit_definition_select

  TYPE function_unit_relationship_type = SELECT
    (type_of_function_unit_relationship,
     name);
  END_TYPE; -- function_unit_relationship_type

  TYPE function_version_relationship_type = SELECT
    (name,
     type_of_function_version_relationship);
  END_TYPE; -- function_version_relationship_type

  TYPE functional_connectivity_definition_relationship_type = SELECT
    (name,
     type_of_functional_connectivity_definition_relationship);
  END_TYPE; -- functional_connectivity_definition_relationship_type

  TYPE functional_unit_allocation_select = SELECT
    (product_component,
     device,
     physical_instance);
  END_TYPE; -- functional_unit_allocation_select

  TYPE general_location_relationship_type = SELECT
    (name,
     type_of_general_location_relationship);
  END_TYPE; -- general_location_relationship_type

  TYPE general_organizational_data_select = SELECT
    (allocation_select,
     contract,
     configuration,
     cable_pull_information,
     activity_element,
     work_item_select,
     specification_information_select,
     relation1_select,
     documentation_element_select,
     design_item_select,
     connectivity_item_select,
     configuration_information_select,
     classification_element_select,
     routed_segment,
     requirement_document_assignment,
     data_element_definition,
     data_element_specification,
     data_element,
     port_association,
     product_identification,
     function_version,
     free_segment,
     material,
     data_element_association,
     functionality,
     item,
     item_version,
     assembly_substitute_relationship,
     approval_status,
     certification,
     class_structure_relationship,
     person_in_organization_relationship,
     person_in_organization);
  END_TYPE; -- general_organizational_data_select

  TYPE geometrical_tolerance_symbol_type = ENUMERATION OF
    (angularity,
     circular_roundout,
     concentricity,
     cylindrically,
     diameter,
     flatness,
     least_material_condition,
     maximum_material_condition,
     parallelism,
     perpendicularity,
     position,
     profile_of_a_line,
     profile_of_a_surface,
     projected_tolerance_zone,
     regardeless_of_feature_size,
     straightness,
     symmetry,
     target_point,
     total_roundout);
  END_TYPE; -- geometrical_tolerance_symbol_type

  TYPE implementation_select = SELECT
    (device,
     physical_instance);
  END_TYPE; -- implementation_select

  TYPE instance_definition_select = SELECT
    (design_discipline_item_definition,
     product_identification);
  END_TYPE; -- instance_definition_select

  TYPE instance_placement_select = SELECT
    (single_device,
     single_function_unit);
  END_TYPE; -- instance_placement_select

  TYPE interface_port_relationship_type = ENUMERATION OF
    (decomposition,
     derivation);
  END_TYPE; -- interface_port_relationship_type

  TYPE interface_terminal_relationship_type = SELECT
    (name,
     type_of_interface_terminal_relationship);
  END_TYPE; -- interface_terminal_relationship_type

  TYPE item_definition_relationship_type = SELECT
    (name,
     type_of_item_definition_relationship);
  END_TYPE; -- item_definition_relationship_type

  TYPE item_version_relationship_type = SELECT
    (name,
     type_of_item_version_relationship);
  END_TYPE; -- item_version_relationship_type

  TYPE kind_of_data = ENUMERATION OF
    (calculated,
     designed,
     estimated,
     measured,
     required,
     setpoint);
  END_TYPE; -- kind_of_data

  TYPE kind_of_rated_power = ENUMERATION OF
    (apparent_power,
     reactive_power,
     true_power);
  END_TYPE; -- kind_of_rated_power

  TYPE kind_of_repository = ENUMERATION OF
    (iec_61360,
     iso_13584);
  END_TYPE; -- kind_of_repository

  TYPE level_of_approval = ENUMERATION OF
    (disposition,
     equipment_order,
     planning);
  END_TYPE; -- level_of_approval

  TYPE level_type = ENUMERATION OF
    (nominal,
     specified,
     typical);
  END_TYPE; -- level_type

  TYPE line_font_type = ENUMERATION OF
    (chain,
     chain_double_dash,
     continuous,
     dashed,
     dotted);
  END_TYPE; -- line_font_type

  TYPE location_assignment_select = SELECT
    (function_unit,
     device,
     port,
     terminal,
     connectivity_definition,
     functional_connectivity_definition,
     physical_instance,
     product_component,
     design_discipline_item_definition,
     function_definition,
     technical_system,
     signal);
  END_TYPE; -- location_assignment_select

  TYPE location_assignment_type = SELECT
    (name,
     type_of_location_assignment);
  END_TYPE; -- location_assignment_type

  TYPE location_definition_select = SELECT
    (single_device,
     technical_system,
     physical_instance,
     specified_device,
     design_discipline_item_definition,
     product_component);
  END_TYPE; -- location_definition_select

  TYPE marking_position_select = SELECT
    (linear_pattern_location,
     cartesian_point);
  END_TYPE; -- marking_position_select

  TYPE marking_select = SELECT
    (generic_note,
     data_element);
  END_TYPE; -- marking_select

  TYPE name = STRING;
  END_TYPE; -- name

  TYPE neighbourhood_location_relationship_type = SELECT
    (type_of_neighbourhood_location_relationship,
     name);
  END_TYPE; -- neighbourhood_location_relationship_type

  TYPE node_area_select = SELECT
    (point_2d,
     curve_2d);
  END_TYPE; -- node_area_select

  TYPE node_relationship_type = SELECT
    (name,
     type_of_node_relationship);
  END_TYPE; -- node_relationship_type

  TYPE note_type = SELECT
    (type_of_note,
     name);
  END_TYPE; -- note_type

  TYPE notification_relationship_type = SELECT
    (name,
     type_of_notification_relationship);
  END_TYPE; -- notification_relationship_type

  TYPE object_designation_type = SELECT
    (type_of_object_designation,
     name);
  END_TYPE; -- object_designation_type

  TYPE offered_function_allocation_type = SELECT
    (name,
     type_of_offered_function_allocation);
  END_TYPE; -- offered_function_allocation_type

  TYPE organization_in_contract_type = SELECT
    (name,
     type_of_organization_in_contract);
  END_TYPE; -- organization_in_contract_type

  TYPE organization_kind = SELECT
    (name,
     type_of_organization);
  END_TYPE; -- organization_kind

  TYPE organization_relationship_type = SELECT
    (name,
     type_of_organization_relationship);
  END_TYPE; -- organization_relationship_type

  TYPE organizational_item_select = SELECT
    (approval,
     approval_status,
     contract,
     organization,
     person,
     retention_period,
     address);
  END_TYPE; -- organizational_item_select

  TYPE page_connector_presentation_type = ENUMERATION OF
    (sink,
     source);
  END_TYPE; -- page_connector_presentation_type

  TYPE page_connector_reference_select = SELECT
    (page_connector,
     page_connector_presentation);
  END_TYPE; -- page_connector_reference_select

  TYPE page_connector_type = ENUMERATION OF
    (exclusive,
     central,
     neutral);
  END_TYPE; -- page_connector_type

  TYPE path_relationship_type = SELECT
    (name,
     type_of_path_relationship);
  END_TYPE; -- path_relationship_type

  TYPE performing_item_select = SELECT
    (design_discipline_item_definition,
     product_component,
     device,
     physical_instance);
  END_TYPE; -- performing_item_select

  TYPE period_or_date_select = SELECT
    (date_time,
     event_reference,
     duration);
  END_TYPE; -- period_or_date_select

  TYPE person_or_organization_assignment_type = SELECT
    (name,
     type_of_person_or_organization_assignment);
  END_TYPE; -- person_or_organization_assignment_type

  TYPE person_or_organization_select = SELECT
    (organization,
     person_in_organization);
  END_TYPE; -- person_or_organization_select

  TYPE physical_instance_definition_select = SELECT
    (design_discipline_item_definition,
     product_identification);
  END_TYPE; -- physical_instance_definition_select

  TYPE point_marker_symbol_type = ENUMERATION OF
    (asterisk,
     circle,
     dot,
     plus,
     square,
     triangle,
     x);
  END_TYPE; -- point_marker_symbol_type

  TYPE port_relationship_type = SELECT
    (type_of_port_relationship,
     name);
  END_TYPE; -- port_relationship_type

  TYPE portrait_or_landscape = ENUMERATION OF
    (portrait,
     landscape);
  END_TYPE; -- portrait_or_landscape

  TYPE position_select = SELECT
    (gis_position,
     cartesian_point);
  END_TYPE; -- position_select

  TYPE predefined_data_element_select = SELECT
    (mounting_features,
     body_height,
     body_length,
     body_breadth,
     outside_diameter,
     mass,
     material,
     rated_power,
     rated_current,
     rated_voltage,
     component_colour,
     cross_section,
     operating_temperature,
     storage_temperature);
  END_TYPE; -- predefined_data_element_select

  TYPE preferred_equipment_select = SELECT
    (function_definition,
     design_discipline_item_definition);
  END_TYPE; -- preferred_equipment_select

  TYPE preferred_item_select = SELECT
    (function_definition,
     design_discipline_item_definition);
  END_TYPE; -- preferred_item_select

  TYPE preferred_item_terminal_select = SELECT
    (interface_terminal,
     interface_port);
  END_TYPE; -- preferred_item_terminal_select

  TYPE presentation_select = SELECT
    (connecting_line,
     activity_element,
     connectivity_item_select,
     design_item_select,
     work_item_select,
     functionality,
     function_version,
     item,
     data_element_definition,
     data_element_specification,
     data_element,
     classification_element_select,
     generic_note,
     document,
     document_version,
     routed_segment,
     alias_identification,
     cross_reference,
     item_identification,
     item_version,
     page_connector_presentation,
     object_designation,
     free_segment);
  END_TYPE; -- presentation_select

  TYPE process_variable_relationship_type = SELECT
    (name,
     type_of_process_variable_relationship);
  END_TYPE; -- process_variable_relationship_type

  TYPE process_variable_system_assignment_type = SELECT
    (name,
     type_of_process_variable_system_assignment);
  END_TYPE; -- process_variable_system_assignment_type

  TYPE product_class_relationship_type = SELECT
    (type_of_product_class_relationship,
     name);
  END_TYPE; -- product_class_relationship_type

  TYPE product_function_component_select = SELECT
    (product_component,
     function_definition);
  END_TYPE; -- product_function_component_select

  TYPE product_structure_relationship_type = SELECT
    (name,
     type_of_product_structure_relationship);
  END_TYPE; -- product_structure_relationship_type

  TYPE project_relationship_type = SELECT
    (name,
     type_of_project_relationship);
  END_TYPE; -- project_relationship_type

  TYPE relation1_select = SELECT
    (alternate_item_relationship,
     assembly_component_relationship,
     composition_relationship,
     connectivity_definition_relationship,
     device_relationship,
     drawing_sequence,
     function_definition_relationship,
     function_version_relationship,
     functional_connectivity_definition_relationship,
     item_definition_relationship,
     item_version_relationship,
     path_node_relationship,
     path_relationship,
     document_version_relationship,
     document_file_relationship,
     drawing_sheet_relationship,
     technical_system_relationship,
     section_relationship,
     data_element_relationship,
     function_unit_relationship,
     location_relationship,
     node_relationship,
     notification_relationship,
     route_relationship,
     section_interface_relationship,
     signal_relationship,
     activity_relationship,
     physical_assembly_relationship,
     process_variable_relationship,
     complex_product_relationship,
     product_structure_relationship);
  END_TYPE; -- relation1_select

  TYPE relation2_select = SELECT
    (item_definition_relationship,
     assembly_component_relationship,
     composition_relationship,
     connectivity_definition_relationship,
     device_relationship,
     functional_connectivity_definition_relationship,
     function_definition_relationship,
     function_unit_relationship,
     node_relationship,
     physical_assembly_relationship,
     route_relationship,
     section_interface_relationship,
     section_relationship,
     technical_system_relationship,
     location_relationship,
     complex_product_relationship,
     product_structure_relationship);
  END_TYPE; -- relation2_select

  TYPE repository_type = SELECT
    (name,
     kind_of_repository);
  END_TYPE; -- repository_type

  TYPE requirement_assignment_type = SELECT
    (name,
     type_of_requirement_assignment);
  END_TYPE; -- requirement_assignment_type

  TYPE requirement_relationship_type = SELECT
    (type_of_requirement_relationship,
     name);
  END_TYPE; -- requirement_relationship_type

  TYPE route_element_select = SELECT
    (section,
     section_interface,
     node);
  END_TYPE; -- route_element_select

  TYPE route_relationship_type = SELECT
    (name,
     type_of_route_relationship);
  END_TYPE; -- route_relationship_type

  TYPE routed_object_select = SELECT
    (physical_instance,
     connectivity_definition,
     device,
     product_component,
     function_unit,
     functional_connectivity_definition);
  END_TYPE; -- routed_object_select

  TYPE routed_segment_select = SELECT
    (route,
     route_element_select);
  END_TYPE; -- routed_segment_select

  TYPE schematic_text_select = SELECT
    (schematic_node,
     user_defined_symbol);
  END_TYPE; -- schematic_text_select

  TYPE section_end_type = SELECT
    (name,
     type_of_section_end);
  END_TYPE; -- section_end_type

  TYPE section_interface_relationship_type = SELECT
    (type_of_section_interface_relationship,
     name);
  END_TYPE; -- section_interface_relationship_type

  TYPE section_relationship_type = SELECT
    (name,
     type_of_section_relationship);
  END_TYPE; -- section_relationship_type

  TYPE security_element_select = SELECT
    (documentation_element_select,
     activity,
     data_element_association,
     classification_system,
     assembly_substitute_relationship,
     class_structure_relationship,
     allocation_select,
     manufacturing_configuration,
     cable_pull_information,
     configuration,
     connectivity_item_select,
     design_item_select,
     relation1_select,
     specification_information_select,
     work_item_select,
     activity_element,
     contract,
     data_element,
     data_element_definition,
     function_version,
     item_version,
     product_identification);
  END_TYPE; -- security_element_select

  TYPE shape_assignment_type = SELECT
    (type_of_shape_assignment,
     name);
  END_TYPE; -- shape_assignment_type

  TYPE shape_association_select = SELECT
    (device,
     terminal,
     section_interface,
     location,
     section,
     design_discipline_item_definition,
     function_definition,
     function_unit,
     product_component,
     physical_instance,
     technical_system,
     connectivity_definition,
     functional_connectivity_definition,
     port,
     interface_port,
     interface_terminal);
  END_TYPE; -- shape_association_select

  TYPE signal_relationship_type = SELECT
    (name,
     type_of_signal_relationship);
  END_TYPE; -- signal_relationship_type

  TYPE signal_system_assignment_type = SELECT
    (name,
     type_of_signal_system_assignment);
  END_TYPE; -- signal_system_assignment_type

  TYPE signal_value_type = SELECT
    (name,
     characteristic_of_signal_value);
  END_TYPE; -- signal_value_type

  TYPE single_value_select = SELECT
    (binary_value,
     logical_value,
     string_value,
     value_with_unit);
  END_TYPE; -- single_value_select

  TYPE solution_base_select = SELECT
    (alternative_solution,
     single_function_unit,
     function_definition,
     product_component);
  END_TYPE; -- solution_base_select

  TYPE solution_instance_select = SELECT
    (technical_system,
     section_interface,
     signal,
     node,
     notification,
     section,
     section_end,
     path_node,
     path,
     route);
  END_TYPE; -- solution_instance_select

  TYPE specification_information_select = SELECT
    (product_class,
     requirement,
     specification,
     specification_category,
     complex_product);
  END_TYPE; -- specification_information_select

  TYPE specification_operand_select = SELECT
    (specification_expression,
     specification);
  END_TYPE; -- specification_operand_select

  TYPE string_alignment = ENUMERATION OF
    (left,
     right,
     up,
     down);
  END_TYPE; -- string_alignment

  TYPE system_select = SELECT
    (function_unit,
     device,
     classification_system,
     physical_instance,
     process_variable,
     requirement,
     route,
     signal,
     notification,
     document_representation);
  END_TYPE; -- system_select

  TYPE technical_system_relationship_type = SELECT
    (type_of_technical_system_relationship,
     name);
  END_TYPE; -- technical_system_relationship_type

  TYPE terminal_relationship_type = SELECT
    (name,
     type_of_terminal_relationship);
  END_TYPE; -- terminal_relationship_type

  TYPE terminator_symbol_type = ENUMERATION OF
    (blanked_arrow,
     blanked_box,
     blanked_dot,
     dimension_origin,
     filled_arrow,
     filled_box,
     filled_dot,
     integral_symbol,
     open_arrow,
     slash,
     unfilled_arrow);
  END_TYPE; -- terminator_symbol_type

  TYPE text_alignment = ENUMERATION OF
    (left_aligned,
     right_aligned,
     centre_aligned);
  END_TYPE; -- text_alignment

  TYPE text_string_line = ENUMERATION OF
    (overline,
     underline);
  END_TYPE; -- text_string_line

  TYPE trigger_select = SELECT
    (signal,
     signal_value,
     process_variable);
  END_TYPE; -- trigger_select

  TYPE type_of_activity = ENUMERATION OF
    (amendment,
     analysis,
     cancellation,
     delivery_change,
     design_change,
     design,
     mock_up_creation,
     order,
     prototype_building,
     rectification,
     restructuring,
     spare_part_creation,
     stop_notice,
     testing,
     work_definition);
  END_TYPE; -- type_of_activity

  TYPE type_of_activity_element = ENUMERATION OF
    (control,
     input,
     output);
  END_TYPE; -- type_of_activity_element

  TYPE type_of_activity_method_assignment = ENUMERATION OF
    (non_recommended_method,
     recommended_method);
  END_TYPE; -- type_of_activity_method_assignment

  TYPE type_of_activity_relationship = ENUMERATION OF
    (decomposition,
     derivation,
     sequence,
     precedence,
     simultaneity);
  END_TYPE; -- type_of_activity_relationship

  TYPE type_of_approval_relationship = ENUMERATION OF
    (decomposition,
     sequence,
     precedence);
  END_TYPE; -- type_of_approval_relationship

  TYPE type_of_association = ENUMERATION OF
    (availability,
     identification,
     non_replaceable_standard,
     option,
     part_usage,
     replaceable_standard);
  END_TYPE; -- type_of_association

  TYPE type_of_class_structure_relationship = ENUMERATION OF
    (availability,
     identification,
     non_replaceable_standard,
     option,
     replaceable_standard);
  END_TYPE; -- type_of_class_structure_relationship

  TYPE type_of_classification_association = ENUMERATION OF
    (electromagnetic_compatibility,
     environmental_conditions,
     flow_direction,
     protection_class);
  END_TYPE; -- type_of_classification_association

  TYPE type_of_code = ENUMERATION OF
    (iec_61286,
     iso_646,
     iso_3098_1,
     iso_6937,
     iso_8859_1,
     iso_10646);
  END_TYPE; -- type_of_code

  TYPE type_of_complex_product_relationship = ENUMERATION OF
    (derivation,
     redundancy,
     substitution,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_complex_product_relationship

  TYPE type_of_condition = ENUMERATION OF
    (part_usage,
     identification,
     validity);
  END_TYPE; -- type_of_condition

  TYPE type_of_configuration = ENUMERATION OF
    (design,
     usage);
  END_TYPE; -- type_of_configuration

  TYPE type_of_connectivity_definition_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     redundancy,
     substitution,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_connectivity_definition_relationship

  TYPE type_of_corner_styles = ENUMERATION OF
    (round,
     square);
  END_TYPE; -- type_of_corner_styles

  TYPE type_of_data_element_definition_relationship = ENUMERATION OF
    (decomposition,
     value_domain,
     substitution);
  END_TYPE; -- type_of_data_element_definition_relationship

  TYPE type_of_data_element_relationship = ENUMERATION OF
    (dependency,
     decomposition,
     equivalence,
     substitution,
     tolerancing_information);
  END_TYPE; -- type_of_data_element_relationship

  TYPE type_of_date_and_person_assignment = ENUMERATION OF
    (creation,
     update);
  END_TYPE; -- type_of_date_and_person_assignment

  TYPE type_of_date_time_assignment = ENUMERATION OF
    (creation,
     update,
     production,
     installation,
     registration);
  END_TYPE; -- type_of_date_time_assignment

  TYPE type_of_device_relationship = ENUMERATION OF
    (associated_equipment,
     derivation,
     envelope,
     redundancy,
     shield,
     substitution);
  END_TYPE; -- type_of_device_relationship

  TYPE type_of_document_assignment = ENUMERATION OF
    (additional_information,
     behaviour,
     catalogue,
     description,
     informative,
     mandatory,
     manual,
     mathematical_description,
     document_assignment_specification);
  END_TYPE; -- type_of_document_assignment

  TYPE type_of_document_file_relationship = ENUMERATION OF
    (addition,
     copy,
     derivation,
     decomposition,
     peer,
     sequence,
     substitution,
     translation);
  END_TYPE; -- type_of_document_file_relationship

  TYPE type_of_document_structure = ENUMERATION OF
    (addition,
     copy,
     decomposition,
     derivation,
     peer,
     reference_212,
     sequence,
     substitution,
     translation);
  END_TYPE; -- type_of_document_structure

  TYPE type_of_document_version_relationship = ENUMERATION OF
    (derivation,
     hierarchy,
     sequence,
     substitution,
     supplied_document);
  END_TYPE; -- type_of_document_version_relationship

  TYPE type_of_drawing_sheet_relationship = ENUMERATION OF
    (derivation,
     substitution,
     translation,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_drawing_sheet_relationship

  TYPE type_of_effectivity_assignment = ENUMERATION OF
    (actual,
     planned,
     required);
  END_TYPE; -- type_of_effectivity_assignment

  TYPE type_of_effectivity_relationship = ENUMERATION OF
    (constraint,
     inheritance);
  END_TYPE; -- type_of_effectivity_relationship

  TYPE type_of_font = ENUMERATION OF
    (iec_61286,
     iso_646,
     iso_3098_1,
     iso_6937,
     iso_8859_1,
     iso_10646);
  END_TYPE; -- type_of_font

  TYPE type_of_function_definition_relationship = ENUMERATION OF
    (alternate,
     derivation,
     substitution);
  END_TYPE; -- type_of_function_definition_relationship

  TYPE type_of_function_unit_relationship = ENUMERATION OF
    (derivation,
     implementation,
     specialization,
     substitution,
     redundancy);
  END_TYPE; -- type_of_function_unit_relationship

  TYPE type_of_function_version_relationship = ENUMERATION OF
    (derivation,
     hierarchy,
     sequence,
     supplied_function);
  END_TYPE; -- type_of_function_version_relationship

  TYPE type_of_functional_connectivity_definition_relationship =
 ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     redundancy,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_functional_connectivity_definition_relationship

  TYPE type_of_general_location_relationship = ENUMERATION OF
    (alternate,
     substitution,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_general_location_relationship

  TYPE type_of_inheritance = ENUMERATION OF
    (exception,
     inherited,
     local_212);
  END_TYPE; -- type_of_inheritance

  TYPE type_of_interface_port_relationship = SELECT
    (name,
     interface_port_relationship_type);
  END_TYPE; -- type_of_interface_port_relationship

  TYPE type_of_interface_terminal_relationship = ENUMERATION OF
    (decomposition,
     derivation);
  END_TYPE; -- type_of_interface_terminal_relationship

  TYPE type_of_item_definition_relationship = ENUMERATION OF
    (alternate,
     derivation,
     substitution);
  END_TYPE; -- type_of_item_definition_relationship

  TYPE type_of_item_version_relationship = ENUMERATION OF
    (derivation,
     supplied_item,
     hierarchy,
     sequence);
  END_TYPE; -- type_of_item_version_relationship

  TYPE type_of_line_styles = ENUMERATION OF
    (round,
     square);
  END_TYPE; -- type_of_line_styles

  TYPE type_of_location_assignment = ENUMERATION OF
    (accommodation);
  END_TYPE; -- type_of_location_assignment

  TYPE type_of_neighbourhood_location_relationship = ENUMERATION OF
    (above,
     across,
     adjoining,
     around,
     outside);
  END_TYPE; -- type_of_neighbourhood_location_relationship

  TYPE type_of_node_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution);
  END_TYPE; -- type_of_node_relationship

  TYPE type_of_note = ENUMERATION OF
    (assembly_instruction,
     installation_instruction,
     manufacturing_instruction,
     operating_instruction,
     explanatory_note);
  END_TYPE; -- type_of_note

  TYPE type_of_notification_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     translation);
  END_TYPE; -- type_of_notification_relationship

  TYPE type_of_object_designation = ENUMERATION OF
    (function_designation,
     location_designation,
     product_designation);
  END_TYPE; -- type_of_object_designation

  TYPE type_of_offered_function_allocation = ENUMERATION OF
    (dedicated_function,
     offered_function);
  END_TYPE; -- type_of_offered_function_allocation

  TYPE type_of_operation = ENUMERATION OF
    (and_212,
     not_212,
     oneof_212,
     or_212);
  END_TYPE; -- type_of_operation

  TYPE type_of_organization = ENUMERATION OF
    (company,
     department,
     plant);
  END_TYPE; -- type_of_organization

  TYPE type_of_organization_in_contract = ENUMERATION OF
    (customer,
     owner);
  END_TYPE; -- type_of_organization_in_contract

  TYPE type_of_organization_relationship = ENUMERATION OF
    (hierarchy,
     legal_succession,
     reorganization);
  END_TYPE; -- type_of_organization_relationship

  TYPE type_of_path_relationship = ENUMERATION OF
    (alternate,
     derivation,
     substitution);
  END_TYPE; -- type_of_path_relationship

  TYPE type_of_person_or_organization_assignment = ENUMERATION OF
    (author,
     creator,
     classifcation_officer,
     custodian,
     customer,
     design_supplier,
     editor,
     id_owner,
     inspector,
     local_representative,
     location,
     manufacturer,
     operator,
     owner,
     scope,
     supplier,
     wholesaler);
  END_TYPE; -- type_of_person_or_organization_assignment

  TYPE type_of_port_relationship = ENUMERATION OF
    (decomposition,
     redundancy);
  END_TYPE; -- type_of_port_relationship

  TYPE type_of_process_variable_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     substitution);
  END_TYPE; -- type_of_process_variable_relationship

  TYPE type_of_process_variable_system_assignment = ENUMERATION OF
    (amplifier,
     monitor,
     source,
     target,
     transmitter);
  END_TYPE; -- type_of_process_variable_system_assignment

  TYPE type_of_product_class_relationship = ENUMERATION OF
    (derivation,
     hierarchy,
     substitution,
     version_sequence);
  END_TYPE; -- type_of_product_class_relationship

  TYPE type_of_product_structure_relationship = ENUMERATION OF
    (decomposition,
     specialization,
     realization);
  END_TYPE; -- type_of_product_structure_relationship

  TYPE type_of_project_relationship = ENUMERATION OF
    (decomposition,
     dependency,
     sequence,
     succession);
  END_TYPE; -- type_of_project_relationship

  TYPE type_of_requirement_assignment = ENUMERATION OF
    (compelled_element,
     solution);
  END_TYPE; -- type_of_requirement_assignment

  TYPE type_of_requirement_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_requirement_relationship

  TYPE type_of_route_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution);
  END_TYPE; -- type_of_route_relationship

  TYPE type_of_section_end = ENUMERATION OF
    (flat_oval,
     round,
     u_shape);
  END_TYPE; -- type_of_section_end

  TYPE type_of_section_interface_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     version_hierarchy);
  END_TYPE; -- type_of_section_interface_relationship

  TYPE type_of_section_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     version_hierarchy,
     version_sequence);
  END_TYPE; -- type_of_section_relationship

  TYPE type_of_shape_assignment = ENUMERATION OF
    (mounting_space,
     safety_space,
     body_shape);
  END_TYPE; -- type_of_shape_assignment

  TYPE type_of_signal_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     redundancy,
     version_hierarchy);
  END_TYPE; -- type_of_signal_relationship

  TYPE type_of_signal_system_assignment = ENUMERATION OF
    (amplifier,
     monitor,
     source,
     target,
     transmitter);
  END_TYPE; -- type_of_signal_system_assignment

  TYPE type_of_technical_system_relationship = ENUMERATION OF
    (alternate,
     decomposition,
     derivation,
     substitution,
     redundancy);
  END_TYPE; -- type_of_technical_system_relationship

  TYPE type_of_terminal_relationship = ENUMERATION OF
    (redundancy);
  END_TYPE; -- type_of_terminal_relationship

  TYPE type_of_work_order = ENUMERATION OF
    (design_deviation_permit,
     design_release,
     management_resolution,
     manufacturing_release,
     production_deviation_permit);
  END_TYPE; -- type_of_work_order

  TYPE type_of_work_request = ENUMERATION OF
    (change_of_standard,
     cost_reduction,
     customer_rejection,
     customer_request,
     durability_improvement,
     government_regulation,
     procurement_alignment,
     production_alignment,
     production_relief,
     production_requirement,
     quality_improvement,
     security_reason,
     standardization,
     supplier_request,
     technical_improvement,
     tool_improvement);
  END_TYPE; -- type_of_work_request

  TYPE type_select = SELECT
    (kind_of_data,
     name);
  END_TYPE; -- type_select

  TYPE typical_node_select = SELECT
    (annotation_curve,
     fill_area,
     text);
  END_TYPE; -- typical_node_select

  TYPE undefined_object = STRING;
  END_TYPE; -- undefined_object
  
  TYPE work_item_select = SELECT
    (activity,
     project,
     work_order,
     work_request);
  END_TYPE; -- work_item_select

  TYPE work_order_kind = SELECT
    (name,
     type_of_work_order);
  END_TYPE; -- work_order_kind

  TYPE work_request_type = SELECT
    (name,
     type_of_work_request);
  END_TYPE; -- work_request_type

  ENTITY activity;
      concerned_organization : SET [0:?] OF organization;
      supplying_organization : SET [0:?] OF organization;
      activity_type          : name;
      id                     : undefined_object;
      status                 : OPTIONAL undefined_object;
      description            : OPTIONAL undefined_object;
      actual_start_date      : OPTIONAL date_time;
      actual_end_date        : OPTIONAL date_time;
      planned_start_date     : OPTIONAL event_or_date_select;
      planned_end_date       : OPTIONAL period_or_date_select;
      chosen_method          : OPTIONAL activity_method;
      requestor              : OPTIONAL date_and_person_or_organization;
      resolved_request       : SET [0:?] OF work_request;
      internal               : OPTIONAL BOOLEAN;
    INVERSE
      associated_project : SET [0:1] OF project FOR work_program;
      authorization      : SET [0:1] OF work_order FOR is_controlling;
  END_ENTITY; -- activity

  ENTITY activity_element;
      role                : name;
      associated_activity : activity;
      element             : activity_element_select;
  END_ENTITY; -- activity_element

  ENTITY activity_method;
      consequence : OPTIONAL undefined_object;
      name        : undefined_object;
      description : undefined_object;
  END_ENTITY; -- activity_method

  ENTITY activity_method_assignment;
      assigned_method       : activity_method;
      assigned_work_request : work_request;
      relation_type         : name;
  END_ENTITY; -- activity_method_assignment

  ENTITY activity_relationship;
      relating      : activity;
      related       : activity;
      description   : OPTIONAL undefined_object;
      relation_type : name;
  END_ENTITY; -- activity_relationship

  ENTITY address;
      country           : OPTIONAL undefined_object;
      postal_code       : OPTIONAL undefined_object;
      region            : OPTIONAL undefined_object;
      town              : OPTIONAL undefined_object;
      postal_box        : OPTIONAL undefined_object;
      street            : OPTIONAL undefined_object;
      street_number     : OPTIONAL undefined_object;
      internal_location : OPTIONAL undefined_object;
      telephone_number  : OPTIONAL undefined_object;
      fax_number        : OPTIONAL undefined_object;
      email_address     : OPTIONAL undefined_object;
      telex_number      : OPTIONAL undefined_object;
  END_ENTITY; -- address

  ENTITY aggregated_value
    SUBTYPE OF (data_element_value);
      member_definition : LIST [1:?] OF data_element_value;
  END_ENTITY; -- aggregated_value

  ENTITY alias_designation;
      alias_extended_designation : object_designation;
      is_applied_to              : alias_designation_select;
      alias_scope                : OPTIONAL organization;
      description                : OPTIONAL undefined_object;
  END_ENTITY; -- alias_designation

  ENTITY alias_identification;
      alias_id      : undefined_object;
      alias_scope   : OPTIONAL organization;
      description   : OPTIONAL undefined_object;
      is_applied_to : alias_name_select;
  END_ENTITY; -- alias_identification

  ENTITY alias_version;
      version_id          : undefined_object;
      associated_alias_id : assigned_alias_identification;
  END_ENTITY; -- alias_version

  ENTITY alternate_item_relationship;
      alternate              : item;
      base                   : item;
      fulfilled_requirements : undefined_object;
  END_ENTITY; -- alternate_item_relationship

  ENTITY alternative_solution
    SUBTYPE OF (complex_product);
      base_element : solution_base_select;
  END_ENTITY; -- alternative_solution

  ENTITY angular_dimension
    SUBTYPE OF (dimension);
      extent    : dimension_line;
      component : OPTIONAL SET [1:2] OF projection_line;
  END_ENTITY; -- angular_dimension

  ENTITY annotation_curve
    SUBTYPE OF (annotation_element);
      assigned_appearance : curve_appearance;
  END_ENTITY; -- annotation_curve

  ENTITY annotation_element
    ABSTRACT SUPERTYPE OF (ONEOF (annotation_symbol,fill_area,text,
        annotation_curve,annotation_subfigure,schematic_node))
    SUBTYPE OF (draughting_annotation);
  END_ENTITY; -- annotation_element

  ENTITY annotation_placed_annotation
    SUBTYPE OF (draughting_annotation);
  END_ENTITY; -- annotation_placed_annotation

  ENTITY annotation_subfigure
    SUBTYPE OF (annotation_element);
      definition : annotation_subfigure_definition;
      position   : point_2d;
      rotation   : undefined_object;
      scale      : undefined_object;
  END_ENTITY; -- annotation_subfigure

  ENTITY annotation_subfigure_definition;
      coordinate_space : cartesian_coordinate_space_2d;
      name             : OPTIONAL undefined_object;
      blanking_box     : OPTIONAL rectangular_area;
    INVERSE
      defined_subfigures : SET [1:?] OF annotation_subfigure FOR 
                              definition;
      components         : SET [1:?] OF
                               annotation_subfigure_definition_element FOR 
                              containing_definition;
  END_ENTITY; -- annotation_subfigure_definition

  ENTITY annotation_subfigure_definition_element;
      containing_definition : annotation_subfigure_definition;
      used_annotation       : annotation_placed_annotation;
      annotation_layers     : SET [1:?] OF layer;
      annotation_visibility : visibility;
  END_ENTITY; -- annotation_subfigure_definition_element

  ENTITY annotation_symbol
    ABSTRACT SUPERTYPE OF (ONEOF (externally_defined_symbol,
        predefined_symbol,user_defined_symbol))
    SUBTYPE OF (annotation_element);
      scale             : undefined_object;
      rotation          : undefined_object;
      position          : point_2d;
      overriding_colour : OPTIONAL colour;
      blanking_box      : OPTIONAL rectangular_area;
  END_ENTITY; -- annotation_symbol

  ENTITY appearance
    ABSTRACT SUPERTYPE OF (ONEOF (curve_appearance,text_appearance,
        fill_area_appearance));
  END_ENTITY; -- appearance

  ENTITY application_context;
      description        : OPTIONAL undefined_object;
      application_domain : undefined_object;
      life_cycle_stage   : undefined_object;
  END_ENTITY; -- application_context

  ENTITY approval;
      status         : approval_status;
      is_applied_to  : SET [1:?] OF approval_item_select;
      level          : OPTIONAL name;
      planned_date   : OPTIONAL date_time;
      actual_date    : OPTIONAL date_time;
      is_approved_by : SET [0:?] OF date_and_person_or_organization;
      scope          : SET [0:?] OF organization;
  END_ENTITY; -- approval

  ENTITY approval_relationship;
      relating      : approval;
      related       : approval;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- approval_relationship

  ENTITY approval_status;
      status_name                : undefined_object;
      used_classification_system : OPTIONAL classification_system;
  END_ENTITY; -- approval_status

  ENTITY assembly_component_relationship
    SUPERTYPE OF (ONEOF (next_higher_assembly,promissory_usage));
      related   : device;
      relating  : assembly_definition;
      placement : OPTIONAL undefined_object;
  END_ENTITY; -- assembly_component_relationship

  ENTITY assembly_definition
    SUBTYPE OF (design_discipline_item_definition);
      assembly_type : OPTIONAL undefined_object;
  END_ENTITY; -- assembly_definition

  ENTITY assembly_substitute_relationship;
      base        : assembly_component_relationship;
      substitute  : assembly_component_relationship;
      description : OPTIONAL undefined_object;
  END_ENTITY; -- assembly_substitute_relationship

  ENTITY binary_value;
      value_of_binary_value : undefined_object;
  END_ENTITY; -- binary_value

  ENTITY body_breadth;
      value_of_body_breadth : value_with_unit;
  END_ENTITY; -- body_breadth

  ENTITY body_height;
      value_of_body_height : value_with_unit;
  END_ENTITY; -- body_height

  ENTITY body_length;
      value_of_body_length : value_with_unit;
  END_ENTITY; -- body_length

  ENTITY cable_pull_information;
      associated_object : SET [1:?] OF routed_object;
      id                : undefined_object;
      version_id        : OPTIONAL undefined_object;
      description       : OPTIONAL undefined_object;
  END_ENTITY; -- cable_pull_information

  ENTITY cartesian_coordinate_space_2d;
      length_measure_unit      : undefined_object;
      plane_angle_measure_unit : undefined_object;
      precision                : numerical_precision;
  END_ENTITY; -- cartesian_coordinate_space_2d

  ENTITY cartesian_coordinate_space_3d;
      length_measure_unit      : undefined_object;
      plane_angle_measure_unit : undefined_object;
      precision                : numerical_precision;
  END_ENTITY; -- cartesian_coordinate_space_3d

  ENTITY cartesian_coordinate_space_with_grid
    SUBTYPE OF (cartesian_coordinate_space_2d);
      delta_x : undefined_object;
      delta_y : undefined_object;
      origin  : undefined_object;
  END_ENTITY; -- cartesian_coordinate_space_with_grid

  ENTITY cartesian_point;
      coordinates : LIST [3:3] OF undefined_object;
  END_ENTITY; -- cartesian_point

  ENTITY certification;
      certification_type : undefined_object;
      name               : undefined_object;
      purpose            : OPTIONAL undefined_object;
      is_applied_to      : SET [1:?] OF certified_element_select;
  END_ENTITY; -- certification

  ENTITY chained_dimension_pair
    SUBTYPE OF (dimension_sequence_pair);
  END_ENTITY; -- chained_dimension_pair

  ENTITY class_category_association;
      associated_product_class : product_class;
      mandatory                : BOOLEAN;
      associated_category      : specification_category;
  END_ENTITY; -- class_category_association

  ENTITY class_condition_association;
      associated_product_class : product_class;
      description              : OPTIONAL undefined_object;
      condition_type           : name;
      associated_condition     : specification_expression;
  END_ENTITY; -- class_condition_association

  ENTITY class_inclusion_association;
      associated_product_class : product_class;
      associated_inclusion     : specification_inclusion;
      description              : OPTIONAL undefined_object;
  END_ENTITY; -- class_inclusion_association

  ENTITY class_reference;
      type_of_repository : name;
      supplier           : undefined_object;
      code               : undefined_object;
      version            : undefined_object;
  END_ENTITY; -- class_reference

  ENTITY class_specification_association;
      associated_product_class : product_class;
      associated_specification : specification;
      association_type         : name;
  END_ENTITY; -- class_specification_association

  ENTITY class_structure_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : product_class;
      related       : product_function_component_select;
  END_ENTITY; -- class_structure_relationship

  ENTITY classification_association;
      classified_element : classified_item_select;
      classification     : general_classification;
      role               : OPTIONAL name;
      definitional       : LOGICAL;
  END_ENTITY; -- classification_association

  ENTITY classification_attribute;
      allowed_value             : SET [0:?] OF data_element;
      id                        : undefined_object;
      description               : OPTIONAL undefined_object;
      associated_classification : general_classification;
      name                      : OPTIONAL undefined_object;
      attribute_definition      : data_element_definition;
  END_ENTITY; -- classification_attribute

  ENTITY classification_system;
      id          : undefined_object;
      description : OPTIONAL undefined_object;
    INVERSE
      allowed_classes : SET [0:?] OF general_classification FOR 
                           used_classification_system;
  END_ENTITY; -- classification_system

  ENTITY coded_size
    SUBTYPE OF (rectangular_size);
      size                : undefined_object;
      referenced_standard : classification_system;
  END_ENTITY; -- coded_size

  ENTITY colour
    ABSTRACT SUPERTYPE OF (ONEOF (predefined_colour,user_defined_colour));
  END_ENTITY; -- colour

  ENTITY complex_product
    ABSTRACT SUPERTYPE OF (ONEOF (alternative_solution,product_component));
      id         : undefined_object;
      version_id : OPTIONAL undefined_object;
  END_ENTITY; -- complex_product

  ENTITY complex_product_relationship;
      description   : OPTIONAL undefined_object;
      relation_type : name;
      related       : complex_product;
      relating      : complex_product;
  END_ENTITY; -- complex_product_relationship

  ENTITY component_colour;
      colour_id     : undefined_object;
      coding_system : OPTIONAL classification_system;
  END_ENTITY; -- component_colour

  ENTITY component_placement;
      transformation              : undefined_object;
      reference_product_component : product_component;
      placed_component            : product_component;
  END_ENTITY; -- component_placement

  ENTITY composition_relationship;
      functional_component : function_unit;
      composed_function    : function_definition;
  END_ENTITY; -- composition_relationship

  ENTITY configuration;
      is_solution_for    : configured_specification_select;
      configured_element : configuration_select;
      configuration_type : type_of_configuration;
      inheritance_type   : type_of_inheritance;
  END_ENTITY; -- configuration

  ENTITY connect_area;
      defined_by : SET [1:?] OF node_area_select;
  END_ENTITY; -- connect_area

  ENTITY connecting_line;
      presents : connectivity_presentation_select;
  END_ENTITY; -- connecting_line

  ENTITY connection
    SUBTYPE OF (connectivity_definition);
      connected_terminal : SET [0:?] OF terminal;
  END_ENTITY; -- connection

  ENTITY connectivity_allocation;
      connectivity_implementation       : connectivity_allocation_select;
      description                       : OPTIONAL undefined_object;
      allocated_connectivity_definition : functional_connectivity_definition;
  END_ENTITY; -- connectivity_allocation

  ENTITY connectivity_definition
    ABSTRACT SUPERTYPE OF (ONEOF (connection,interface_terminal_connection));
      id              : undefined_object;
      description     : OPTIONAL undefined_object;
      implemented_by  : SET [0:?] OF implementation_select;
      version_id      : OPTIONAL undefined_object;
      connectivity_of : assembly_definition;
  END_ENTITY; -- connectivity_definition

  ENTITY connectivity_definition_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : connectivity_definition;
      related       : connectivity_definition;
  END_ENTITY; -- connectivity_definition_relationship

  ENTITY contract;
      id                 : undefined_object;
      description        : OPTIONAL undefined_object;
      contracted_element : SET [0:?] OF contracted_element_select;
    INVERSE
      release : SET [0:?] OF organization_in_contract FOR contract;
  END_ENTITY; -- contract

  ENTITY cross_reference
    ABSTRACT SUPERTYPE OF (ONEOF (detached_representation_reference,
        page_connector_reference,note_reference));
  END_ENTITY; -- cross_reference

  ENTITY cross_section;
      value_of_cross_section : value_with_unit;
  END_ENTITY; -- cross_section

  ENTITY curve_2d;
  END_ENTITY; -- curve_2d

  ENTITY curve_3d;
  END_ENTITY; -- curve_3d

  ENTITY curve_appearance
    SUBTYPE OF (appearance);
      draughting_role : OPTIONAL undefined_object;
      width           : undefined_object;
      font            : line_font;
      curve_colour    : colour;
      curve_ends      : OPTIONAL type_of_line_styles;
      corner_styles   : OPTIONAL type_of_corner_styles;
  END_ENTITY; -- curve_appearance

  ENTITY curve_dimension
    SUBTYPE OF (dimension);
      component : OPTIONAL SET [1:2] OF projection_line;
      extent    : dimension_line;
  END_ENTITY; -- curve_dimension

  ENTITY data_element
    ABSTRACT SUPERTYPE OF (ONEOF (user_defined_data_element,
        predefined_data_element));
      description         : OPTIONAL undefined_object;
      value_determination : OPTIONAL name;
      qualifier           : OPTIONAL name;
      global_unit         : OPTIONAL undefined_object;
  END_ENTITY; -- data_element

  ENTITY data_element_association;
      associated_data_element : data_element;
      description             : OPTIONAL undefined_object;
      definitional            : LOGICAL;
      data_element_context    : OPTIONAL data_element_context_select;
      associated_item         : data_element_select;
  END_ENTITY; -- data_element_association

  ENTITY data_element_definition;
      version_id         : OPTIONAL undefined_object;
      admitted_qualifier : SET [0:?] OF level_type;
      description        : OPTIONAL undefined_object;
      source             : OPTIONAL data_element_source_select;
      id                 : undefined_object;
      allowed_unit       : SET [0:?] OF undefined_object;
    INVERSE
      associated_format : SET [0:1] OF format_of_value FOR 
                             associated_definition;
  END_ENTITY; -- data_element_definition

  ENTITY data_element_definition_relationship;
      related       : data_element_definition;
      relating      : data_element_definition;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- data_element_definition_relationship

  ENTITY data_element_relationship;
      related       : data_element;
      relating      : data_element;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- data_element_relationship

  ENTITY data_element_specification;
      definition             : undefined_object;
      note                   : OPTIONAL undefined_object;
      remark                 : OPTIONAL undefined_object;
      language_specification : OPTIONAL language;
      specification_of       : data_element_definition;
  END_ENTITY; -- data_element_specification

  ENTITY data_element_value
    ABSTRACT SUPERTYPE OF (ONEOF (aggregated_value,single_value));
      name : undefined_object;
  END_ENTITY; -- data_element_value

  ENTITY date_and_person_assignment;
      role                     : name;
      is_applied_to            : SET [1:?] OF
                                     general_organizational_data_select;
      assigned_date_and_person : date_and_person_or_organization;
      description              : OPTIONAL undefined_object;
  END_ENTITY; -- date_and_person_assignment

  ENTITY date_and_person_or_organization;
      associated_date        : date_time;
      person_or_organization : person_or_organization_select;
  END_ENTITY; -- date_and_person_or_organization

  ENTITY date_time;
      date : undefined_object;
      time : OPTIONAL undefined_object;
  END_ENTITY; -- date_time

  ENTITY date_time_assignment;
      role               : name;
      assigned_date_time : date_time;
      is_applied_to      : SET [1:?] OF general_organizational_data_select;
      description        : OPTIONAL undefined_object;
  END_ENTITY; -- date_time_assignment

  ENTITY date_time_interval_assignment;
      assigned_time_interval : interval_of_time;
      description            : OPTIONAL undefined_object;
      role                   : undefined_object;
      is_applied_to          : SET [1:?] OF
                                   general_organizational_data_select;
  END_ENTITY; -- date_time_interval_assignment

  ENTITY dated_configuration
    SUBTYPE OF (manufacturing_configuration);
      start_date : undefined_object;
      end_date   : OPTIONAL undefined_object;
  END_ENTITY; -- dated_configuration

  ENTITY datum_feature_callout
    SUBTYPE OF (draughting_callout);
  END_ENTITY; -- datum_feature_callout

  ENTITY datum_target_callout
    SUBTYPE OF (draughting_callout);
  END_ENTITY; -- datum_target_callout

  ENTITY descriptive_specification;
      description : undefined_object;
      id          : OPTIONAL undefined_object;
  END_ENTITY; -- descriptive_specification

  ENTITY design_discipline_item_definition
    SUPERTYPE OF (assembly_definition);
      name                    : OPTIONAL undefined_object;
      associated_item_version : item_version;
      id                      : undefined_object;
      additional_context      : SET [0:?] OF application_context;
      initial_context         : application_context;
  END_ENTITY; -- design_discipline_item_definition

  ENTITY detached_representation_reference
    SUBTYPE OF (cross_reference);
      part_of   : annotation_element;
      refers_to : annotation_element;
  END_ENTITY; -- detached_representation_reference

  ENTITY device
    ABSTRACT SUPERTYPE OF (ONEOF (single_device,selected_device,
        quantified_device,specified_device))
    SUBTYPE OF (product_constituent);
      extended_designation : OPTIONAL object_reference_designation;
      definition           : instance_definition_select;
      description          : OPTIONAL undefined_object;
      id                   : undefined_object;
  END_ENTITY; -- device

  ENTITY device_relationship;
      relating      : device;
      related       : device;
      description   : OPTIONAL undefined_object;
      relation_type : device_relationship_type;
  END_ENTITY; -- device_relationship

  ENTITY diameter_dimension
    SUBTYPE OF (dimension);
      component : OPTIONAL SET [1:2] OF projection_line;
      extent    : dimension_line;
  END_ENTITY; -- diameter_dimension

  ENTITY digital_document
    SUBTYPE OF (document_representation);
      file : SET [0:?] OF digital_file;
  END_ENTITY; -- digital_document

  ENTITY digital_file
    SUBTYPE OF (document_file);
  END_ENTITY; -- digital_file

  ENTITY dimension
    ABSTRACT SUPERTYPE OF (ONEOF (diameter_dimension,
        leader_directed_dimension,ordinate_dimension,angular_dimension,
        linear_dimension,radius_dimension,curve_dimension))
    SUBTYPE OF (draughting_annotation);
  END_ENTITY; -- dimension

  ENTITY dimension_callout
    ABSTRACT SUPERTYPE OF (ONEOF (unstructured_dimension_callout,
        structured_dimension_callout));
      defined_primary_dimension   : OPTIONAL dimension;
      defined_secondary_dimension : OPTIONAL dimension;
  END_ENTITY; -- dimension_callout

  ENTITY dimension_line
    SUBTYPE OF (directed_curve);
  END_ENTITY; -- dimension_line

  ENTITY dimension_line_terminator;
      symbol : annotation_symbol;
      line   : dimension_line;
  END_ENTITY; -- dimension_line_terminator

  ENTITY dimension_sequence_pair
    ABSTRACT SUPERTYPE OF (ONEOF (parallel_dimension_pair,
        chained_dimension_pair));
      predecessor : dimension;
      successor   : dimension;
  END_ENTITY; -- dimension_sequence_pair

  ENTITY dimension_symbol
    SUBTYPE OF (predefined_symbol);
      symbol_type : dimension_symbol_type;
  END_ENTITY; -- dimension_symbol

  ENTITY directed_curve
    ABSTRACT SUPERTYPE OF (ONEOF (projection_line,leader,dimension_line))
    SUBTYPE OF (annotation_curve);
      directed_callout : OPTIONAL draughting_callout;
  END_ENTITY; -- directed_curve

  ENTITY direction_range;
      minimal_angle           : undefined_object;
      maximal_angle           : undefined_object;
      associated_connect_area : connect_area;
  END_ENTITY; -- direction_range

  ENTITY document;
      id                   : undefined_object;
      description          : OPTIONAL undefined_object;
      name                 : OPTIONAL undefined_object;
      extended_designation : OPTIONAL document_designation;
    INVERSE
      associated_version : SET [1:?] OF document_version FOR 
                              associated_document;
  END_ENTITY; -- document

  ENTITY document_assignment;
      is_assigned_to    : described_object_select;
      role              : name;
      assigned_document : assigned_document_select;
  END_ENTITY; -- document_assignment

  ENTITY document_content_property;
      languages        : SET [0:?] OF language;
      real_world_scale : OPTIONAL numerical_value;
      geometry_type    : OPTIONAL undefined_object;
      detail_level     : OPTIONAL undefined_object;
  END_ENTITY; -- document_content_property

  ENTITY document_creation_property;
      creating_interface : OPTIONAL undefined_object;
      operating_system   : OPTIONAL undefined_object;
      creating_system    : undefined_object;
  END_ENTITY; -- document_creation_property

  ENTITY document_designation
    SUBTYPE OF (object_designation);
  END_ENTITY; -- document_designation

  ENTITY document_file
    ABSTRACT SUPERTYPE OF (ONEOF (digital_file,hardcopy));
      id                       : undefined_object;
      version_id               : OPTIONAL undefined_object;
      document_file_type       : OPTIONAL document_type_property;
      content                  : OPTIONAL document_content_property;
      creation                 : OPTIONAL document_creation_property;
      file_format              : OPTIONAL document_format_property;
      size                     : OPTIONAL document_size_property;
      external_id_and_location : SET [0:?] OF
                                     external_file_id_and_location;
  END_ENTITY; -- document_file

  ENTITY document_file_relationship;
      relating      : document_file;
      related       : document_file;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- document_file_relationship

  ENTITY document_format_property;
      data_format    : OPTIONAL undefined_object;
      character_code : OPTIONAL name;
      size_format    : rectangular_size;
  END_ENTITY; -- document_format_property

  ENTITY document_location_property;
      location_name : undefined_object;
  END_ENTITY; -- document_location_property

  ENTITY document_representation
    ABSTRACT SUPERTYPE OF (ONEOF (digital_document,physical_document,
        physical_model));
      associated_document_version : document_version;
      description                 : OPTIONAL undefined_object;
      id                          : undefined_object;
      content                     : OPTIONAL document_content_property;
      creation                    : OPTIONAL document_creation_property;
      representation_format       : OPTIONAL document_format_property;
      size                        : OPTIONAL document_size_property;
      common_location             : SET [0:?] OF
                                        document_location_property;
  END_ENTITY; -- document_representation

  ENTITY document_size_property;
      file_size  : OPTIONAL value_with_unit;
      page_count : OPTIONAL value_with_unit;
  END_ENTITY; -- document_size_property

  ENTITY document_structure;
      related       : document_representation;
      relating      : document_representation;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- document_structure

  ENTITY document_type_property;
      used_classification_system : OPTIONAL classification_system;
      document_type_name         : undefined_object;
  END_ENTITY; -- document_type_property

  ENTITY document_version;
      associated_document : document;
      id                  : undefined_object;
      description         : OPTIONAL undefined_object;
  END_ENTITY; -- document_version

  ENTITY document_version_relationship;
      relating      : document_version;
      related       : document_version;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- document_version_relationship

  ENTITY draughting_annotation
    ABSTRACT SUPERTYPE OF (ONEOF (sheet_placed_annotation,
        view_placed_annotation,model_placed_annotation,
        annotation_placed_annotation) AND ONEOF (annotation_element,
        dimension,draughting_callout));
  END_ENTITY; -- draughting_annotation

  ENTITY draughting_callout
    ABSTRACT SUPERTYPE OF (ONEOF (geometrical_tolerance,
        datum_target_callout,datum_feature_callout))
    SUBTYPE OF (draughting_annotation);
      components : SET [1:?] OF callout_component_select;
  END_ENTITY; -- draughting_callout

  ENTITY draughting_model;
      name             : undefined_object;
      coordinate_space : cartesian_coordinate_space_2d;
      element          : SET [1:?] OF model_placed_annotation;
    INVERSE
      displayed_in : view_displayed_model FOR displayed_model;
  END_ENTITY; -- draughting_model

  ENTITY drawing;
      drawing_specification : SET [0:?] OF undefined_object;
      version_id            : undefined_object;
      language_code         : SET [0:?] OF undefined_object;
      extended_designation  : OPTIONAL document_designation;
      name                  : OPTIONAL undefined_object;
      drawing_type          : undefined_object;
      source                : OPTIONAL undefined_object;
      id                    : undefined_object;
  END_ENTITY; -- drawing

  ENTITY drawing_assignment;
      assigned_drawing : drawing;
      is_assigned_to   : drawing_assignment_select;
  END_ENTITY; -- drawing_assignment

  ENTITY drawing_sequence;
      preceding_version : drawing;
      following_version : drawing;
  END_ENTITY; -- drawing_sequence

  ENTITY drawing_sheet;
      version_id           : undefined_object;
      extended_designation : OPTIONAL document_designation;
      name                 : OPTIONAL undefined_object;
      orientation          : portrait_or_landscape;
      associated_drawing   : drawing;
      coordinate_space     : cartesian_coordinate_space_2d;
      sheet_number         : OPTIONAL undefined_object;
      size                 : rectangular_size;
  END_ENTITY; -- drawing_sheet

  ENTITY drawing_sheet_layout
    SUBTYPE OF (user_defined_symbol_definition);
  END_ENTITY; -- drawing_sheet_layout

  ENTITY drawing_sheet_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : drawing_sheet;
      related       : drawing_sheet;
  END_ENTITY; -- drawing_sheet_relationship

  ENTITY drawing_view;
      position         : point_2d;
      rotation         : undefined_object;
      id               : OPTIONAL undefined_object;
      coordinate_space : cartesian_coordinate_space_2d;
      containing_sheet : drawing_sheet;
  END_ENTITY; -- drawing_view

  ENTITY duration;
      time      : undefined_object;
      time_unit : undefined_object;
  END_ENTITY; -- duration

  ENTITY effectivity;
      concerned_organization : SET [0:?] OF organization;
      effectivity_context    : OPTIONAL undefined_object;
      description            : OPTIONAL undefined_object;
      end_definition         : OPTIONAL event_or_date_select;
      start_definition       : OPTIONAL event_or_date_select;
      id                     : OPTIONAL undefined_object;
      version_id             : OPTIONAL undefined_object;
      period                 : OPTIONAL duration;
  END_ENTITY; -- effectivity

  ENTITY effectivity_assignment;
      is_applied_to          : effective_element_select;
      role                   : name;
      assigned_effectivity   : effectivity;
      effectivity_indication : BOOLEAN;
  END_ENTITY; -- effectivity_assignment

  ENTITY effectivity_relationship;
      related       : effectivity;
      relating      : effectivity;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- effectivity_relationship

  ENTITY event_reference;
      event_context : OPTIONAL general_organizational_data_select;
      offset        : OPTIONAL duration;
      event_type    : undefined_object;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- event_reference

  ENTITY external_file_id_and_location;
      location    : document_location_property;
      external_id : undefined_object;
  END_ENTITY; -- external_file_id_and_location

  ENTITY external_library_reference;
      external_id  : undefined_object;
      description  : OPTIONAL undefined_object;
      library_type : undefined_object;
  END_ENTITY; -- external_library_reference

  ENTITY externally_defined_hatching
    SUBTYPE OF (fill_area_appearance);
      hatching_name      : undefined_object;
      hatching_reference : undefined_object;
  END_ENTITY; -- externally_defined_hatching

  ENTITY externally_defined_line_font
    SUBTYPE OF (line_font);
      font_id        : undefined_object;
      font_reference : undefined_object;
  END_ENTITY; -- externally_defined_line_font

  ENTITY externally_defined_symbol
    SUBTYPE OF (annotation_symbol);
      symbol_name      : undefined_object;
      symbol_reference : undefined_object;
  END_ENTITY; -- externally_defined_symbol

  ENTITY externally_defined_text_font
    SUBTYPE OF (text_font);
      font_id        : undefined_object;
      font_reference : undefined_object;
  END_ENTITY; -- externally_defined_text_font

  ENTITY externally_defined_tile
    SUBTYPE OF (tile);
      tile_name      : undefined_object;
      tile_reference : undefined_object;
  END_ENTITY; -- externally_defined_tile

  ENTITY externally_defined_tiling
    SUBTYPE OF (fill_area_appearance);
      tiling_name      : undefined_object;
      tiling_reference : undefined_object;
  END_ENTITY; -- externally_defined_tiling

  ENTITY fill_area
    SUBTYPE OF (annotation_element);
      reference_point     : OPTIONAL point_2d;
      boundary            : fill_area_boundary;
      assigned_appearance : fill_area_appearance;
  END_ENTITY; -- fill_area

  ENTITY fill_area_appearance
    ABSTRACT SUPERTYPE OF (ONEOF (externally_defined_hatching,
        user_defined_tiling,externally_defined_tiling,user_defined_hatching,
        solid_fill_area))
    SUBTYPE OF (appearance);
      draughting_role : OPTIONAL undefined_object;
  END_ENTITY; -- fill_area_appearance

  ENTITY fill_area_boundary;
      defining_curve : annotation_curve;
    INVERSE
      area_contained : SET [1:?] OF fill_area FOR boundary;
  END_ENTITY; -- fill_area_boundary

  ENTITY final_solution
    SUBTYPE OF (alternative_solution);
      final_status        : undefined_object;
      final_specification : SET [1:?] OF final_specification_select;
  END_ENTITY; -- final_solution

  ENTITY format_of_value;
      value_format                   : undefined_object;
      source_document                : undefined_object;
      default_language_specification : OPTIONAL language;
      associated_definition          : data_element_definition;
  END_ENTITY; -- format_of_value

  ENTITY free_segment;
      ends_at     : SET [1:?] OF node;
      id          : undefined_object;
      description : OPTIONAL undefined_object;
  END_ENTITY; -- free_segment

  ENTITY function_definition;
      version            : function_version;
      id                 : undefined_object;
      additional_context : SET [0:?] OF application_context;
      name               : OPTIONAL undefined_object;
      initial_context    : application_context;
  END_ENTITY; -- function_definition

  ENTITY function_definition_relationship;
      relating      : function_definition;
      related       : function_definition;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- function_definition_relationship

  ENTITY function_interface;
      id              : undefined_object;
      external_access : SET [1:?] OF interface_port;
      interface_of    : function_definition;
      description     : OPTIONAL undefined_object;
  END_ENTITY; -- function_interface

  ENTITY function_unit
    ABSTRACT SUPERTYPE OF (ONEOF (specified_function_unit,
        single_function_unit))
    SUBTYPE OF (product_constituent);
      instanciated_function : function_unit_definition_select;
      extended_designation  : OPTIONAL object_reference_designation;
      description           : OPTIONAL undefined_object;
      id                    : undefined_object;
  END_ENTITY; -- function_unit

  ENTITY function_unit_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : function_unit;
      related       : function_unit;
  END_ENTITY; -- function_unit_relationship

  ENTITY function_version;
      base_function : functionality;
      description   : OPTIONAL undefined_object;
      version_id    : undefined_object;
  END_ENTITY; -- function_version

  ENTITY function_version_relationship;
      relating      : function_version;
      related       : function_version;
      description   : OPTIONAL undefined_object;
      relation_type : name;
  END_ENTITY; -- function_version_relationship

  ENTITY functional_connectivity_definition
    ABSTRACT SUPERTYPE OF (ONEOF (network,interface_port_connectivity));
      id              : undefined_object;
      description     : OPTIONAL undefined_object;
      connectivity_of : function_definition;
      version_id      : OPTIONAL undefined_object;
  END_ENTITY; -- functional_connectivity_definition

  ENTITY functional_connectivity_definition_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : functional_connectivity_definition;
      related       : functional_connectivity_definition;
  END_ENTITY; -- functional_connectivity_definition_relationship

  ENTITY functional_unit_allocation;
      function_implementation   : functional_unit_allocation_select;
      description               : OPTIONAL undefined_object;
      allocated_functional_unit : function_unit;
  END_ENTITY; -- functional_unit_allocation

  ENTITY functionality;
      description : OPTIONAL undefined_object;
      id          : undefined_object;
      name        : OPTIONAL undefined_object;
    INVERSE
      associated_version : SET [1:?] OF function_version FOR base_function;
  END_ENTITY; -- functionality

  ENTITY general_classification;
      used_classification_system : SET [0:1] OF classification_system;
      id                         : undefined_object;
      description                : OPTIONAL undefined_object;
      version_id                 : OPTIONAL undefined_object;
      classification_source      : OPTIONAL class_source_select;
  END_ENTITY; -- general_classification

  ENTITY general_classification_hierarchy;
      super_classification : general_classification;
      sub_classification   : general_classification;
  END_ENTITY; -- general_classification_hierarchy

  ENTITY general_location_relationship
    SUBTYPE OF (location_relationship);
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- general_location_relationship

  ENTITY generic_note
    ABSTRACT SUPERTYPE OF (ONEOF (note,set_of_notes));
      version_id  : OPTIONAL undefined_object;
      description : OPTIONAL undefined_object;
      id          : undefined_object;
  END_ENTITY; -- generic_note

  ENTITY geometrical_tolerance
    SUBTYPE OF (draughting_callout);
  END_ENTITY; -- geometrical_tolerance

  ENTITY geometrical_tolerance_symbol
    SUBTYPE OF (predefined_symbol);
      symbol_type : geometrical_tolerance_symbol_type;
  END_ENTITY; -- geometrical_tolerance_symbol

  ENTITY gis_position;
      x_axis_delta_x : undefined_object;
      x_axis_delta_y : undefined_object;
      scale          : undefined_object;
      x_coordinate   : undefined_object;
      y_coordinate   : undefined_object;
      height         : undefined_object;
      system         : undefined_object;
      zone           : undefined_object;
  END_ENTITY; -- gis_position

  ENTITY group;
      id          : undefined_object;
      description : OPTIONAL undefined_object;
      members     : SET [0:?] OF group_element;
  END_ENTITY; -- group

  ENTITY group_annotation_element
    SUBTYPE OF (group_element);
      basis_annotation : draughting_annotation;
  END_ENTITY; -- group_annotation_element

  ENTITY group_element
    ABSTRACT SUPERTYPE OF (ONEOF (group_annotation_element,sub_group));
    INVERSE
      parent_groups : SET [1:?] OF group FOR members;
  END_ENTITY; -- group_element

  ENTITY hardcopy
    SUBTYPE OF (document_file);
  END_ENTITY; -- hardcopy

  ENTITY hatching_pattern;
      angle                 : undefined_object;
      displacement          : undefined_object;
      hatch_line_appearance : curve_appearance;
    INVERSE
      hatchings_defined : SET [1:?] OF user_defined_hatching FOR 
                             defining_pattern;
  END_ENTITY; -- hatching_pattern

  ENTITY hierarchical_location_relationship
    SUBTYPE OF (location_relationship);
      transformation : OPTIONAL undefined_object;
      description    : OPTIONAL undefined_object;
  END_ENTITY; -- hierarchical_location_relationship

  ENTITY instance_placement;
      placed_instance              : instance_placement_select;
      referenced_product_component : product_component;
      transformation               : undefined_object;
  END_ENTITY; -- instance_placement

  ENTITY interface;
      id              : undefined_object;
      external_access : SET [1:?] OF interface_terminal;
      interface_of    : design_discipline_item_definition;
      description     : OPTIONAL undefined_object;
  END_ENTITY; -- interface

  ENTITY interface_port;
      description       : OPTIONAL undefined_object;
      id                : undefined_object;
      interface_port_of : function_definition;
    INVERSE
      connected_to : SET [0:1] OF interface_port_connectivity FOR 
                        connected_interface_port;
  END_ENTITY; -- interface_port

  ENTITY interface_port_connectivity
    SUBTYPE OF (functional_connectivity_definition);
      connected_interface_port : SET [0:?] OF interface_port;
  END_ENTITY; -- interface_port_connectivity

  ENTITY interface_port_relationship;
      relating      : interface_port;
      related       : interface_port;
      description   : OPTIONAL undefined_object;
      relation_type : name;
  END_ENTITY; -- interface_port_relationship

  ENTITY interface_terminal;
      description                  : OPTIONAL undefined_object;
      interface_terminal_of        : design_discipline_item_definition;
      id                           : undefined_object;
      uses                         : SET [0:1] OF terminal;
      maximum_number_of_conductors : OPTIONAL undefined_object;
  END_ENTITY; -- interface_terminal

  ENTITY interface_terminal_connection
    SUBTYPE OF (connectivity_definition);
      connected_interface_terminal : SET [0:?] OF interface_terminal;
  END_ENTITY; -- interface_terminal_connection

  ENTITY interface_terminal_relationship;
      relating      : interface_terminal;
      related       : interface_terminal;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- interface_terminal_relationship

  ENTITY interval_of_time;
      start_definition : event_or_date_select;
      end_definition   : period_or_date_select;
  END_ENTITY; -- interval_of_time

  ENTITY item;
      description          : OPTIONAL undefined_object;
      name                 : undefined_object;
      extended_designation : OPTIONAL item_identification;
      id                   : undefined_object;
    INVERSE
      associated_version  : SET [1:?] OF item_version FOR associated_item;
      item_classification : SET [1:?] OF specific_item_classification FOR 
                               associated_item;
  END_ENTITY; -- item

  ENTITY item_definition_relationship;
      related       : design_discipline_item_definition;
      relating      : design_discipline_item_definition;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- item_definition_relationship

  ENTITY item_identification;
      id          : undefined_object;
      coding_type : OPTIONAL classification_system;
  END_ENTITY; -- item_identification

  ENTITY item_presentation;
      presented_item  : presentation_select;
      presenting_item : annotation_element;
      id              : OPTIONAL undefined_object;
  END_ENTITY; -- item_presentation

  ENTITY item_version;
      description     : OPTIONAL undefined_object;
      version_id      : undefined_object;
      associated_item : item;
    INVERSE
      associated_product : SET [0:1] OF product_design FOR design;
  END_ENTITY; -- item_version

  ENTITY item_version_relationship;
      relating      : item_version;
      related       : item_version;
      description   : OPTIONAL undefined_object;
      relation_type : name;
  END_ENTITY; -- item_version_relationship

  ENTITY language;
      language_code : undefined_object;
      country_code  : OPTIONAL undefined_object;
  END_ENTITY; -- language

  ENTITY layer;
      layer_id           : undefined_object;
      element_visibility : visibility;
      description        : OPTIONAL undefined_object;
  END_ENTITY; -- layer

  ENTITY leader
    SUBTYPE OF (directed_curve);
      target_element : OPTIONAL annotation_element;
  END_ENTITY; -- leader

  ENTITY leader_directed_dimension
    SUBTYPE OF (dimension);
      component : leader;
  END_ENTITY; -- leader_directed_dimension

  ENTITY leader_terminator;
      line   : leader;
      symbol : annotation_symbol;
  END_ENTITY; -- leader_terminator

  ENTITY line_font
    ABSTRACT SUPERTYPE OF (ONEOF (externally_defined_line_font,
        user_defined_line_font,predefined_line_font));
    INVERSE
      appearances : SET [1:?] OF curve_appearance FOR font;
  END_ENTITY; -- line_font

  ENTITY linear_dimension
    SUBTYPE OF (dimension);
      component : OPTIONAL SET [1:2] OF projection_line;
      extent    : dimension_line;
  END_ENTITY; -- linear_dimension

  ENTITY linear_pattern_location;
      distance       : undefined_object;
      start_location : cartesian_point;
      orientation    : OPTIONAL undefined_object;
  END_ENTITY; -- linear_pattern_location

  ENTITY location;
      extended_designation   : OPTIONAL object_reference_designation;
      version_id             : OPTIONAL undefined_object;
      position               : OPTIONAL position_select;
      local_coordinate_space : OPTIONAL cartesian_coordinate_space_3d;
      description            : OPTIONAL undefined_object;
      defining_item          : location_definition_select;
      id                     : undefined_object;
  END_ENTITY; -- location

  ENTITY location_assignment;
      associated_item   : location_assignment_select;
      assigned_location : location;
      role              : name;
      description       : OPTIONAL undefined_object;
  END_ENTITY; -- location_assignment

  ENTITY location_relationship
    ABSTRACT SUPERTYPE OF (ONEOF (neighbourhood_location_relationship,
        general_location_relationship,hierarchical_location_relationship));
      related  : location;
      relating : location;
  END_ENTITY; -- location_relationship

  ENTITY logical_value;
      value_of_logical_value : undefined_object;
  END_ENTITY; -- logical_value

  ENTITY lot_configuration
    SUBTYPE OF (manufacturing_configuration);
      lot_id   : undefined_object;
      lot_size : undefined_object;
  END_ENTITY; -- lot_configuration

  ENTITY make_from_relationship
    SUBTYPE OF (item_definition_relationship);
  END_ENTITY; -- make_from_relationship

  ENTITY manufacturing_configuration
    ABSTRACT SUPERTYPE OF (ONEOF (lot_configuration,serial_configuration,
        dated_configuration));
      is_solution_for        : product_design;
      configured_element     : device;
      concerned_organization : SET [0:?] OF organization;
  END_ENTITY; -- manufacturing_configuration

  ENTITY marking;
      meaning          : marking_select;
      marked_device    : single_device;
      marking_system   : classification_system;
      position         : SET [0:?] OF marking_position_select;
      figure           : OPTIONAL annotation_element;
      character_string : undefined_object;
  END_ENTITY; -- marking

  ENTITY mass;
      value_of_mass : value_with_unit;
  END_ENTITY; -- mass

  ENTITY material;
      substance : undefined_object;
  END_ENTITY; -- material

  ENTITY model_placed_annotation
    SUBTYPE OF (draughting_annotation);
      annotation_layers     : SET [1:?] OF layer;
      annotation_visibility : visibility;
  END_ENTITY; -- model_placed_annotation

  ENTITY mounting_features;
      fixture : undefined_object;
  END_ENTITY; -- mounting_features

  ENTITY multi_language_note
    SUBTYPE OF (set_of_notes);
  END_ENTITY; -- multi_language_note

  ENTITY neighbourhood_location_relationship
    SUBTYPE OF (location_relationship);
      relation_type : name;
  END_ENTITY; -- neighbourhood_location_relationship

  ENTITY network
    SUBTYPE OF (functional_connectivity_definition);
      connected_port : SET [0:?] OF port;
  END_ENTITY; -- network

  ENTITY next_higher_assembly
    SUBTYPE OF (assembly_component_relationship);
  END_ENTITY; -- next_higher_assembly

  ENTITY node;
      id                : undefined_object;
      implemented_by    : SET [0:?] OF device;
      assigned_location : location;
      position          : OPTIONAL path_node;
      description       : OPTIONAL undefined_object;
  END_ENTITY; -- node

  ENTITY node_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      related       : node;
      relating      : node;
  END_ENTITY; -- node_relationship

  ENTITY note
    SUBTYPE OF (generic_note);
      language_specification : language;
      text_of_note           : undefined_object;
      kind                   : name;
  END_ENTITY; -- note

  ENTITY note_association;
      role                   : undefined_object;
      assigned_note          : generic_note;
      associated_item        : annotated_item_select;
      applied_attribute_name : OPTIONAL undefined_object;
  END_ENTITY; -- note_association

  ENTITY note_reference
    SUBTYPE OF (cross_reference);
      presentation_of_item : item_presentation;
      note_presentation    : item_presentation;
  END_ENTITY; -- note_reference

  ENTITY notification;
      id                     : undefined_object;
      version_id             : OPTIONAL undefined_object;
      description            : OPTIONAL undefined_object;
      language_specification : OPTIONAL language;
      text_of_message        : OPTIONAL undefined_object;
      trigger                : SET [0:?] OF trigger_select;
  END_ENTITY; -- notification

  ENTITY notification_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : notification;
      related       : notification;
  END_ENTITY; -- notification_relationship

  ENTITY numerical_precision;
      distance_precision : undefined_object;
      angular_precision  : undefined_object;
  END_ENTITY; -- numerical_precision

  ENTITY numerical_value
    SUBTYPE OF (value_with_unit);
      value_component : undefined_object;
  END_ENTITY; -- numerical_value

  ENTITY object_designation
    SUPERTYPE OF (ONEOF (terminal_designation,document_designation,
        object_reference_designation,signal_designation));
      designator                 : undefined_object;
      type_of_object_designation : OPTIONAL name;
      designation_system         : OPTIONAL classification_system;
  END_ENTITY; -- object_designation

  ENTITY object_designation_relationship;
      related_object_designation  : object_designation;
      relating_object_designation : object_designation;
  END_ENTITY; -- object_designation_relationship

  ENTITY object_reference_designation
    SUBTYPE OF (object_designation);
  END_ENTITY; -- object_reference_designation

  ENTITY offered_function_allocation;
      offered_functionality : function_definition;
      performing_item       : performing_item_select;
      relation_type         : name;
      description           : OPTIONAL undefined_object;
  END_ENTITY; -- offered_function_allocation

  ENTITY operating_temperature;
      temperature : value_with_unit;
  END_ENTITY; -- operating_temperature

  ENTITY ordinate_dimension
    SUBTYPE OF (dimension);
      component : projection_line;
  END_ENTITY; -- ordinate_dimension

  ENTITY organization;
      name              : undefined_object;
      id                : undefined_object;
      visitor_address   : OPTIONAL address;
      postal_address    : OPTIONAL address;
      delivery_address  : OPTIONAL address;
      organization_type :name;
  END_ENTITY; -- organization

  ENTITY organization_in_contract;
      role_of_organization    : name;
      contracted_organization : organization;
      signature               : SET [0:?] OF
                                    date_and_person_or_organization;
      contract                : SET [1:?] OF contract;
  END_ENTITY; -- organization_in_contract

  ENTITY organization_relationship;
      related       : organization;
      relating      : organization;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- organization_relationship

  ENTITY outside_diameter;
      value_of_outside_diameter : value_with_unit;
  END_ENTITY; -- outside_diameter

  ENTITY page_connector;
      type_of           : page_connector_type;
      page_connector_id : undefined_object;
      part_of           : connecting_line;
  END_ENTITY; -- page_connector

  ENTITY page_connector_presentation;
      of_page_connector : page_connector;
      type_of           : page_connector_presentation_type;
  END_ENTITY; -- page_connector_presentation

  ENTITY page_connector_reference
    SUBTYPE OF (cross_reference);
      part_of   : page_connector_presentation;
      refers_to : page_connector_reference_select;
  END_ENTITY; -- page_connector_reference

  ENTITY parallel_dimension_pair
    SUBTYPE OF (dimension_sequence_pair);
  END_ENTITY; -- parallel_dimension_pair

  ENTITY partial_document_assignment
    SUBTYPE OF (document_assignment);
      document_portion : undefined_object;
  END_ENTITY; -- partial_document_assignment

  ENTITY path;
      version_id  : OPTIONAL undefined_object;
      id          : undefined_object;
      consists_of : LIST [1:?] OF path_segment;
  END_ENTITY; -- path

  ENTITY path_node;
      defined_in : location;
      position   : cartesian_point;
      id         : undefined_object;
  END_ENTITY; -- path_node

  ENTITY path_node_relationship;
      related       : path_node;
      relating      : path_node;
      relation_type : undefined_object;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- path_node_relationship

  ENTITY path_relationship;
      related       : path;
      relating      : path;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- path_relationship

  ENTITY path_segment;
      id         : undefined_object;
      begins_at  : path_node;
      ends_at    : path_node;
      defined_in : location;
      form       : curve_3d;
  END_ENTITY; -- path_segment

  ENTITY person;
      first_name                 : OPTIONAL undefined_object;
      last_name                  : OPTIONAL undefined_object;
      middle_names               : OPTIONAL LIST [1:?] OF undefined_object;
      prefix_titles              : OPTIONAL LIST [1:?] OF undefined_object;
      suffix_titles              : OPTIONAL LIST [1:?] OF undefined_object;
      preferred_business_address : OPTIONAL address;
    INVERSE
      associated_organization : SET [1:?] OF person_in_organization FOR 
                                   associated_person;
  END_ENTITY; -- person

  ENTITY person_in_organization;
      role                    : undefined_object;
      associated_person       : person;
      associated_organization : organization;
      location                : OPTIONAL address;
      id                      : undefined_object;
  END_ENTITY; -- person_in_organization

  ENTITY person_in_organization_relationship;
      related       : person_in_organization;
      relating      : person_in_organization;
      relation_type : undefined_object;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- person_in_organization_relationship

  ENTITY person_organization_assignment;
      role                            : name;
      is_applied_to                   : SET [1:?] OF general_organizational_data_select;
      assigned_person_or_organization : person_or_organization_select;
      description                     : OPTIONAL undefined_object;
  END_ENTITY; -- person_organization_assignment

  ENTITY physical_assembly_relationship;
      physical_component : physical_instance;
      physical_assembly  : physical_instance;
      is_realization_of  : device;
  END_ENTITY; -- physical_assembly_relationship

  ENTITY physical_document
    SUBTYPE OF (document_representation);
      component : SET [0:?] OF hardcopy;
  END_ENTITY; -- physical_document

  ENTITY physical_instance
    SUBTYPE OF (product_constituent);
      description       : OPTIONAL undefined_object;
      serial_number     : OPTIONAL undefined_object;
      inventory_number  : OPTIONAL undefined_object;
      lot_id            : OPTIONAL undefined_object;
      is_realization_of : physical_instance_definition_select;
  END_ENTITY; -- physical_instance

  ENTITY physical_model
    SUBTYPE OF (document_representation);
  END_ENTITY; -- physical_model

  ENTITY point_2d;
  END_ENTITY; -- point_2d

  ENTITY point_marker_symbol
    SUBTYPE OF (predefined_symbol);
      symbol_type : point_marker_symbol_type;
  END_ENTITY; -- point_marker_symbol

  ENTITY port;
      description               : OPTIONAL undefined_object;
      port_of                   : single_function_unit;
      id                        : undefined_object;
      associated_interface_port : interface_port;
      extended_designation      : OPTIONAL terminal_designation;
  END_ENTITY; -- port

  ENTITY port_allocation;
      port_implementation : terminal;
      description         : OPTIONAL undefined_object;
      allocated_port      : port;
      item_allocation     : OPTIONAL functional_unit_allocation;
  END_ENTITY; -- port_allocation

  ENTITY port_association;
      associated_port           : port;
      associated_interface_port : interface_port;
  END_ENTITY; -- port_association

  ENTITY port_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : port;
      related       : port;
  END_ENTITY; -- port_relationship

  ENTITY predefined_colour
    SUBTYPE OF (colour);
      colour_id : colour_type;
  END_ENTITY; -- predefined_colour

  ENTITY predefined_connection
    SUBTYPE OF (connection);
  END_ENTITY; -- predefined_connection

  ENTITY predefined_data_element
    SUBTYPE OF (data_element);
      data : predefined_data_element_select;
  END_ENTITY; -- predefined_data_element

  ENTITY predefined_line_font
    SUBTYPE OF (line_font);
      font_id : line_font_type;
  END_ENTITY; -- predefined_line_font

  ENTITY predefined_symbol
    ABSTRACT SUPERTYPE OF (ONEOF (terminator_symbol,
        geometrical_tolerance_symbol,dimension_symbol,point_marker_symbol))
    SUBTYPE OF (annotation_symbol);
  END_ENTITY; -- predefined_symbol

  ENTITY predefined_text_font
    SUBTYPE OF (text_font);
      font_id : type_of_font;
  END_ENTITY; -- predefined_text_font

  ENTITY preferred_equipment_assignment;
      preferred_equipment : SET [0:?] OF preferred_equipment_select;
      related_signal      : signal;
      valid_context       : OPTIONAL context_select;
  END_ENTITY; -- preferred_equipment_assignment

  ENTITY preferred_item_allocation;
      functional_definition : single_function_unit;
      preferred_item        : preferred_item_select;
      description           : OPTIONAL undefined_object;
  END_ENTITY; -- preferred_item_allocation

  ENTITY preferred_item_terminal_allocation;
      functional_definition : port;
      preferred_node        : preferred_item_terminal_select;
      description           : OPTIONAL undefined_object;
      item_allocation       : preferred_item_allocation;
  END_ENTITY; -- preferred_item_terminal_allocation

  ENTITY process_variable;
      id               : undefined_object;
      description      : OPTIONAL undefined_object;
      associated_value : OPTIONAL data_element_value;
  END_ENTITY; -- process_variable

  ENTITY process_variable_relationship;
      relating      : process_variable;
      related       : process_variable;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- process_variable_relationship

  ENTITY process_variable_system_assignment;
      associated_process_variable : process_variable;
      associated_system           : associated_system_select;
      role                        : name;
      description                 : OPTIONAL undefined_object;
  END_ENTITY; -- process_variable_system_assignment

  ENTITY product_class;
      level_type  : undefined_object;
      version_id  : OPTIONAL undefined_object;
      id          : undefined_object;
      name        : OPTIONAL undefined_object;
      description : OPTIONAL undefined_object;
  END_ENTITY; -- product_class

  ENTITY product_class_relationship;
      relating      : product_class;
      related       : product_class;
      description   : OPTIONAL undefined_object;
      relation_type : name;
  END_ENTITY; -- product_class_relationship

  ENTITY product_component
    SUBTYPE OF (complex_product, product_constituent);
      is_influenced_by     : SET [0:?] OF class_category_association;
      instance_required    : LOGICAL;
      name                 : OPTIONAL undefined_object;
      description          : OPTIONAL undefined_object;
      is_relevant_for      : SET [0:?] OF application_context;
      extended_designation : OPTIONAL object_reference_designation;
  END_ENTITY; -- product_component

  ENTITY product_constituent
    ABSTRACT SUPERTYPE OF (ONEOF (product_component,device,
        physical_instance,function_unit));
  END_ENTITY; -- product_constituent

  ENTITY product_design;
      product : product_identification;
      design  : item_version;
  END_ENTITY; -- product_design

  ENTITY product_identification;
      associated_product_class : product_class;
      id                       : undefined_object;
      version_id               : OPTIONAL undefined_object;
      name                     : OPTIONAL undefined_object;
      description              : OPTIONAL undefined_object;
    INVERSE
      associated_design : SET [0:1] OF product_design FOR product;
  END_ENTITY; -- product_identification

  ENTITY product_specification
    SUBTYPE OF (product_identification);
      defining_specification : SET [1:?] OF specification;
  END_ENTITY; -- product_specification

  ENTITY product_structure_relationship;
      relating      : complex_product;
      related       : product_constituent;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- product_structure_relationship

  ENTITY project;
      work_program           : SET [0:?] OF activity;
      id                     : undefined_object;
      description            : OPTIONAL undefined_object;
      affected_product_class : SET [0:?] OF product_class;
      planned_end_date       : OPTIONAL period_or_date_select;
      planned_start_date     : OPTIONAL event_or_date_select;
      actual_end_date        : OPTIONAL date_time;
      actual_start_date      : OPTIONAL date_time;
      name                   : undefined_object;
  END_ENTITY; -- project

  ENTITY project_relationship;
      related       : project;
      relating      : project;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- project_relationship

  ENTITY projection_line
    SUBTYPE OF (directed_curve);
      projected_element : OPTIONAL annotation_element;
  END_ENTITY; -- projection_line

  ENTITY promissory_usage
    SUBTYPE OF (assembly_component_relationship);
  END_ENTITY; -- promissory_usage

  ENTITY property_reference;
      name_scope : class_reference;
      code       : undefined_object;
      version    : undefined_object;
  END_ENTITY; -- property_reference

  ENTITY quantified_device
    SUBTYPE OF (device);
      quantity : numerical_value;
  END_ENTITY; -- quantified_device

  ENTITY radius_dimension
    SUBTYPE OF (dimension);
      extent    : dimension_line;
      component : OPTIONAL projection_line;
  END_ENTITY; -- radius_dimension

  ENTITY rated_current;
      type_of_rated_current  : ac_dc;
      value_of_rated_current : value_with_unit;
  END_ENTITY; -- rated_current

  ENTITY rated_power;
      type_of_rated_power  : kind_of_rated_power;
      value_of_rated_power : value_with_unit;
  END_ENTITY; -- rated_power

  ENTITY rated_voltage;
      type_of_rated_voltage  : ac_dc;
      value_of_rated_voltage : value_with_unit;
  END_ENTITY; -- rated_voltage

  ENTITY rectangular_area;
      height   : undefined_object;
      width    : undefined_object;
      position : undefined_object;
  END_ENTITY; -- rectangular_area

  ENTITY rectangular_size;
      height  : undefined_object;
      width   : undefined_object;
      density : OPTIONAL undefined_object;
  END_ENTITY; -- rectangular_size

  ENTITY reference_grid;
      column_id   : LIST [1:?] OF undefined_object;
      row_id      : LIST [1:?] OF undefined_object;
      grid_origin : undefined_object;
    INVERSE
      presentation : SET [1:?] OF reference_grid_layout FOR 
                        assigned_reference_grid;
  END_ENTITY; -- reference_grid

  ENTITY reference_grid_layout
    SUBTYPE OF (user_defined_symbol_definition);
      assigned_reference_grid : reference_grid;
  END_ENTITY; -- reference_grid_layout

  ENTITY requirement;
      name        : OPTIONAL undefined_object;
      description : OPTIONAL undefined_object;
      version_id  : OPTIONAL undefined_object;
      id          : undefined_object;
  END_ENTITY; -- requirement

  ENTITY requirement_assignment;
      associated_requirement : requirement;
      constrained_element    : constrained_design_element_select;
      description            : OPTIONAL undefined_object;
      relation_type          : name;
  END_ENTITY; -- requirement_assignment

  ENTITY requirement_document_assignment;
      documented_requirement : requirement;
      role_of_document       : OPTIONAL undefined_object;
      description            : OPTIONAL undefined_object;
      documentation          : document_select;
  END_ENTITY; -- requirement_document_assignment

  ENTITY requirement_relationship;
      relating      : requirement;
      related       : requirement;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- requirement_relationship

  ENTITY retention_period;
      start_definition        : event_or_date_select;
      earliest_end_definition : period_or_date_select;
      latest_end_definition   : period_or_date_select;
      retention_purpose       : OPTIONAL undefined_object;
      is_applied_to           : SET [1:?] OF
                                    general_organizational_data_select;
  END_ENTITY; -- retention_period

  ENTITY route;
      id                 : undefined_object;
      version_id         : OPTIONAL undefined_object;
      description        : OPTIONAL undefined_object;
      course             : LIST [0:?] OF route_element_select;
      encountered_object : LIST [0:?] OF encountered_object_select;
  END_ENTITY; -- route

  ENTITY route_relationship;
      related       : route;
      relating      : route;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- route_relationship

  ENTITY routed_object;
      associated_object : routed_object_select;
      arrangement       : LIST [1:?] OF arrangement_select;
  END_ENTITY; -- routed_object

  ENTITY routed_segment;
      id          : undefined_object;
      course      : LIST [1:?] OF routed_segment_select;
      description : OPTIONAL undefined_object;
  END_ENTITY; -- routed_segment

  ENTITY schematic_node
    SUBTYPE OF (annotation_element);
      definition  : typical_schematic_node;
      position    : point_2d;
      rotation    : undefined_object;
      scale       : undefined_object;
      assigned_to : OPTIONAL user_defined_symbol;
  END_ENTITY; -- schematic_node

  ENTITY schematic_text
    SUBTYPE OF (text);
      definition  : typical_schematic_text;
      assigned_to : OPTIONAL schematic_text_select;
  END_ENTITY; -- schematic_text

  ENTITY section;
      id                   : undefined_object;
      version_id           : OPTIONAL undefined_object;
      length_of_section    : OPTIONAL SET [1:?] OF value_with_unit;
      cross_sectional_area : OPTIONAL SET [1:?] OF cross_section;
      space_factor         : OPTIONAL SET [1:?] OF value_with_unit;
      implemented_by       : SET [0:?] OF device;
      bending_radius       : OPTIONAL SET [1:?] OF value_with_unit;
      course               : OPTIONAL path;
      description          : OPTIONAL undefined_object;
  END_ENTITY; -- section

  ENTITY section_end;
      of_section : section;
      located_at : OPTIONAL node;
      id         : undefined_object;
      kind       : OPTIONAL name;
  END_ENTITY; -- section_end

  ENTITY section_interface;
      description          : OPTIONAL undefined_object;
      id                   : undefined_object;
      version_id           : OPTIONAL undefined_object;
      joins                : SET [0:?] OF section_end;
      implemented_by       : SET [0:?] OF device;
      cross_sectional_area : OPTIONAL SET [1:?] OF cross_section;
      space_factor         : OPTIONAL SET [1:?] OF single_value;
      located_at           : OPTIONAL node;
  END_ENTITY; -- section_interface

  ENTITY section_interface_relationship;
      related       : section_interface;
      relating      : section_interface;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- section_interface_relationship

  ENTITY section_relationship;
      description   : OPTIONAL undefined_object;
      relation_type : name;
      relating      : section;
      related       : section;
  END_ENTITY; -- section_relationship

  ENTITY security_classification;
      name                          : undefined_object;
      purpose                       : undefined_object;
      security_classification_level : security_level;
      is_applied_to                 : SET [1:?] OF security_element_select;
  END_ENTITY; -- security_classification

  ENTITY security_level;
      level_name                 : undefined_object;
      used_classification_system : OPTIONAL classification_system;
  END_ENTITY; -- security_level

  ENTITY selected_device
    SUBTYPE OF (device);
      selection_control : undefined_object;
      selected_quantity : value_with_unit;
  END_ENTITY; -- selected_device

  ENTITY serial_configuration
    SUBTYPE OF (manufacturing_configuration);
      serial_start_number : undefined_object;
      serial_end_number   : OPTIONAL undefined_object;
  END_ENTITY; -- serial_configuration

  ENTITY set_of_notes
    SUBTYPE OF (generic_note);
      grouped_notes : SET [1:?] OF generic_note;
  END_ENTITY; -- set_of_notes

  ENTITY shape;
      id : undefined_object;
  END_ENTITY; -- shape

  ENTITY shape_assignment;
      assigned_shape  : shape;
      associated_item : shape_association_select;
      role            : name;
      description     : OPTIONAL undefined_object;
  END_ENTITY; -- shape_assignment

  ENTITY sheet_placed_annotation
    SUBTYPE OF (draughting_annotation);
      annotation_layers     : SET [1:?] OF layer;
      annotation_visibility : visibility;
  END_ENTITY; -- sheet_placed_annotation

  ENTITY signal;
      description            : OPTIONAL undefined_object;
      associated_parameter   : SET [0:?] OF process_variable;
      extended_designation   : OPTIONAL signal_designation;
      version_id             : OPTIONAL undefined_object;
      signal_level_indicator : OPTIONAL undefined_object;
      id                     : undefined_object;
  END_ENTITY; -- signal

  ENTITY signal_designation
    SUBTYPE OF (object_designation);
  END_ENTITY; -- signal_designation

  ENTITY signal_relationship;
      relating      : signal;
      related       : signal;
      relation_type : name;
      description   : OPTIONAL undefined_object;
  END_ENTITY; -- signal_relationship

  ENTITY signal_system_assignment;
      associated_signal : signal;
      role              : name;
      description       : OPTIONAL undefined_object;
      associated_system : associated_system_select;
  END_ENTITY; -- signal_system_assignment

  ENTITY signal_value;
      valued_parameter  : OPTIONAL process_variable;
      value_of_signal   : data_element_value;
      characteristic    : OPTIONAL name;
      associated_signal : signal;
      description       : OPTIONAL undefined_object;
      id                : undefined_object;
  END_ENTITY; -- signal_value

  ENTITY single_device
    SUBTYPE OF (device);
  END_ENTITY; -- single_device

  ENTITY single_function_unit
    SUBTYPE OF (function_unit);
  END_ENTITY; -- single_function_unit

  ENTITY single_value
    SUBTYPE OF (data_element_value);
      value_of_single_value : single_value_select;
  END_ENTITY; -- single_value

  ENTITY solid_fill_area
    SUBTYPE OF (fill_area_appearance);
      fill_colour : colour;
  END_ENTITY; -- solid_fill_area

  ENTITY solution_instance_assignment;
      solution : alternative_solution;
      instance : solution_instance_select;
  END_ENTITY; -- solution_instance_assignment

  ENTITY specific_document_classification;
      classification_name : undefined_object;
      description         : OPTIONAL undefined_object;
      associated_document : SET [1:?] OF document;
  END_ENTITY; -- specific_document_classification

  ENTITY specific_document_classification_hierarchy;
      super_classification : specific_document_classification;
      sub_classification   : specific_document_classification;
  END_ENTITY; -- specific_document_classification_hierarchy

  ENTITY specific_item_classification;
      associated_item     : SET [1:?] OF item;
      classification_name : undefined_object;
      description         : OPTIONAL undefined_object;
  END_ENTITY; -- specific_item_classification

  ENTITY specific_item_classification_hierarchy;
      super_classification : specific_item_classification;
      sub_classification   : specific_item_classification;
  END_ENTITY; -- specific_item_classification_hierarchy

  ENTITY specification;
      category    : specification_category;
      id          : undefined_object;
      version_id  : OPTIONAL undefined_object;
      name        : OPTIONAL undefined_object;
      description : OPTIONAL undefined_object;
      package     : BOOLEAN;
  END_ENTITY; -- specification

  ENTITY specification_category;
      description                  : undefined_object;
      implicit_exclusive_condition : BOOLEAN;
      id                           : undefined_object;
  END_ENTITY; -- specification_category

  ENTITY specification_category_hierarchy;
      super_category : specification_category;
      sub_category   : specification_category;
  END_ENTITY; -- specification_category_hierarchy

  ENTITY specification_expression;
      description : OPTIONAL undefined_object;
      operand     : SET [1:?] OF specification_operand_select;
      operation   : type_of_operation;
      id          : OPTIONAL undefined_object;
  END_ENTITY; -- specification_expression

  ENTITY specification_inclusion;
      description            : OPTIONAL undefined_object;
      if_condition           : specification_operand_select;
      included_specification : specification_operand_select;
      id                     : OPTIONAL undefined_object;
  END_ENTITY; -- specification_inclusion

  ENTITY specified_device
    SUBTYPE OF (device);
      related_device   : device;
      upper_usage      : device;
      assembly_context : OPTIONAL assembly_definition;
  END_ENTITY; -- specified_device

  ENTITY specified_function_unit
    SUBTYPE OF (function_unit);
      related_function_unit : function_unit;
      upper_usage           : function_unit;
      functional_context    : OPTIONAL function_definition;
  END_ENTITY; -- specified_function_unit

  ENTITY storage_temperature;
      temperature : value_with_unit;
  END_ENTITY; -- storage_temperature

  ENTITY string_value;
      value_of_string_value : undefined_object;
  END_ENTITY; -- string_value

  ENTITY structured_dimension_callout
    SUBTYPE OF (dimension_callout);
      dimension_value : SET [1:?] OF text_string;
      unit_text       : OPTIONAL SET [1:?] OF text_string;
      tolerance_value : OPTIONAL SET [1:?] OF text_string;
      prefix_callout  : OPTIONAL draughting_callout;
      suffix_callout  : OPTIONAL draughting_callout;
      symbol          : OPTIONAL annotation_symbol;
  END_ENTITY; -- structured_dimension_callout

  ENTITY sub_group
    SUBTYPE OF (group_element);
      basis_group : group;
  END_ENTITY; -- sub_group

  ENTITY supplier_solution
    SUBTYPE OF (alternative_solution);
      supplier         : organization;
      probability_rate : OPTIONAL undefined_object;
  END_ENTITY; -- supplier_solution

  ENTITY technical_solution
    SUBTYPE OF (alternative_solution);
      description : undefined_object;
  END_ENTITY; -- technical_solution

  ENTITY technical_system;
      version_id           : OPTIONAL undefined_object;
      description          : OPTIONAL undefined_object;
      contains             : SET [0:?] OF system_select;
      extended_designation : OPTIONAL object_reference_designation;
      id                   : undefined_object;
  END_ENTITY; -- technical_system

  ENTITY technical_system_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      relating      : technical_system;
      related       : technical_system;
  END_ENTITY; -- technical_system_relationship

  ENTITY terminal;
      description                   : OPTIONAL undefined_object;
      terminal_of                   : single_device;
      id                            : undefined_object;
      implemented_by                : SET [0:?] OF implementation_select;
      associated_interface_terminal : interface_terminal;
      extended_designation          : OPTIONAL terminal_designation;
  END_ENTITY; -- terminal

  ENTITY terminal_designation
    SUBTYPE OF (object_designation);
  END_ENTITY; -- terminal_designation

  ENTITY terminal_relationship;
      relation_type : name;
      description   : OPTIONAL undefined_object;
      related       : terminal;
      relating      : terminal;
  END_ENTITY; -- terminal_relationship

  ENTITY terminator_symbol
    SUBTYPE OF (predefined_symbol);
      symbol_type : terminator_symbol_type;
  END_ENTITY; -- terminator_symbol

  ENTITY text
    SUBTYPE OF (annotation_element);
      alignment                 : text_alignment;
      blanking_box              : OPTIONAL rectangular_area;
      mirror_angle              : OPTIONAL undefined_object;
      surrounding_box           : OPTIONAL rectangular_area;
      default_appearance        : text_appearance;
      boundary_of_displayed_box : OPTIONAL SET [1:?] OF annotation_curve;
      language_code             : OPTIONAL undefined_object;
    INVERSE
      strings : SET [1:?] OF text_string FOR containing_text;
  END_ENTITY; -- text

  ENTITY text_appearance
    SUBTYPE OF (appearance);
      character_aspect_ratio   : undefined_object;
      character_rotation_angle : undefined_object;
      character_scale          : undefined_object;
      character_slant_angle    : undefined_object;
      font                     : text_font;
      text_colour              : colour;
  END_ENTITY; -- text_appearance

  ENTITY text_font
    ABSTRACT SUPERTYPE OF (ONEOF (externally_defined_text_font,
        predefined_text_font));
    INVERSE
      definition_of : SET [1:?] OF text_appearance FOR font;
  END_ENTITY; -- text_font

  ENTITY text_string;
      assigned_appearance : OPTIONAL text_appearance;
      character_alignment : string_alignment;
      character_string    : undefined_object;
      overline_underline  : OPTIONAL text_string_line;
      surrounding_box     : rectangular_area;
      position            : point_2d;
      containing_text     : text;
      rotation            : undefined_object;
  END_ENTITY; -- text_string

  ENTITY tile
    ABSTRACT SUPERTYPE OF (ONEOF (user_defined_tile,
        externally_defined_tile));
      overriding_colour : OPTIONAL colour;
    INVERSE
      defined_tilings : SET [1:?] OF user_defined_tiling FOR defining_tile;
  END_ENTITY; -- tile

  ENTITY typical_schematic_node;
      node_area        : OPTIONAL SET [1:?] OF connect_area;
      id               : undefined_object;
      coordinate_space : cartesian_coordinate_space_2d;
      consists_of      : OPTIONAL SET [1:?] OF typical_node_select;
  END_ENTITY; -- typical_schematic_node

  ENTITY typical_schematic_text;
      consists_of : text;
      id          : undefined_object;
  END_ENTITY; -- typical_schematic_text

  ENTITY unstructured_dimension_callout
    SUBTYPE OF (dimension_callout);
      basis_callout : draughting_callout;
  END_ENTITY; -- unstructured_dimension_callout

  ENTITY user_defined_colour
    SUBTYPE OF (colour);
      blue_proportion  : undefined_object;
      green_proportion : undefined_object;
      red_proportion   : undefined_object;
      colour_id        : OPTIONAL undefined_object;
  END_ENTITY; -- user_defined_colour

  ENTITY user_defined_data_element
    SUBTYPE OF (data_element);
      definition            : data_element_definition;
      value_of_data_element : OPTIONAL data_element_value;
  END_ENTITY; -- user_defined_data_element

  ENTITY user_defined_hatching
    SUBTYPE OF (fill_area_appearance);
      defining_pattern : SET [1:?] OF hatching_pattern;
  END_ENTITY; -- user_defined_hatching

  ENTITY user_defined_line_font
    SUBTYPE OF (line_font);
      font_id : undefined_object;
      pattern : SET [2:?] OF undefined_object;
  END_ENTITY; -- user_defined_line_font

  ENTITY user_defined_symbol
    SUBTYPE OF (annotation_symbol);
      definition : user_defined_symbol_definition;
  END_ENTITY; -- user_defined_symbol

  ENTITY user_defined_symbol_definition
    SUPERTYPE OF (ONEOF (drawing_sheet_layout,reference_grid_layout));
      symbol_definition_id : undefined_object;
      coordinate_space     : cartesian_coordinate_space_2d;
      components           : SET [1:?] OF annotation_element;
      blanking_box         : OPTIONAL rectangular_area;
  END_ENTITY; -- user_defined_symbol_definition

  ENTITY user_defined_tile
    SUBTYPE OF (tile);
      definition : user_defined_symbol_definition;
  END_ENTITY; -- user_defined_tile

  ENTITY user_defined_tiling
    SUBTYPE OF (fill_area_appearance);
      angle           : undefined_object;
      repeat_vector_1 : undefined_object;
      repeat_vector_2 : undefined_object;
      scale           : undefined_object;
      defining_tile   : tile;
  END_ENTITY; -- user_defined_tiling

  ENTITY value_limit
    SUBTYPE OF (value_with_unit);
      limit           : undefined_object;
      limit_qualifier : undefined_object;
  END_ENTITY; -- value_limit

  ENTITY value_range
    SUBTYPE OF (value_with_unit);
      upper_limit : undefined_object;
      lower_limit : undefined_object;
  END_ENTITY; -- value_range

  ENTITY value_with_unit
    ABSTRACT SUPERTYPE OF (ONEOF (value_limit,numerical_value,value_range));
      unit_component     : OPTIONAL undefined_object;
      significant_digits : OPTIONAL undefined_object;
  END_ENTITY; -- value_with_unit

  ENTITY view_displayed_model;
      clipping              : rectangular_area;
      displayed_model       : draughting_model;
      transformation        : undefined_object;
      overriding_appearance : OPTIONAL appearance;
      presented_in          : drawing_view;
      scale                 : undefined_object;
  END_ENTITY; -- view_displayed_model

  ENTITY view_placed_annotation
    SUBTYPE OF (draughting_annotation);
      containing_view       : drawing_view;
      annotation_layers     : SET [1:?] OF layer;
      annotation_visibility : visibility;
  END_ENTITY; -- view_placed_annotation

  ENTITY visibility;
  END_ENTITY; -- visibility

  ENTITY work_order;
      description     : OPTIONAL undefined_object;
      work_order_type : name;
      id              : undefined_object;
      version_id      : OPTIONAL undefined_object;
      is_controlling  : activity;
  END_ENTITY; -- work_order

  ENTITY work_request;
      id                              : undefined_object;
      version_id                      : OPTIONAL undefined_object;
      status                          : undefined_object;
      request_type                    : name;
      description                     : OPTIONAL undefined_object;
      notified_person_or_organization : SET [1:?] OF date_and_person_or_organization;
      requestor                       : OPTIONAL date_and_person_or_organization;
      scope                           : SET [0:?] OF
                                            activity_element_select;
  END_ENTITY; -- work_request

END_SCHEMA; -- ap212_application_reference_model
