-- 2000-09-08

(*

	WG12 N525 								2000-05-30

	EXPRESS Declarations for ISO 10303-41: 2nd Edition
*)

SCHEMA certification_schema;
REFERENCE FROM support_resource_schema
  (label,
   text);

ENTITY certification;
  name    : label;
  purpose : text;
  kind    : certification_type;
END_ENTITY; -- certification

ENTITY certification_type;
  description : label;
END_ENTITY; -- certification_type

END_SCHEMA; -- certification_schema
