SCHEMA ida_step_schema;

-- Main changes from original ap214_arm, 2003-09-27
-- 1) USE from integrated resources the geometric and persopn/organization/address
-- 2) replace geometric_model with shape_representation
-- 3) replace cartesian_coordinate_space, _2d, _3d with geometric_representation_context

-- 4) replace model_image with camera_image
-- 5) replace view with presentation_view
-- 6) replace drawing_sheet with drawing_sheet_revision
-- 7) replace drawing with drawing_revision
-- 8) removed path entity
-- 9) general_shape_dependent_property.property_value type changed to representation_item
--10) JB: kinematic_pair from ap214_arm changed to kinematic_pair from kinematic_structure_schema
--11) JB: pair_value from ap214_arm changed to pair_value from kinematic_structure_schema

--12) RR: changed digital_file.associated_model_space from inverse aggregate made direct link to representation

--13) EM: Added implementation_select from AP212
--14) EM: Added terminal from AP212
--15) EM: Added interface_terminal from AP212
--16) EM: Added terminal_designation from AP212
--17) EM: Added object_designation from AP212 (commented subtype definitions document_designation and signal_designation and
		--attribute type_of_object_designation type name substituted with STRING)
--18) EM: Added connection from AP212
--19) EM: Added connectivity_definition from AP212 (commented subtype interface_terminal_connection)

--20) RR: Added coordinated_universal_time_offset, ahead_or_behind from Date_time_schema
--21) RR: Added some missing schemas .. such as Quantified_measure_schema

--22)EM Added connectivity_definition to classified_element_select
--23)EM Added item to item_property_select
--24)EM Added drawing_sheet_revision to item_property_select
--25)EM Added connectivity_definition to item_property_select

--26)RR: Added dimensional_exponents from measure_schema

--27)EM Added camera_image_2d_with_scale from automotive_design

--28)RR: Changed attributes types of dated_configuration to date_time

--29)EM Added item_presentation from AP212_ARM
--30)EM Added presentation_select from AP212_ARM, but strongly reduced entities count - left onfy necessary.

--31)EM Added terminal to item_property_select

--32)EM Added interface_terminals_relationship and terminal_relationship, the attribute types name substituted with STRING.

--33)EM Added resource_item, resource_item_assignment, time_interval_assignment from modules (ADDED TEMPORARILY)

--34)EM Added view_definition_context, work_breakdown_element, work_breakdown_element_version, work_breakdown_element_definition, 
--work_breakdown_element_usage, wbs_element_precedence (ADDED TEMPORARILY)
 

	(* added for extended ARM *)
	USE FROM aic_advanced_brep; -- ISO 10303-514

	USE FROM aic_csg; -- ISO 10303-515

	USE FROM aic_edge_based_wireframe; -- ISO 10303-501

	USE FROM aic_geometrically_bounded_2d_wireframe; -- ISO 10303-503

	USE FROM aic_draughting_elements; -- ISO 10303-506

	USE FROM aic_draughting_annotation; -- ISO 10303-504

	USE FROM aic_associative_draughting_elements; -- ISO 10303-520

	USE FROM aic_geometrically_bounded_surface; -- ISO 10303-507

	USE FROM aic_geometrically_bounded_wireframe; -- ISO 10303-510

	USE FROM aic_manifold_surface; -- ISO 10303-509

	USE FROM aic_manifold_subsurface; -- ISO 10303-521

	USE FROM aic_shell_based_wireframe; -- ISO 10303-502

	USE FROM aic_mechanical_design_geometric_presentation; -- ISO 10303-517

	USE FROM aic_non_manifold_surface; -- ISO 10303-508

	USE FROM aic_topologically_bounded_surface; -- ISO 10303-511

	USE FROM presentation_definition_schema; -- ISO 10303-46

	USE FROM presentation_appearance_schema; -- ISO 10303-46

	USE FROM qualified_measure_schema   -- ISO 10303-45
	(	descriptive_representation_item,
	   	measure_qualification,
		measure_representation_item,
		precision_qualifier,
		qualified_representation_item,
		standard_uncertainty,
		type_qualifier,
		uncertainty_qualifier
	);

	USE FROM draughting_element_schema(
		terminator_symbol
	);

	USE FROM ida_step_aim_schema(
		edge_round,
		transition_feature,
		chamfer,
		fillet,
		person_and_organization_address,
		name_item,
		applied_name_assignment,
		draughting_specification_reference,
		camera_image_2d_with_scale
	);

	USE FROM electrotechnical_design(
		document_designation_assignment,
		item_designation_assignment
	);

	USE FROM person_organization_schema(
		address,
		organization,
		organizational_address,
		person,
		personal_address
	);

	USE FROM product_property_representation_schema(
   		shape_representation,
   		shape_representation_relationship
	);
		-- shape_definition_representation,

	USE FROM geometric_model_schema   -- ISO 10303-42
	  (
	  	block,
		boolean_result,
		brep_with_voids,
		csg_solid,
		edge_based_wireframe_model,
		extruded_face_solid,
		face_based_surface_model,
		faceted_brep,
		geometric_curve_set,
		geometric_set,
		half_space_solid,
		manifold_solid_brep,
		revolved_face_solid,
		right_angular_wedge,
		right_circular_cone,
		right_circular_cylinder,
		shell_based_surface_model,
		solid_model,
		solid_replica,
		sphere,
		swept_face_solid,
		torus
	);

	USE FROM geometry_schema   -- ISO 10303-42
	  (
	  	axis1_placement,
	   	axis2_placement_2d,
	   	axis2_placement_3d,
	   	b_spline_curve,
	   	b_spline_surface,
	   	bounded_curve,
	   	bounded_surface,
	   	cartesian_point,
	   	cartesian_transformation_operator,
	   	cartesian_transformation_operator_2d,
	   	cartesian_transformation_operator_3d,
	   	circle,
	   	composite_curve,
		conic,
	   	conical_surface,
	   	curve,
	   	curve_bounded_surface,
	   	cylindrical_surface,
	   	degenerate_pcurve,
	   	degenerate_toroidal_surface,
	   	direction,
	   	elementary_surface,
	   	ellipse,
	   	geometric_representation_context,
	   	geometric_representation_item,
	   	hyperbola,
	   	line,
	   	offset_curve_2d,
	   	offset_curve_3d,
	   	offset_surface,
	   	oriented_surface,
	   	parabola,
	   	pcurve,
	   	placement,
	   	plane,
	   	point,
	   	point_on_curve,
	   	point_on_surface,
	  	point_replica,
	   	polyline,
	   	rectangular_composite_surface,
	   	rectangular_trimmed_surface,
	   	spherical_surface,
	   	surface,
	   	surface_curve,
	   	surface_of_linear_extrusion,
	   	surface_of_revolution,
	   	toroidal_surface,
	   	trimmed_curve
	);

	USE FROM topology_schema   -- ISO 10303-42
	  (
	  	closed_shell,
	   	connected_edge_set,
	   	connected_face_set,
	   	connected_face_sub_set,
	   	edge,
	   	edge_curve,
	   	edge_loop,
	   	face,
	   	face_bound,
	   	face_outer_bound,
	   	face_surface,
	   	loop,
	   	open_shell,
	   	oriented_closed_shell,
	   	oriented_edge,
	   	oriented_face,
	   	path,
	   	poly_loop,
	   	seam_edge,
	   	subedge,
	   	subface,
	   	topological_representation_item,
	   	vertex,
	   	vertex_loop,
	   	vertex_point);

	USE FROM measure_schema   -- ISO 10303-41
	  (amount_of_substance_measure,
	   amount_of_substance_measure_with_unit,
	   amount_of_substance_unit,
	   area_measure,
	   area_measure_with_unit,
	   area_unit,
	   celsius_temperature_measure,
	   celsius_temperature_measure_with_unit,
	   context_dependent_measure,
	   context_dependent_unit,
	   conversion_based_unit,
	   count_measure,
	   derived_unit,
	   descriptive_measure,
	   dimensional_exponents,
	   electric_current_measure,
	   electric_current_measure_with_unit,
	   electric_current_unit,
	   global_unit_assigned_context,
	   length_measure,
	   length_measure_with_unit,
	   length_unit,
	   luminous_intensity_measure,
	   luminous_intensity_measure_with_unit,
	   luminous_intensity_unit,
	   mass_measure,
	   mass_measure_with_unit,
	   mass_unit,
	   measure_with_unit,
	   named_unit,
	   numeric_measure,
	   parameter_value,
	   plane_angle_measure,
	   plane_angle_measure_with_unit,
	   plane_angle_unit,
	   positive_length_measure,
	   positive_plane_angle_measure,
	   positive_ratio_measure,
	   ratio_measure,
	   ratio_measure_with_unit,
	   ratio_unit,
	   si_unit,
	   solid_angle_measure,
	   solid_angle_measure_with_unit,
	   solid_angle_unit,
	   thermodynamic_temperature_measure,
	   thermodynamic_temperature_measure_with_unit,
	   thermodynamic_temperature_unit,
	   time_measure,
	   time_measure_with_unit,
	   time_unit,
	   volume_measure,
	   volume_measure_with_unit,
	   volume_unit,
	   unit);

	USE FROM date_time_schema(
		date,
		calendar_date,
		date_and_time,
		local_time,
		coordinated_universal_time_offset,
		ahead_or_behind
	);

(*
	USE FROM representation_schema(
		global_uncertainty_assigned_context,
		representation_item
	);
*)

	USE FROM representation_schema   -- ISO 10303-43
	  (
	  	compound_representation_item,
	   	founded_item,
	   	functionally_defined_transformation,
	   	global_uncertainty_assigned_context,
	   	item_defined_transformation,
	   	list_representation_item,
	   	mapped_item,
	   	representation,
	   	representation_context,
	   	representation_item,
	   	representation_map,
	   	representation_relationship,
	  	representation_relationship_with_transformation,
	   	set_representation_item,
	   	uncertainty_assigned_representation,
	   	uncertainty_measure_with_unit,
	   	value_representation_item
	);


	USE FROM presentation_organization_schema --ISO 10303-46
	(
		area_in_set,
		camera_image,
		camera_model,
		camera_model_d2,
		camera_model_d3,
		camera_model_d3_with_hlhsr,
		camera_usage,
		light_source,
		light_source_ambient,
		light_source_directional,
		light_source_positional,
		light_source_spot,
		presentation_area,
		presentation_layer_assignment,
		presentation_representation,
		presentation_set,
		presentation_size,
		presentation_view,
		view_volume
	);
		-- presented_item,
		-- presented_item_representation,

	REFERENCE FROM presentation_organization_schema
		(aspect_ratio);


	USE FROM drawing_definition_schema -- ISO 10303-101
	(
		draughting_title,
		drawing_definition,
		drawing_revision,
		drawing_revision_sequence,
		drawing_sheet_revision,
		drawing_sheet_revision_usage
	);


	USE FROM basic_attribute_schema -- ISO 10303-41.2
	(
		description_attribute,
		id_attribute,
		name_attribute,
		object_role,
		role_association
	);

	USE FROM kinematic_structure_schema -- ISO 10303-105
	(
		kinematic_pair,
		cylindrical_pair,
		fully_constrained_pair,
		gear_pair,
		planar_curve_pair,
		planar_pair,
		point_on_planar_curve_pair,
		point_on_surface_pair,
		prismatic_pair,
		rack_and_pinion_pair,
		revolute_pair,
		screw_pair,
		spherical_pair,
		surface_pair,
		unconstrained_pair,
		universal_pair,
		pair_value,
		cylindrical_pair_value,
		gear_pair_value,
		planar_pair_value,
		point_on_planar_curve_pair_value,
		point_on_surface_pair_value,
		prismatic_pair_value,
		rack_and_pinion_pair_value,
		revolute_pair_value,
		rolling_curve_pair_value,
		rolling_surface_pair_value,
		screw_pair_value,
		sliding_curve_pair_value,
		sliding_surface_pair_value,
		spherical_pair_value,
		unconstrained_pair_value,
		universal_pair_value,
		spatial_rotation,
		ypr_rotation,
		rotation_about_direction,
		rigid_placement,
		su_parameters,
		kinematic_joint,
		kinematic_link,
		kinematic_link_representation,
		kinematic_link_representation_relation,
		kinematic_link_representation_association
	);
	
	USE FROM management_resources_schema(
		identification_assignment,
		identification_role
	);

-- support of AP209
	USE FROM structural_response_representation_schema ( -- ISO 10303-104
		fea_model,
		fea_model_3d,
		fea_model_2d,
		fea_axis2_placement_3d,
		fea_axis2_placement_2d,
		surface_3d_element_representation
	);

-- for usages of structural_response_representation_schema
 TYPE text = STRING;
 END_TYPE;

 TYPE undefined_object_string = STRING;
 END_TYPE;

 ENTITY undefined_object_entity;
 END_ENTITY;

 TYPE undefined_object = STRING;
 END_TYPE;
(*
 TYPE undefined_object = SELECT (
   undefined_object_string,
   undefined_object_entity
  );
 END_TYPE;
*)

 TYPE general_organizational_data_select = SELECT (
   product_identification,
   assembly_substitute_relationship,
   design_discipline_item_definition,
   kinematic_simulation_information,
   class_category_association,
   class_specification_association,
   class_condition_association,
   class_inclusion_association,
   design_constraint,
   product_class,
   activity,
   activity_element,
   document,
   document_version,
   configuration,
   drawing_revision,
   drawing_sheet_revision,
   process_plan,
   certification,
   classification_system,
   classification_association,
   document_representation,
   document_file,
   process_operation_occurrence,
   material,
   physical_instance,
   physical_assembly_relationship,
   physical_instance_test_result,
   product_structure_relationship,
   manufacturing_configuration,
   complex_product,
   activity_method_assignment,
   alternate_item_relationship,
   approval_status,
   class_structure_relationship,
   complex_product_relationship,
   contract,
   general_classification,
   shape_representation,
   item,
   item_definition_instance_relationship,
   item_definition_relationship,
   item_instance,
   item_instance_relationship,
   item_version,
   item_version_relationship,
   person_in_organization_relationship,
   organization_relationship,
   process_operation_definition,
   process_operation_resource_assignment,
   person_in_organization,
   general_organizational_data_sub_select
  );
 END_TYPE;

(* arm entities removed. no usage of this select
 TYPE boolean_operand_select = SELECT (
   csg_select,
   half_space_solid
  );
 END_TYPE;
 *)

(* arm entities removed. no usage of this select
 TYPE csg_select = SELECT (
   boolean_result,
   non_primitive_solid_select,
   csg_primitive_arm
  );
 END_TYPE;
 *)

 TYPE limitation_definition_select = SELECT (
   limits_and_fits,
   plus_minus_bounds
  );
 END_TYPE;

 TYPE fill_area_associated_element_select = SELECT (
   annotation_curve_occurrence,
   geometric_representation_item
  );
 END_TYPE;

 TYPE general_tolerance_table_select = SELECT (
   document_file,
   general_tolerance_table
  );
 END_TYPE;

 TYPE area_select = SELECT (
   view_area,
   drawing_sheet_revision
  );
 END_TYPE;

 TYPE appearance_context_select = SELECT (
   presentation_view,
   structuring_method_select,
   area_select,
   camera_image
  );
 END_TYPE;

 TYPE structuring_method_select = SELECT (
   group,
   layer
  );
 END_TYPE;

 TYPE default_setting_select = SELECT (
   default_surface_texture,
   default_chamfer,
   default_draft_angle,
   default_fillet,
   default_edge_round,
   general_tolerances,
   default_thickness
  );
 END_TYPE;

 TYPE model_change_select = SELECT (
   styled_model_relationship,
   geometric_model_relationship,
   view_area_relationship,
   view_relationship
  );
 END_TYPE;

 TYPE cell_entry_select = SELECT (
   plus_minus_toleranced_datum,
   upper_lower_toleranced_datum
  );
 END_TYPE;

 TYPE documented_element_select = SELECT (
   contract,
   material,
   activity,
   approval,
   drawing_sheet_revision,
   change,
   item_instance,
   design_constraint,
   design_discipline_item_definition,
   descriptive_specification,
   general_classification,
   classification_attribute,
   classification_system,
   certification,
   activity_method,
   item_shape,
   item_definition_instance_relationship,
   item_instance_relationship,
   item_definition_relationship,
   complex_product,
   feature_definition,
   general_feature,
   catalogue_thread,
   physical_assembly_relationship,
   physical_instance,
   physical_instance_test_result,
   process_plan,
   process_operation_occurrence,
   product_identification,
   product_class,
   product_structure_relationship,
   profile,
   project,
   property,
   class_structure_relationship,
   item,
   activity_element,
   item_version,
   person,
   documented_element_sub_select,
   path,
   organization
  );
 END_TYPE;

 TYPE connected_element_select = SELECT (
   oriented_edge_curve,
   face
  );
 END_TYPE;

 TYPE loop_select = SELECT (
   vertex_loop,
   edge_loop
  );
 END_TYPE;

 TYPE appearance_select = SELECT (
   solid_fill_area,
   tiling,
   text_appearance,
   surface_appearance,
   curve_appearance,
   point_appearance,
   hatching
  );
 END_TYPE;

 TYPE taper_select = SELECT (
   diameter_taper,
   angle_taper,
   directed_taper
  );
 END_TYPE;

 TYPE non_primitive_solid_select = SELECT (
   swept_face_solid,
   faceted_brep_shape_representation,
   advanced_brep_shape_representation,
   solid_replica
  );
 END_TYPE;

 TYPE resource_definition_select = SELECT (
   descriptive_specification,
   design_discipline_item_definition,
   item_instance,
   physical_instance,
   product_component
  );
 END_TYPE;

 TYPE point_direction_element_select = SELECT (
   point_on_surface,
   axis1_placement
  );
 END_TYPE;

 TYPE specification_operand_select = SELECT (
   specification_expression,
   specification
  );
 END_TYPE;

 TYPE configured_specification_select = SELECT (
   class_specification_association,
   class_condition_association
  );
 END_TYPE;

 TYPE configured_item_select = SELECT (
   process_operation_occurrence,
   item_instance,
   complex_product_select,
   process_plan
  );
 END_TYPE;

 TYPE limit_select = SELECT (
   significant_number_of_digits,
   upper_lower_limit
  );
 END_TYPE;

 TYPE template_definition_select = SELECT (
   shape_representation,
   styled_model,
   external_model
  );
 END_TYPE;

 TYPE associated_element_select = SELECT (
   draughting_annotation_occurrence,
   geometric_representation_item
  );
 END_TYPE;

 TYPE datum_representation_select = SELECT (
   datum_target_set,
   shape_element,
   derived_geometry
  );
 END_TYPE;

 TYPE placed_element_select = SELECT (
   derived_geometry,
   constructive_geometric_element,
   element_with_dimension_select
  );
 END_TYPE;

 TYPE complex_product_select = SELECT (
   alternative_solution,
   product_component,
   product_function
  );
 END_TYPE;

 TYPE element_with_dimension_select = SELECT (
   shape_element,
   annotation_curve_occurrence
  );
 END_TYPE;

 TYPE constructive_element_select = SELECT (
   face,
   point,
   curve,
   surface,
   oriented_edge_curve,
   placement,
   vertex_point
  );
 END_TYPE;

 TYPE compound_in_solid_select = SELECT (
   process_feature_in_solid,
   transition_feature,
   thread_feature
  );
 END_TYPE;

 TYPE person_organization_select = SELECT (
   person_in_organization,
   organization
  );
 END_TYPE;

 TYPE contracted_element_select = SELECT (
   drawing_revision,
   item_version,
   activity
  );
 END_TYPE;

 TYPE shape_information_select = SELECT (
   shape_element_relationship,
   feature_definition_select,
   shaped_element_select
  );
 END_TYPE;

 TYPE process_operation_input_or_output_select = SELECT (
   design_discipline_item_definition,
   mated_item_association,
   assembly_component_relationship,
   item_instance
  );
 END_TYPE;

 TYPE item_information_select = SELECT (
   design_discipline_item_definition,
   item_instance,
   physical_instance,
   product_component
  );
 END_TYPE;

 TYPE presentation_association_select = SELECT (
   process_plan,
   process_operation_occurrence,
   product_class,
   specification,
   specification_category,
   design_constraint,
   design_discipline_item_definition,
   item_instance,
   item_definition_instance_relationship,
   item_definition_relationship,
   item_instance_relationship,
   complex_product,
   item_version,
   process_operation_definition
  );
 END_TYPE;

 TYPE string_select = SELECT (
   multi_language_string,
   default_language_string
  );
 END_TYPE;

 TYPE point_or_curve_select = SELECT (
   curve,
   point
  );
 END_TYPE;

 TYPE model_property_representation_select = SELECT (
   shape_representation,
   styled_model,
   external_model
  );
 END_TYPE;

 TYPE default_context_select = SELECT (
   area_select,
   digital_document,
   item_shape,
   digital_file
  );
 END_TYPE;

 TYPE activity_element_select = SELECT (
   property,
   view_area,
   specification,
   specification_category,
   specification_expression,
   specification_inclusion,
   class_category_association,
   class_inclusion_association,
   class_specification_association,
   product_class,
   design_constraint,
   activity_method,
   configuration,
   item_instance,
   product_identification,
   document_representation,
   shape_representation,
   document_file,
   styled_model,
   assembly_substitute_relationship,
   document,
   document_version,
   feature_occurrence,
   product_structure_relationship,
   item_definition_instance_relationship,
   item_definition_relationship,
   item_instance_relationship,
   complex_product,
   process_plan,
   property_value_association,
   process_operation_definition,
   design_discipline_item_definition,
   alternate_item_relationship,
   class_condition_association,
   class_structure_relationship,
   item,
   item_version,
   kinematic_simulation_information,
   manufacturing_configuration,
   material,
   process_operation_occurrence,
   physical_instance,
   physical_assembly_relationship,
   drawing_revision
  );
 END_TYPE;

 TYPE security_element_select = SELECT (
   work_request,
   physical_instance,
   drawing_revision,
   configuration,
   material,
   activity,
   activity_element,
   work_order,
   project,
   view_area,
   drawing_sheet_revision,
   item_version,
   specification,
   specification_category,
   design_constraint,
   item,
   document,
   document_version,
   document_file,
   classification_system,
   styled_model,
   physical_instance_test_result,
   assembly_substitute_relationship,
   physical_assembly_relationship,
   shape_representation,
   kinematic_simulation_information,
   document_representation,
   manufacturing_configuration,
   complex_product,
   property_value_association,
   property,
   class_structure_relationship,
   product_structure_relationship,
   product_class,
   process_plan
  );
 END_TYPE;

 TYPE approval_element_select = SELECT (
   document,
   document_version,
   document_representation,
   shape_representation,
   kinematic_simulation_information,
   activity_method_assignment,
   styled_model,
   design_constraint,
   specification_category,
   class_category_association,
   class_specification_association,
   class_condition_association,
   specification_expression,
   specification_inclusion,
   certification,
   contract,
   product_class,
   physical_instance_test_result,
   document_file,
   class_inclusion_association,
   drawing_revision,
   specification,
   configuration,
   material,
   activity,
   activity_element,
   process_plan,
   work_order,
   project,
   work_request,
   physical_assembly_relationship,
   design_discipline_item_definition,
   physical_instance,
   assembly_substitute_relationship,
   alternate_item_relationship,
   drawing_sheet_revision,
   view_area,
   product_structure_relationship,
   manufacturing_configuration,
   complex_product,
   property_value_association,
   item_version,
   property,
   class_structure_relationship,
   item_definition_instance_relationship,
   item_definition_relationship,
   item_instance,
   item_instance_relationship,
   general_classification,
   classification_association,
   classification_system
  );
 END_TYPE;

 TYPE change_relationship_select = SELECT (
   item_version_relationship,
   process_plan_relationship,
   design_constraint_relationship,
   shape_element_relationship,
   replaced_definition_relationship,
   replaced_usage_relationship,
   complex_product_relationship,
   process_operation_occurrence_relationship
  );
 END_TYPE;

(* use aim types
 TYPE topologically_bounded_curve_select = SELECT (
   line,
   curve_on_surface,
   b_spline_curve,
   parabola,
   hyperbola,
   ellipse,
   circle,
   polyline
  );
 END_TYPE;
*)

 TYPE starting_or_ending = ENUMERATION OF ( starting, ending  );
 END_TYPE;

 TYPE constructive_geometry_select = SELECT (
   shape_representation,
   constructive_geometry
  );
 END_TYPE;

 TYPE geometric_or_external_model_select = SELECT (
   external_model,
   shape_representation
  );
 END_TYPE;

 TYPE feature_definition_select = SELECT (
   transition_feature,
   feature_definition,
   general_feature,
   thread_feature
  );
 END_TYPE;

 TYPE straight_or_tapered = ENUMERATION OF ( straight, tapered  );
 END_TYPE;

 TYPE transformation_select = SELECT (
   mapped_item,
   representation_relationship_with_transformation
  );
 END_TYPE;

 TYPE presented_model_select = SELECT (
   styled_model,
   external_model
  );
 END_TYPE;

 TYPE profile_or_angle_select = SELECT (
   closed_profile_usage,
   angle_specification
  );
 END_TYPE;

 TYPE boss_pocket_stairstep_enumeration = ENUMERATION OF ( boss, pocket, stairstep  );
 END_TYPE;

 TYPE event_or_date_select = SELECT (
   event_reference,
   date_time
  );
 END_TYPE;

 TYPE period_or_date_select = SELECT (
   time_measure_with_unit,
   event_reference,
   date_time
  );
 END_TYPE;

 TYPE alias_select = SELECT (
   organization,
   product_class,
   approval_status,
   security_level,
   item,
   document,
   document_version,
   specification,
   item_version,
   item_instance,
   styled_model,
   specification_category,
   document_representation,
   document_type_property,
   physical_instance,
   shape_representation,
   general_classification,
   complex_product,
   classification_system,
   property,
   classification_attribute,
   design_discipline_item_definition
  );
 END_TYPE;

 TYPE accuracy_select = SELECT (
   vertex_point,
   shape_representation,
   face,
   oriented_edge_curve,
   external_geometric_model
  );
 END_TYPE;

 TYPE instance_definition_select = SELECT (
   design_discipline_item_definition,
   product_identification
  );
 END_TYPE;

 TYPE physical_instance_definition_select = SELECT (
   product_identification,
   design_discipline_item_definition
  );
 END_TYPE;

 TYPE origin_enumeration = ENUMERATION OF ( unchanged, mirror, positive_normal, negative_normal  );
 END_TYPE;

 TYPE chamfer_value_select = SELECT (
   chamfer_angle,
   chamfer_offset
  );
 END_TYPE;

 TYPE compound_in_panel_select = SELECT (
   transition_feature,
   process_feature_in_panel
  );
 END_TYPE;

 TYPE angle_reference_enumeration = ENUMERATION OF ( punch_direction, profile_normal, surface_normal  );
 END_TYPE;

 TYPE general_end_select = SELECT (
   surface,
   connected_face_set
  );
 END_TYPE;

 TYPE active_or_inactive = ENUMERATION OF ( active,inactive  );
 END_TYPE;

 TYPE default_language_string = STRING;
 END_TYPE;

 TYPE point_or_curve_or_surface_select = SELECT (
   surface,
   point_or_curve_select
  );
 END_TYPE;

 TYPE simulation_context_select = SELECT (
   design_discipline_item_definition,
   item_instance,
   product_specification,
   product_class,
   item_definition_instance_relationship,
   item_instance_relationship,
   item_definition_relationship,
   complex_product
  );
 END_TYPE;

 TYPE assigned_document_select = SELECT (
   document,
   document_version,
   document_file,
   document_representation
  );
 END_TYPE;

 TYPE annotation_select = SELECT (
   draughting_annotation_occurrence,
   draughting_elements
  );
 END_TYPE;

 TYPE class_source_select = SELECT (
   external_library_reference,
   plib_class_reference
  );
 END_TYPE;

 TYPE classified_element_select = SELECT (
   design_constraint,
   item,
   approval_status,
   security_level,
   product_class,
   document,
   document_representation,
   project,
   contract,
   activity_method,
   property,
   catalogue_thread,
   material,
   product_identification,
   complex_product,
   feature_definition,
   general_feature,
   activity,
   item_version,
   property_value_association,
   item_instance,
   design_discipline_item_definition,
   document_version,
   shape_element,
   specification_category,
   thread_feature,
   transition_feature,
   work_order,
   work_request,
   process_plan,
   process_operation_definition,
   process_operation_occurrence,
   document_file,
   connectivity_definition (*added because of AP212 compatibility*)
  );
 END_TYPE;

 TYPE property_source_select = SELECT (
   external_library_reference,
   plib_property_reference
  );
 END_TYPE;

 TYPE item_property_select = SELECT (
   product_class,
   design_constraint,
   catalogue_thread,
   item_instance,
   design_discipline_item_definition,
   product_structure_relationship,
   item_definition_relationship,
   item_definition_instance_relationship,
   item_instance_relationship,
   item_shape,
   shape_element,
   shape_element_relationship,
   complex_product,
   document_file,
   document_representation,
   feature_definition,
   general_feature,
   thread_feature,
   transition_feature,
   product_identification,
   physical_instance,
   item, (*added because of AP212 compatibility*)
   drawing_sheet_revision, (*added because of AP212 compatibility*)
   connectivity_definition, (*added because of AP212 compatibility*)
   terminal (*added because of AP212 compatibility*)
  );
 END_TYPE;

 TYPE model_property_select = SELECT (
   process_property_select,
   item_property_select
  );
 END_TYPE;

 TYPE effective_element_select = SELECT (
   item,
   item_version,
   product_identification,
   item_instance,
   material,
   drawing_revision,
   view_area,
   specification,
   specification_category,
   specification_inclusion,
   specification_expression,
   product_class,
   design_constraint,
   security_classification,
   class_inclusion_association,
   class_category_association,
   kinematic_simulation_information,
   class_specification_association,
   assembly_substitute_relationship,
   class_condition_association,
   shape_representation,
   styled_model,
   document_file,
   document,
   feature_occurrence,
   classification_system,
   product_structure_relationship,
   document_version,
   configuration,
   item_definition_instance_relationship,
   item_definition_relationship,
   item_instance_relationship,
   complex_product,
   property_value_association,
   property,
   class_structure_relationship,
   complex_product_relationship,
   document_representation,
   process_operation_definition,
   process_operation_definition_relationship,
   process_plan,
   process_operation_occurrence,
   process_operation_resource_assignment,
   process_operation_occurrence_relationship
  );
 END_TYPE;

 TYPE certified_element_select = SELECT (
   item_version_relationship,
   item_version,
   item_instance,
   supplier_solution
  );
 END_TYPE;

 TYPE test_activity_select = SELECT (
   activity,
   process_operation_occurrence
  );
 END_TYPE;

 TYPE process_property_select = SELECT (
   process_plan,
   process_operation_occurrence,
   process_operation_resource_assignment,
   activity,
   activity_method_assignment,
   process_operation_definition
  );
 END_TYPE;

 TYPE model_change_element_select = SELECT (
   shape_representation,
   styled_model
  );
 END_TYPE;

 TYPE incremental_change_select = SELECT (
   incremental_model_change,
   model_change_element_select
  );
 END_TYPE;

 TYPE instance_usage_context_select = SELECT (
   product_structure_relationship,
   item_definition_instance_relationship,
   process_operation_input_or_output
  );
 END_TYPE;

 TYPE texture_select = SELECT (
   surface_texture,
   default_surface_texture
  );
 END_TYPE;

 TYPE dimension_callout_select = SELECT (
   annotation_text_occurrence,
   dimension_symbol
  );
 END_TYPE;

 TYPE shaped_element_select = SELECT (
   shape_element,
   item_shape
  );
 END_TYPE;

 TYPE final_definition_select = SELECT (
   physical_instance,
   design_discipline_item_definition,
   descriptive_specification
  );
 END_TYPE;

 TYPE product_function_component_select = SELECT (
   product_component,
   product_function
  );
 END_TYPE;

 TYPE date_time_person_organization_element_select = SELECT (
   event_reference,
   general_organizational_data_select
  );
 END_TYPE;

 TYPE symbol_definition_select = SELECT (
   dimension_symbol,
   geometric_tolerance_symbol,
   general_symbol,
   surface_condition_symbol,
   terminator_symbol,
   point_marker_symbol
  );
 END_TYPE;

 TYPE pocket_bottom_condition_select = SELECT (
   pocket_bottom_condition,
   through_pocket_bottom_condition
  );
 END_TYPE;

 TYPE group_element_select = SELECT (
   representation_item,
   shape_element
  );
 END_TYPE;

 TYPE hole_bottom_condition_select = SELECT (
   hole_bottom_condition,
   through_hole_bottom_condition
  );
 END_TYPE;

 TYPE validity_context_select = SELECT (
   organization,
   product_identification,
   product_class
  );
 END_TYPE;

 TYPE general_organizational_data_sub_select = SELECT (
   security_level,
   security_classification,
   project,
   property,
   property_value_association,
   specification_category,
   specification,
   specification_expression,
   specification_inclusion,
   styled_model,
   view_area,
   work_order,
   work_request
  );
 END_TYPE;

 TYPE documented_element_sub_select = SELECT (
   specification_category,
   thread_feature,
   surface_condition,
   work_request,
   work_order,
   transition_feature,
   security_classification,
   view_area,
   retention_period,
   shape_element,
   shape_element_relationship,
   specific_item_classification,
   specification
  );
 END_TYPE;

 TYPE shape_definition_select = SELECT (
   external_geometric_model,
   shape_representation
  );
 END_TYPE;

 TYPE draughting_callout_content_select = SELECT (
   annotation_text_occurrence,
   annotation_curve_occurrence,
   annotation_subfigure_occurrence,
   annotation_symbol_occurrence
  );
 END_TYPE;

 TYPE project_information_select = SELECT (
   item,
   product_identification,
   document_version,
   product_class,
   document,
   physical_instance,
   complex_product,
   item_version
  );
 END_TYPE;

 TYPE date_time = SELECT(
 	date_and_time,
 	calendar_date
  );
 END_TYPE;

 TYPE oriented_edge_curve = SELECT(
 	oriented_edge,
 	edge_curve
  );
 END_TYPE;

 TYPE dimension = SELECT (
	angular_dimension,
	curve_dimension,
	diameter_dimension,
	leader_directed_dimension,
	linear_dimension,
	ordinate_dimension,
	radius_dimension
  );
 END_TYPE;

 TYPE styled_model = SELECT(
 	draughting_model,
 	mechanical_design_geometric_presentation_representation
   );
 END_TYPE;

 TYPE implementation_select = SELECT
 (*
 From AP212
 *)
    (item_instance,
     physical_instance);
  END_TYPE;
  
  TYPE presentation_select = SELECT
  (*
 From AP212
 *)
    (connectivity_definition,
	item_instance,
	terminal);
  END_TYPE; -- presentation_select

  TYPE general_shape_dependent_value_select = SELECT
	(* 
		Custom select for general_shape_dependent_property 
	*)
	(
		representation_item,
		value_with_unit
	);
  END_TYPE; -- general_shape_dependent_value_select


 ENTITY product_class;
(*
UOF:S4,S7
*)
  name : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  level_type : OPTIONAL UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY group;
(*
UOF:S2
*)
  purpose : OPTIONAL string_select;
  element : SET [0:?] OF group_element_select;
  name : string_select;
 END_ENTITY;

(* use mapped_item
 ENTITY template_instance
  SUBTYPE OF (
   detailed_model_element
  );
*
UOF:E1,S2
*
  template_definition : template_definition_select;
  id : UNDEFINED_OBJECT;
  model_placement : transformation;
  scale : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;
*)

 ENTITY layer;
(*
UOF:S2
*)
  id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  element : SET [1:?] OF representation_item;
 END_ENTITY;

(*
 ENTITY drawing;
  drawing_id : UNDEFINED_OBJECT;
  language : SET [0:?] OF UNDEFINED_OBJECT;
  title : OPTIONAL string_select;
  drawing_revision_id : UNDEFINED_OBJECT;
  drawing_specification : SET [0:?] OF UNDEFINED_OBJECT;
  drawing_type : UNDEFINED_OBJECT;
 INVERSE
  sheet : SET [1:?] OF drawing_sheet_revision FOR associated_drawing;
 END_ENTITY;
*)
(*
 ENTITY drawing_sheet;
  associated_drawing : drawing;
  size : UNDEFINED_OBJECT;
  title : OPTIONAL string_select;
  sheet_id : UNDEFINED_OBJECT;
  sheet_revision_id : UNDEFINED_OBJECT;
  sheet_space : geometric_representation_context;
 END_ENTITY;
*)
(* use geometric_representation_context instead
 ENTITY cartesian_coordinate_space_2d
  SUBTYPE OF (
   cartesian_coordinate_space
  );
 END_ENTITY;
 ENTITY cartesian_coordinate_space_3d
  SUBTYPE OF (
   cartesian_coordinate_space
  );
 END_ENTITY;
*)

 ENTITY area_placed_annotation;
(*
UOF:P2
*)
  element : annotation_select;
  reference_area : area_select;
 END_ENTITY;

 ENTITY view_area;
(*
UOF:P1
*)
  id : OPTIONAL UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  size : UNDEFINED_OBJECT;
  revision_id : OPTIONAL UNDEFINED_OBJECT;
  area_space : geometric_representation_context;
 END_ENTITY;

 ENTITY view_placed_annotation;
(*
UOF:P2
*)
  reference_view : presentation_view;
  element : annotation_select;
 END_ENTITY;

(*
 ENTITY model_image;
  clipping : OPTIONAL UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  view_projection : UNDEFINED_OBJECT;
  is_presented_in : view;
  scale : UNDEFINED_OBJECT;
  view_volume_placement : UNDEFINED_OBJECT;
  is_displaying : presented_model_select;
 INVERSE
  has : SET [0:1] OF hidden_element_handling FOR is_defined_for;
 END_ENTITY;
*)
 ENTITY general_item_definition_relationship
  SUBTYPE OF (
   item_definition_relationship
  );
(*
UOF:S3
*)
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY tool_part_relationship
  SUBTYPE OF (
   item_definition_relationship
  );
(*
UOF:S8
*)
  placement : OPTIONAL transformation_select;
  used_technology_description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY geometrical_relationship
  SUBTYPE OF (
   item_definition_relationship
  );
(*
UOF:S3
*)
  description : OPTIONAL string_select;
  definition_placement : transformation_select;
 END_ENTITY;

 ENTITY mating_definition
  SUBTYPE OF (
   design_discipline_item_definition
  );
(*
UOF:S8
*)
  mating_type : UNDEFINED_OBJECT;
 INVERSE
(* Express compiler complains here. V.N.
  mated_items : SET [2:?] OF mated_item_association FOR SELF\item_definition_instance_relationship.relating;
*)
  mated_items : SET [2:?] OF mated_item_association FOR relating;
 END_ENTITY;

 ENTITY replaced_definition_relationship
  SUBTYPE OF (
   item_definition_relationship
  );
(*
UOF:S3
*)
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY assembly_component_relationship
  SUPERTYPE OF ( ONEOF(promissory_usage,next_higher_assembly) )
  SUBTYPE OF (
   item_definition_instance_relationship
  );
(*
UOF:S3
*)
  SELF\item_definition_instance_relationship.relating : assembly_definition;
  placement : OPTIONAL transformation_select;
 END_ENTITY;

 ENTITY promissory_usage
  SUBTYPE OF (
   assembly_component_relationship
  );
(*
UOF:S3
*)
 END_ENTITY;

 ENTITY next_higher_assembly
  SUBTYPE OF (
   assembly_component_relationship
  );
(*
UOF:S3
*)
 END_ENTITY;

 ENTITY item;
(*
UOF:S1
*)
  id : UNDEFINED_OBJECT;
  name : string_select;
  description : OPTIONAL string_select;
 INVERSE
  associated_version : SET [1:?] OF item_version FOR associated_item;
  item_classification : SET [1:?] OF specific_item_classification FOR associated_item;
 END_ENTITY;

 ENTITY item_version;
(*
UOF:S1
*)
  id : UNDEFINED_OBJECT;
  associated_item : item;
  description : OPTIONAL string_select;
 INVERSE
  associated_product : SET [0:1] OF product_design FOR design;
 END_ENTITY;

 ENTITY design_discipline_item_definition;
(*
UOF:S1
*)
  name : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
  associated_item_version : item_version;
  additional_context : SET [0:?] OF application_context;
  initial_context : application_context;
 END_ENTITY;

(* use geometric_representation_context instead
 ENTITY cartesian_coordinate_space
  ABSTRACT SUPERTYPE OF ( ONEOF(cartesian_coordinate_space_2d,cartesian_coordinate_space_3d) );
  unit_of_values : OPTIONAL SET [2:?] OF unit;
 END_ENTITY;
*)


 ENTITY general_classification;
(*
UOF:S6
*)
  classification_source : OPTIONAL class_source_select;
  used_classification_system : OPTIONAL classification_system;
  description : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_classification_hierarchy;
(*
UOF:S6
*)
  super_classification : general_classification;
  sub_classification : general_classification;
 END_ENTITY;

 ENTITY specific_item_classification;
(*
UOF:S1,S6
*)
  associated_item : SET [1:?] OF item;
  classification_name : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY accuracy;
(*
UOF:S2,E1
*)
  accuracy_value : UNDEFINED_OBJECT;
  accuracy_type : UNDEFINED_OBJECT;
  is_defined_for : SET [1:?] OF accuracy_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY activity;
(*
UOF:S5
*)
  activity_type : UNDEFINED_OBJECT;
  id : UNDEFINED_OBJECT;
  status : OPTIONAL UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  resolved_request : SET [0:?] OF work_request;
  concerned_organization : SET [0:?] OF organization;
  supplying_organization : SET [0:?] OF organization;
  requestor : OPTIONAL date_and_person_organization;
  actual_end_date : OPTIONAL date_time;
  planned_end_date : OPTIONAL period_or_date_select;
  planned_start_date : OPTIONAL event_or_date_select;
  actual_start_date : OPTIONAL date_time;
  internal : OPTIONAL BOOLEAN;
  chosen_method : OPTIONAL activity_method;
 INVERSE
  authorization : SET [0:1] OF work_order FOR is_controlling;
  associated_project : SET [0:1] OF project FOR work_program;
 END_ENTITY;

 ENTITY activity_relationship;
(*
UOF:S5
*)
  related : activity;
  relating : activity;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY approval;
(*
UOF:S1
*)
  status : approval_status;
  is_applied_to : SET [1:?] OF approval_element_select;
  is_approved_by : SET [0:?] OF date_and_person_organization;
  planned_date : OPTIONAL date_time;
  actual_date : OPTIONAL date_time;
  scope : SET [0:?] OF organization;
  level : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

(* use person_organization_schema.organization instead
 ENTITY organization;

-- UOF:S1

  organization_name : UNDEFINED_OBJECT;
  visitor_address : OPTIONAL UNDEFINED_OBJECT;
  organization_type : OPTIONAL UNDEFINED_OBJECT;
  id : UNDEFINED_OBJECT;
  delivery_address : OPTIONAL UNDEFINED_OBJECT;
  postal_address : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;
*)

 ENTITY date_and_person_organization;
(*
UOF:S1
*)
  person_or_organization : person_organization_select;
  actual_date : date_time;
 END_ENTITY;

 ENTITY contract;
(*
UOF:S1
*)
  id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  contracted_element : SET [0:?] OF contracted_element_select;
 INVERSE
  release : SET [0:?] OF organization_in_contract FOR signed_contract;
 END_ENTITY;

(* use geometrically_bounded_wireframe_shape_representation instead
 ENTITY wireframe_model_3d
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF curve_set_3d;
 END_ENTITY;
*)

(* use manifold_surface_shape_representation instead
 ENTITY surface_model
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF shell;
 END_ENTITY;
*)

(* use faceted_brep_shape_representation instead
 ENTITY faceted_b_rep_model
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF faceted_b_rep;
 END_ENTITY;
*)

(* use advanced_brep_shape_representation instead
 ENTITY b_rep_model
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF b_rep;
 END_ENTITY;
*)

(* use csg_shape_representation instead
 ENTITY csg_model
  SUBTYPE OF (
   geometric_model
  );
  tree_root_expression : SET [0:?] OF csg_select;
 END_ENTITY;
*)

(* use Compound_shape_representation or edge_based_wieframe_shape_representation or non_manifold_surface_shape_representation instead
 ENTITY compound_model
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF topologically_connected_set;
 END_ENTITY;
*)

(* use geometrically_bounded_2d_wireframe_representation instead
 ENTITY wireframe_model_2d
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF curve_set_2d;
 END_ENTITY;
*)

(* use compound_representation_item instead
 ENTITY point_direction_sequence
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:MD1
*
  element : LIST [1:?] OF point_direction_element_select;
 END_ENTITY;
*)

(* use axis1_placement instead
 ENTITY point_direction
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:MD1
*
  location : cartesian_point;
  vector : UNDEFINED_OBJECT;
 END_ENTITY;
*)

(* use 0ffset_curve_2d, offset_curve_3d instead
 ENTITY offset_curve
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G8
*
 END_ENTITY;

 ENTITY curve_on_surface
  SUBTYPE OF (
   curve
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY composite_curve
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G8
*
 END_ENTITY;

-- use aim instead
 ENTITY trimmed_curve
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G8
*
 END_ENTITY;

 ENTITY polyline
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G5,G6,G7,G8
*
 END_ENTITY;

 ENTITY b_spline_curve
  SUBTYPE OF (
   curve
  );

-- UOF:G1,G2,G3,G5,G6,G7,G8

 END_ENTITY;

 ENTITY line
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY face
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G3,G5,G6,G7
*
  bound : SET [1:?] OF face_bound;
  face_geometry : surface;
 END_ENTITY;
*)

(* use aim instead
 ENTITY vertex_loop;
*
UOF:G3,G5,G6,G7
*
  loop_vertex : vertex_point;
 END_ENTITY;
*)

(* use aim instead
 ENTITY edge_loop;
*
UOF:G3,G5,G6,G7
*
  edge : LIST [1:?] OF oriented_edge_curve;
 END_ENTITY;
*)

(* use select type instead
 ENTITY oriented_edge_curve;
*
UOF:G3,G5,G6,G7
*
  edge_start : vertex_point;
  edge_end : vertex_point;
  edge_geometry : topologically_bounded_curve_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY vertex_point;
*
UOF:G3,G5,G6,G7
*
  vertex_geometry : point;
 END_ENTITY;
*)

(* use aim instead
 ENTITY face_transition;
*
UOF:G3,G5,G6,G7
*
  edge_joint : oriented_edge_curve;
  face_2 : face;
  face_1 : face;
  transition : UNDEFINED_OBJECT;
 END_ENTITY;
*)

(* use aim instead
 ENTITY offset_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G6,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY b_spline_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY plane
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G4,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY conical_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY cylindrical_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY toroidal_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY spherical_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY surface_of_linear_extrusion
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY surface_of_revolution
  SUBTYPE OF (
   surface
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use shape_aspect_transition instead
 ENTITY edge_transition;
*
UOF:G3,G5,G6,G7
*
  edge_1 : oriented_edge_curve;
  edge_2 : oriented_edge_curve;
  transition : UNDEFINED_OBJECT;
  vertex_joint : vertex_point;
 END_ENTITY;
*)

(* use closed_shell instead
 ENTITY faceted_closed_shell;
*
UOF:G4,G7
*
  shell_boundary : SET [4:?] OF faceted_face;
 END_ENTITY;
*)

(* use face_surface instead
 ENTITY faceted_face;
*
UOF:G4,G7
*
  face_geometry : plane;
  bound : SET [1:?] OF poly_loop;
 END_ENTITY;
*)

(* use aim instead
 ENTITY poly_loop;
*
UOF:G4,G7
*
  polygon : LIST [3:?] OF cartesian_point;
  outer : BOOLEAN;
 INVERSE
  is_bound_for : SET [1:1] OF faceted_face FOR bound;
 END_ENTITY;
*)

(* use aim instead
 ENTITY closed_shell;
*
UOF:G5,G7
*
  shell_boundary : SET [1:?] OF face;
 END_ENTITY;
*)

(* use aim instead
 ENTITY sphere
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;

 ENTITY block
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;
-- use aim Right_angular_wedge instead
 ENTITY right_angular_wedge
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;

-- use aim instead
 ENTITY torus
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;
-- use aim Right_circular_cone instead
 ENTITY right_circular_cone
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;
-- use aim Right_circular_cylinder instead
 ENTITY right_circular_cylinder
  SUBTYPE OF (
   csg_primitive_arm
  );
*
UOF:G7
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY solid_replica
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G7
*
  replicated_solid : csg_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY swept_face_solid
  ABSTRACT SUPERTYPE OF ( ONEOF(solid_of_revolution,solid_of_linear_extrusion) )
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G7
*
  swept_face : face;
 END_ENTITY;
*)

(* use revolved_face_solid instead
 ENTITY solid_of_revolution
  SUBTYPE OF (
   swept_face_solid
  );
*
UOF:G7
*
 END_ENTITY;
*)
(* use extruded_face_solid instead
 ENTITY solid_of_linear_extrusion
  SUBTYPE OF (
   swept_face_solid
  );
*
UOF:G7
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY boolean_result
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G7
*
  first_operand : boolean_operand_select;
  second_operand : boolean_operand_select;
  boolean_operation : UNDEFINED_OBJECT;
 END_ENTITY;
*)

(* use aim instead
 ENTITY half_space_solid
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G7
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY circle
  SUBTYPE OF (
   curve
  );

-- UOF:G1,G2,G3,G5,G6,G7,G8

 END_ENTITY;
 ENTITY ellipse
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G5,G6,G7,G8
*
 END_ENTITY;

 ENTITY hyperbola
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G5,G6,G7,G8
*
 END_ENTITY;

 ENTITY parabola
  SUBTYPE OF (
   curve
  );
*
UOF:G1,G2,G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* added by JB
*)
 ENTITY kinematic_element_association;
(*
UOF:K1
*)
  is_defining_kinematic_element_for : simulation_context_select;
  defining_kinematic_element : kinematic_link;
  role : undefined_object;
 END_ENTITY;

 ENTITY kinematic_mechanism;
(*
UOF:K1
*)
  structure_definition : kinematic_structure;
  base_link : kinematic_link;
  base_placement : cartesian_transformation_operator_3d;
(* base_placement : transformation_to_reference_frame; *)
 INVERSE
  is_referenced_by : SET [1:?] OF kinematic_simulation_information FOR mechanism;
 END_ENTITY;

 ENTITY kinematic_structure
  SUBTYPE OF (
   kinematic_element
  );
(*
UOF:K1
*)
  joint : SET [1:?] OF kinematic_joint;
 INVERSE
  is_referenced_by : SET [1:1] OF kinematic_mechanism FOR structure_definition;
 END_ENTITY;

(*
 ENTITY kinematic_joint
  SUBTYPE OF (
   kinematic_element
  );
  first_link : kinematic_link;
  second_link : kinematic_link;
  pair : kinematic_pair;
 INVERSE
  is_referenced_by : SET [1:?] OF kinematic_structure FOR joint;
 END_ENTITY;

 ENTITY kinematic_link
  SUBTYPE OF (
   kinematic_element
  );
  representation : kinematic_link_representation;
 END_ENTITY;
*)

 ENTITY ground_representation;
(*
UOF:K1
*)
  shape_description : shape_representation;
 INVERSE
  is_referenced_by : SET [1:?] OF kinematic_simulation_information FOR ground;
 END_ENTITY;

(*
UOF:K1
*)
(*
 ENTITY kinematic_pair
  SUBTYPE OF (
  	kinematic_element
  	);
  	transformation_item_1: axis2_placement_3d;
  	transformation_item_2: axis2_placement_3d;
  	pair_type: undefined_object;
 INVERSE
 	is_referenced_by: SET [0:1] OF actuator FOR is_applied_to;
	joint: SET [1:1] OF kinematic_joint FOR pair;
END_ENTITY; -- kinematic_pair
*)

 ENTITY simple_pair_range;
(*
UOF:K1
*)
  is_applied_to : kinematic_pair;
 END_ENTITY;

(*
UOF:K1, removed from ARM, used kinematic_structure_schema

 ENTITY kinematic_link_representation;
  additional_reference_frame : SET [0:?] OF transformation_to_reference_frame;
  physical_description : shape_representation;
 END_ENTITY;
*)

(*
UOF:K1, removed from ARM, used kinematic_structure_schema

 ENTITY pair_value;
  is_applied_to : kinematic_pair;
 END_ENTITY;
*)

 ENTITY initial_configuration;
(*
UOF:K1
*)
  initial_pair_values : SET [1:?] OF pair_value;
  is_applied_to : kinematic_mechanism;
 END_ENTITY;

 ENTITY transformation_to_reference_frame
  SUPERTYPE OF ( ONEOF(tool_attachment_point_frame,tool_centre_point_frame) );
(*
UOF:K1
*)
 END_ENTITY;

 ENTITY tool_attachment_point_frame
  SUBTYPE OF (
   transformation_to_reference_frame
  );
(*
UOF:K1
*)
 END_ENTITY;

 ENTITY tool_centre_point_frame
  SUBTYPE OF (
   transformation_to_reference_frame
  );
(*
UOF:K1
*)
 END_ENTITY;

 ENTITY digital_document
  SUBTYPE OF (
   document_representation
  );
(*
UOF:E1
*)
  file : SET [0:?] OF digital_file;
 END_ENTITY;

 ENTITY physical_model
  SUBTYPE OF (
   physical_representation
  );
(*
UOF:E1
*)
 END_ENTITY;

 ENTITY physical_document
  SUBTYPE OF (
   physical_representation
  );
(*
UOF:E1
*)
  component : SET [0:?] OF hardcopy;
 END_ENTITY;

 ENTITY recyclability_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
 END_ENTITY;

 ENTITY material_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
  property_name : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY mass_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
 END_ENTITY;

 ENTITY centre_of_mass
  SUBTYPE OF (
   shape_dependent_property
  );
(*
UOF:PR1
*)
  centre_point : point;
  SELF\shape_dependent_property.is_defined_in : geometric_representation_context;
 END_ENTITY;

 ENTITY moments_of_inertia
  SUBTYPE OF (
   shape_dependent_property
  );
(*
UOF:PR1
*)
  inertia_value : ARRAY [1:3] OF ARRAY [1:3] OF numerical_value;
  reference_axis_placement : placement;
  SELF\shape_dependent_property.is_defined_in : geometric_representation_context;
 END_ENTITY;

 ENTITY surface_condition
  ABSTRACT SUPERTYPE OF ( ONEOF(contact_ratio,hardness,tactile_appearance,treatment_result,visual_appearance,surface_texture) );
(*
UOF:C1
*)
  value_determination : OPTIONAL UNDEFINED_OBJECT;
  is_caused_by : OPTIONAL process_operation_occurrence;
 END_ENTITY;

 ENTITY coating_layer
  SUBTYPE OF (
   shape_element
  );
(*
UOF:C1
*)
  thickness : OPTIONAL thickness_dimension;
  used_material : material;
 END_ENTITY;

 ENTITY surface_texture
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)
  measuring_method : UNDEFINED_OBJECT;
  measuring_direction : OPTIONAL measurement_path;
 END_ENTITY;

 ENTITY visual_appearance
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)
  colour_id : UNDEFINED_OBJECT;
  lustre : UNDEFINED_OBJECT;
  transparency : OPTIONAL UNDEFINED_OBJECT;
  id : OPTIONAL UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  pattern : OPTIONAL UNDEFINED_OBJECT;
  colour_name : OPTIONAL string_select;
 END_ENTITY;

 ENTITY hardness
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)
  measuring_method : UNDEFINED_OBJECT;
  environment_condition : SET [0:?] OF UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  measuring_position : OPTIONAL UNDEFINED_OBJECT;
  hardness_value : value_with_unit;
  depth : OPTIONAL value_with_unit;
 END_ENTITY;

 ENTITY project;
(*
UOF:S5
*)
  id : UNDEFINED_OBJECT;
  name : string_select;
  description : OPTIONAL string_select;
  actual_start_date : OPTIONAL date_time;
  actual_end_date : OPTIONAL date_time;
  planned_start_date : OPTIONAL event_or_date_select;
  is_applied_to : SET [0:?] OF project_information_select;
  work_program : SET [0:?] OF activity;
  planned_end_date : OPTIONAL period_or_date_select;
 END_ENTITY;

 ENTITY appearance_assignment;
(*
UOF:P1
*)
  component : SET [1:?] OF appearance_select;
 END_ENTITY;

 (* use aim instead of
 ENTITY light_source;

-- UOF:P3
  colour : OPTIONAL UNDEFINED_OBJECT;
  light_type : UNDEFINED_OBJECT;
  is_defined_for : SET [1:?] OF camera_image;
 END_ENTITY;
 *)

 ENTITY hidden_element_handling;
(*
UOF:P3,P1
*)
  is_defined_for : SET [1:?] OF camera_image;
  switch : active_or_inactive;
  hidden_element_appearance : OPTIONAL appearance_assignment;
 END_ENTITY;

 ENTITY vector_appearance
  SUBTYPE OF (
   curve_appearance
  );
(*
UOF:P1
*)
  arrow_head_type : terminator_symbol;
 END_ENTITY;

 ENTITY point_appearance;
(*
UOF:P1
*)
  marker : point_marker_symbol;
  colour : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY curve_appearance;
(*
UOF:P1
*)
  width : UNDEFINED_OBJECT;
  colour : UNDEFINED_OBJECT;
  font : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY surface_appearance;
(*
UOF:P1
*)
  side : UNDEFINED_OBJECT;
  element : SET [1:?] OF surface_appearance_element;
 END_ENTITY;

 ENTITY text_appearance;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY surface_appearance_element;
(*
UOF:P1
*)
  presented_surface_condition : OPTIONAL visual_appearance;
 END_ENTITY;

 ENTITY hatching;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY tiling;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY solid_fill_area;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY geometric_dimension
  ABSTRACT SUPERTYPE OF ( ONEOF(size_dimension,location_dimension) );
(*
UOF:T1
*)
  dimension_value : value_with_unit;
  id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY geometric_tolerance
  ABSTRACT SUPERTYPE OF ( ONEOF(line_profile_tolerance,flatness_tolerance,surface_profile_tolerance,total_runout_tolerance,straightness_tolerance,circular_runout_tolerance,symmetry_tolerance,position_tolerance,perpendicularity_tolerance,parallelism_tolerance,concentricity_tolerance,angularity_tolerance,cylindricity_tolerance,coaxiality_tolerance,roundness_tolerance) );
(*
UOF:T2
*)
  value_determination : OPTIONAL UNDEFINED_OBJECT;
  tolerance_value : UNDEFINED_OBJECT;
  is_applied_to : placed_element_select;
  modification : OPTIONAL tolerance_condition;
  qualifying_note : OPTIONAL string_select;
  name : OPTIONAL string_select;
  significant_digits : OPTIONAL UNDEFINED_OBJECT;
  segment_size : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY limits_and_fits;
(*
UOF:T1
*)
  deviation : UNDEFINED_OBJECT;
  grade : UNDEFINED_OBJECT;
  fitting_type : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_plan;
(*
UOF:S8
*)
  plan_id : UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  produced_output : OPTIONAL SET [1:?] OF item_version;
 END_ENTITY;

 ENTITY process_operation_occurrence;
(*
UOF:S8
*)
  plan : process_plan;
  is_defined_in : OPTIONAL geometric_representation_context;
  operation_definition : process_operation_definition;
  id : UNDEFINED_OBJECT;
 END_ENTITY;

(* use annotation_subfigure_occurrence instead
 ENTITY annotation_subfigure
  SUBTYPE OF (
   annotation_element
  );
*
UOF:P2
*
 END_ENTITY;
*)

(* use annotation_symbol_occurrence instead
 ENTITY annotation_symbol
  SUBTYPE OF (
   annotation_element
  );
*
UOF:P2
*
  symbol_definition : symbol_definition_select;
 END_ENTITY;
*)

(* use annotation_text_occurrence instead
 ENTITY text
  SUBTYPE OF (
   annotation_element
  );
*
UOF:P2
*
 END_ENTITY;
*)

(* use annotation_fill_area_occurrence instead
 ENTITY fill_area
  SUBTYPE OF (
   annotation_element
  );
*
UOF:P2
*
  reference_point : OPTIONAL UNDEFINED_OBJECT;
  boundary : SET [1:?] OF annotation_curve_occurrence;
 END_ENTITY;
*)

(* use leader_curve instead
 ENTITY leader
  SUBTYPE OF (
   annotation_curve
  );
*
UOF:P2
*
  terminator : OPTIONAL terminator_symbol;
 END_ENTITY;
*)

(* use leader_curve instead
 ENTITY associated_leader
  SUBTYPE OF (
   leader
  );
*
UOF:D2
*
  target : associated_element_select;
 END_ENTITY;
*)

(* use projection_curve instead
 ENTITY associated_projection_curve
  SUBTYPE OF (
   projection_curve
  );
*
UOF:D2
*
  is_projected_to : associated_element_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY projection_curve
  SUBTYPE OF (
   annotation_curve
  );
*
UOF:D1
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY dimension_curve
  SUBTYPE OF (
   annotation_curve
  );
*
UOF:D1
*
  terminator : LIST [0:2] OF terminator_symbol;
 END_ENTITY;
*)

(* use type instead
 ENTITY dimension
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D1
*
  id : UNDEFINED_OBJECT;
  primary_callout : dimension_callout;
  secondary_callout : OPTIONAL dimension_callout;
 END_ENTITY;
*)

 ENTITY dimension_sequence_pair;
(*
UOF:D1
*)
  predecessor : dimension;
  successor : dimension;
 END_ENTITY;

 ENTITY same_time_machining_relationship
  SUBTYPE OF (
   item_instance_relationship
  );
(*
UOF:S8
*)
  description : OPTIONAL string_select;
  placement : OPTIONAL transformation_select;
 END_ENTITY;

 ENTITY general_tolerances;
(*
UOF:T1
*)
  table_definition : general_tolerance_table_select;
  tolerance_class : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY alternate_item_relationship;
(*
UOF:S3
*)
  fulfilled_requirements : string_select;
  base : item;
  alternate : item;
 END_ENTITY;

 ENTITY shape_element
  SUPERTYPE OF ( ONEOF(feature_occurrence,coating_layer) );
(*
UOF:S2,E1
*)
  description : OPTIONAL string_select;
  composition : item_shape;
  element_name : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY item_version_relationship;
(*
UOF:S1
*)
  relating : item_version;
  related : item_version;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY structuring_method_hierarchy;
(*
UOF:S2
*)
  relating : structuring_method_select;
  related : group;
 END_ENTITY;

 ENTITY general_feature;
(*
UOF:FF1
*)
  feature_type : UNDEFINED_OBJECT;
  feature_category : UNDEFINED_OBJECT;
  location_and_orientation : OPTIONAL placement;
  additional_parameter : SET [0:?] OF general_parameter;
 END_ENTITY;

(* use draughting_elements instead
 ENTITY draughting_callout
  SUPERTYPE OF ( associated_draughting_callout ANDOR ONEOF(surface_condition_callout,geometric_tolerance_callout,dimension,datum_target_callout,datum_feature_callout) )
  SUBTYPE OF (
   detailed_element
  );
*
UOF:P2
*
  contents : SET [1:?] OF draughting_callout_content_select;
 END_ENTITY;
*)

 ENTITY process_state
  SUBTYPE OF (
   design_discipline_item_definition
  );
(*
UOF:S8
*)
  related_item_definition : design_discipline_item_definition;
 END_ENTITY;

 ENTITY process_plan_relationship;
(*
UOF:S8
*)
  relating : process_plan;
  related : process_plan;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_operation_input_or_output;
(*
UOF:S8
*)
  role : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  operation : process_operation_occurrence;
  element : process_operation_input_or_output_select;
  placement : OPTIONAL transformation;
  concerned_shape : SET [0:?] OF shape_element;
 END_ENTITY;

 ENTITY process_operation_resource_assignment;
(*
UOF:S8
*)
  reference_tool : BOOLEAN;
  operation : process_operation_occurrence;
  reason : OPTIONAL string_select;
  resource_definition : resource_definition_select;
  placement : OPTIONAL transformation;
 END_ENTITY;

 ENTITY mated_item_association
  SUBTYPE OF (
   item_definition_instance_relationship
  );
(*
UOF:S8
*)
  SELF\item_definition_instance_relationship.relating : mating_definition;
  placement : OPTIONAL transformation_select;
 END_ENTITY;

 ENTITY tolerance_table_cell;
(*
UOF:T1
*)
  cell_value : cell_entry_select;
  tolerance_class : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  limit : limit_select;
  table : general_tolerance_table;
 END_ENTITY;

 ENTITY plus_minus_toleranced_datum;
(*
UOF:T1
*)
  tolerance_value : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY upper_lower_toleranced_datum;
(*
UOF:T1
*)
  lower_tolerance_value : UNDEFINED_OBJECT;
  upper_tolerance_value : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY default_surface_texture;
(*
UOF:C1
*)
  measuring_method : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY context_dependent_appearance_assignment
  SUBTYPE OF (
   appearance_assignment
  );
(*
UOF:P1
*)
  appearance_context : appearance_context_select;
 END_ENTITY;

 ENTITY view_relationship;
(*
UOF:P2
*)
  related : presentation_view;
  relating : presentation_view;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

(*
 ENTITY view;
  id : OPTIONAL UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  view_space : geometric_representation_context;
  view_placement : transformation_2d;
  name : string_select;
  layout : area_select;
 INVERSE
  image : SET [0:1] OF camera_image FOR is_presented_in;
 END_ENTITY;
*)

 ENTITY view_area_relationship;
(*
UOF:P2
*)
  related : view_area;
  relating : view_area;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

(* use geometrically_bounded_surface_shape_representation instead
 ENTITY geometrically_bounded_surface_model
  SUBTYPE OF (
   geometric_model
  );
  element : SET [0:?] OF geometric_set_3d;
 END_ENTITY;
*)

 ENTITY tactile_appearance
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)
  id : OPTIONAL UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  depth : OPTIONAL value_with_unit;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY treatment_result
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)
  id : OPTIONAL UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : string_select;
  purpose : OPTIONAL string_select;
 END_ENTITY;

 ENTITY actuator;
(*
UOF:K1
*)
  name : string_select;
  is_applied_to : kinematic_pair;
 END_ENTITY;

(* use person_organization_schema.person instead
 ENTITY person;
-- UOF:S1
  person_name : UNDEFINED_OBJECT;
  preferred_business_address : OPTIONAL UNDEFINED_OBJECT;
 INVERSE
  associated_organization : SET [1:?] OF person_in_organization FOR associated_person;
 END_ENTITY;
*)

 ENTITY default_setting_association;
(*
UOF:C1,FF2,T1
*)
  default_value : SET [1:?] OF default_setting_select;
  default_context : default_context_select;
 END_ENTITY;

 ENTITY model_change
  ABSTRACT SUPERTYPE OF ( ONEOF(full_model_change,incremental_model_change) );
(*
UOF:S2
*)
  id : OPTIONAL UNDEFINED_OBJECT;
  description : string_select;
  is_describing : change;
  deleted_element : SET [0:?] OF representation_item;
 END_ENTITY;

 ENTITY property
  ABSTRACT SUPERTYPE OF ( ONEOF(cost_property,quality_property,duration_property,material_property,general_property,recyclability_property,mass_property) );
(*
UOF:PR1
*)
  allowed_unit : SET [0:?] OF unit;
  description : OPTIONAL string_select;
  property_source : OPTIONAL property_source_select;
  id : UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document;
(*
UOF:E1
*)
  description : OPTIONAL string_select;
  name : string_select;
  document_id : UNDEFINED_OBJECT;
 INVERSE
  associated_version : SET [1:?] OF document_version FOR associated_document;
 END_ENTITY;

 ENTITY material;
(*
UOF:PR1
*)
  material_name : UNDEFINED_OBJECT;
  described_element : SET [1:?] OF item_property_select;
 END_ENTITY;

 ENTITY project_relationship;
(*
UOF:S5
*)
  related : project;
  relating : project;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY compound_feature_in_solid
  ABSTRACT SUPERTYPE OF ( ONEOF(compound_hole,general_compound_feature_in_solid) )
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  feature_type : OPTIONAL UNDEFINED_OBJECT;
 INVERSE
  element : SET [2:?] OF compound_feature_in_solid_element FOR is_element_for;
 END_ENTITY;

 ENTITY round_hole
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  taper : OPTIONAL taper_select;
  hole_depth : linear_path;
  diameter : closed_profile_usage;
  bottom_condition : hole_bottom_condition_select;
 END_ENTITY;

 ENTITY angle_taper;
(*
UOF:FF2
*)
  angle : feature_parameter;
 END_ENTITY;

 ENTITY diameter_taper;
(*
UOF:FF2
*)
  final_diameter : feature_parameter;
 END_ENTITY;

 ENTITY boss_feature
  ABSTRACT SUPERTYPE OF ( ONEOF(general_boss,circular_boss,rectangular_boss) )
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  base_radius : OPTIONAL feature_parameter;
  boss_height : linear_path;
  top_condition : boss_top_condition;
  taper : OPTIONAL taper_select;
  boundary : closed_profile_usage;
 END_ENTITY;

 ENTITY circular_boss
  SUBTYPE OF (
   boss_feature
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY general_boss
  SUBTYPE OF (
   boss_feature
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY pocket_feature
  ABSTRACT SUPERTYPE OF ( ONEOF(general_pocket,rectangular_closed_pocket,rectangular_open_pocket) )
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  boundary : profile_usage;
  pocket_depth : linear_path;
  bottom_condition : pocket_bottom_condition_select;
  base_radius : OPTIONAL feature_parameter;
  taper : OPTIONAL taper_select;
 END_ENTITY;

 ENTITY rectangular_closed_pocket
  SUBTYPE OF (
   pocket_feature
  );
(*
UOF:FF2
*)
  SELF\pocket_feature.boundary : closed_profile_usage;
 END_ENTITY;

 ENTITY general_pocket
  SUBTYPE OF (
   pocket_feature
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY planar_bottom_condition
  SUBTYPE OF (
   pocket_bottom_condition
  );
(*
UOF:FF2
*)
  floor_normal : UNDEFINED_OBJECT;
  floor_radius : OPTIONAL feature_parameter;
  floor_location : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_bottom_condition
  SUBTYPE OF (
   pocket_bottom_condition
  );
(*
UOF:FF2
*)
  floor_face : general_end_select;
  floor_radius : OPTIONAL feature_parameter;
 END_ENTITY;

(* use aim instead
 ENTITY transition_feature
  ABSTRACT SUPERTYPE OF ( ONEOF(fillet,chamfer,edge_round) );
*
UOF:FF2
*
  face_1 : face;
  face_2 : face;
 END_ENTITY;
*)

(* use aim instead
 ENTITY fillet
  SUBTYPE OF (
   transition_feature
  );
*
UOF:FF2
*
  fillet_face : face;
 END_ENTITY;
*)

(* use aim instead
 ENTITY chamfer
  SUBTYPE OF (
   transition_feature
  );
*
UOF:FF2
*
  is_defined_by : chamfer_definition;
  chamfer_face : face;
 END_ENTITY;
*)

 ENTITY slot_feature
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  slot_profile : open_profile_usage;
  sweep_path : path;
  end_condition : SET [2:2] OF slot_end_type;
 END_ENTITY;

 ENTITY woodruff_slot_end_type
  SUBTYPE OF (
   slot_end_type
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
 END_ENTITY;

 ENTITY flat_slot_end_type
  SUBTYPE OF (
   slot_end_type
  );
(*
UOF:FF2
*)
  first_radius : feature_parameter;
  second_radius : feature_parameter;
 END_ENTITY;

 ENTITY radiused_slot_end_type
  SUBTYPE OF (
   slot_end_type
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY open_slot_end_type
  SUBTYPE OF (
   slot_end_type
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY circular_pattern
  SUBTYPE OF (
   replicate_feature
  );
(*
UOF:FF2
*)
  number_of_features : UNDEFINED_OBJECT;
  relocated_feature : SET [0:?] OF circular_offset_pattern;
  missing_feature : SET [0:?] OF circular_omit_pattern;
  diameter : OPTIONAL feature_parameter;
  angular_spacing : feature_parameter;
  rotation : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY circular_offset_pattern;
(*
UOF:FF2
*)
  index : UNDEFINED_OBJECT;
  angular_offset : UNDEFINED_OBJECT;
 INVERSE
  base_feature : SET [1:?] OF circular_pattern FOR relocated_feature;
 END_ENTITY;

 ENTITY circular_omit_pattern;
(*
UOF:FF2
*)
  index : UNDEFINED_OBJECT;
 INVERSE
  base_feature : SET [1:?] OF circular_pattern FOR missing_feature;
 END_ENTITY;

 ENTITY rectangular_pattern
  SUBTYPE OF (
   replicate_feature
  );
(*
UOF:FF2
*)
  rows : UNDEFINED_OBJECT;
  columns : UNDEFINED_OBJECT;
  row_layout_direction : UNDEFINED_OBJECT;
  column_layout_direction : UNDEFINED_OBJECT;
  relocated_feature : SET [0:?] OF rectangular_offset_pattern;
  missing_feature : SET [0:?] OF rectangular_omit_pattern;
  row_spacing : feature_parameter;
  column_spacing : feature_parameter;
 END_ENTITY;

 ENTITY rectangular_offset_pattern;
(*
UOF:FF2
*)
  offset_direction : UNDEFINED_OBJECT;
  column_index : UNDEFINED_OBJECT;
  row_index : UNDEFINED_OBJECT;
  offset_distance : feature_parameter;
 INVERSE
  base_feature : SET [1:?] OF rectangular_pattern FOR relocated_feature;
 END_ENTITY;

 ENTITY rectangular_omit_pattern;
(*
UOF:FF2
*)
  row_index : UNDEFINED_OBJECT;
  column_index : UNDEFINED_OBJECT;
 INVERSE
  base_feature : SET [1:?] OF rectangular_pattern FOR missing_feature;
 END_ENTITY;

 ENTITY dimension_callout;
(*
UOF:D1
*)
  callout_element : SET [1:?] OF dimension_callout_select;
  is_displaying : OPTIONAL geometric_dimension;
 END_ENTITY;

 ENTITY activity_method;
(*
UOF:S5
*)
  description : string_select;
  consequence : OPTIONAL UNDEFINED_OBJECT;
  name : string_select;
 END_ENTITY;

 ENTITY work_request;
(*
UOF:S5
*)
  id : UNDEFINED_OBJECT;
  request_type : UNDEFINED_OBJECT;
  status : UNDEFINED_OBJECT;
  notified_person : SET [1:?] OF date_and_person_organization;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  requestor : date_and_person_organization;
  scope : SET [0:?] OF activity_element_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY included_feature
  SUBTYPE OF (
   feature_occurrence
  );
(*
UOF:FF1
*)
  definition : feature_definition_select;
 END_ENTITY;

 ENTITY classification_attribute;
(*
UOF:S6
*)
  id : UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  allowed_value : SET [0:?] OF property_value_representation;
  attribute_definition : property;
  associated_classification : general_classification;
 END_ENTITY;

 ENTITY kinematic_configuration_definition;
(*
UOF:K1
*)
  t_parameter : path_approximation;
  pair_values : SET [1:?] OF pair_value;
 END_ENTITY;

 ENTITY kinematic_configuration_interpolation;
(*
UOF:K1
*)
  next_definition : kinematic_configuration_definition;
  previous_definition : kinematic_configuration_definition;
  interpolation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY interpolated_configuration_sequence;
(*
UOF:K1
*)
  interpolation : SET [1:?] OF kinematic_configuration_interpolation;
 END_ENTITY;

 ENTITY kinematic_transformation_result;
(*
UOF:K1
*)
  result : SET [1:?] OF interpolated_configuration_sequence;
  is_applied_to : kinematic_mechanism;
 END_ENTITY;

 ENTITY path_approximation;
(*
UOF:K1
*)
 END_ENTITY;

 ENTITY organization_relationship;
(*
UOF:S5
*)
  related : organization;
  relating : organization;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY make_from_relationship
  SUBTYPE OF (
   item_definition_relationship
  );
(*
UOF:S3,S8
*)
  description : OPTIONAL string_select;
 END_ENTITY;

(* use Point_placement_shape_representation instead
 ENTITY point_direction_model
  SUBTYPE OF (
   geometric_model
  );
  point_direction_elements : SET [0:?] OF point_direction_sequence;
  point_elements : SET [0:?] OF point_sequence;
 END_ENTITY;
*)

 ENTITY general_parameter;
(*
UOF:S1
*)
  parameter_role : UNDEFINED_OBJECT;
  parameter_value : feature_parameter;
 END_ENTITY;

 ENTITY feature_parameter;
(*
UOF:S1
*)
  parameter_name : OPTIONAL UNDEFINED_OBJECT;
  parameter_value : value_with_unit;
 END_ENTITY;

 ENTITY thread_specification
  ABSTRACT SUPERTYPE OF ( ONEOF(defined_thread,catalogue_thread) );
(*
UOF:FF2
*)
  form_type : UNDEFINED_OBJECT;
  hand : UNDEFINED_OBJECT;
  fit_class : UNDEFINED_OBJECT;
  major_diameter : feature_parameter;
  density : feature_parameter;
  inner : BOOLEAN;
  qualifier : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY rib_feature
  SUBTYPE OF (
   process_feature_in_solid
  );
(*
UOF:FF2
*)
  fillet_radius : OPTIONAL feature_parameter;
  shoulder_radius : OPTIONAL feature_parameter;
  rib_profile : open_profile_usage;
  sweep_path : path;
  draft_taper : OPTIONAL directed_taper;
 END_ENTITY;

 ENTITY bead_feature
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  bead_profile : open_profile_usage;
  sweep_path : path;
  base_radius : OPTIONAL feature_parameter;
  end_condition : SET [2:2] OF bead_end_type;
 END_ENTITY;

 ENTITY descriptive_specification;
(*
UOF:S7,S8
*)
  description : string_select;
  id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY organization_in_contract;
(*
UOF:S1
*)
  role_of_organization : UNDEFINED_OBJECT;
  contracted_organization : organization;
  signature : SET [0:?] OF date_and_person_organization;
  signed_contract : SET [1:?] OF contract;
 END_ENTITY;

 ENTITY general_compound_feature
  SUBTYPE OF (
   general_feature
  );
(*
UOF:FF1
*)
  elements : SET [2:?] OF feature_definition_select;
 END_ENTITY;

 ENTITY group_relationship;
(*
UOF:S2
*)
  related : group;
  relating : group;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY process_feature_in_solid
  ABSTRACT SUPERTYPE OF ( ONEOF(pocket_feature,rib_feature,round_hole,compound_feature_in_solid,boss_feature,slot_feature) )
  SUBTYPE OF (
   feature_definition
  );
(*
UOF:FF2
*)
  SELF\feature_definition.location_and_orientation : placement;
 END_ENTITY;

 ENTITY compound_feature_in_solid_element;
(*
UOF:FF2
*)
  is_element_for : compound_feature_in_solid;
  feature : compound_in_solid_select;
  element_placement : OPTIONAL transformation;
 END_ENTITY;

(* use aim instead
 ENTITY edge_round
  SUBTYPE OF (
   transition_feature
  );
*
UOF:FF2
*
  edge_round_face : face;
 END_ENTITY;
*)

 ENTITY through_pocket_bottom_condition;
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY profile
  ABSTRACT SUPERTYPE OF ( ONEOF(closed_profile,open_profile) );
(*
UOF:FF2
*)
  is_defined_in : geometric_representation_context;
  location_and_orientation : placement;
 END_ENTITY;

 ENTITY closed_profile
  ABSTRACT SUPERTYPE OF ( ONEOF(circular_closed_profile,ngon_profile,rectangular_closed_profile,general_closed_profile) )
  SUBTYPE OF (
   profile
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY open_profile
  ABSTRACT SUPERTYPE OF ( ONEOF(tee_profile,partial_circular_profile,general_open_profile,vee_profile,rounded_u_profile,square_u_profile) )
  SUBTYPE OF (
   profile
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY circular_closed_profile
  SUBTYPE OF (
   closed_profile
  );
(*
UOF:FF2
*)
  diameter : feature_parameter;
 END_ENTITY;

 ENTITY ngon_profile
  SUBTYPE OF (
   closed_profile
  );
(*
UOF:FF2
*)
  diameter : feature_parameter;
  corner_radius : OPTIONAL feature_parameter;
  number_of_sides : UNDEFINED_OBJECT;
  circumscribed_or_across_flats : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY rectangular_closed_profile
  SUBTYPE OF (
   closed_profile
  );
(*
UOF:FF2
*)
  profile_width : feature_parameter;
  profile_length : feature_parameter;
  corner_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY general_closed_profile
  SUBTYPE OF (
   closed_profile
  );
(*
UOF:FF2
*)
  profile_shape : curve;
 END_ENTITY;

 ENTITY square_u_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  width : feature_parameter;
  first_angle : feature_parameter;
  second_angle : feature_parameter;
  first_radius : OPTIONAL feature_parameter;
  second_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY partial_circular_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  sweep_angle : feature_parameter;
  radius : feature_parameter;
 END_ENTITY;

 ENTITY rounded_u_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  width : feature_parameter;
 END_ENTITY;

 ENTITY vee_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  tilt_angle : feature_parameter;
  profile_angle : feature_parameter;
  radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY tee_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  first_offset : feature_parameter;
  second_offset : feature_parameter;
  first_angle : feature_parameter;
  second_angle : feature_parameter;
  depth : feature_parameter;
  width : feature_parameter;
  cross_bar_depth : feature_parameter;
  cross_bar_width : feature_parameter;
  radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY general_open_profile
  SUBTYPE OF (
   open_profile
  );
(*
UOF:FF2
*)
  profile_shape : curve;
 END_ENTITY;

 ENTITY general_pattern
  SUBTYPE OF (
   replicate_feature
  );
(*
UOF:FF2
*)
  added_instance : SET [1:?] OF placement;
 END_ENTITY;

(* use placement instead
 ENTITY axis_placement;
*
UOF:S2,E1
*
 END_ENTITY;
*)

 ENTITY catalogue_thread
  SUBTYPE OF (
   thread_specification
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY defined_thread
  SUBTYPE OF (
   thread_specification
  );
(*
UOF:FF2
*)
  crest : OPTIONAL feature_parameter;
  minor_diameter : OPTIONAL feature_parameter;
  pitch_diameter : feature_parameter;
 END_ENTITY;

 ENTITY product_class_relationship;
(*
UOF:S7
*)
  relating : product_class;
  related : product_class;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY class_specification_association;
(*
UOF:S7
*)
  associated_product_class : product_class;
  association_type : UNDEFINED_OBJECT;
  associated_specification : specification;
 END_ENTITY;

 ENTITY class_condition_association;
(*
UOF:S7
*)
  condition_type : UNDEFINED_OBJECT;
  associated_product_class : product_class;
  description : OPTIONAL string_select;
  associated_condition : specification_expression;
 END_ENTITY;

 ENTITY specification;
(*
UOF:S7
*)
  id : UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  category : specification_category;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  package : BOOLEAN;
 END_ENTITY;

 ENTITY configuration;
(*
UOF:S7
*)
  configured_element : configured_item_select;
  is_solution_for : configured_specification_select;
  configuration_type : UNDEFINED_OBJECT;
  inheritance_type : UNDEFINED_OBJECT;
 END_ENTITY;

(* use annotation_fill_area_occurrence instead
 ENTITY associated_fill_area
  SUBTYPE OF (
   fill_area
  );
*
UOF:D2
*
  is_derived_from : SET [1:?] OF fill_area_associated_element_select;
 END_ENTITY;
*)

 ENTITY effectivity;
(*
UOF:S4
*)
  concerned_organization : SET [0:?] OF organization;
  description : OPTIONAL string_select;
  id : OPTIONAL UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  effectivity_context : OPTIONAL UNDEFINED_OBJECT;
  period : OPTIONAL time_measure_with_unit;
  start_definition : OPTIONAL event_or_date_select;
  end_definition : OPTIONAL event_or_date_select;
 END_ENTITY;

 ENTITY significant_number_of_digits;
(*
UOF:T1
*)
  number_of_digits : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY upper_lower_limit;
(*
UOF:T1
*)
  upper_limit : UNDEFINED_OBJECT;
  lower_limit : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_tolerance_table;
(*
UOF:T1
*)
  tolerance_type : UNDEFINED_OBJECT;
 INVERSE
  cell : SET [1:?] OF tolerance_table_cell FOR table;
 END_ENTITY;

(* use compound_representation_item  instead
 ENTITY point_sequence
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:MD1
*
  element : LIST [1:?] OF cartesian_point;
 END_ENTITY;
*)

 ENTITY compound_feature_in_solid_element_relationship;
(*
UOF:FF2
*)
  predecessor : compound_feature_in_solid_element;
  successor : compound_feature_in_solid_element;
 END_ENTITY;

 ENTITY process_feature_in_panel
  ABSTRACT SUPERTYPE OF ( ONEOF(form_feature_in_panel,bead_feature,hole_feature_in_panel,compound_feature_in_panel,joggle_feature,locator_feature) )
  SUBTYPE OF (
   feature_definition
  );
(*
UOF:FF2
*)
  punch_direction : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY circular_path
  ABSTRACT SUPERTYPE OF ( ONEOF(partial_circular_path,complete_circular_path) )
  SUBTYPE OF (
   path
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
 END_ENTITY;

 ENTITY linear_path
  SUBTYPE OF (
   path
  );
(*
UOF:FF2
*)
  distance : feature_parameter;
 END_ENTITY;

 ENTITY general_path
  SUBTYPE OF (
   path
  );
(*
UOF:FF2
*)
  path_geometry : curve;
 END_ENTITY;

 ENTITY complete_circular_path
  SUBTYPE OF (
   circular_path
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY partial_circular_path
  SUBTYPE OF (
   circular_path
  );
(*
UOF:FF2
*)
  sweep_angle : feature_parameter;
 END_ENTITY;

 ENTITY compound_feature_in_panel
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  feature_type : UNDEFINED_OBJECT;
 INVERSE
  element : SET [2:?] OF compound_feature_in_panel_element FOR is_element_for;
 END_ENTITY;

 ENTITY compound_feature_in_panel_element;
(*
UOF:FF2
*)
  feature : compound_in_panel_select;
  is_element_for : compound_feature_in_panel;
  element_placement : OPTIONAL transformation;
 END_ENTITY;

 ENTITY compound_feature_in_panel_element_relationship;
(*
UOF:FF2
*)
  predecessor : compound_feature_in_panel_element;
  successor : compound_feature_in_panel_element;
 END_ENTITY;

 ENTITY hole_feature_in_panel
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  hole_type : OPTIONAL UNDEFINED_OBJECT;
  hole_profile : closed_profile_usage;
 END_ENTITY;

 ENTITY form_feature_in_panel
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  target_boundary_defined_by : profile_or_angle_select;
  base_radius : feature_parameter;
  target_radius : feature_parameter;
  feature_type : boss_pocket_stairstep_enumeration;
  base_boundary_defined_by : profile_or_angle_select;
  target_face : OPTIONAL general_end_select;
 END_ENTITY;

 ENTITY radiused_bead_end_type
  SUBTYPE OF (
   bead_end_type
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY linear_bead_end_type
  SUBTYPE OF (
   bead_end_type
  );
(*
UOF:FF2
*)
  end_length : UNDEFINED_OBJECT;
  end_shape : straight_or_tapered;
 END_ENTITY;

 ENTITY replicate_feature
  ABSTRACT SUPERTYPE OF ( ONEOF(general_pattern,rectangular_pattern,circular_pattern) )
  SUBTYPE OF (
   feature_definition
  );
(*
UOF:FF2
*)
  replicate_base : replicate_base_assignment;
  SELF\feature_definition.location_and_orientation : placement;
 END_ENTITY;

(* use annotation_curve_occurrence instead
 ENTITY annotation_curve
  SUPERTYPE OF ( ONEOF(leader,projection_curve,dimension_curve) )
  SUBTYPE OF (
   annotation_element
  );
*
UOF:P2,D1
*
  annotation_curve_type : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;
*)

 ENTITY specification_expression;
(*
UOF:S7
*)
  description : OPTIONAL string_select;
  operation : UNDEFINED_OBJECT;
  operand : SET [1:?] OF specification_operand_select;
  id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY default_chamfer;
(*
UOF:FF2
*)
  description : OPTIONAL string_select;
  offset_value : feature_parameter;
 END_ENTITY;

 ENTITY default_draft_angle;
(*
UOF:FF2
*)
  description : OPTIONAL string_select;
  draft_angle_value : feature_parameter;
 END_ENTITY;

 ENTITY default_fillet;
(*
UOF:FF2
*)
  description : OPTIONAL string_select;
  radius_value : feature_parameter;
 END_ENTITY;

 ENTITY default_edge_round;
(*
UOF:FF2
*)
  description : OPTIONAL string_select;
  radius_value : feature_parameter;
 END_ENTITY;

 ENTITY featured_shape
  SUBTYPE OF (
   item_shape
  );
(*
UOF:FF3
*)
  base_shape : item_shape;
 END_ENTITY;

 ENTITY geometric_tolerance_symbol;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY surface_condition_symbol;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY specification_category;
(*
UOF:S7
*)
  implicit_exclusive_condition : BOOLEAN;
  id : UNDEFINED_OBJECT;
  description : string_select;
 END_ENTITY;

(* use draughting_elements instead
 ENTITY associated_draughting_callout
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D2
*
  is_associated_to : SET [1:?] OF associated_element_select;
 END_ENTITY;
*)

 ENTITY property_value_representation;
(*
UOF:PR1
*)
  specified_value : property_value;
  value_determination : OPTIONAL UNDEFINED_OBJECT;
  global_unit : OPTIONAL unit;
  qualifier : OPTIONAL UNDEFINED_OBJECT;
  definition : property;
 END_ENTITY;

 ENTITY lot_configuration
  SUBTYPE OF (
   manufacturing_configuration
  );
(*
UOF:S4
*)
  lot_id : UNDEFINED_OBJECT;
  lot_size : measure_with_unit;
 END_ENTITY;

 ENTITY serial_configuration
  SUBTYPE OF (
   manufacturing_configuration
  );
(*
UOF:S4
*)
  serial_start_number : UNDEFINED_OBJECT;
  serial_end_number : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY dated_configuration
  SUBTYPE OF (
   manufacturing_configuration
  );
(*
UOF:S4
*)
  start_date : date_time;
  end_date : OPTIONAL date_time;
 END_ENTITY;

 ENTITY class_category_association;
(*
UOF:S7
*)
  associated_product_class : product_class;
  mandatory : BOOLEAN;
  associated_category : specification_category;
 END_ENTITY;

 ENTITY alternative_solution
  SUBTYPE OF (
   complex_product
  );
(*
UOF:S7
*)

  base_element : complex_product_select;
 END_ENTITY;

 ENTITY contact_ratio
  SUBTYPE OF (
   surface_condition
  );
(*
UOF:C1
*)

  ratio_value : value_with_unit;
  measuring_gauge : physical_model;
 END_ENTITY;

 ENTITY product_function
  SUBTYPE OF (
   complex_product,
   product_constituent
  );
(*
UOF:S7
*)
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  is_relevant_for : SET [0:?] OF application_context;
 END_ENTITY;

 ENTITY application_context;
(*
UOF:S1
*)
  description : OPTIONAL string_select;
  application_domain : UNDEFINED_OBJECT;
  life_cycle_stage : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY technical_solution
  SUBTYPE OF (
   alternative_solution
  );
(*
UOF:S7
*)

  description : string_select;
 END_ENTITY;

 ENTITY supplier_solution
  SUBTYPE OF (
   alternative_solution
  );
(*
UOF:S7
*)

  supplier : organization;
  probability_rate : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY final_solution
  SUBTYPE OF (
   alternative_solution
  );
(*
UOF:S7
*)

  final_specification : SET [1:?] OF final_definition_select;
  final_status : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY collected_item_association
  SUBTYPE OF (
   item_definition_instance_relationship
  );
(*
UOF:S7
*)

  SELF\item_definition_instance_relationship.relating : collection_definition;
 END_ENTITY;

 ENTITY plus_minus_bounds;
(*
UOF:T1
*)

  upper_bound : UNDEFINED_OBJECT;
  lower_bound : UNDEFINED_OBJECT;
  value_determination : OPTIONAL UNDEFINED_OBJECT;
  significant_digits : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY angular_size_dimension
  SUBTYPE OF (
   size_dimension
  );
(*
UOF:T1
*)

  major_angle : BOOLEAN;
  full : BOOLEAN;
 END_ENTITY;

 ENTITY curved_distance_dimension
  SUBTYPE OF (
   location_dimension
  );
(*
UOF:T1
*)

  with_curve_direction : BOOLEAN;
  used_path : measurement_path;
 END_ENTITY;

 ENTITY angular_location_dimension
  SUBTYPE OF (
   location_dimension
  );
(*
UOF:T1
*)

  major_angle : BOOLEAN;
  mirror_target : BOOLEAN;
  origin_determination : origin_enumeration;
 END_ENTITY;

 ENTITY linear_distance_dimension
  SUBTYPE OF (
   location_dimension
  );
(*
UOF:T1
*)

  directed : BOOLEAN;
  orientation : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY concentricity_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : datum;
 END_ENTITY;

 ENTITY position_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [0:3] OF datum;
  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY symmetry_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [1:3] OF datum;
  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY circular_runout_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [1:2] OF datum;
  angle : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY total_runout_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  angle : OPTIONAL UNDEFINED_OBJECT;
  reference_datum : SET [1:2] OF datum;
 END_ENTITY;

 ENTITY surface_profile_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [0:3] OF datum;
 END_ENTITY;

 ENTITY line_profile_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [0:3] OF datum;
  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY perpendicularity_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [1:3] OF datum;
  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY parallelism_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [1:2] OF datum;
  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY straightness_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  affected_plane : OPTIONAL reference_plane;
 END_ENTITY;

 ENTITY flatness_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

 END_ENTITY;

 ENTITY tolerance_condition;
(*
UOF:T2
*)

  condition : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY single_datum
  SUBTYPE OF (
   datum
  );
(*
UOF:T2
*)

  is_defined_by : datum_representation_select;
  datum_name : UNDEFINED_OBJECT;
  modification : OPTIONAL tolerance_condition;
 END_ENTITY;

 ENTITY datum_target
  ABSTRACT SUPERTYPE OF ( ONEOF(target_area,placed_target) );
(*
UOF:T2
*)

  id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY target_point
  SUBTYPE OF (
   placed_target
  );
(*
UOF:T2
*)

 END_ENTITY;

 ENTITY target_circle
  SUBTYPE OF (
   placed_target
  );
(*
UOF:T2
*)

  diameter : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY angularity_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

  reference_datum : SET [1:2] OF datum;
 END_ENTITY;

 ENTITY cylindricity_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)

 END_ENTITY;

 ENTITY datum
  ABSTRACT SUPERTYPE OF ( ONEOF(single_datum,compound_datum) );
(*
UOF:T2
*)

  precedence : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY target_rectangle
  SUBTYPE OF (
   placed_target
  );
(*
UOF:T2
*)

  target_length : UNDEFINED_OBJECT;
  target_width : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY target_line
  SUBTYPE OF (
   placed_target
  );
(*
UOF:T2
*)

  target_length : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY datum_target_set;
(*
UOF:T2
*)

  target : SET [1:?] OF datum_target;
  rule_description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY tolerance_zone;
(*
UOF:T2
*)

  form_type : UNDEFINED_OBJECT;
  is_zone_for : SET [1:?] OF geometric_tolerance;
 END_ENTITY;

 ENTITY projection
  SUBTYPE OF (
   tolerance_zone_definition
  );
(*
UOF:T2
*)

  projection_end : shape_element;
  projection_length : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY size_dimension
  ABSTRACT SUPERTYPE OF ( ONEOF(angular_size_dimension,thickness_dimension,general_size_dimension) )
  SUBTYPE OF (
   geometric_dimension
  );
(*
UOF:T1
*)

  is_applied_to : element_with_dimension_select;
 END_ENTITY;

 ENTITY location_dimension
  ABSTRACT SUPERTYPE OF ( ONEOF(curved_distance_dimension,linear_distance_dimension,angular_location_dimension) )
  SUBTYPE OF (
   geometric_dimension
  );
(*
UOF:T1
*)

  description : OPTIONAL string_select;
  origin : placed_element_select;
  target : placed_element_select;
 END_ENTITY;

 ENTITY target_area
  SUBTYPE OF (
   datum_target
  );
(*
UOF:T2
*)

  is_defined_by : shape_element;
 END_ENTITY;

 ENTITY quantified_instance
  SUBTYPE OF (
   item_instance
  );
(*
UOF:S3
*)

  quantity : numerical_value;
 END_ENTITY;

 ENTITY open_bead_end_type
  SUBTYPE OF (
   bead_end_type
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY planar_top_condition
  SUBTYPE OF (
   boss_top_condition
  );
(*
UOF:FF2
*)

  top_location : UNDEFINED_OBJECT;
  top_normal : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_top_condition
  SUBTYPE OF (
   boss_top_condition
  );
(*
UOF:FF2
*)

  top_face : general_end_select;
 END_ENTITY;

 ENTITY value_limitation;
(*
UOF:T1
*)

  is_defined_by : limitation_definition_select;
  envelope : OPTIONAL BOOLEAN;
  limited_value : numerical_value;
 END_ENTITY;

 ENTITY constructive_geometry;
(*
UOF:S2
*)

  element : SET [1:?] OF constructive_geometric_element;
  name : OPTIONAL string_select;
 INVERSE
  associated_model : SET [1:?] OF constructive_geometry_association FOR auxiliary_geometry;
 END_ENTITY;

 ENTITY constructive_geometry_association;
(*
UOF:S2
*)

  auxiliary_geometry : constructive_geometry;
  description : OPTIONAL string_select;
  base_geometry : constructive_geometry_select;
 END_ENTITY;

 ENTITY compound_datum
  SUBTYPE OF (
   datum
  );
(*
UOF:T2
*)

  is_made_up_by : SET [2:2] OF single_datum;
 END_ENTITY;

 ENTITY placed_target
  ABSTRACT SUPERTYPE OF ( ONEOF(target_line,target_circle,target_rectangle,target_point) )
  SUBTYPE OF (
   datum_target
  );
(*
UOF:T2
*)

  parameter_reference : placement;
  is_defined_in : geometric_representation_context;
 END_ENTITY;

 ENTITY tolerance_zone_definition;
(*
UOF:T2
*)

  is_defining : tolerance_zone;
  first_element : shape_element;
  second_element : OPTIONAL shape_element;
 END_ENTITY;

 ENTITY design_constraint;
(*
UOF:S7
*)

  constraint_id : UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  is_valid_for : SET [0:?] OF product_class;
 END_ENTITY;

 ENTITY design_constraint_version
  SUBTYPE OF (
   design_constraint
  );
(*
UOF:S7
*)

  version_id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY design_constraint_association;
(*
UOF:S7
*)

  is_based_on : design_constraint;
  name : OPTIONAL string_select;
  is_constraining : complex_product;
 END_ENTITY;

 ENTITY constant_radius_fillet
  SUBTYPE OF (
   fillet
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
  first_offset : OPTIONAL feature_parameter;
  second_offset : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY constant_radius_edge_round
  SUBTYPE OF (
   edge_round
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
  first_offset : OPTIONAL feature_parameter;
  second_offset : OPTIONAL feature_parameter;
 END_ENTITY;

(*
 ENTITY path
  ABSTRACT SUPERTYPE OF ( ONEOF(general_path,linear_path,circular_path) );
*
UOF:FF2
*
  is_defined_in : OPTIONAL geometric_representation_context;
  is_defined_by : placement;
 END_ENTITY;
*)

 ENTITY directed_taper;
(*
UOF:FF2
*)
  angle : feature_parameter;
  direction : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY through_hole_bottom_condition;
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY flat_bottom
  SUBTYPE OF (
   hole_bottom_condition
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY flat_with_radius_bottom
  SUBTYPE OF (
   hole_bottom_condition
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
 END_ENTITY;

 ENTITY conical_bottom
  SUBTYPE OF (
   hole_bottom_condition
  );
(*
UOF:FF2
*)
  tip_angle : feature_parameter;
  tip_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY spherical_bottom
  SUBTYPE OF (
   hole_bottom_condition
  );
(*
UOF:FF2
*)
  radius : feature_parameter;
 END_ENTITY;

 ENTITY reference_plane;
(*
UOF:T2
*)
  plane_location : UNDEFINED_OBJECT;
  plane_normal : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY derived_geometry;
(*
UOF:T1,T2
*)
  geometry : constructive_geometric_element;
  is_derived_from : SET [1:?] OF shape_element;
  role : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY value_range
  SUBTYPE OF (
   value_with_unit
  );
(*
UOF:S1
*)
  upper_limit : UNDEFINED_OBJECT;
  lower_limit : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY value_limit
  SUBTYPE OF (
   value_with_unit
  );
(*
UOF:S1
*)
  limit_qualifier : UNDEFINED_OBJECT;
  limit : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY thickness_dimension
  SUBTYPE OF (
   size_dimension
  );
(*
UOF:T1
*)
  used_path : OPTIONAL measurement_path;
 END_ENTITY;

 ENTITY material_property_value_representation
  SUBTYPE OF (
   property_value_representation
  );
(*
UOF:PR1
*)
  environment_condition : data_environment;
  SELF\property_value_representation.definition : material_property;
 END_ENTITY;

 ENTITY data_environment;
(*
UOF:PR1
*)
  environment_name : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY certification;
(*
UOF:S1
*)
  name : string_select;
  certification_type : UNDEFINED_OBJECT;
  is_applied_to : SET [1:?] OF certified_element_select;
  purpose : OPTIONAL string_select;
 END_ENTITY;

 ENTITY design_constraint_relationship;
(*
UOF:S7
*)
  related : design_constraint;
  relating : design_constraint;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY date_and_person_assignment;
(*
UOF:S1
*)
  is_applied_to : SET [1:?] OF date_time_person_organization_element_select;
  assigned_date_and_person : date_and_person_organization;
  role : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY date_time_assignment;
(*
UOF:S1
*)
  assigned_date_time : date_time;
  role : UNDEFINED_OBJECT;
  is_applied_to : SET [1:?] OF date_time_person_organization_element_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY person_organization_assignment;
(*
UOF:S1
*)
  is_applied_to : SET [1:?] OF date_time_person_organization_element_select;
  assigned_person_organization : person_organization_select;
  role : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY security_classification;
(*
UOF:S1
*)
  is_applied_to : SET [1:?] OF security_element_select;
  level : security_level;
  name : string_select;
  purpose : OPTIONAL string_select;
 END_ENTITY;

 ENTITY activity_element;
(*
UOF:S5
*)
  element : activity_element_select;
  associated_activity : activity;
  role : UNDEFINED_OBJECT;
 END_ENTITY;

(* use shape_representation instead
 ENTITY geometric_model
  SUPERTYPE OF ( geometric_model_version ANDOR ONEOF(wireframe_model_3d,point_direction_model,wireframe_model_2d,hybrid_geometric_model_3d,geometrically_bounded_surface_model,surface_model,compound_model,csg_model,b_rep_model,faceted_b_rep_model) );
  is_defined_in : cartesian_coordinate_space;
  model_id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  model_extent : OPTIONAL UNDEFINED_OBJECT; -- for this we have to add a new entity later on
  additional_element : SET [0:?] OF mapped_item;
 END_ENTITY;
*)

 ENTITY hybrid_geometric_model_3d
  SUBTYPE OF (
   shape_representation
  );
(*
UOF:S2
*)
--  element : SET [0:?] OF detailed_geometric_model_element;
 END_ENTITY;

 ENTITY external_model
  ABSTRACT SUPERTYPE OF ( ONEOF(external_picture,external_geometric_model) );
(*
UOF:E1
*)
  is_defined_as : digital_file;
  is_defined_in : geometric_representation_context;
  description : OPTIONAL string_select;
  model_id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY shape_description_association;
(*
UOF:E1,S2
*)
  is_defining_shape_for : shape_information_select;
  role : UNDEFINED_OBJECT;
  defining_geometry : shape_definition_select;
 END_ENTITY;

 ENTITY item_shape;
(*
UOF:S2,E1
*)
  described_object : item_information_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY shape_element_relationship;
(*
UOF:S2,E1
*)
  relating : shape_element;
  related : shape_element;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY geometric_model_relationship;
(*
UOF:E1,S2
*)
  relating : geometric_or_external_model_select;
  related : geometric_or_external_model_select;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

(*
 ENTITY detailed_geometric_model_element
  ABSTRACT SUPERTYPE OF ( ONEOF(curve_set_2d,point_direction_sequence,point_direction,point_sequence,curve_set_3d,topologically_connected_set,faceted_b_rep,shell,b_rep,face,geometric_set_3d,csg_primitive_arm,boolean_result,half_space_solid,point,curve,surface,swept_face_solid,solid_replica) )
  SUBTYPE OF (
   detailed_model_element
  );
*
UOF:G1,G2,G3,G4,G5,G6,G7
*
 END_ENTITY;
*)

(* use defined type styled_model instead
 ENTITY styled_model
  ABSTRACT SUPERTYPE OF ( styled_model_version ANDOR ONEOF(styled_geometric_model,styled_annotation_model) );
*
UOF:P1
*
  element : SET [1:?] OF styled_element;
  model_id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  additional_elements : SET [0:?] OF mapped_item;
 END_ENTITY;
*)

(*  use styled_item instead
 ENTITY styled_element
  ABSTRACT SUPERTYPE OF ( ONEOF(annotation_element,styled_model_element) )
  SUBTYPE OF (
   detailed_element
  );
*
UOF:P1
*
  appearance : appearance_assignment;
  invisible : BOOLEAN;
 END_ENTITY;
*)

(* use draughting_annotation_occurrence instead
 ENTITY annotation_element
  ABSTRACT SUPERTYPE OF ( ONEOF(annotation_curve,text,annotation_subfigure,annotation_symbol,fill_area) )
  SUBTYPE OF (
   styled_element
  );
*
UOF:P2
*
 END_ENTITY;
*)

 ENTITY kinematic_simulation_information;
(*
UOF:K1
*)
  mechanism : SET [1:?] OF kinematic_mechanism;
  ground : ground_representation;
  described_element : SET [1:?] OF simulation_context_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY transformation
  ABSTRACT SUPERTYPE OF ( ONEOF(transformation_2d,transformation_3d) );
(*
UOF:E1,S2
*)
 END_ENTITY;

 ENTITY document_assignment;
(*
UOF:E1
*)
  assigned_document : assigned_document_select;
  is_assigned_to : documented_element_select;
  role : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_version;
(*
UOF:E1
*)
  associated_document : document;
  id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

(* use subtypes of representation_item instead
 ENTITY detailed_element
  ABSTRACT SUPERTYPE OF ( ONEOF(styled_element,detailed_model_element,draughting_callout) );
*
UOF:G1,G2,G3,G4,G5,G6,G7,P2
*
  name : OPTIONAL string_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY point
  ABSTRACT SUPERTYPE OF ( ONEOF(cartesian_point,point_on_surface,point_on_curve) )
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G1,G2,G3,G4,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY curve
  ABSTRACT SUPERTYPE OF ( ONEOF(composite_curve,trimmed_curve,offset_curve,line,parabola,b_spline_curve,hyperbola,curve_on_surface,ellipse,circle,polyline) )
  SUBTYPE OF (
   detailed_geometric_model_element
  );

-- UOF:G1,G2,G3,G5,G6,G7,G8

 END_ENTITY;
*)

(* use aim instead
 ENTITY surface
  ABSTRACT SUPERTYPE OF ( ONEOF(cylindrical_surface,offset_surface,surface_of_linear_extrusion,surface_of_revolution,conical_surface,plane,b_spline_surface,toroidal_surface,spherical_surface,trimmed_surface) )
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G3,G5,G6,G7,G8
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY csg_primitive_arm
  ABSTRACT SUPERTYPE OF ( ONEOF(right_circular_cylinder,right_circular_cone,torus,right_angular_wedge,block,sphere) )
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G7
*
 END_ENTITY;
*)

 ENTITY rectangular_open_pocket
  SUBTYPE OF (
   pocket_feature
  );
(*
UOF:FF2
*)
  SELF\pocket_feature.boundary : open_profile_usage;
 END_ENTITY;

 ENTITY boss_top_condition
  ABSTRACT SUPERTYPE OF ( ONEOF(planar_top_condition,general_top_condition) );
(*
UOF:FF2
*)
  is_applied_to : starting_or_ending;
  top_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY hole_bottom_condition
  ABSTRACT SUPERTYPE OF ( ONEOF(flat_with_radius_bottom,flat_bottom,spherical_bottom,flat_with_taper_bottom,conical_bottom) );
(*
UOF:FF2
*)
  is_applied_to : starting_or_ending;
 END_ENTITY;

 ENTITY slot_end_type
  ABSTRACT SUPERTYPE OF ( ONEOF(flat_slot_end_type,radiused_slot_end_type,open_slot_end_type,woodruff_slot_end_type) );
(*
UOF:FF2
*)
  is_applied_to : starting_or_ending;
 END_ENTITY;

 ENTITY pocket_bottom_condition
  ABSTRACT SUPERTYPE OF ( ONEOF(general_bottom_condition,planar_bottom_condition) );
(*
UOF:FF2
*)
  is_applied_to : starting_or_ending;
 END_ENTITY;

 ENTITY joggle_feature
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  defining_path : linear_path;
  slope_angle_1 : feature_parameter;
  slope_angle_2 : feature_parameter;
  height : feature_parameter;
  termination : joggle_termination;
  direction_angle_2 : feature_parameter;
  direction_angle_1 : feature_parameter;
  top_radius_1 : OPTIONAL feature_parameter;
  top_radius_2 : OPTIONAL feature_parameter;
  base_radius_2 : OPTIONAL feature_parameter;
  base_radius_1 : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY bead_end_type
  ABSTRACT SUPERTYPE OF ( ONEOF(linear_bead_end_type,open_bead_end_type,radiused_bead_end_type) );
(*
UOF:FF2
*)
  is_applied_to : starting_or_ending;
 END_ENTITY;

(* use complex shape_representation_relatioship$representation_relationship_with_transformation instead
 ENTITY geometric_model_relationship_with_transformation
  SUBTYPE OF (
   geometric_model_relationship
  );
*
UOF:E1,S2
*
  model_placement : transformation;
 END_ENTITY;
*)

 ENTITY multi_language_string;
(*
UOF:S1
*)
  additional_language_dependent_string : SET [0:?] OF string_with_language;
  primary_language_dependent_string : string_with_language;
 END_ENTITY;

 ENTITY string_with_language;
(*
UOF:S1
*)
  contents : STRING;
  language_specification : language;
 INVERSE
  used_by : SET [1:?] OF multi_language_string FOR primary_language_dependent_string;
 END_ENTITY;

(* use aim instead
 ENTITY face_bound;
*
UOF:G3,G5,G6,G7
*
  outer : BOOLEAN;
  loop : loop_select;
 END_ENTITY;
*)

 ENTITY shape_dependent_property
  ABSTRACT SUPERTYPE OF ( ONEOF(centre_of_mass,moments_of_inertia,general_shape_dependent_property) );
(*
UOF:PR1,S2
*)
  description : OPTIONAL string_select;
  value_determination : OPTIONAL UNDEFINED_OBJECT;
  described_element : shaped_element_select;
  is_defined_in : OPTIONAL geometric_representation_context;
 END_ENTITY;

 ENTITY styled_model_relationship;
(*
UOF:P1
*)
  related : styled_model;
  relating : styled_model;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY transformation_2d
  SUBTYPE OF (
   transformation
  );
(*
UOF:E1,S2
*)
 END_ENTITY;

 ENTITY transformation_3d
  SUBTYPE OF (
   transformation
  );
(*
UOF:E1,S2
*)
 END_ENTITY;

(* use aim instead
 ENTITY curve_set_2d
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G1
*
  element : SET [1:?] OF point_or_curve_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY curve_set_3d
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G2
*
  element : SET [1:?] OF point_or_curve_select;
 END_ENTITY;
*)

(*
 ENTITY geometric_set_3d
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G8
*
  element : SET [1:?] OF point_or_curve_or_surface_select;
 END_ENTITY;
*)

(* use aim instead
 ENTITY b_rep
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G5,G7
*
  void : SET [0:?] OF closed_shell;
  outer : closed_shell;
 END_ENTITY;
*)

(* use aim instead
 ENTITY faceted_b_rep
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G4,G7
*
  outer : faceted_closed_shell;
  void : SET [0:?] OF faceted_closed_shell;
 END_ENTITY;
-- use connected_face_set instead
 ENTITY shell
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G3
*
  included_face : SET [1:?] OF face;
 END_ENTITY;
*)

(* not supported yet
 ENTITY styled_model_version
  SUBTYPE OF (
   styled_model
  );
*
UOF:P1
*
  version_id : UNDEFINED_OBJECT;
 END_ENTITY;
*)

 ENTITY geometric_model_version
  SUBTYPE OF (
   shape_representation
  );
(*
UOF:E1,S2
*)
  version_id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_plan_version
  SUBTYPE OF (
   process_plan
  );
(*
UOF:S8
*)
  version_id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY effectivity_relationship;
(*
UOF:S4
*)
  relating : effectivity;
  related : effectivity;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY work_order;
(*
UOF:S5
*)
  is_controlling : SET [1:?] OF activity;
  id : UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  work_order_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY element_delivery;
(*
UOF:S5
*)
  destination : organization;
  quantity : value_with_unit;
  deliverable_element : activity_element;
 END_ENTITY;

 ENTITY approval_status;
(*
UOF:S1
*)
  status_name : UNDEFINED_OBJECT;
  used_classification_system : OPTIONAL classification_system;
 END_ENTITY;

 ENTITY approval_relationship;
(*
UOF:S1
*)
  relating : approval;
  related : approval;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY security_level;
(*
UOF:S1
*)
  level_name : UNDEFINED_OBJECT;
  used_classification_system : OPTIONAL classification_system;
 END_ENTITY;

 ENTITY assembly_substitute_relationship;
(*
UOF:S3
*)
  base : assembly_component_relationship;
  substitute : assembly_component_relationship;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY mated_item_relationship;
(*
UOF:S8
*)
  mated_shape : OPTIONAL shape_element_relationship;
  relating : mated_item_association;
  related : mated_item_association;
  mating_material : SET [0:?] OF quantified_instance;
 END_ENTITY;

 ENTITY drawing_sequence;
(*
UOF:D1
*)
  preceding_drawing : drawing_revision;
  succeeding_drawing : drawing_revision;
 END_ENTITY;

 ENTITY property_change;
(*
UOF:PR1
*)
  is_describing : change;
  added_property : SET [0:?] OF property_value_representation;
  deleted_property : SET [0:?] OF property_value_representation;
  description : string_select;
  id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY change;
(*
UOF:S5,S2,PR1
*)
  description : OPTIONAL string_select;
  described_change : change_relationship_select;
 END_ENTITY;

 ENTITY joggle_termination
  ABSTRACT SUPERTYPE OF ( ONEOF(value_termination,face_termination) );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY value_termination
  SUBTYPE OF (
   joggle_termination
  );
(*
UOF:FF2
*)
  depth : feature_parameter;
  angle : feature_parameter;
 END_ENTITY;

 ENTITY face_termination
  SUBTYPE OF (
   joggle_termination
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY constructive_geometric_element;
(*
UOF:S2
*)
  element : constructive_element_select;
  description : OPTIONAL string_select;
 INVERSE
  geometry : SET [1:?] OF constructive_geometry FOR element;
 END_ENTITY;

 ENTITY feature_placement;
(*
UOF:FF3
*)

  placement : transformation;
  placed_definition : feature_definition;
  placement_reference : shape_representation;
 END_ENTITY;

 ENTITY feature_definition
  ABSTRACT SUPERTYPE OF ( ONEOF(replicate_feature,process_feature_in_solid,process_feature_in_panel) );
(*
UOF:FF2
*)
  is_defined_in : geometric_representation_context;
  location_and_orientation : OPTIONAL placement;
 END_ENTITY;

 ENTITY replicate_base_assignment;
(*
UOF:FF2
*)
  base_feature : feature_definition;
  replicate_placement : OPTIONAL transformation;
 END_ENTITY;

 ENTITY single_instance
  SUBTYPE OF (
   item_instance
  );
(*
UOF:S3
*)
 END_ENTITY;

 ENTITY physical_instance;
(*
UOF:S7
*)

  is_realization_of : OPTIONAL physical_instance_definition_select;
  serial_number : OPTIONAL UNDEFINED_OBJECT;
  lot_id : OPTIONAL UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  inventory_number : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY physical_assembly_relationship;
(*
UOF:S7
*)

  physical_component : physical_instance;
  physical_assembly : physical_instance;
  is_realization_of : item_instance;
 END_ENTITY;

(* use draughting_model instead
 ENTITY styled_annotation_model
  SUBTYPE OF (
   styled_model
  );
*
UOF:P2
*
  is_defined_in : geometric_representation_context;
 END_ENTITY;
*)

(* use draughting_model or mechanical_design_geometric_presentation_representation instead
 ENTITY styled_geometric_model
  SUBTYPE OF (
   styled_model
  );
*
UOF:P1
*
  styled_geometry_context : shape_representation;
 END_ENTITY;
*)

 ENTITY placed_feature
  SUBTYPE OF (
   feature_occurrence
  );
(*
UOF:FF3
*)
  is_placed_by : feature_placement;
 END_ENTITY;

 ENTITY feature_occurrence
  ABSTRACT SUPERTYPE OF ( ONEOF(placed_feature,included_feature) )
  SUBTYPE OF (
   shape_element
  );
(*
UOF:FF1
*)
(*
attribute changed to optional by Valdas Zigas
*)
  maximum_feature_limit : OPTIONAL plane;
 END_ENTITY;

 ENTITY collection_definition
  SUBTYPE OF (
   design_discipline_item_definition
  );
(*
UOF:S7
*)
  purpose : OPTIONAL string_select;
 INVERSE
(* Express compiler complains here. V.N.
  collected_items : SET [2:?] OF collected_item_association FOR SELF\item_definition_instance_relationship.relating;
*)
  collected_items : SET [2:?] OF collected_item_association FOR relating;
 END_ENTITY;

 ENTITY assembly_definition
  SUBTYPE OF (
   design_discipline_item_definition
  );
(*
UOF:S3
*)
  assembly_type : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY item_instance
  ABSTRACT SUPERTYPE OF ( ONEOF(single_instance,quantified_instance,selected_instance,specified_instance) )
  SUBTYPE OF (
   product_constituent
  );
(*
UOF:S3
*)
  description : OPTIONAL string_select;
  definition : instance_definition_select;
  id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY selected_instance
  SUBTYPE OF (
   item_instance
  );
(*
UOF:S3
*)
  selection_control : UNDEFINED_OBJECT;
  selected_quantity : value_with_unit;
 END_ENTITY;

 ENTITY external_library_reference;
(*
UOF:S6
*)
  external_id : UNDEFINED_OBJECT;
  library_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY specification_inclusion;
(*
UOF:S7
*)
  if_condition : specification_operand_select;
  included_specification : specification_operand_select;
  description : OPTIONAL string_select;
  id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY person_in_organization;
(*
UOF:S1
*)
  associated_person : person;
  associated_organization : organization;
  role : UNDEFINED_OBJECT;
  location : OPTIONAL person_and_organization_address;
  id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY default_thickness;
(*
UOF:T1
*)
  thickness_value : value_with_unit;
  description : OPTIONAL string_select;
  parameter_name : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY model_property_association;
(*
UOF:PR1
*)
  described_element : model_property_select;
  associated_property_value : model_property_value;
  validity_context : OPTIONAL validity_context_select;
 END_ENTITY;

 ENTITY quality_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
 END_ENTITY;

 ENTITY cost_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
 END_ENTITY;

 ENTITY property_relationship;
(*
UOF:PR1
*)
  relating : property;
  related : property;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

(* use aim instead
 ENTITY detailed_model_element
  ABSTRACT SUPERTYPE OF ( ONEOF(detailed_geometric_model_element,template_instance) )
  SUBTYPE OF (
   detailed_element
  );
*
UOF:G1,G2,G3,G4,G5,G6,G7,E1
*
 END_ENTITY;
*)

 ENTITY closed_profile_usage
  SUBTYPE OF (
   profile_usage
  );
(*
UOF:FF2
*)
  SELF\profile_usage.used_profile : closed_profile;
 END_ENTITY;

 ENTITY panel_hole_with_barring
  SUBTYPE OF (
   hole_feature_in_panel
  );
(*
UOF:FF2
*)
  barring_profile : closed_profile_usage;
  angle_defined_by : OPTIONAL angle_specification;
  base_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY rectangular_boss
  SUBTYPE OF (
   boss_feature
  );
(*
UOF:FF2
*)
 END_ENTITY;

 ENTITY flat_with_taper_bottom
  SUBTYPE OF (
   hole_bottom_condition
  );
(*
UOF:FF2
*)
  final_diameter : feature_parameter;
  taper_angle : feature_parameter;
 END_ENTITY;

 ENTITY chamfer_definition;
(*
UOF:FF2
*)
  value_2 : chamfer_value_select;
  offset_1 : chamfer_offset;
 END_ENTITY;

 ENTITY retention_period;
(*
UOF:S4
*)
  start_definition : event_or_date_select;
  earliest_end_definition : period_or_date_select;
  latest_end_definition : period_or_date_select;
  is_applied_to : SET [1:?] OF general_organizational_data_select;
  retention_purpose : OPTIONAL string_select;
 END_ENTITY;

(* use styled_item instead
 ENTITY styled_model_element
  SUBTYPE OF (
   styled_element
  );
*
UOF:P1
*
  element : detailed_model_element;
 END_ENTITY;
*)

 ENTITY classification_system;
(*
UOF:S6
*)
  description : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
 INVERSE
  allowed_classification : SET [0:?] OF general_classification FOR used_classification_system;
 END_ENTITY;

 ENTITY class_inclusion_association;
(*
UOF:S7
*)
  associated_product_class : product_class;
  description : OPTIONAL string_select;
  associated_inclusion : specification_inclusion;
 END_ENTITY;

 ENTITY product_component
  SUBTYPE OF (
   complex_product,
   product_constituent
  );
(*
UOF:S7
*)
  is_influenced_by : SET [0:?] OF class_category_association;
  name : OPTIONAL string_select;
  description : OPTIONAL string_select;
  is_relevant_for : SET [0:?] OF application_context;
  instance_required : BOOLEAN;
 END_ENTITY;

 ENTITY alias_identification;
(*
UOF:S1
*)
  alias_id : UNDEFINED_OBJECT;
  alias_version_id : OPTIONAL UNDEFINED_OBJECT;
  is_applied_to : alias_select;
  alias_scope : OPTIONAL organization;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY document_type_property;
(*
UOF:E1
*)
  document_type_name : UNDEFINED_OBJECT;
  used_classification_system : OPTIONAL classification_system;
 END_ENTITY;

 ENTITY drawing_assignment;
(*
UOF:D1
*)
  associated_drawing : drawing_revision;
  is_describing : presentation_association_select;
 END_ENTITY;

 ENTITY view_area_assignment;
(*
UOF:P1
*)
  associated_view_area : view_area;
  is_describing : presentation_association_select;
 END_ENTITY;

 ENTITY item_definition_relationship
  ABSTRACT SUPERTYPE OF ( ONEOF(replaced_definition_relationship,geometrical_relationship,tool_part_relationship,make_from_relationship,general_item_definition_relationship) );
(*
UOF:S3
*)
  relating : design_discipline_item_definition;
  related : design_discipline_item_definition;
 END_ENTITY;

 ENTITY item_definition_instance_relationship
  ABSTRACT SUPERTYPE OF ( ONEOF(collected_item_association,mated_item_association,assembly_component_relationship,general_item_definition_instance_relationship) );
(*
UOF:S3
*)
  related : item_instance;
  relating : design_discipline_item_definition;
 END_ENTITY;

 ENTITY replaced_usage_relationship
  SUBTYPE OF (
   item_instance_relationship
  );
(*
UOF:S7
*)
  usage_context : instance_usage_context_select;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY item_instance_relationship
  ABSTRACT SUPERTYPE OF ( ONEOF(replaced_usage_relationship,same_time_machining_relationship,general_item_instance_relationship) );
(*
UOF:S7
*)
  relating : item_instance;
  related : item_instance;
 END_ENTITY;

 ENTITY instance_placement;
(*
UOF:S7
*)
  reference_product_component : product_component;
  placed_instance : single_instance;
  placement : transformation_select;
 END_ENTITY;

 ENTITY event_reference;
(*
UOF:S4
*)
  offset : OPTIONAL time_measure_with_unit;
  event_context : OPTIONAL general_organizational_data_select;
  event_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY product_identification;
(*
UOF:S4,S7
*)

  associated_product_class : product_class;
  name : OPTIONAL string_select;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  id : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 INVERSE
  associated_design : SET [0:1] OF product_design FOR product;
 END_ENTITY;

 ENTITY chamfer_offset;
(*
UOF:FF2
*)
  offset : feature_parameter;
 END_ENTITY;

 ENTITY chamfer_angle;
(*
UOF:FF2
*)
  angle : feature_parameter;
 END_ENTITY;

 ENTITY angle_specification;
(*
UOF:FF2
*)
  angle : feature_parameter;
  angle_reference : angle_reference_enumeration;
 END_ENTITY;

 ENTITY measurement_path;
(*
UOF:C1,T1
*)
  is_defined_in : geometric_representation_context;
  is_defined_as : curve;
 END_ENTITY;

 ENTITY locator_feature
  SUBTYPE OF (
   process_feature_in_panel
  );
(*
UOF:FF2
*)
  diameter : feature_parameter;
  tip_angle : feature_parameter;
  base_radius : OPTIONAL feature_parameter;
  tip_radius : OPTIONAL feature_parameter;
 END_ENTITY;

 ENTITY general_item_definition_instance_relationship
  SUBTYPE OF (
   item_definition_instance_relationship
  );
(*
UOF:S7
*)
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_item_instance_relationship
  SUBTYPE OF (
   item_instance_relationship
  );
(*
UOF:S7
*)
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY thread_feature;
(*
UOF:FF2
*)
  effective_thread_length : UNDEFINED_OBJECT;
  maximum_thread_length : OPTIONAL UNDEFINED_OBJECT;
  thread_definition : thread_specification;
  location_and_orientation : placement;
 END_ENTITY;

 ENTITY geometric_tolerance_relationship;
(*
UOF:T2
*)
  relating : geometric_tolerance;
  related : geometric_tolerance;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

(* use bounded_surface instead
 ENTITY trimmed_surface
  SUBTYPE OF (
   surface
  );
*
UOF:G8
*
 END_ENTITY;
*)

(* use edge_based_wireframe_model or face_based_surface_model instead
 ENTITY topologically_connected_set
  SUBTYPE OF (
   detailed_geometric_model_element
  );
*
UOF:G6
*
  element : SET [1:?] OF connected_element_select;
 END_ENTITY;
*)

 ENTITY digital_file
  SUBTYPE OF (
   document_file
  );
(*
UOF:E1
*)
  associated_model_space : OPTIONAL representation;
 -- INVERSE
  --associated_model_space : SET [0:1] OF external_model FOR is_defined_as;
 END_ENTITY;

 ENTITY hardcopy
  SUBTYPE OF (
   document_file
  );
(*
UOF:E1
*)
 END_ENTITY;

 ENTITY document_representation
  ABSTRACT SUPERTYPE OF ( ONEOF(physical_representation,digital_document) );
(*
UOF:E1
*)
  description : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
  associated_document_version : document_version;
  creation : OPTIONAL document_creation_property;
  common_location : SET [0:?] OF document_location_property;
  representation_format : OPTIONAL document_format_property;
  size : OPTIONAL document_size_property;
  content : OPTIONAL document_content_property;
 END_ENTITY;

 ENTITY document_file
  ABSTRACT SUPERTYPE OF ( ONEOF(digital_file,hardcopy) );
(*
UOF:E1
*)
  file_id : UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
  document_file_type : OPTIONAL document_type_property;
  external_id_and_location : SET [0:?] OF external_file_id_and_location;
  size : OPTIONAL document_size_property;
  file_format : OPTIONAL document_format_property;
  content : OPTIONAL document_content_property;
  creation : OPTIONAL document_creation_property;
 END_ENTITY;

 ENTITY document_structure;
(*
UOF:E1
*)
  relating : document_representation;
  related : document_representation;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_file_relationship;
(*
UOF:E1
*)
  relating : document_file;
  related : document_file;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_size_property;
(*
UOF:E1
*)
  file_size : OPTIONAL value_with_unit;
  page_count : OPTIONAL value_with_unit;
 END_ENTITY;

 ENTITY document_version_relationship;
(*
UOF:E1
*)
  description : OPTIONAL string_select;
  relating : document_version;
  related : document_version;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_content_property;
(*
UOF:E1
*)
  detail_level : OPTIONAL UNDEFINED_OBJECT;
  geometry_type : OPTIONAL UNDEFINED_OBJECT;
  real_world_scale : OPTIONAL numerical_value;
  languages : SET [0:?] OF language;
 END_ENTITY;

 ENTITY document_creation_property;
(*
UOF:E1
*)
  creating_system : UNDEFINED_OBJECT;
  operating_system : OPTIONAL UNDEFINED_OBJECT;
  creating_interface : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_format_property;
(*
UOF:E1
*)
  data_format : OPTIONAL UNDEFINED_OBJECT;
  character_code : OPTIONAL UNDEFINED_OBJECT;
  size_format : OPTIONAL rectangular_size;
 END_ENTITY;

 ENTITY surface_texture_parameter;
(*
UOF:C1
*)
  parameter_value : value_with_unit;
  parameter_name : UNDEFINED_OBJECT;
  described_texture : texture_select;
  parameter_index : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY kinematic_element
  ABSTRACT SUPERTYPE OF ( ONEOF(kinematic_structure) );
(*
UOF:K1
*)
  name : OPTIONAL string_select;
 END_ENTITY;

 ENTITY classification_association;
(*
UOF:S6
*)
  associated_classification : general_classification;
  role : OPTIONAL UNDEFINED_OBJECT;
  definitional : OPTIONAL BOOLEAN;
  classified_element : classified_element_select;
 END_ENTITY;

(* use measure_schema.unit instead
 ENTITY unit;
-- UOF:S1
  unit_name : UNDEFINED_OBJECT;
 END_ENTITY;
*)

 ENTITY duration_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
 END_ENTITY;

 ENTITY general_property
  SUBTYPE OF (
   property
  );
(*
UOF:PR1
*)
  property_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY property_value_representation_relationship;
(*
UOF:PR1
*)
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  relating : property_value_representation;
  related : property_value_representation;
 END_ENTITY;

 ENTITY property_value_association
  ABSTRACT SUPERTYPE OF ( ONEOF(item_property_association,process_property_association) );
(*
UOF:PR1
*)
  validity_context : OPTIONAL validity_context_select;
  description : OPTIONAL string_select;
  describing_property_value : property_value_representation;
 END_ENTITY;

 ENTITY plib_class_reference;
(*
UOF:S6
*)
  version : UNDEFINED_OBJECT;
  supplier_bsu : UNDEFINED_OBJECT;
  code : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY plib_property_reference;
(*
UOF:S6
*)
  name_scope : plib_class_reference;
  code : UNDEFINED_OBJECT;
  version : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY activity_method_assignment;
(*
UOF:S5
*)
  assigned_method : activity_method;
  associated_request : work_request;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY physical_instance_test_result;
(*
UOF:S7
*)
  test_activity : OPTIONAL test_activity_select;
  test_result : SET [0:?] OF property_value_representation;
  tested_instance : physical_instance;
  description : OPTIONAL string_select;
  id : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_property_association
  SUBTYPE OF (
   property_value_association
  );
(*
UOF:PR1
*)
  described_element : process_property_select;
 END_ENTITY;

 ENTITY item_property_association
  SUBTYPE OF (
   property_value_association
  );
(*
UOF:PR1
*)
  definitional : OPTIONAL BOOLEAN;
  described_element : item_property_select;
 END_ENTITY;

 ENTITY physical_representation
  ABSTRACT SUPERTYPE OF ( ONEOF(physical_model,physical_document) )
  SUBTYPE OF (
   document_representation
  );
(*
UOF:E1
*)
 END_ENTITY;

(* use aim instead
 ENTITY terminator_symbol;
*
UOF:P2,P1
*
 END_ENTITY;
*)

 ENTITY dimension_symbol;
(*
UOF:P2
*)
 END_ENTITY;

 ENTITY point_marker_symbol;
(*
UOF:P2,P1
*)
 END_ENTITY;

 ENTITY full_model_change
  SUBTYPE OF (
   model_change
  );
(*
UOF:S2
*)
  related_description : model_change_select;
  added_element : SET [0:?] OF representation_item;
 END_ENTITY;

 ENTITY incremental_model_change
  SUBTYPE OF (
   model_change
  );
(*
UOF:S2
*)
  basis_model : incremental_change_select;
  added_element : SET [0:?] OF model_change_element_select;
 END_ENTITY;

 ENTITY effectivity_assignment;
(*
UOF:S4
*)
  assigned_effectivity : effectivity;
  effective_element : effective_element_select;
  role : UNDEFINED_OBJECT;
  effectivity_indication : BOOLEAN;
 END_ENTITY;

 ENTITY product_structure_relationship;
(*
UOF:S7
*)
  relating : complex_product;
  related : product_constituent;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY complex_product
  ABSTRACT SUPERTYPE OF ( ONEOF(product_component,product_function,alternative_solution) );
(*
UOF:S7
*)
  id : UNDEFINED_OBJECT;
  version_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY product_constituent
  ABSTRACT SUPERTYPE OF ( ONEOF(product_component,product_function,item_instance) );
(*
UOF:S3
*)
 END_ENTITY;

 ENTITY partial_document_assignment
  SUBTYPE OF (
   document_assignment
  );
(*
UOF:E1
*)
  document_portion : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY external_geometric_model_with_parameters
  SUBTYPE OF (
   external_geometric_model
  );
(*
UOF:E1
*)
  parameter_value : SET [1:?] OF general_parameter;
 END_ENTITY;

 ENTITY external_geometric_model
  SUBTYPE OF (
   external_model
  );
(*
UOF:E1
*)
  model_extent : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY external_picture
  SUBTYPE OF (
   external_model
  );
(*
UOF:E1
*)
  SELF\external_model.is_defined_in : geometric_representation_context;
 END_ENTITY;

 ENTITY product_design;
(*
UOF:S4
*)
  design : item_version;
  product : product_identification;
 END_ENTITY;

 ENTITY manufacturing_configuration
  ABSTRACT SUPERTYPE OF ( ONEOF(serial_configuration,dated_configuration,lot_configuration) );
(*
UOF:S4
*)
  is_solution_for : product_design;
  configured_element : item_instance;
  concerned_organization : SET [0:?] OF organization;
 END_ENTITY;

 ENTITY material_property_association;
(*
UOF:PR1
*)
  described_material : material;
  associated_property_value : material_property_value_representation;
  definitional : OPTIONAL BOOLEAN;
 END_ENTITY;

 ENTITY general_size_dimension
  SUBTYPE OF (
   size_dimension
  );
(*
UOF:T1
*)
  dimension_type : UNDEFINED_OBJECT;
  used_path : OPTIONAL measurement_path;
 END_ENTITY;

 ENTITY specified_instance
  SUBTYPE OF (
   item_instance
  );
(*
UOF:S3
*)
  upper_usage : item_instance;
  related_instance : item_instance;
  assembly_context : assembly_definition;
 END_ENTITY;

 ENTITY value_with_unit
  ABSTRACT SUPERTYPE OF ( ONEOF(numerical_value,value_range,value_limit) )
  SUBTYPE OF (
   property_value
  );
(*
UOF:S1
*)
  unit_component : OPTIONAL unit;
  significant_digits : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY complex_product_relationship;
  relating : complex_product;
  related : complex_product;
(*
UOF:S7
*)
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY product_specification
  SUBTYPE OF (
   product_identification
  );
(*
UOF:S7
*)
  defining_specification : SET [1:?] OF specification;
 END_ENTITY;

 ENTITY class_structure_relationship;
(*
UOF:S7
*)
  related : product_function_component_select;
  relating : product_class;
  description : OPTIONAL string_select;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY item_function_association;
(*
UOF:S7
*)
  associated_function : product_function;
  associated_item : design_discipline_item_definition;
  description : OPTIONAL string_select;
  association_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY model_property_value;
(*
UOF:PR1
*)
  describing_model : model_property_representation_select;
  definition : general_property;
 END_ENTITY;

(* use geometrical_tolerance_callout instead
 ENTITY geometric_tolerance_callout
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D1
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY surface_condition_callout
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D1
*
 END_ENTITY;
*)

 ENTITY kinematic_control;
(*
UOF:K1
*)

  is_controlling : kinematic_mechanism;
  program : SET [1:?] OF interpolated_configuration_sequence;
  related_result : SET [0:?] OF kinematic_transformation_result;
 END_ENTITY;

 ENTITY named_size
  SUBTYPE OF (
   rectangular_size
  );
(*
UOF:E1
*)

  referenced_standard : OPTIONAL classification_system;
  size : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY rectangular_size;
(*
UOF:E1
*)

  density : OPTIONAL value_with_unit;
  width : value_with_unit;
  height : value_with_unit;
 END_ENTITY;

 ENTITY duration;
(*
UOF:S4
*)
  time : UNDEFINED_OBJECT;
  time_unit : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_symbol;
(*
UOF:P2
*)
 END_ENTITY;

(* use aim instead
 ENTITY datum_feature_callout
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D1
*
 END_ENTITY;
*)

(* use aim instead
 ENTITY datum_target_callout
  SUBTYPE OF (
   draughting_callout
  );
*
UOF:D1
*
 END_ENTITY;
*)

 ENTITY compound_hole
  SUBTYPE OF (
   compound_feature_in_solid
  );
(*
UOF:FF2
*)
  compound_hole_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY specific_item_classification_hierarchy;
(*
UOF:S1,S6
*)
  super_classification : specific_item_classification;
  sub_classification : specific_item_classification;
 END_ENTITY;

 ENTITY language;
(*
UOF:S1
*)
  language_code : UNDEFINED_OBJECT;
  country_code : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY general_shape_dependent_property
  SUBTYPE OF (
   shape_dependent_property
  );
(*
UOF:PR1,S2
*)
  property_type : UNDEFINED_OBJECT;
  property_value : general_shape_dependent_value_select;
--  property_value : representation_item;
 END_ENTITY;

 ENTITY general_compound_feature_in_solid
  SUBTYPE OF (
   compound_feature_in_solid
  );
(*
UOF:FF2
*)
  SELF\compound_feature_in_solid.feature_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY profile_usage
  ABSTRACT SUPERTYPE OF ( ONEOF(open_profile_usage,closed_profile_usage) );
(*
UOF:FF2
*)
  used_profile : profile;
  profile_placement : OPTIONAL transformation;
 END_ENTITY;

 ENTITY open_profile_usage
  SUBTYPE OF (
   profile_usage
  );
(*
UOF:FF2
*)
  profile_limit : OPTIONAL plane;
  SELF\profile_usage.used_profile : open_profile;
 END_ENTITY;

 ENTITY coaxiality_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)
  reference_datum : SET [1:2] OF datum;
 END_ENTITY;

 ENTITY roundness_tolerance
  SUBTYPE OF (
   geometric_tolerance
  );
(*
UOF:T2
*)
 END_ENTITY;

 ENTITY surface_condition_association;
(*
UOF:C1
*)
  describing_surface_condition : surface_condition;
  described_element : shaped_element_select;
 END_ENTITY;

 ENTITY person_in_organization_relationship;
(*
UOF:S1
*)
  relating : person_in_organization;
  related : person_in_organization;
  relation_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
 END_ENTITY;

 ENTITY interval_of_time;
(*
UOF:S1
*)
  start_definition : event_or_date_select;
  end_definition : period_or_date_select;
 END_ENTITY;

 ENTITY date_time_interval_assignment;
(*
UOF:S1
*)
  assigned_time_interval : interval_of_time;
  role : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  is_applied_to : SET [1:?] OF general_organizational_data_select;
 END_ENTITY;

 ENTITY specification_category_hierarchy;
(*
UOF:S7
*)
  sub_category : specification_category;
  super_category : specification_category;
 END_ENTITY;

 ENTITY specific_document_classification_hierarchy;
(*
UOF:E1
*)
  super_classification : specific_document_classification;
  sub_classification : specific_document_classification;
 END_ENTITY;

 ENTITY specific_document_classification;
(*
UOF:E1
*)
  associated_document : SET [1:?] OF document;
  description : OPTIONAL string_select;
  classification_name : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY document_location_property;
(*
UOF:E1
*)
  location_name : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY external_file_id_and_location;
(*
UOF:E1
*)
  location : document_location_property;
  external_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY component_placement;
(*
UOF:S7
*)
  placed_component : product_component;
  placement : transformation_select;
  reference_product_component : product_component;
 END_ENTITY;

 ENTITY process_operation_definition;
(*
UOF:S8
*)
  id : UNDEFINED_OBJECT;
  name : OPTIONAL string_select;
  process_type : UNDEFINED_OBJECT;
  description : OPTIONAL string_select;
  version_id : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_operation_definition_relationship;
(*
UOF:S8
*)
  relating : process_operation_definition;
  related : process_operation_definition;
  relation_type : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY process_operation_occurrence_relationship;
(*
UOF:S8
*)
  related : process_operation_occurrence;
  relation_type : UNDEFINED_OBJECT;
  relating : process_operation_occurrence;
  waiting_time : OPTIONAL property_value;
  description : OPTIONAL string_select;
  cycle_time : OPTIONAL UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY value_list
  SUBTYPE OF (
   property_value
  );
(*
UOF:S1
*)
  values : LIST [1:?] OF property_value;
 END_ENTITY;

 ENTITY numerical_value
  SUBTYPE OF (
   value_with_unit
  );
(*
UOF:S1
*)
  value_component : UNDEFINED_OBJECT;
 INVERSE
  limitation : SET [0:1] OF value_limitation FOR limited_value;
 END_ENTITY;

 ENTITY property_value
  ABSTRACT SUPERTYPE OF ( ONEOF(value_list,value_with_unit,string_value) );
(*
UOF:S1
*)
  value_name : UNDEFINED_OBJECT;
 END_ENTITY;

 ENTITY string_value
  SUBTYPE OF (
   property_value
  );
(*
UOF:S1
*)
  value_specification : string_select;
 END_ENTITY;

 ENTITY path_parameter;
(*
UOF:FF1
*)
  associated_path : path;
  parameter_role : UNDEFINED_OBJECT;
  parameter_context : general_feature;
 END_ENTITY;

 ENTITY profile_parameter;
(*
UOF:FF1
*)
  associated_profile : profile;
  parameter_role : UNDEFINED_OBJECT;
  parameter_context : general_feature;
 END_ENTITY;

 ENTITY terminal;
	(*
	From AP212
	*)
      description                   : OPTIONAL undefined_object;
      terminal_of                   : (*single_device*)single_instance;
      id                            : undefined_object;
      implemented_by                : SET [0:?] OF implementation_select;
      associated_interface_terminal : interface_terminal;
      extended_designation          : OPTIONAL terminal_designation;
  END_ENTITY;

 ENTITY interface_terminal;
	(*
	From AP212
	*)
      description                  : OPTIONAL undefined_object;
      interface_terminal_of        : design_discipline_item_definition;
      id                           : undefined_object;
      uses                         : SET [0:1] OF terminal;
      maximum_number_of_conductors : OPTIONAL undefined_object;
 END_ENTITY;

 ENTITY terminal_designation
    SUBTYPE OF (object_designation);
	(*
	From AP212
	*)
 END_ENTITY;

 ENTITY object_designation
    SUPERTYPE OF ((*ONEOF ( *)terminal_designation(*,document_designation,
        object_reference_designation,signal_designation)*));
	(*
	From AP212
	*)
      designator                 : undefined_object;
      type_of_object_designation : OPTIONAL STRING;
      designation_system         : OPTIONAL classification_system;
  END_ENTITY;

  ENTITY connection
    SUBTYPE OF (connectivity_definition);
	(*
	From AP212
	*)
      connected_terminal : SET [0:?] OF terminal;
  END_ENTITY;

  ENTITY connectivity_definition
    ABSTRACT SUPERTYPE OF ((*ONEOF ( *)connection(*,interface_terminal_connection)*));
	(*
	From AP212
	*)
      id              : undefined_object;
      description     : OPTIONAL undefined_object;
      implemented_by  : SET [0:?] OF implementation_select;
      version_id      : OPTIONAL undefined_object;
      connectivity_of : assembly_definition;
  END_ENTITY;
  
  ENTITY item_presentation;
  	(*
	From AP212
	*)
      presented_item  : presentation_select;
      presenting_item : representation_item;
      id              : OPTIONAL undefined_object;
  END_ENTITY; -- item_presentation
  
  ENTITY interface_terminal_relationship;
  	(*
	From AP212
	*)
  	relating      : interface_terminal;
	related       : interface_terminal;
	relation_type : STRING;
	description   : OPTIONAL undefined_object;
  END_ENTITY; -- interface_terminal_relationship
  
  ENTITY terminal_relationship;
    (*
	From AP212
	*)
      relation_type : STRING;
      description   : OPTIONAL undefined_object;
      related       : terminal;
      relating      : terminal;
  END_ENTITY; -- terminal_relationship
  
  ENTITY resource_item;
    (*
	From modules
	*)
      name: STRING;
      description: OPTIONAL STRING;
  END_ENTITY; -- Resource_item
  
  ENTITY resource_item_assignment;
  	(*
	From modules
	*)
      assigned_resource: resource_item;
      item: activity;
  END_ENTITY; -- Resource_item_assignment
  
  ENTITY time_interval_assignment;
  	(*
	From modules
	*)
      assigned_time_interval: duration;
      role: STRING;
      items: activity;
  END_ENTITY; -- Time_interval_assignment
  
  ENTITY view_definition_context;
    (*
	From modules
	*)
    application_domain: STRING;
    life_cycle_stage: STRING;
    description: OPTIONAL STRING;
  END_ENTITY; -- View_definition_context
  
  ENTITY work_breakdown_element;
    (*
	From modules
	*)
  	id: STRING;
    name: OPTIONAL STRING;
    description: OPTIONAL STRING;
  END_ENTITY;
  
  ENTITY work_breakdown_element_version;
    (*
	From modules
	*)
   id: STRING;
   description: STRING;
   of_product: work_breakdown_element;
  END_ENTITY;
  
  ENTITY work_breakdown_element_definition;
    (*
	From modules
	*)
	id: STRING;
    name: STRING;
    additional_characterization: STRING;
    initial_context: view_definition_context;
    additional_contexts: SET [0:?] OF view_definition_context;
    defined_version: work_breakdown_element_version;
  END_ENTITY;
  
  ENTITY work_breakdown_element_usage;
    (*
	From modules
	*)
    id: OPTIONAL STRING;
    relation_type: OPTIONAL STRING;
    description: OPTIONAL STRING;
    relating_view: work_breakdown_element_definition;
    related_view: work_breakdown_element_definition;
  END_ENTITY;
  
  ENTITY wbs_element_precedence;
    (*
	From modules
	*)
  	predecessor : work_breakdown_element_definition;
	successor : work_breakdown_element_definition;
  END_ENTITY;
  
END_SCHEMA;
